### ISSUE TITLE
PAD 1 and PAD 2 get swapped once X360CE is run, even when manually set through the configuration file.

### ISSUE THREAD

**Issue by ghost** [x360ce/x360ce#100]
Swapping the PAD ID tags ends up with them reverting back.

Before loading X360CE, manual edit.
PAD1=IG_MainController (PS3 Controller)
PAD2=IG_SecondaryController (Logitech PS3 Controller)

After loading X360CE.
PAD1=IG_SecondaryController (Logitech PS3 Controller)
PAD2=IG_MainController (PS3 Controller)

No matter what I do, my main controller is always set to Controller 2.

**Comment by Nucleoprotein** [comment]
I think this is known issue.

PS: You not need to keep x360ce.exe running when playing.

**Comment by ghost** [comment]
I'm not running any games, X360CE keeps identifying my second controller as my first controller, when I want it to be the other way around. That's it.

**Comment by Nucleoprotein** [comment]
As I written above, this is know issue - x360ce config app incorrectly displays device order, swapping PADx in [Mappings] should work in game.

**Comment by ghost** [comment]
So what I should do is not run X360CE anymore once I edited the Config file, so that it can stop overriding my changes. I'll add that as a note on PCGamingWiki. I'll test it now.
http://pcgamingwiki.com/wiki/X360ce

**Comment by Nucleoprotein** [comment]
PS: xinput1_4.dll can be only used by games on Windows 8/8.1 because is not redistributable.

**Comment by ghost** [comment]
Thanks. Sorry if I sounded annoyed, wasn't my intent.

**Comment by EJocys** [comment]
@RaTcHeT302 
With new version of application v3.2.8.74 (2015-08-27) it is possible to use "Map To" drop down on Direct Input Panel to map displayed Direct Input device to specific XInput position.
