### ISSUE TITLE
Witcher 3 Right Analog stick constantly spinning to the left

### ISSUE THREAD

**Issue by Lhek328** [x360ce/x360ce#101]
Yeah, the title says it all
After long trouble I managed to make x360ce detecting witcher 3
Had to use 360ce 64 bit for the first time
Everything works fine except the right analog stick
The X axis constanly spins to the left and I dont really know why
Im using just a basic hama direct input ps2 style controller
I already tried re-recording the axis and everything, doesnt work, it keeps going left
That's what it looks like
![749b9f9848817dc52e36d49a64695b97](https://cloud.githubusercontent.com/assets/12565527/7779345/f25241be-00d3-11e5-9c12-227c08ffe2e7.png)
Would be glad if anyone knows a solution

**Comment by Nucleoprotein** [comment]
Click "Game Controllers..." (bottom left) and check if same thing happens there for your controller. If is, then go to "Settings" tab there and run calibration.

**Comment by Lhek328** [comment]
Ye it does, guess my controller's broke
Even though it had been working a day before witcher 3 released, haven't touched it since today
Edit: Wow Im dumb, just had to recalibrate it
Thanks for the advice btw ! :D

**Comment by Nucleoprotein** [comment]
Check if calibration helps, if not then right thumb stick seems to be damaged. Closing this.
