### ISSUE TITLE
sorry for being stupid but where do you download the libraries? I cant seem to find the link 

### ISSUE THREAD

**Issue by OldSchoolPH** [x360ce/x360ce#102]
when I download it, it's just the application

**Comment by Squall-Leonhart** [comment]
what does the application ask you to create when you run it.

**Comment by Nucleoprotein** [comment]
I think we need to update ngemu guides.

**Comment by Squall-Leonhart** [comment]
I think people have forgotten that we only provided libs back when Ejocy wasn't actively keeping the App updated
