### ISSUE TITLE
4.1.0.0 Detroit Become Human issues

### ISSUE THREAD

**Issue by DmitryDMR** [x360ce/x360ce#1033]
Logitech Cordless RumblePad 2
I mapped all button and stick And Pad working correctly in the game, but i have one issue. When i tilt right stick on left direction it working as right stick and right trigger simultaneously.

**Comment by DmitryDMR** [comment]
Deleted all games profiles and setup new one profile for x360ce.exe

**Comment by GiuseppeMMM** [comment]
Im having the same issue here. Tried with other softwares as x360ce, XOutput, nigthing works. Not actually using the same controller, im using a generic Dragonrise inc. USB Joystick.

When u said to delete the game profiles, you say the in game archives?

**Comment by DmitryDMR** [comment]
No. In x360ce Profile page
