### ISSUE TITLE
No x64 library

### ISSUE THREAD

**Issue by janpeeters95** [x360ce/x360ce#106]
Hi, where do I find the x64 library? When I go to "64-bit Download - for 64-bit games" I only download the .exe. But I need the library for the Witcher 3.

**Comment by Nucleoprotein** [comment]
Library is included in exe file, run it to create it.

**Comment by janpeeters95** [comment]
I did, but I only get the xinput1_3.dll. And I saw that there a more files.

And when I start the Witcher with the created xinput1_3.dll, I get an error sound, but no message.
