### ISSUE TITLE
x360ce cannot find my gamepad (grey light) but the gamepad is working.

### ISSUE THREAD

**Issue by Akfiz** [x360ce/x360ce#1067]
The Xbox 360 Controller Emulator used to work, I used it to play Dirt 3, Insane 2 and Overlord 2. I played with it many times and it worked many times.

Today I wanted to play Lara Croft and the Temple of Osiris but x360ce couldn't find my gamepad, there was no red box, there was a grey box:
* I was using the same gamepad I previously used to play Dirt 3, Insane 2 and Overlord 2.
* I downloaded x360ce from the official site and tried both 32-bit and 64-bit versions.
* I tried to download an older version, it still had no effect.
* I tried to uninstall and reinstall x360ce.
* I tried to manually download the xinput1_3.dll.
* I checked on control panel -> devices and the computer recognizes the gamepad and it's working.
* I tried to use another gamepad, x360ce couldn't find that one either.
* I tried to play Dirt 3 with x360ce like I used to, x360ce couldn't find the gamepad anymore.

I don't know what happened, it's all so sudden. I had no difficulties using x360ce before, I have no idea why it's not working anymore, the computer says that the gamepad is working but the x360ce cannot detect the gamepad.

**Comment by adfvavqad** [comment]
i have same problem with gta v other games work fine i tried same steps still not working

**Comment by lukemp3** [comment]
me too the same problem.
My controller is working within the calibration panel from control panel in win10.
Everything is working, digital and analogic buttons.
Win10 recognizes my controller (it's a non brand controller via usb)

X360ce does not.
When I run x360ce_x64 to use ( Red Dead R. 2 ) an error appears: 
"failed to load xinput9_1_0.dll
system component model win32exception 0x80004005. can't find the specified module

I already tried to solve by myself, before writing here, but no success.

**Comment by VanWolf** [comment]
Same problem here controller Trust Ctx24, worked fine before, win 10 recognixe the controller as before.

**Comment by mathiross** [comment]
Exactly the same problem. Suddenly...
the only test I made more is I tried to run it as administrator. but same result, not recognized

**Comment by mathiross** [comment]
![x360ce](https://user-images.githubusercontent.com/37271791/79243400-dcdd8580-7e75-11ea-9cd9-6a9f7dbb4222.jpg)

**Comment by mathiross** [comment]
More informations about this bug: I tried to refresh the gamepad in the controller settings tab and this message came: 
![Sans titre](https://user-images.githubusercontent.com/37271791/79496391-5c11bb80-8026-11ea-90f4-e60d6788328c.jpg)


I think I remember this message came once, automatically, withour refreshing the controller detection.
If someone can help us, it would be so nice. thanks in advance.


The detail of the error message is:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at x360ce.App.Controls.ControllerSettingsUserControl.FillSearchParameterWithFiles(List`1 sp)
   at x360ce.App.Controls.ControllerSettingsUserControl.RefreshGrid(Boolean showResult)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
x360ce
    Assembly Version: 3.2.10.82
    Win32 Version: 3.2.10.82
    CodeBase: file:///F:/Jeux%20Video/Worms%20W.M.D/x360ce_x64.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Configuration.Install
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration.Install/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.Install.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
SharpDX.DirectInput
    Assembly Version: 2.6.3.0
    Win32 Version: 3.2.10.82
    CodeBase: file:///F:/Jeux%20Video/Worms%20W.M.D/x360ce_x64.exe
----------------------------------------
SharpDX
    Assembly Version: 2.6.3.0
    Win32 Version: 3.2.10.82
    CodeBase: file:///F:/Jeux%20Video/Worms%20W.M.D/x360ce_x64.exe
----------------------------------------
x360ce.Engine
    Assembly Version: 1.0.0.0
    Win32 Version: 3.2.10.82
    CodeBase: file:///F:/Jeux%20Video/Worms%20W.M.D/x360ce_x64.exe
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data.Entity
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Entity/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Entity.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web.Services
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by Akfiz** [comment]
I fixed the grey light issue by moving the x360ce in a folder outside "Program Files", letting him create his files there and then moving it with all the new files back inside the file of the game I want to play.

- Someone suggested to get x360ce on another PC, let him download his files there, and then copy it on the PC that you want to use the gamepad on inside the game's folder. It worked for him, didn't work for me.

In my case, everything that would go wrong has went wrong so I think I have a fix for everything. Here is how I made x360ce work step by step, from the worst to smallest problems:

I) Grey Light -> Controller is connected, the PC sees the controller, x360ce doesn't see the controller.

1. Don't have the x360ce file inside "Program Files" as for some reason the program cannot create the xinput file there. This should be mentioned on x360ce's download page but it isn't.
2. Unplug the Gamepad and then start x360ce without the gamepad. This sounds 100% weird, but when I did this, it asked me to create xinput. When I started it with the gamepad connected, it didn't ask me to create the xinput.
I believe the problem with the grey light was that x360ce cannot create the required files if its inside "Program Files".
After I did all of that, the next time I connected the gamepad, the grey light turned to red.

II) Red Light -> x360ce sees the controller but something isn't right.

3. Go to Control Panel -> Devices and Printers -> Select your Gamepad and do a test. Move the axis a bit and press a few buttons.
4. Go back to x360ce and click on auto-assign. If auto-assign doesn't work, make sure key buttons like "start" are assigned.
After I did all of that, the red light turned green, but it still didn't work.

III) Green Light -> x360ce says it should work, but it doesn't work.

- I tried to get an older x360ce version that a lot of people said it works. It didn't work for me.
5. Copy all the files inside x360ce, for me they were: xinput1_1.dll, xinput1_3.dll, x360ce.exe, x360ce,ini and vJoyInterface.dll, inside the files of the game you want to play.
6. It will show you the grey light again, giving you the impression that it did not work, but the controller is actually working.

**Extra:** If you want to play more than 1 game with x360ce, since the download page doesn't mention this either. Copy and paste a x360ce.exe with the necessary files (for me it was: xinput1_1.dll, xinput1_3.dll, x360ce.exe, x360ce,ini and vJoyInterface.dll) inside every game that you want to play. It has an option for multiple games inside it, but I'm not sure how that works or why is it even there if you need one x360ce.exe inside the folder of every game you want to play.

**Short Version:** It didn't work originally because x360ce cannot create the required files if its inside "Program Files", so you will have to move the x360ce in your own folder outside "Program Files", unplug the controller, start x360ce and let him create its own files right there. Plug the controller back in and now the grey light will turn red. Do the controller testing in Control Panel -> Devices and Printers and inside x360ce press auto-assign, if auto-assign doesn't work make sure that key buttons such as "start" are assigned. Now the red light will turn green. Close x360ce, copy and paste all the new files (for me, it was: xinput1_1.dll, xinput1_3.dll, x360ce.exe, x360ce,ini and vJoyInterface.dll) inside the game's file that was inside "Program Files". It will show a grey light on the controller but it will actually work inside the game.

**Comment by mathiross** [comment]
THANKS A LOT IT'S WORKING !
game evening in sight .....

**Comment by TheFluffyOne99** [comment]
> I fixed the grey light issue by moving the x360ce in a folder outside "Program Files", letting him create his files there and then moving it with all the new files back inside the file of the game I want to play.
> 
> * Someone suggested to get x360ce on another PC, let him download his files there, and then copy it on the PC that you want to use the gamepad on inside the game's folder. It worked for him, didn't work for me.
> 
> In my case, everything that would go wrong has went wrong so I think I have a fix for everything. Here is how I made x360ce work step by step, from the worst to smallest problems:
> 
> I) Grey Light -> Controller is connected, the PC sees the controller, x360ce doesn't see the controller.
> 
> 1. Don't have the x360ce file inside "Program Files" as for some reason the program cannot create the xinput file there. This should be mentioned on x360ce's download page but it isn't.
> 2. Unplug the Gamepad and then start x360ce without the gamepad. This sounds 100% weird, but when I did this, it asked me to create xinput. When I started it with the gamepad connected, it didn't ask me to create the xinput.
>    I believe the problem with the grey light was that x360ce cannot create the required files if its inside "Program Files".
>    After I did all of that, the next time I connected the gamepad, the grey light turned to red.
> 
> II) Red Light -> x360ce sees the controller but something isn't right.
> 
> 3. Go to Control Panel -> Devices and Printers -> Select your Gamepad and do a test. Move the axis a bit and press a few buttons.
> 4. Go back to x360ce and click on auto-assign. If auto-assign doesn't work, make sure key buttons like "start" are assigned.
>    After I did all of that, the red light turned green, but it still didn't work.
> 
> III) Green Light -> x360ce says it should work, but it doesn't work.
> 
> * I tried to get an older x360ce version that a lot of people said it works. It didn't work for me.
> 
> 5. Copy all the files inside x360ce, for me they were: xinput1_1.dll, xinput1_3.dll, x360ce.exe, x360ce,ini and vJoyInterface.dll, inside the files of the game you want to play.
> 6. It will show you the grey light again, giving you the impression that it did not work, but the controller is actually working.
> 
> **Extra:** If you want to play more than 1 game with x360ce, since the download page doesn't mention this either. Copy and paste a x360ce.exe with the necessary files (for me it was: xinput1_1.dll, xinput1_3.dll, x360ce.exe, x360ce,ini and vJoyInterface.dll) inside every game that you want to play. It has an option for multiple games inside it, but I'm not sure how that works or why is it even there if you need one x360ce.exe inside the folder of every game you want to play.
> 
> **Short Version:** It didn't work originally because x360ce cannot create the required files if its inside "Program Files", so you will have to move the x360ce in your own folder outside "Program Files", unplug the controller, start x360ce and let him create its own files right there. Plug the controller back in and now the grey light will turn red. Do the controller testing in Control Panel -> Devices and Printers and inside x360ce press auto-assign, if auto-assign doesn't work make sure that key buttons such as "start" are assigned. Now the red light will turn green. Close x360ce, copy and paste all the new files (for me, it was: xinput1_1.dll, xinput1_3.dll, x360ce.exe, x360ce,ini and vJoyInterface.dll) inside the game's file that was inside "Program Files". It will show a grey light on the controller but it will actually work inside the game.

When I keep it plugged.. Start the app it only works for stuff like GTA IV.. 
When I try the older version. It crashes or if I open it up in a place where it can't write. It will work but not notice the gamepad. While on desktop it crashes. If I unplug it. It crashes in the RAR where it can't write immidietly. But doesn't crash anymore on the desktop. After plugging the controller back in. It finds it and seems to work. For like 2 seconds then it crashes every time no matter what I try to do. However nothing I tried so far seems to have helped me trying to use a direct controller for my Forza Horizon 4 which I bought the controler for...
