### ISSUE TITLE
Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 breaks the app

### ISSUE THREAD

**Issue by lordmedo** [x360ce/x360ce#1068]
**windows 10 x64
x360ce 4.8.0.14**

Installing the Redistributable for 2015-2017-2019 (single file) suddenly broke the app, which now prompts to install the 2015 standalone package. 
Unistalling the 2019 and reinstalling 2015 didn't solve the issue, x360ce just closes few second after start 
Deleting c:\ProgramData\X360CE\ didn't help either.
![x360](https://user-images.githubusercontent.com/13256611/77272053-8c2c9f80-6cb0-11ea-99b7-0f4c8d87b527.png)

Prior to installing 2019 package, app worked perfectly for over a year.

**Comment by joao-haraujo** [comment]
Same problem here. I did manage to get it working again by uninstalling the 2019 version (make sure you reinstall both the x64 and x86 redistributables).

However, I am now required to have the 2019 version installed as part of other projects I'm developing so I would greatly appreciate it if this issue is resolved.

**Comment by lordmedo** [comment]
x360ce 4.10.0.0 alpha solved the issue but only when I installed this [driver](https://github.com/aitte2/dualshock_driver).
I'm using the blue double-port ps2 to usb converter which has rumble driver problems it seems...

**Comment by keerthan657** [comment]
> Same problem here. I did manage to get it working again by uninstalling the 2019 version (make sure you reinstall both the x64 and x86 redistributables).
> 
> However, I am now required to have the 2019 version installed as part of other projects I'm developing so I would greatly appreciate it if this issue is resolved.

Yes, the solution worked. Just installed both x86 and x64 redistributables, no need to uninstall 2019 version.

**Comment by Kashend124** [comment]
> Same problem here. I did manage to get it working again by uninstalling the 2019 version (make sure you reinstall both the x64 and x86 redistributables).
> 
> However, I am now required to have the 2019 version installed as part of other projects I'm developing so I would greatly appreciate it if this issue is resolved.

Sorry to revive a dead thread, but this worked for me as well. The Dualshock driver recommended above sadly did nothing.
