### ISSUE TITLE
Dont work on witcher 3

### ISSUE THREAD

**Issue by janpeeters95** [x360ce/x360ce#107]
Hey,

sorry for open a new issues. But I only get the xinput1_3.dll and not the other files, that are listed in the tutorial for x64 games. And when I start the Witcher, I get an error sound but no message, and the controller doesnt work.

**Comment by Nucleoprotein** [comment]
Tutorials are deprecated, needs to be updated. Now all required files are included in x360ce.exe, you need only to set what files you need in options.
Also you have ngemu x360ce forum for such configuration questions, this is issue tracker ie. only for reporting bugs and this clearly is not bug.
