### ISSUE TITLE
How to download ?

### ISSUE THREAD

**Issue by guiguilyon** [x360ce/x360ce#108]
Hi. I never downloaded a software from Github. This website is very confusing.
I just want to install x360ce as a user.
I seee a tons of files, and a zip on a right of the page, which Chrome sees as malicious. I downloaded it anyway, but it also contains a lots of files. And I can't find any exe inside.

Where do I download the software from?
Please help.

**Comment by papin97** [comment]
http://www.x360ce.com/default.aspx

**Comment by guiguilyon** [comment]
What a quick response! Thanks. But don't you need more files (.ini, .dll...) That's what I read in a tutorial.

**Comment by Squall-Leonhart** [comment]
run the application in a location that has neither ;)

**Comment by almurphy123** [comment]
X360ce master  can't see how to use.there is nice. Exe to install

**Comment by guiguilyon** [comment]
Thanks guys! That works. I managed to play Shovel Knight with my old Saitek p880. Awesome!

**Comment by killa2103** [comment]
When I run the application (64 bit) it just creates xinput.dll and x360ce.ini however in order to support mortal kombat x I need dinput8.dll (64 bit) which I cannot find anywhere.. and there is no separate link for libraries on this site please help.

**Comment by papin97** [comment]
Search for old version of x360ce (2013 probably). They included dinput8.dll inside

**Comment by Nucleoprotein** [comment]
MK10 does not need HookLL so does not require dinput8.dll.

**Comment by killa2103** [comment]
Thanks for response guys I managed to download 64bit libraries with dinput8 but that too didn't work neither in gta 5 nor in mk10 both crash immediately after launching....I don't know wats wrong.. all other games work fine with x360ce except gta 5 and mk10

**Comment by killa2103** [comment]
tapcio thanks but I don't know technicals but I tried both with and without dinput8..but same result crash at launch

**Comment by Nucleoprotein** [comment]
We not support older versions, because that some bug were fixed etc.
I know that MK10.exe is listed in GDB file with HookMask 0x00000002 ie. HookCOM, so it should work out-of-the-box.

**Comment by papin97** [comment]
But I tried using dinput8.dll old version with x360ce.exe new version for game Akiba's Trip, and the game ran smoothly without crash.
If I use xinput1_3 (and other version), it will crash, and if I dont use dinput8.dll, the game will detect wrong buttons.

**Comment by Nucleoprotein** [comment]
Report proper issues ie. with logs so we can fix issues instead of using old and not supported version.
