### ISSUE TITLE
Swap Motor feature doesn't do anything

### ISSUE THREAD

**Issue by Blackbird88** [x360ce/x360ce#109]
As title says. Newest version and all.

**Comment by Squall-Leonhart** [comment]
WFM, more information required.

**Comment by Blackbird88** [comment]
- I open X360CE.
- I tick Swap Motor
- I try to test it by sliders
- Left is still left and right is still right

**Comment by Squall-Leonhart** [comment]
Rumble Mode
Controller Type
etc.

**Comment by Blackbird88** [comment]
I can't find that option http://i.imgur.com/4rIIqpB.png
It's DS3 with XInput wrapper, but that should give same behavior.

EDIT: Alright I figured it out. For some odd reason I had to set **Force Pass Through**

**Comment by Squall-Leonhart** [comment]
What drivers?

Look, you need to be clear and descriptive here, as far as i can tell it works fine.

**Comment by Blackbird88** [comment]
I am on Windows 8.1 x64 with w/e default 360 drivers are. I use Scarlett's
XInput wrapper for DS3 which fakes 360 perfectly anyhow. I need to use the
Force Pass Through option else it doesn't work at all.

2015-05-28 10:19 GMT+02:00 Squall Leonhart notifications@github.com:

**Comment by Squall-Leonhart** [comment]
We don't have any control over the motors when you use force passthrough.
