### ISSUE TITLE
Double input in The Escapists 2

### ISSUE THREAD

**Issue by henriquesdm7** [x360ce/x360ce#1095]
Hello people,
I know this game is not on the compatibility list, but I hope someone can help me.
I want to play with two generic usb gamepads but the game recognizes two gamepads for each one I own. I was able to configure the controls correctly, but the "copy" of the control has unconfigured commands, so every time I press the equivalent to button "B" the unconfigured player is recognized, and when I press the equivalent to button "A", the correctly configured player is recognized.
I'm using all 32bit xinput* dll's. (1_1, 1_2, 1_3, 1_4 and 9_1_0).
Thanks!

**Comment by doge57589** [comment]
ok

**Comment by LoudKat** [comment]
If you're playing on steam it's best not to use x360ce because in big picture mode you can just enable all the compatibility options for your controllers
