### ISSUE TITLE
Compiled version does not work on Windows XP

### ISSUE THREAD

**Issue by jbienz** [x360ce/x360ce#11]
_From [georg.li...@gmail.com](https://code.google.com/u/100964941758256259856/) on April 25, 2010 18:15:36_

What steps will reproduce the problem? 1. Download the application and start it in Windows XP
2. A few exception dialogs occur (two or three)
3. Application does not recognize any game controllers. What is the expected output? What do you see instead? Application should recognize all game controllers connected to the computer. What version of the product are you using? On what operating system? 2.0.2.21 on Windows XP SP3 32bit What gamepad are you using? On what version of drivers? Ehere JoyPad, generic PlayStation 2 controller with USB connection ($7 on
Ebay) and force feedback. Microsoft Driver 5.1.2600.5512. PCI VID 0x0810,
PID 0x0001.

Partial solution: I recompiled the app on Windows XP with VisualStudio
2008. VisualStudio outputs

------ Build started: Project: x360ce.App, Configuration: Release Any CPU
------
Project file contains ToolsVersion="4.0", which is not supported by this
version of MSBuild. Treating the project as if it had ToolsVersion="3.5".
x360ce.App -> C:\Documents and Settings\lippold\My Documents\Visual Studio
2008\Projects\x360ce-read-only\x360ce.App\bin\Release\x360ce.exe
"C:\Documents and Settings\lippold\My Documents\Visual Studio
2008\Projects\x360ce-read-only\x360ce.App\Documents\JocysCom.sign.bat"
"C:\Documents and Settings\lippold\My Documents\Visual Studio
2008\Projects\x360ce-read-only\x360ce.App\bin\Release\x360ce.exe"
File doesn't Exist: "C:\Program Files\Microsoft
SDKs\Windows\v7.0\Bin\signtool.exe"
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========

So it seems as if the application uses the .NET Framework 4.0, which is not
supported on Windows XP. Recompiling with .NET 3.5 is OK, resulting
executable is attached. Game controllers are now properly recognized, and
no exceptions occur. However, when I try to start Sonic & SEGA Allstars
Racing PC, my controllers are not recognized (meaning that the XBox
Controller emulation does not work for that particular game).

**Attachment:** [x360ce.exe](http://code.google.com/p/x360ce/issues/detail?id=11)

_Original issue: http://code.google.com/p/x360ce/issues/detail?id=11_

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 30, 2010 09:30:09_

No, project should be even 2.0. Please check latest svn revision, maybe bug in project 
files.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on August 08, 2010 09:24:51_

**Status:** Done

**Comment by jbienz** [comment]
_From [danialho...@gmail.com](https://code.google.com/u/116142181712224615034/) on February 16, 2013 11:12:21_

**Status:** Verified

**Comment by gusky651** [comment]
Cant download attachment
