### ISSUE TITLE
Can't get FIFA 14 to work

### ISSUE THREAD

**Issue by mviksi** [x360ce/x360ce#111]
Okay, so i have 3 controllers i want to get to work
First one is Logitech F310 and it works perfect in game
Other 2 are Saiteks, but named Cordless Rumblepad 2,
They all work good in emulator, all the buttons are like they are supposed to be, but when i go to play the game, the settings are wrong, like when i press button A it's B.
Thank you
Steps I made:
1. Put xbox_x64.ce to Program files.
2. Run it
3.All the controllers are fine and i close it.
4.Start the game, and 2 controllers still wrong settings

**Comment by Squall-Leonhart** [comment]
Ejocy, i think problems like this are due to GDB not being automatically created on first start.

**Comment by EJocys** [comment]
Ok, I will update code to make sure that it is automatically created on first start.

**Comment by mviksi** [comment]
Let me know, when u done please,
Thanks man

**Comment by mviksi** [comment]
How far is this coding? :)

**Comment by EJocys** [comment]
@mart2: You can try new version which is available to download from home page. It will auto-create and update XML/GDB file.
