### ISSUE TITLE
[PAD0] Misconfigured device check GUIDs

### ISSUE THREAD

**Issue by seelkadoom500** [x360ce/x360ce#112]
i'm new to x360ce when i do any input i get [PAD0] Misconfigured device check GUIDs i'm using windows 7 ultimate what should i do and please give me a step to step instruction.

**Comment by Nucleoprotein** [comment]
Load and save configuration ? Delete x360ce.ini if you have problem and re-run x360ce.exe.
Also this is not place for a questions about x360ce configuration, goto here: http://ngemu.com/forums/x360ce.140/
