### ISSUE TITLE
msvcr100.dll missing

### ISSUE THREAD

**Issue by almurphy123** [x360ce/x360ce#113]
this dll is not missing, so whats wrong with this program.i have dll fixer and they have confirmed the file is there

**Comment by Nucleoprotein** [comment]
1. Latest version do not require this runtime library
2. Required runtime library is msvcr120.dll, and you not require the library but install proper redistributable package form here: http://www.microsoft.com/en-us/download/details.aspx?id=40784

This is not a bug/issue in problem but system configuration problem so use our forum: http://ngemu.com/forums/x360ce.140/

**Comment by Gin8Gin** [comment]
Try to load it from here [dangerous link deleted]. When U start the application/game you may experience various kinds of errors. Then replace the old file by new and restart computer. It must help.

**Comment by Nucleoprotein** [comment]
**NEVER EVER DOWNLOAD RUNTIME FROM SUCH SITES, RUNTIME IS FREE TO DOWNLOAD FROM MICROSOFT SITE !!!!**
