### ISSUE TITLE
Controller Power Off Causes Joystick & DPad Output

### ISSUE THREAD

**Issue by Burstroc** [x360ce/x360ce#1143]
v4.12.18.0: When a wireless controller powers off while the program is running it causes it to output both analog sticks as being in the upper left position and the dpad as holding down up.
![x360ce 4 Error](https://user-images.githubusercontent.com/13581542/89603038-27747a80-d836-11ea-9604-d6a079ca1643.png)

**Comment by EJocys** [comment]
@Burstroc: Thank you for reporting. Fixed this issue in new version 4.12.23.0: https://github.com/x360ce/x360ce/releases
