### ISSUE TITLE
Cannot build x360ce.App.Beta from source

### ISSUE THREAD

**Issue by kakashidinho** [x360ce/x360ce#1160]
Hi,
I tried to build and debug x360ce v4.x from source and encountered this error:
```
Invalid Resx file. Could not find a part of the path 'C:\Users\...\x360ce\x360ce.Engine\JocysCom\Controls\MessageBoxFormImages\MessageBoxIcon_Error_32x32.png'. Line 123, position 5.
```
I don't see `MessageBoxIcon_Error_32x32.png` on the git repo. How to get this file?
Thanks,

**Comment by EJocys** [comment]
Added missing files. Should be fine now.
