### ISSUE TITLE
Problem updating button bindings

### ISSUE THREAD

**Issue by C4noe** [x360ce/x360ce#1176]
When clearing a button binding, the box may show as empty but even after uninstalling and reinstalling drivers, using the "clear" button, saving, and restarting the program, the button is still bound. The original binding even persists after binding a new key to the button, and binding the original key to a different button. Additionally, bindings for one device will randomly be applied to the other device used for that "controller". x360ce v4.14.9.0.

**Comment by C4noe** [comment]
Found workaround: Edit C:\ProgramData\X360CE\Settings\x360ce.PadSettings.xml to manually change bindings

**Comment by EJocys** [comment]
Please try new version. (v4.17.12.0, 2020-11-15). There was an issue where multiple map settings would merge from all games.
You can download latest version from here: https://github.com/x360ce/x360ce/releases
