### ISSUE TITLE
(ezfrd64.dll)  crash 

### ISSUE THREAD

**Issue by playbos4** [x360ce/x360ce#1178]
The crash occurs in a 3rd-party device driver (ezfrd64.dll). To resolve the issue, please follow the steps below:
pls fix x360ce

thaNK ^^
*unsourced dll file removed*

**Comment by Seamas73** [comment]
Same issue. Ezfrd64.dll from SVEN X-PAD force feedback driver causes crash of the x360ce v.4.14.15.0 and earlier. When I replaced dll with downloaded from the internet, app didn't crash, but force feedback didn't work, although app showed in Direct input tab, that FF is supported.

*unsourced dll file removed*

**Comment by playbos4** [comment]
此驅動程序不適用於您的設備，但應該可以正常使用， http：//www.speedlink.com/support/bin/SL-6535-BK_Driver_V1.0.zip

**Comment by Squall-Leonhart** [comment]
Not our bug
