### ISSUE TITLE
replica of switch pro controller connect to WIn10 via BT

### ISSUE THREAD

**Issue by mrbarnie** [x360ce/x360ce#1179]
Hi Guy,

I hope you can help me. I installed version  4.14.14.0 and see my controller under devices.
But I am not able to assign any buttons and that like.

Any help is very very much appreciated!!!

THANKS
MrBarnie

**Comment by EJocys** [comment]
@mrbarnie:

Thank you for reporting. Fixed error in HidGuardianHelper.cs file (line: 224) and reuploaded x360ce.zip on https://github.com/x360ce/x360ce/releases

Changes:

v4.14.15.0 (2020-10-10)
- Fixed: Crash when configuring HID Guardian when Device Id is missing.

**Comment by mrbarnie** [comment]
@EJocys 
thank you very much for your quick help!!
i will try it and let you know

**Comment by mrbarnie** [comment]
@EJocys

hmm strange, although i found the controller in bluetooth settings and paired with PC, I cannot connect to it.
The controller was found by using the first choice and not the third.

![image](https://user-images.githubusercontent.com/34183950/95671278-5213e400-0b95-11eb-9fd1-1bd3ba09c1f3.png)

****
![image](https://user-images.githubusercontent.com/34183950/95671284-6657e100-0b95-11eb-8883-a8aa50bffd14.png)


Do you have an idea why I cannot connect this controller to WIn?
I also turned my switch into flight mode to make sure it does not connect there.
After paring there are no additional drivers installed... Can these drivers be installed manually?


Thanks a lot in adavence.


By the way I found another bug.
I wanted to remove the 2 demo devices I created, but the list does not get updated.
SO I need to close the window, open it again and then I see that they were deleted.
Minor one, but I thought I mention it.

By the way great great work!!!! 
Keep on going.

Have a great day
MrBarnie
