### ISSUE TITLE
x360ce 4.x is not showing up

### ISSUE THREAD

**Issue by Pindang2** [x360ce/x360ce#1184]
![image](https://user-images.githubusercontent.com/45694028/96706008-fb967900-13d0-11eb-9b49-c63aba7c6a0b.png)
x360ce 4.x (4.13, 4.14, 4.15) program is not showing up with high CPU usage.

![image](https://user-images.githubusercontent.com/45694028/96706340-6e075900-13d1-11eb-9700-4c22c384b829.png)

I tried to Windows 7 and Windows 8 mode, and Administrator mode.
I moved program to C:\Program Files\x360ce, but not fixed.
![image](https://user-images.githubusercontent.com/45694028/96707696-2da8da80-13d3-11eb-8862-707bdf4c17a8.png)

**Comment by Pindang2** [comment]
I'm using Nintendo switch JoyCon with [vJoy](http://vjoystick.sourceforge.net/site/) and [JoyCon-Driver by fosse](https://github.com/fossephate/JoyCon-Driver).

**Comment by EJocys** [comment]
New release is available:  4.16.8.0 (2020-10-25)
...
- Fix: Do not request XInput states when program is minimized to save CPU resources.
...

[x] Get XInput State, which is for testing only, was causing high CPU usage. I've updated application no to request XInput state when X360CE is minimized.
