### ISSUE TITLE
Literally deletes my controller until I plug it back in

### ISSUE THREAD

**Issue by Jturner2223** [x360ce/x360ce#1186]
It does it constantly, idk why. It was fine yesterday and it didn't even come close to doing that.

**Comment by EJocys** [comment]
I've just release new version 4.16.7.0 which no longer auto-configures HID Guardian (hides or unhides devices) by default.

**Comment by Jturner2223** [comment]
Fixed the issue completely, thanks! I looked for the solution elsewhere and
they just gave me "turn off passthrough", an option I couldn't even find in
the previous release.
