### ISSUE TITLE
Deletes the contents of the HidGuardian AffectedDevices Registry after closing

### ISSUE THREAD

**Issue by AJRadaza** [x360ce/x360ce#1187]
I suggest to disable elevated app privileges so it won't mess up the registry. The hide devices feature in x360ce is rather useless especially for certain wireless controllers. It will be the users' choice to run the app as administrator.

**Comment by EJocys** [comment]
It makes sense. Users will lose some convenience, but it will be safer.

I've just release new version 4.16.7.0 which do not require elevated privileges by default again. Application no longer asks for HID Guardian if user is no longer asking to hide devices. Also, auto-configuration of HID Guardian (hiding, unhiding devices) is OFF by default.
