### ISSUE TITLE
Deadzone not working

### ISSUE THREAD

**Issue by AlexFrim** [x360ce/x360ce#119]
I have a wireless xbox360 controller. And to fix my problem with deadzone on sticks I was trying to use x360ce. But there is a problem: deadzone not working with active "pass through", and with disabled "pass through" triggers not working together. Is there any solution for this problem? Can I set a deadzone without things like emulation keyboard to joystick?

**Comment by Nucleoprotein** [comment]
Use KrossX Durazno instead: https://drive.google.com/folderview?id=0B1wssOeJs5_7czZ1WW93SzFxUWs&usp=sharing
