### ISSUE TITLE
Two buttons worked when one is pressed. Found the reason, but don't have a solution

### ISSUE THREAD

**Issue by coolcashew** [x360ce/x360ce#1193]
This problem only happens when same gamepad using in two game profiles. For example, if x360ce has two game profiles and both have the same gamdpad set, two random buttons would be detected when one is pressed. I tried it several times, once one game profile is deleted or one gamepad is removed, the problem would be solved.

**Comment by EJocys** [comment]
Thank you. I was able to replicate this issue. I will include fix in the next release.

**Comment by coolcashew** [comment]
> Thank you. I was able to replicate this issue. I will include fix in the next release.

You are welcome!  Thank you for you work!  Just one more question, Does x360ce auto-detect the game and apply the profile(mapping) since it scans the game folder?   It seems not working to me. I have to manually switch the gaming profiles.

**Comment by EJocys** [comment]
x360ce doesn't detect running game at the moment. Will add this as an optional thing too. I will let you know in this post when new release is ready. Will take couple days, because I have to finish other updates and features.

**Comment by coolcashew** [comment]
> x360ce doesn't detect running game at the moment. Will add this as an optional thing too. I will let you know in this post when new release is ready. Will take couple days, because I have to finish other updates and features.

Take your time! I appreciate it.

**Comment by EJocys** [comment]
@coolcashew 

Fixed issue with map settings merging from multiple games. Added support for Guide button and fixed more things. (v4.17.12.0, 2020-11-15). You can download latest version from here: https://github.com/x360ce/x360ce/releases
