### ISSUE TITLE
'Anti-dead zone' values not being saved

### ISSUE THREAD

**Issue by ghost** [x360ce/x360ce#1199]
Hi
I have configured a Logitech G29 wheel with x360ce and it's working good in Ride 2, wheel operating range is locked (LGS control panel)  to 120º, 60º to each side (matchs real lean angle), so it doesn't feel too weird steering the bikes!

I have the steering wheel mapped to the left stick axis X, I needed to set an anti dead zone value of 16% (game imposes dead zone, hardware is fine), the anti dead zone works as intended, but when I restart the x360ce or after resuming from suspend the setting is reset to 0.

I tried many times, saving and then exiting, it's always reset to zero.
I have also set Sensivity to 30%, and this one get saved correctly.

Not sure what's wrong on my side.

Many thanks for your time.

**Comment by EJocys** [comment]
@Tony-il-Capo 

Thank you for reporting this issue. Fixed it (v4.17.12.0, 2020-11-15). You can download latest version from here:
https://github.com/x360ce/x360ce/releases
