### ISSUE TITLE
The application has failed to start because its side by side configuration is incorrect

### ISSUE THREAD

**Issue by Jonah66** [x360ce/x360ce#120]
Hi im trying to download the xbox360ce file to be able to use a game controller on pc every time I try I get the message "The application has failed to start because its side by side configuration is incorrect" it doesn't matter wether I try the 32 or 64 bit version, hoping fort some help to understand why this is happening.
Thanks

**Comment by Nucleoprotein** [comment]
Install .NET 4.5 as requirements page says so.

**Comment by Jonah66** [comment]
Hi , ty for the reply, I have .NET 4.5 installed , my current version is 4.5.2

Date: Sun, 31 May 2015 14:12:19 -0700
