### ISSUE TITLE
Triggers neutralize each other

### ISSUE THREAD

**Issue by ssvx** [x360ce/x360ce#122]
[edit] short issue description: pressing left and right triggers together neutralizes the input and nothing is being sent at all - just as if no trigger is pressed. [/edit]

Using the Logitech F710 with x360ce to get rid of the left analog stick deadzone in GTA5.

The issue is described and marked being solved here: https://github.com/GivePass/x360ce/issues/180

Example of a practical issue: In GTA5 you can't do a burnout without being able to press both triggers (accelerate + brake) at the same time.

The "Pass Through" option ain't an option because then I can't use acceleration curves and deadzone elimination.

Suggested workaround: New option "Trigger Pass Through" - maybe make a "Pass Through" group and add multiple checkboxes for every element? Like: LT, RT, Force, LStick, RStick, etc?

Suggested solution: Implement whatever "GivePass" did within their tree to fix this?

Before dismissing this, please consider: When not using x360ce and in "Pass Through" mode the triggers work together OK in GTA5, so I consider this to be a real issue - not just an inevitable result of having a "single axis", as suggested in issue 180 over at "GivePass" tree. Please don't dismiss this easily. Thank you :-)

**Comment by Nucleoprotein** [comment]
Then use KrossX Durazno (Xinput re-mapper): https://drive.google.com/folderview?id=0B1wssOeJs5_7czZ1WW93SzFxUWs&usp=sharing

**Comment by ssvx** [comment]
Thanks for making me feel like the last retard and not worth any conversation or explaination. Such a happy first impression of github sunshine for me. I'll leave you alone then.

Ps, to be clear: any intel about "doesn't work" or "can't do this, sorry" or "won't happen because this project is discontinued" would have been really nice. Closing this without any note, completely ignoring my kindly made request to not "dismiss easily" feels very rude. Thanks for the keywords "KrossX Durazno" tho, now looking into https://github.com/KrossX/Durazno - I'm just not sure why Google Drive has been linked directly instead of the project page.

**Comment by Nucleoprotein** [comment]
Because question about support of remapping Xinput was on Google code issue tracker before.
We not make support for this specific issue because:
- emulating DirectInput -> Xinput to only remap Xinput is not optimized way of doing things
- there exist other software that do same thing

**Comment by ssvx** [comment]
Ah, I see (and understand). 

Sorry I've missed that this issue had been discussed already. I thought I had thoroughly searched the issues before creating this and didn't find anything related to triggers - plus I didn't know that "remapping Xinput" is a whole different thing. Makes sense now and puts x360ce in a different light for me. Thank you very much for this piece of information :+1:
