### ISSUE TITLE
Steering wheel showing offline

### ISSUE THREAD

**Issue by W0lfiiii** [x360ce/x360ce#1238]
Hello! I got a Thrustmaster T150 Steering wheel & Pedals for christmas, and I've been wanting to use it on games that doesn't support steering wheels, but when I try to use the steering wheel with x360ce, it shows my steering wheel as offline. X360ce registers my pedal inputs and the buttons on my steering wheel, but it doesn't register when I turn my wheel in either direction. Please help!

**Comment by W0lfiiii** [comment]
Solved

**Comment by logitechg920steeringwheeluser** [comment]
wow it sure would be awesome if you could say how to fucking fix it
