### ISSUE TITLE
Doesn't function normally on Persona 4 Golden unlike in other games

### ISSUE THREAD

**Issue by ghost** [x360ce/x360ce#1247]
I'm 100 hours into the game and I noticed my left analog stick (mostly diagonally, northwest and southeast) doesn't function as well in the game. Tried testing it other games (GTA IV, Undertale and PSO2) and re-calibrate it, but my controllers seems to not have issues itself but instead either on the game or on x360ce. I also noticed in this picture below:
![image](https://user-images.githubusercontent.com/68719008/108610667-6ead0c00-7412-11eb-8edb-73ba65fbc36a.png)
That the mc seems to stop moving when the green plus is over the edge, same when northwest.

[https://youtu.be/2U_7dnGbWwI](url) <this is the video when I am struggling with this issue.
Controller: ファイナルファンタジーXIV推奨 USBゲームパッド JC-U3312BK-FF https://www2.elecom.co.jp/peripheral/gamepad/jc-u3312-ff/

**Comment by RobiNuzaman** [comment]
same problem, so I'm using xpadder now
