### ISSUE TITLE
Windows Defender Flagging Trojan

### ISSUE THREAD

**Issue by closure-io** [x360ce/x360ce#1251]
I was running a full scan earlier on my PC and caught a Trojan:Win32/Wacatac.B!ml alert within the ditool.exe file. I had this downloaded from 2017 and only recently hit this flag in AV, so I was curious if anyone else had run into this as well. I can paste the log from Windows Defender below. This was in the nucleus coop folder, but it was built using x360ce. From what I can tell changes haven't been made to the ditool.exe file in 6 years, so it would stand to reason that the version in this zip was the most up to date. 

I imagine this was probably a false flag, but from what I've read wacatac seems pretty serious, so I wanted to err on the side of caution. 

Detected: Trojan:Win32/Wacatac.B!ml
Status: Removed
A threat or app was removed from this device. 

Date: 2/26/2021 2:28 PM 
Details: This program is dangerous and executes commands from an attacker. 

Affected Items

containerfile: ...\Downloads\nucleuscoop-master.zip

file: ...\Downloads\nucleuscoop-master.zip->nucleuscoop-master/Master/ThirdParty/x360ce/branches/ffb-revision/x360ce/Support/ditool.exe

**Comment by EJocys** [comment]
ditool.exe on x360ce project was digitally signed on 2015-06-25.
https://github.com/x360ce/x360ce/blob/master/x360ce/Support/ditool.exe

I am signing all executables with Digital Signatures, so that users could check if original file was modified. If digital signature is OK, then file was not modified since 2015-06-25 and it must be a false positive.

You can go to Properties of ditool.exe and check if Digital Signature is not broken:

![image](https://user-images.githubusercontent.com/11958537/109388451-0755f700-78ff-11eb-95c6-4131cbc7ad53.png)

**Comment by closure-io** [comment]
Unfortunately there's not a way for me to verify the digital signature since the original file was deleted by Windows Defender. 

That said, looking at the rest of the folder, no other strange modifications had been made. Pulling the most recent version of ditool.exe directly from the repo still threw a flag from Windows Defender, so I quarantined the file and submitted it to Microsoft for evaluation. They got back to me and said it looked like a false positive and there was nothing to indicate malicious activity. They also mentioned they would update their definitions, so I imagine this will be resolved during the next Windows security patch. 

If you check virustotal there are a good number of AVs that flag this as malware. I imagine it has to do with tricking input being similar to activity caused by a virus, but I don't know for sure since I haven't dug into the code too much.

**Comment by EJocys** [comment]
Thank you for reporting this to Microsoft. This reminded me an issue when Windows Defender falsely flagged x360ce.exe for about 10 hours as Trojan:Win32/Emali.A!cl: https://github.com/x360ce/x360ce/issues/1137. Not a pleasant experience to be false flagged, but, when it comes to viruses, better safe than sorry :).
