### ISSUE TITLE
Can't steer and accelerate simultaneously

### ISSUE THREAD

**Issue by coder0x0** [x360ce/x360ce#1268]
Wheel: Logitech Formula Racing Wheel with Pedals (Driver: Logitech Racing Wheel USB) 
Program Version: 4.17.15.0
Mapping: 
_wheel x-axis <=> left stick move left/right (steer),
left pedal <=> left trigger (brake),
right pedal <=> right trigger (gas)_

Everything's working fine besides the fact that I can't brake/accelerate **and** steer at the same time. 
3-2-1... GO! I accelerate up to a decent speed and then have to steer a little to the right and gas is taken off.

_**Solution:**_
The Emulated XBOX Controller has to be set as default game controller in Windows to make sure games use this device on startup.

**Comment by tcfurrer** [comment]
<img width="290" alt="default_controller" src="https://github.com/x360ce/x360ce/assets/39924916/4f313cd5-6c57-4d7c-98e6-fdfd54862442">

Is this what you mean by "default game controller in Windows"?

This didn't fix the issue for me.  I'm trying to use a Logitech Extreme 3D Pro with Forza Horizon 5 and still the accelerator is ignored whenever I'm steering.

I'm running x360ce 4.17.15.0, by the way.
