### ISSUE TITLE
Vibration driver causes X360CE to crash but only the old version of X360ce works fine.

### ISSUE THREAD

**Issue by officialnochill** [x360ce/x360ce#1275]
Faulting application name: x360ce.exe, version: 4.17.15.0, time stamp: 0x5fb168db
Faulting module name: EZFRD64.DLL, version: 0.0.0.0, time stamp: 0x4693218c
Exception code: 0xc0000005
Fault offset: 0x0000000000003654
Faulting process id: 0x3344
Faulting application start time: 0x01d757b1e2ac40d0
Faulting application path: D:\Downloads\x360ce_2\x360ce.exe
Faulting module path: C:\WINDOWS\USB Vibration\7906\EZFRD64.DLL
Report Id: ce933f79-702a-4188-875d-4b019003741e

If I delete that file, the controller will work but the force feedback will not work. 
Using the older version of X360CE (the per game one) will work perfectly with vibration drivers as well, only the modern one crashes.

**Comment by Squall-Leonhart** [comment]
There is nothing for us to fix, the file is faulty and hasn't worked since 2016.
