### ISSUE TITLE
When I connect a gamepad to my PC, the program crashes without any notification

### ISSUE THREAD

**Issue by Zemanul** [x360ce/x360ce#1284]
Windows 10. Gamepad Dialog GP-A11. It good works with x360ce ver.3, but ver.4.17.15.0 crushes. I dot`t know, where i can find logs to put it here

**Comment by Zemanul** [comment]
Driver for gamepad downloaded

**Comment by Zemanul** [comment]
This problem was on x360ce v4.15.16.0 too, I just decided to wait for the fixes

**Comment by BarbosaRT** [comment]
The same

**Comment by Zemanul** [comment]
I find where are crush-reports, so I create new issue here: https://github.com/x360ce/x360ce/issues/1300
