### ISSUE TITLE
Cannot open the .exe 

### ISSUE THREAD

**Issue by okami-one** [x360ce/x360ce#129]
Getting this error when I try to open x360ce_x64.exe (I'm on 64-bit system)

![capture](https://cloud.githubusercontent.com/assets/12784380/8023972/1ab98cb6-0d40-11e5-96a4-5c7c1b665a81.PNG)

**Comment by Nucleoprotein** [comment]
I think `x360ce` directory in `%ProgramData%` does not exist here.

**Comment by Nucleoprotein** [comment]
Upps, duplicate of #127

**Comment by okami-one** [comment]
Thanks a lot! :+1:

**Comment by EJocys** [comment]
Fixed.
