### ISSUE TITLE
If I connect a gamepad to my PC, the program crashes without any notification, now with crash report

### ISSUE THREAD

**Issue by Zemanul** [x360ce/x360ce#1300]
Windows 10. Gamepad Dialog GP-A11. It good works with x360ce ver.3, but ver.4.17.15.0 crushes. I dot`t know, where I can find logs to put it here. I found where Windows hides crash reports, but I don`t know, what can I do with that

Version=1
EventType=APPCRASH
EventTime=132725798425895386
ReportType=2
Consent=1
UploadTime=132725798441985389
ReportStatus=268435456
ReportIdentifier=578f4210-a7ba-4ce0-ad1e-decfc3df03d0
IntegratorReportIdentifier=24d7f866-e6fa-421e-9307-07ca3dbc2667
Wow64Host=34404
NsAppName=x360ce.exe
OriginalFilename=x360ce.exe
AppSessionGuid=00003920-000a-0048-cdd7-3b0f6989d701
TargetAppId=W:0006561671cb1291bce6ba3444396577233100000000!000040ea5de9a7a15f6e0d891cd1ba4bca8519bb85ed!x360ce.exe
TargetAppVer=2020//11//15:17:43:55!ec6264!x360ce.exe
BootId=4294967295
TargetAsId=11052
UserImpactVector=816
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=26fd0fc5b8e8c8f8b73a9ab7a5bd67bf
Response.BucketTable=4
Response.LegacyBucketId=1673820325071906751
Response.type=4
Sig[0].Name=Имя приложения
Sig[0].Value=x360ce.exe
Sig[1].Name=Версия приложения
Sig[1].Value=4.17.15.0
Sig[2].Name=Отметка времени приложения
Sig[2].Value=5fb168db
Sig[3].Name=Имя модуля с ошибкой
Sig[3].Value=EZFRD64.DLL
Sig[4].Name=Версия модуля с ошибкой
Sig[4].Value=0.0.0.0
Sig[5].Name=Отметка времени модуля с ошибкой
Sig[5].Value=4693218c
Sig[6].Name=Код исключения
Sig[6].Value=c0000005
Sig[7].Name=Смещение исключения
Sig[7].Value=0000000000003654
DynamicSig[1].Name=Версия ОС
DynamicSig[1].Value=10.0.19042.2.0.0.768.100
DynamicSig[2].Name=Код языка
DynamicSig[2].Value=1049
DynamicSig[22].Name=Дополнительные сведения 1
DynamicSig[22].Value=2974
DynamicSig[23].Name=Дополнительные сведения 2
DynamicSig[23].Value=2974eb2886355bb10f029c5794b3d447
DynamicSig[24].Name=Дополнительные сведения 3
DynamicSig[24].Value=fa40
DynamicSig[25].Name=Дополнительные сведения 4
DynamicSig[25].Value=fa40bc81111a1887e4e9dfcd237474e4
UI[2]=G:\Programs\x360ce\ver4\x360ce.exe
LoadedModule[0]=G:\Programs\x360ce\ver4\x360ce.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[6]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\System32\sechost.dll
LoadedModule[8]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[9]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[10]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[11]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[12]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[13]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
LoadedModule[14]=C:\WINDOWS\System32\USER32.dll
LoadedModule[15]=C:\WINDOWS\System32\win32u.dll
LoadedModule[16]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[17]=C:\WINDOWS\SYSTEM32\VCRUNTIME140_CLR0400.dll
LoadedModule[18]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[19]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[20]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[21]=C:\WINDOWS\SYSTEM32\ucrtbase_clr0400.dll
LoadedModule[22]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[23]=C:\WINDOWS\System32\psapi.dll
LoadedModule[24]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\mscorlib\16234675ede351917e6b94c968a734df\mscorlib.ni.dll
LoadedModule[25]=C:\WINDOWS\System32\ole32.dll
LoadedModule[26]=C:\WINDOWS\System32\combase.dll
LoadedModule[27]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[28]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[29]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
LoadedModule[30]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System\f2fbfb8c5e5ca3d878cda8322aa09c62\System.ni.dll
LoadedModule[31]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Drawing\81542dd5dffc7bd19487acfcf85eaec8\System.Drawing.ni.dll
LoadedModule[32]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\f2ea7aa07968617d1133b79c0e2ce659\System.Windows.Forms.ni.dll
LoadedModule[33]=C:\WINDOWS\System32\shell32.dll
LoadedModule[34]=C:\WINDOWS\SYSTEM32\windows.storage.dll
LoadedModule[35]=C:\WINDOWS\SYSTEM32\Wldp.dll
LoadedModule[36]=C:\WINDOWS\System32\SHCORE.dll
LoadedModule[37]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Confe64a9051#\ad4ee62ffe1feb37ba604019f1addeda\System.Configuration.Install.ni.dll
LoadedModule[38]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Core\50e467896408e5712e17a1a135f5529a\System.Core.ni.dll
LoadedModule[39]=C:\WINDOWS\SYSTEM32\amsi.dll
LoadedModule[40]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[41]=C:\WINDOWS\SYSTEM32\profapi.dll
LoadedModule[42]=C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2107.4-0\MpOav.dll
LoadedModule[43]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[44]=C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.2107.4-0\MPCLIENT.DLL
LoadedModule[45]=C:\WINDOWS\SYSTEM32\gpapi.dll
LoadedModule[46]=C:\WINDOWS\SYSTEM32\sxs.dll
LoadedModule[47]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Configuration\865d52c0991b67808a106c3b5601bb33\System.Configuration.ni.dll
LoadedModule[48]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Xml\164cbde40352a6ecd3dec0af43a53fd0\System.Xml.ni.dll
LoadedModule[49]=C:\WINDOWS\System32\bcrypt.dll
LoadedModule[50]=C:\WINDOWS\SYSTEM32\CRYPTSP.dll
LoadedModule[51]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[52]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[53]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\WindowsBase\64722d8fb8086e6b58d9eb40e77fe2ca\WindowsBase.ni.dll
LoadedModule[54]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PresentationCore\70a7a4cc176e1b099c6992e82d3e8b82\PresentationCore.ni.dll
LoadedModule[55]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Runteb92aa12#\3f4bd85b05c17e6258072a05ecdbacb3\System.Runtime.Serialization.ni.dll
LoadedModule[56]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\comctl32.dll
LoadedModule[57]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.1110_none_91a01826cc8bca4c\gdiplus.dll
LoadedModule[58]=C:\WINDOWS\SYSTEM32\DWrite.dll
LoadedModule[59]=C:\WINDOWS\System32\MSCTF.dll
LoadedModule[60]=C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
LoadedModule[61]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[62]=C:\WINDOWS\System32\TextShaping.dll
LoadedModule[63]=C:\WINDOWS\SYSTEM32\MsftEdit.DLL
LoadedModule[64]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[65]=C:\Windows\System32\Windows.Globalization.dll
LoadedModule[66]=C:\Windows\System32\Bcp47Langs.dll
LoadedModule[67]=C:\Windows\System32\bcp47mrm.dll
LoadedModule[68]=C:\WINDOWS\SYSTEM32\globinputhost.dll
LoadedModule[69]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\comctl32.DLL
LoadedModule[70]=C:\WINDOWS\SYSTEM32\iphlpapi.dll
LoadedModule[71]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[72]=C:\WINDOWS\System32\NSI.dll
LoadedModule[73]=C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[74]=C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
LoadedModule[75]=C:\WINDOWS\SYSTEM32\WINNSI.DLL
LoadedModule[76]=C:\WINDOWS\System32\ws2_32.dll
LoadedModule[77]=C:\WINDOWS\system32\mswsock.dll
LoadedModule[78]=C:\WINDOWS\SYSTEM32\wtsapi32.dll
LoadedModule[79]=C:\WINDOWS\SYSTEM32\WINSTA.dll
LoadedModule[80]=C:\WINDOWS\SYSTEM32\secur32.dll
LoadedModule[81]=C:\WINDOWS\SYSTEM32\SSPICLI.DLL
LoadedModule[82]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Data\064e0ecafb415391138ca19c7de46d3d\System.Data.ni.dll
LoadedModule[83]=C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll
LoadedModule[84]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[85]=C:\WINDOWS\SYSTEM32\textinputframework.dll
LoadedModule[86]=C:\WINDOWS\System32\CoreUIComponents.dll
LoadedModule[87]=C:\WINDOWS\System32\CoreMessaging.dll
LoadedModule[88]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[89]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\Presentatio5ae0f00f#\97535ae9e5323cf0ec895c76784eacab\PresentationFramework.ni.dll
LoadedModule[90]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Xaml\3964cc0aad3412daf7b63deb9225fba3\System.Xaml.ni.dll
LoadedModule[91]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\wpfgfx_v0400.dll
LoadedModule[92]=C:\WINDOWS\SYSTEM32\MSVCP140_CLR0400.dll
LoadedModule[93]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\PresentationNative_v0400.dll
LoadedModule[94]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Numerics\ee2b6bd31331ebfeb2652dda601dd0e2\System.Numerics.ni.dll
LoadedModule[95]=C:\WINDOWS\SYSTEM32\DWMAPI.dll
LoadedModule[96]=C:\WINDOWS\SYSTEM32\d3d9.dll
LoadedModule[97]=C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_2635d5c616c804dc\nvldumdx.dll
LoadedModule[98]=C:\WINDOWS\SYSTEM32\msasn1.dll
LoadedModule[99]=C:\WINDOWS\SYSTEM32\cryptnet.dll
LoadedModule[100]=C:\WINDOWS\System32\WINTRUST.DLL
LoadedModule[101]=C:\WINDOWS\System32\imagehlp.dll
LoadedModule[102]=C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_2635d5c616c804dc\nvd3dumx.dll
LoadedModule[103]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[104]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\Presentatioaec034ca#\5442cec4d0ae545e9c141fbf0bf9afeb\PresentationFramework.Aero2.ni.dll
LoadedModule[105]=C:\WINDOWS\SYSTEM32\powrprof.dll
LoadedModule[106]=C:\WINDOWS\SYSTEM32\UMPDC.dll
LoadedModule[107]=C:\WINDOWS\system32\dataexchange.dll
LoadedModule[108]=C:\WINDOWS\system32\dcomp.dll
LoadedModule[109]=C:\WINDOWS\system32\d3d11.dll
LoadedModule[110]=C:\WINDOWS\system32\dxgi.dll
LoadedModule[111]=C:\WINDOWS\system32\twinapi.appcore.dll
LoadedModule[112]=C:\WINDOWS\SYSTEM32\dinput8.dll
LoadedModule[113]=C:\WINDOWS\SYSTEM32\inputhost.dll
LoadedModule[114]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[115]=C:\WINDOWS\SYSTEM32\HID.DLL
LoadedModule[116]=C:\WINDOWS\System32\SETUPAPI.DLL
LoadedModule[117]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[118]=C:\WINDOWS\SYSTEM32\DEVOBJ.dll
LoadedModule[119]=C:\WINDOWS\system32\nvspcap64.dll
LoadedModule[120]=C:\WINDOWS\SYSTEM32\dxcore.dll
LoadedModule[121]=C:\WINDOWS\SYSTEM32\D3DCOMPILER_47.dll
LoadedModule[122]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Web.Services\8bffa3b4f7885bf0a4815102b247502e\System.Web.Services.ni.dll
LoadedModule[123]=C:\WINDOWS\USB Vibration\7906\EZFRD64.DLL
LoadedModule[124]=C:\WINDOWS\SYSTEM32\DINPUT.dll
LoadedModule[125]=C:\ProgramData\X360CE\Temp\ViGEmClient.dll.84A31178\ViGEmClient.dll
LoadedModule[126]=C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
LoadedModule[127]=C:\WINDOWS\SYSTEM32\MSVCP140.dll
LoadedModule[128]=C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=19042
OsInfo[3].Key=ubr
OsInfo[3].Value=1110
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1049
OsInfo[7].Key=geoid
OsInfo[7].Value=203
OsInfo[8].Key=sku
OsInfo[8].Value=100
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=768
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=221206953
OsInfo[15].Key=osinsty
OsInfo[15].Value=3
OsInfo[16].Key=iever
OsInfo[16].Value=11.789.19041.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=6134
OsInfo[19].Key=svolsz
OsInfo[19].Value=199
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=191206
OsInfo[22].Key=bldtm
OsInfo[22].Value=1406
OsInfo[23].Key=bldbrch
OsInfo[23].Value=vb_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.19041.1110.amd64fre.vb_release.191206-1406
OsInfo[30].Key=buildflightid
OsInfo[30].Value=DAE2CE71-729B-45FF-8810-7BBCD473FF03.1
OsInfo[31].Key=edition
OsInfo[31].Value=CoreSingleLanguage
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=RS:81B6
OsInfo[34].Key=fconid
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
FriendlyEventName=Остановка работы
ConsentKey=APPCRASH
AppName=Jocys.com X360 Controller Emulator
AppPath=G:\Programs\x360ce\ver4\x360ce.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=854D142F5216E21914E3634D75186FE6
MetadataHash=-1057633159

**Comment by Zemanul** [comment]
Ugh... my google translate is more bad, that T9, and I cant do something with that

**Comment by Zemanul** [comment]
If I delete EZFRD64.DLL , the controller will work but the force feedback will not work.
Using the older version of X360CE (the per game one) will work perfectly with vibration drivers as well, only the modern one crashes.

**Comment by pranshuthegamer** [comment]
> 
> 
> If I delete EZFRD64.DLL , the controller will work but the force feedback will not work.
> Using the older version of X360CE (the per game one) will work perfectly with vibration drivers as well, only the modern one crashes.

same with me

**Comment by Squall-Leonhart** [comment]
Not our bug

**Comment by pranshuthegamer** [comment]
> Not our bug

btw, its a generic controller

**Comment by ali-ahnaf** [comment]
how did you fix the issue?

**Comment by pranshuthegamer** [comment]
this is not your bug, but this problem effects a lot of generic controllers, i think a lot of people have this issue. also, its only broken in 4.0 and works fine in 3.0, but something must have changed that broke it

**Comment by Squall-Leonhart** [comment]
it doesn't work fine in 3.0, its not used at all.

**Comment by pranshuthegamer** [comment]
> it doesn't work fine in 3.0, its not used at all.

i can make a video comparing the 2 versions if you need me to
also, this issue is related to vibration drivers

**Comment by Squall-Leonhart** [comment]
you miscomprehend.

The faulting DLL is not used by 3.0 x86, 4.0 is AnyCPU target and defaults to x64.
