### ISSUE TITLE
Missing Reference

### ISSUE THREAD

**Issue by Jadams29** [x360ce/x360ce#1304]
![image](https://user-images.githubusercontent.com/38890445/128763402-6df41fd6-72e0-4b48-b673-52d0813e4d34.png)

On line 42 in 'MainWindow.xaml.cs' it is trying to initialize the 'TlvSerializer'. 

The first problem I have found is that, I cannot find that file (TlvSerializer) anywhere, specifically when looking in x360ce.Engine.JocysCom.Data.TlvSerializer.cs is not there. That specific file is referenced only in MainWindow.xaml.cs.

If that file existed we could just include in the .csproj file.

**Comment by EJocys** [comment]
Thank you for reporting. Commited missing files of experimental project.
