### ISSUE TITLE
Windows 11 Program Freeze and Close Upon Opening ?

### ISSUE THREAD

**Issue by KanekoHato** [x360ce/x360ce#1311]
I Use windows 11 : V.220000.176
With bitdefender av
is there any log file that i can upload here ?

**Comment by KanekoHato** [comment]
Faulting application name: x360ce.exe, version: 4.17.15.0, time stamp: 0x5fb168db
Faulting module name: EZFRD64.DLL, version: 0.0.0.0, time stamp: 0x46282a8f
Exception code: 0xc0000005
Fault offset: 0x0000000000003654
Faulting process id: 0x3a44
Faulting application start time: 0x01d7a18c54ebec19
Faulting application path: C:\Users\*\OneDrive\Desktop\x360ce.exe
Faulting module path: C:\WINDOWS\USB Vibration\7906\EZFRD64.DLL
Report Id: cf1c1c5a-a115-4a68-9ad7-547e2bb62afe
Faulting package full name: 
Faulting package-relative application ID: 

Application: x360ce.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 0000000010003654
Stack:


Fault bucket 2255571936867376476, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: x360ce.exe
P2: 4.17.15.0
P3: 5fb168db
P4: EZFRD64.DLL
P5: 0.0.0.0
P6: 46282a8f
P7: c0000005
P8: 0000000000003654
P9: 
P10:

**Comment by Squall-Leonhart** [comment]
Not our bug
