### ISSUE TITLE
Messed up control sticks

### ISSUE THREAD

**Issue by RikuAzhurlar** [x360ce/x360ce#132]
So for some reason in certain games e.g. fallout newvegas. my control sticks are swapped and inverted. Aka left looks dow right looks up etc and I've tried both 32 and 64bit xinputs and fiddles with other settings to no avail. I'm using a PlayStation2 controller hooked up to a dongle. I can send logs if needed

**Comment by Squall-Leonhart** [comment]
that means it is enumerating to dinput and not xinput, no logs required, you just need to follow the game tutorials.
