### ISSUE TITLE
Where's the x360ce.ini and the dlls?

### ISSUE THREAD

**Issue by Rodillaconmorett** [x360ce/x360ce#134]
I only can find the x360ce.exe, but when i tried to launch it, occured an exception; "System.InvalidOperationException...", when clicked retry the app halt.
In many tutorials on youtube that explain how to install it, the interface of the page is completly different than the one that is today.
So, you moved the files or what?

**Comment by Squall-Leonhart** [comment]
post the full contents of the error message.
