### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [x360ce/x360ce#1340]
Hey there!

I belong to an open source security research community, and a member (@michaellrowley) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by EJocys** [comment]
Hi Jamie,

I've added SECURITY.md with an email for reporting security issues.

Kind regards,
Evaldas Jocys

**Comment by JamieSlome** [comment]
@EJocys - thanks for your response! ⚡ 

We will send you further details via e-mail! Otherwise, you can view both reports directly here:

https://huntr.dev/bounties/338d8486-b0e5-4242-884a-440912874e7e/
https://huntr.dev/bounties/1116abd8-2d8d-446f-90f6-c2a7d7e655b1/
