### ISSUE TITLE
map keys of keyboard

### ISSUE THREAD

**Issue by marcop123** [x360ce/x360ce#135]
Hi,

I like to know if is possible assign a key of keyboard to a button of joystick with x360ce.

There are many software that do it, but they don't emulate xinput, function very important.

For my opinion this feature is very useful, expecially if there is a macro function (assign different keys on one button ex: ALT + A).

**Comment by Squall-Leonhart** [comment]
no, and we have no intention of adding this support.

**Comment by X-Arcade** [comment]
Just curious, why are you folks so against keyboard support? Did TocaEdit start this project, and it had keyboard support?

**Comment by Nucleoprotein** [comment]
Yes and no, it never had keyboard support.

**Comment by X-Arcade** [comment]
I guess a user named viirus edited it to make it work with a keyboard, so just wonder why not. Many retro arcade enthusiasts use that version for their keyboard encoder based controllers and cabinets, but it won't work with the newest games.

See: http://forum.arcadecontrols.com/index.php?topic=96377.0

**Comment by Nucleoprotein** [comment]
If you talking about vibmod by Virus/Virusek - i'm that user, and I do not remember to adding keyboard support in it.

**Comment by X-Arcade** [comment]
"It is based on forum user RacerS’ X360 emulator which was later modded by user Viirus.  Capcom-unity forum user pkt has based his SFIV patch on these previous works." - I misread, pkt added the keyboard support. He did it in a day: http://www.capcom-unity.com/ask_capcom/go/thread/view/7371/18347559/sfiv-pc---2-players-on-keyboard?post_num=98#318969416

Anyhow, there are lot of retro arcade enthusiasts who would really appreciate the support for newer games like SFV: http://forum.arcadecontrols.com/index.php?topic=96377.120

**Comment by m93a** [comment]
This is exactly how an opensource project *should not* be maintained. I see you have some intention with this project but you should at least *explain*, why you aren't going to support features requested by your community. I'm not saying I'm angry or something, you have full right to reject such requests as you've put limitless efforts into coding the project. It just doesn't seem logical to reject a feature which a) doesn't make the application worse by any means and b) afaik there's no good substitute application for it. So be nice to your community!

**Comment by Squall-Leonhart** [comment]
Fuck off.

**Comment by EJocys** [comment]
Hi,

 >> you should at least /explain/, why you aren't going to support 
features requested by your community

I think, main reason is lack of free time due to other life priorities 
taking time. I am trying to code for at least 5 hours a week on this 
project and it makes updates slow. Now, main goal is to reduce amount of 
configuration needed by the users, so I am trying to rewrite all 
configuration part, so millions of records can be parsed and stored 
locally in a compact format. Second goal will be to use virtual XInput 
driver so there will be no need to mess with xinput dll files inside the 
game folder. I've experimented with adding keyboard support, but removed 
it later. There is a possibility that keyboard and mouse will be added 
in the future, but don't know when at the moment.

Sincerely,
Evaldas Jocys

**Comment by X-Arcade** [comment]
> . Second goal will be to use virtual XInput
driver so there will be no need to mess with xinput dll files inside the
game folder. 

Like Xoutput does? https://github.com/Stents-/XOutput/releases

That would be great. And not sure what's up with the rudeness/cursing from SL here for people asking,  keyboard-biggot, or what?

**Comment by Squall-Leonhart** [comment]
nah, response to a removed poster who decided to bitch/whine instead of taking the source and adding it himself.

**Comment by X-Arcade** [comment]
The X-Arcade controller acts like a keyboard, see layout here: https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/12001660453/original/PC_Layout_Mode1.JPG?1455235495

I would be willing to ship a free Tansktick controller to you folks if you would be able to add support for it. Seen here: https://shop.xgaming.com/collections/arcade-joysticks/products/x-arcade-tankstick-trackball-usb-included

**Comment by Bluscream** [comment]
> no, and we have no intention of adding this support.

big claps for you. you're a real hero
