### ISSUE TITLE
ViGemBus Uninstall

### ISSUE THREAD

**Issue by deonizm** [x360ce/x360ce#1353]
The vigembus install is silent. Where does it store the files? How can it be removed?

**Comment by EJocys** [comment]
You can use  Installer/Uninstaller of x360ce ([Options] -> [Virtual Device] tab):

![image](https://user-images.githubusercontent.com/11958537/166629889-1e77e125-578f-4ea9-adc8-c7136e7af22d.png)

Original Installer/Uninstaller is here: https://github.com/x360ce/x360ce/blob/master/x360ce.App.Beta/Resources/ViGEmBus.zip

You can extract it and run ViGEmBus_Setup.bat to uninstall:

![image](https://user-images.githubusercontent.com/11958537/166630799-ee4af477-8995-403f-a7d7-1ef961b6a52c.png)

Files:
"C:\Windows\System32\drivers\ViGEmBus.sys"
"C:\Windows\System32\WdfCoInstaller01009.dll"

DLL Client: c:\ProgramData\X360CE\Temp\ViGEmClient.dll.84A31178\ViGEmClient.dll
