### ISSUE TITLE
Program crashes everytime it's closed

### ISSUE THREAD

**Issue by darkdream787** [x360ce/x360ce#137]
I'm using windows 7 64-Bit operating system.

Everytime I close the program it crashes. I didn't find it a big deal since it still worked but, when I go to close my game, no matter what game it is, the game ends up crashing and I have to open task manager to be able to close it.

Problem signature:
  Problem Event Name:   BEX
  Application Name: x360ce.exe
  Application Version:  3.0.7.55
  Application Timestamp:    5575c1ba
  Fault Module Name:    GA0003FF.dll
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   3e0a94c6
  Exception Offset: 00001070
  Exception Code:   c0000005
  Exception Data:   00000008
  OS Version:   6.1.7601.2.1.0.256.48
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by Squall-Leonhart** [comment]
Not an issue in our code, issue is caused by bad rumble dll of controller driver.
