### ISSUE TITLE
What is the purpose/usage of x360ce.UserMacros.xml?

### ISSUE THREAD

**Issue by Valiante** [x360ce/x360ce#1370]
I noticed a file named _x360ce.UserMacros.xml_ in _ProgramData\X360CE\Settings_ and wondered as to its usage?  I can find no documentation anywhere, or indeed any search results at all pertaining to this file.

```
<!--Keyboard, mouse and xinput macro maps.-->
<Data Version="0">
  <Items />
</Data>
```

**Comment by garfieldbanks** [comment]
Did you ever figure this out? I don't understand why Jocys hasn't responded here... Why is there no documentation for creating a macro? I'd be fine doing it manually in the text file but I have no idea how to start. A simple example would be nice.

**Comment by Valiante** [comment]
I'm afraid not.

**Comment by EJocys** [comment]
@Valiante
The macro feature is not complete, and therefore hidden. It is designed for attaching macros (keyboard, mouse, and XInput actions) to Direct Input controller events. For example, the game will receive {ButtonX} and {DPadUp} press when Axis 5 on the mapped controller crosses the value of 22000. The RPM feature was intended to allow for mapping macro repetition to an axis. The further you move the axis, the faster the macro will repeat. This could be useful, for instance, when playing an old driving game where driving is done with keyboard keys using a controller.

![image](https://user-images.githubusercontent.com/11958537/223524025-eed4e98a-5152-4c8e-b2a7-306bc659b3fd.png)

```XML
<!--Keyboard, mouse and XInput macro maps.-->
<Data Version="0">
  <Items>
    <UserMacro>
      <Id>861b8afc-a277-4960-b493-87e23a052785</Id>
      <SettingId>8204af23-49ed-4873-ba95-cd28611fb5f3</SettingId>
      <MapType>1</MapType>
      <MapCode>0</MapCode>
      <MapIndex>10</MapIndex>
      <MapRangeMin>0</MapRangeMin>
      <MapRangeMax>0</MapRangeMax>
      <MapEventType>0</MapEventType>
      <MapRpmType>2</MapRpmType>
      <MapRpmMin>0</MapRpmMin>
      <MapRpmMax>0</MapRpmMax>
      <Name>Press X and Left Thumb Down</Name>
      <Text>{ButtonX}{LeftThumbDown}</Text>
      <IsEnabled>false</IsEnabled>
      <Checksum>00000000-0000-0000-0000-000000000000</Checksum>
      <Created>2023-03-07T18:52:28.7977504+00:00</Created>
      <Updated>2023-03-07T18:52:28.7977504+00:00</Updated>
    </UserMacro>
  </Items>
</Data>
```
