### ISSUE TITLE
Your beta links to a virus.

### ISSUE THREAD

**Issue by Evelyn-SoT** [x360ce/x360ce#1379]
Check your wiki page edits please, and please keep ontop of this. People are being infected due to people not paying attention to what happens to their github wikis.

Thank you.

- Someone who downloaded atrocious RAT.

**Comment by EJocys** [comment]
Thanks for reporting. I'll try to figure out how this was allowed on GitHub.

Restricted WIKI to collaborator only:
https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

**Comment by EJocys** [comment]
Added note to the front page:

> IMPORTANT: Please download and run digitally signed files only! If someone asks to disable antivirus or exclude X360CE app from anti-virus - DON'T! Report any suspicion in [Issues](https://github.com/x360ce/x360ce/issues) and we will try to resolve any false positive with anti-virus developers.
> 
> On 2022-07-14 some malicious people updated the "Beta Testing" WIKI page with a link to a file which was not signed by developers of X360CE.
> The "Beta Testing" WIKI page has been restored and all WIKI pages have been locked for project contributors only, to ensure this does not happen again.

**Comment by EJocys** [comment]
Did your antivirus detect anything specific?
Downloaded suspicious file and ran via VirusTotal:
https://www.virustotal.com/gui/file/8c9a297c7b28d63416428cf0eda4d1ced6cb928f9276d0408145fc86dceba73d

**Comment by EJocys** [comment]
@Evelyn-SoT Thank you again for reporting this. Sorry for the trouble. The beta page has been restored, WIKI is locked for contributors only, so the problem should not happen again. I've also tried to download older malicious files to test and run against VirusTotal, but it seems that the malicious files were removed quickly from external websites, which is probably why the WIKI page was updated so frequently.

Kind regards,
Evaldas Jocys

**Comment by FlooSz** [comment]
https://www.virustotal.com/gui/file/74faf334cb0bdd3e9dfab8c323d4eb3b9b089bcaadc7dbd639d9aa93a4f6f829 .... Not again!? this is for the exe in this Repo and here https://www.x360ce.com/

**Comment by FlooSz** [comment]
Is not flagged anymore cause you was hidden it better buts not clean.

Crowdsourced YARA rules
Matches rule MALWARE_Win_AgentRacoon from ruleset malware at https://github.com/ditekshen/detection by ditekShen
Detects AgentRacoon. Not Raccoon
Matches rule Origin from ruleset Origin at https://github.com/kevoreilly/CAPEv2 by kevoreilly
Origin Logger payload

**Comment by EJocys** [comment]
@FlooSz 

Tanks for reporting. Temporary false positive. That file (74faf334cb0bdd3e9dfab8c323d4eb3b9b089bcaadc7dbd639d9aa93a4f6f829 *x360ce.exe) is 4.5 years old and has a valid digital signature to confirm that it was not modified throughout this period.

![Image](https://github.com/user-attachments/assets/efbf326d-a19a-4c46-bcc9-0f2383cefd5b)

Kind regards,
Evaldas Jocys
