### ISSUE TITLE
Dead Rising 2 won't work with x360ce

### ISSUE THREAD

**Issue by TheSnoogans** [x360ce/x360ce#138]
I tried a bunch of hook masks with my Xbox 360 controller but seemingly none of them work. Both Force feedback and pass through are unchecked, so I have no idea what else to try here.

Oh and there's no Init Beep sound, and controller option in setting is greyed out, so I can't possibly turn it on.

**Comment by Squall-Leonhart** [comment]
if theres no beep, then dll is not being loaded.

use forum for game support.
