### ISSUE TITLE
Can't build due to missing AssemblyInfo.Ext1.cs

### ISSUE THREAD

**Issue by cocoelacanth** [x360ce/x360ce#1390]
When attempting to build x360ce from source using Visual Studio 2022, the build fails with the error:

>Source file 'D:\Downloads\x360ce\x360ce.Engine\JocysCom\Configuration\AssemblyInfo.Ext1.cs' could not be found.

I have checked for the file in question, and the only trace of it is a symlink that leads to a nonexistent location.

>D:\Projects\Jocys.com\Class Library\Configuration\AssemblyInfo.Ext1.cs

The file appears to have been added by 94416568d30b1e44631d116ac920589f60b0b1f1, and has not been updated since.

Of course, I could attempt to build 5e1ed440ecd23657f5bad2482ba336d2f9674e17 instead, which directly precedes the change, but this is not ideal as this commit is five months old and there have been 18 more commits since then.

**Comment by EJocys** [comment]
@CocoTheMii Thanks for reporting. Committed missing file.
