### ISSUE TITLE
HID Guardian disabled all devices after proper uninstall

### ISSUE THREAD

**Issue by NancokPS2** [x360ce/x360ce#1429]
Sorry that i cannot provide much info, but it left my pc unusable  
I cannot access the advanced menu because i cannot use my keyboard, is there anything i can do?

**Comment by EJocys** [comment]
How to remove HID Guardian if access to your Mouse and Keyboard is lost (X360CE v4.x)

Instructions: https://github.com/x360ce/x360ce/wiki/HID-Guardian

**Comment by NancokPS2** [comment]
Update, i did as mentioned in the post exactly as described trough another install, it did not fix it.  
This issue is not solved

**Comment by NancokPS2** [comment]
> How to remove HID Guardian if access to your Mouse and Keyboard is lost (X360CE v4.x)
> 
> Instructions: https://github.com/x360ce/x360ce/wiki/HID-Guardian

Not working
