### ISSUE TITLE
x360ce gives the error FCE_DInputException after I deleted the (C:\Windows\USB_Vibration\081001\EZFRD64.DLL) because it makes x360ce crash

### ISSUE THREAD

**Issue by marawana988** [x360ce/x360ce#1438]
![Screenshot 2023-05-13 152820](https://github.com/x360ce/x360ce/assets/67123294/12a1df9a-4342-42ae-b0b0-fb8111eae4f3)
![image](https://github.com/x360ce/x360ce/assets/67123294/8f331fd5-69f0-4042-b5b7-db3a2bf0d805)
[https://we.tl/t-7a7Qm7m3bj](url) error file

**Comment by Squall-Leonhart** [comment]
You cannot have a faulting module if that module doesn't exist.
