### ISSUE TITLE
X360 problem with loading

### ISSUE THREAD

**Issue by TheM4tix** [x360ce/x360ce#1439]
Hello, i have an issue with my x360ce application, it's not working.
![image](https://github.com/x360ce/x360ce/assets/133534996/decc50dc-21d5-4354-81ef-f2430443c8be)
As you can see in the attached picture, it stays like this all the time, even though the application does not crash, nothing loads, and it stays like that, reinstallation did not help, please help.

**Comment by smurillox** [comment]
try run as admin

**Comment by TheM4tix** [comment]
didn't help

**Comment by lufog** [comment]
Went from x360ce to XOutput + HidHide, work as charm on latest Win11.

**Comment by TheM4tix** [comment]
> Went from x360ce to XOutput + HidHide, work as charm on latest Win11.

thank you <3
