### ISSUE TITLE
dinput8.dll not created by x360ce application

### ISSUE THREAD

**Issue by killa2103** [x360ce/x360ce#144]
I wanted to run my controller with Mortal kombat x but in a tutorial I saw it needs 64 bit libraries. I cant find download link for libraries. But then I found the application creates xinput.dll and x360ce.ini but does not creates dinput8.dll. Where can I find dinput8.dll (64bit). Please help!!

**Comment by killa2103** [comment]
I managed to download 64bit libraries with dinput8 but that too didn't work neither in gta 5 nor in mk10 both crash immediately after launching....I don't know wats wrong.. all other games work fine with x360ce except gta 5 and mk10

**Comment by Squall-Leonhart** [comment]
neither of these games requires dinput8.dll
