### ISSUE TITLE
BSOD at First Run

### ISSUE THREAD

**Issue by johnjar28** [x360ce/x360ce#1445]
When I run x360ce my computer restarts with a blue screen of death. It displays " Thread exception code could not be handled ".
It records data from 0 to 100 % and then restarts. No Error Code is displayed. Note the normal x360ce background screen is displayed for a minute before the restart happens. This is a Windows 10 64 bit machine. 
Thank you for your time and help, johnjar28

**Comment by Squall-Leonhart** [comment]
update vigem
