### ISSUE TITLE
Keyboard not working after opening x360ce

### ISSUE THREAD

**Issue by mdrakibur179** [x360ce/x360ce#1456]
I am having problems with my keyboard after opening x360ce. All the switches are blocked. Mouse is working.

My PC: 
CPU: Ryzen 5 5600G
MoBo: Gigabyte b550

But, on other PC I tried, it was all okay.

I tried on another PC with: 
CPU: Ryzen 5 5600G
MoBo: Asrock b450

**Comment by AnIHULI** [comment]
Try to enable/disable several times checkbox "Enable # Mapped Device". It helps me sometime.
I have same issue with amd 3400g, msi x570
