### ISSUE TITLE
Game list with full support of force feedback / vibrations that work with x360ce

### ISSUE THREAD

**Issue by marcop123** [x360ce/x360ce#147]
Hi,

I think can be usefull a list of games with force feedback / vibration tested with x360ce.

Actually there is only a list of supported games, but nothing about if the force feedback is tested with x360ce.

I suppose some games need a particular setting to enabled this feature or simply not work.

Many joypads support this features, including my joystick Microsoft Sidewinder Force Feedback 2.

Best Regards

Marco

**Comment by Squall-Leonhart** [comment]
vibration working is a matter of controller compatibility, not game  compatibility (with single digit exceptions)
