### ISSUE TITLE
Game: Never Alone. (Kisima Inŋitchuŋa). X360ce does not work with that title.

### ISSUE THREAD

**Issue by Sopheus** [x360ce/x360ce#148]
The title. :(.

Any workarounds?

**Comment by Squall-Leonhart** [comment]
Unity engine does not use xinput for accepting directional information.

**Comment by Sopheus** [comment]
No, I have successfully managed to make x360ce work with the game through hook masks. The only issue left is vibration does not work.

**Comment by pmhpereira** [comment]
@Sopheus, what settings (dll, hookmasks) did you use? I can't make it work.
