### ISSUE TITLE
Right Stick is using Y,X,B,A buttons, Left Stick Problem too

### ISSUE THREAD

**Issue by mrmohy** [x360ce/x360ce#150]
Hi Guys,

I'm using a copy of PSController, works on other games well, but borderlands 2 requires me to use XBOX so I used this program and it didn't go well.

This is my first time using this app, i don't really know what to configure on the settings here. While I'm playing borderlands 2, my left stick going to left and right is fine but when press up and down, it's like moving my mouse up and down instead of walking, while my right stick using buttons yxba instead of looking up,down,side.

I don't know how to remap this because i don't know what are the button/parts of a console controller, sorry. I'm new in these controllers.

I hope someone help me with my problem.

Thanks guys!

**Comment by Nucleoprotein** [comment]
This is not place for such help, go to x360ce forum: http://ngemu.com/forums/x360ce.140/

**Comment by KrazyCat27** [comment]
DO you see the analog button on your pscontroller?
