### ISSUE TITLE
Austria and Australia

### ISSUE THREAD

**Issue by LaugeSvan** [x360ce/x360ce#1501]
Hi! It's really bothering me, because what you're calling Austria is actually Australia and vice versa

**Comment by EJocys** [comment]
Yes, it looks like we might have confused the land of the kangaroos with the homeland of Mozart! Fortunately, our unerring map offers definitive proof of our well-investigated conclusions.

https://www.x360ce.com/Files/Website_x360ce/Australia_and_Austria_Big.jpg

**Comment by EJocys** [comment]
Sorry, forgot to translate into "Kangaroo English":
[ƃdɾ˙ƃıq‾ɐıɹʇsn∀‾puɐ‾ɐıןɐɹʇsn∀/ǝɔ063x‾ǝʇısqǝM/sǝןıℲ/ɯoɔ˙ǝɔ063x˙ʍʍʍ//:sdʇʇɥ](https://www.x360ce.com/Files/Website_x360ce/Australia_and_Austria_Big.jpg)
.suoᴉsulɔuoɔ ǝʇɐƃᴉʇsǝʌuᴉ llǝʍ ɹno ɟo ɟooɹd ǝʌᴉʇᴉuᴉɟǝp sɹǝɟɟo dɐɯ ƃuᴉɹɹǝun, ʎlǝʇɐunʇɹoℲ ¡ʇɹɐzʇoW ɟo puɐlɯoɥ ǝɥʇ ɥʇᴉʍ sooɹɐƃuɐʞ ɟo puɐl ǝɥʇ pǝsnɟuoɔ ǝʌɐɥ ʇɥƃᴉɯ ǝʍ ǝʞᴉl sʞool ʇᴉ 'sǝ⅄
