### ISSUE TITLE
proplem

### ISSUE THREAD

**Issue by ahmedmoniem** [x360ce/x360ce#151]
when i open x360ce it told me that MSVCR120.dll is missing and failed to load xinput1_3.dll and when i downloaded the MSVCR120.dll the proplem still exict what can i do please

**Comment by Nucleoprotein** [comment]
Do I really need to comment this ?
Install all required redistributes.

**Comment by ahmedmoniem** [comment]
i dont understan

**Comment by ahmedmoniem** [comment]
i have a proplem can u help me plzz

**Comment by Nucleoprotein** [comment]
Can't because THIS IS NOT PLACE FOR THIS, use forums.
I do not know why people make issues about config/installation ...

**Comment by ahmedmoniem** [comment]
i installed all requirments and i need help please

**Comment by Nucleoprotein** [comment]
No - you not installed all requirements, because MSVCR120.dll is in one of them.

**Comment by ahmedmoniem** [comment]
u mean this requirments right ?
.NET 3.5 (also installs 2.0 and 3.0) (included in Windows 7)
.NET 4.0 (link to 4.5, also installs 4.0) (included with Windows 8)
.NET 4.5 is not supported on Windows XP SP3, download .NET 4.0 from here.
DirectX End-User Runtimes (June 2010) (Required regardless of OS)
Depending on the library, either one or both of the following redistributable:
Visual C++ Redistributable for Visual Studio 2010 SP1
Visual C++ Redistributable for Visual Studio 2013

**Comment by Nucleoprotein** [comment]
I will now delete all you posts and will not respond to any of them - go to forums for help about installation. issue tracker Is for reporting bugs only! Not user help.

**Comment by ahmedmoniem** [comment]
thank u for ur help !!!!!!!!!!!!

**Comment by ahmedmoniem** [comment]
where is the forum

**Comment by Nucleoprotein** [comment]
Yes, now blame me for your stupidity and bloating our issue tracker...

Forum link: http://ngemu.com/forums/x360ce.140/

**Comment by Nucleoprotein** [comment]
Updated System Requirements section of Readme, you should find your solution there...
ie. you not installed VS2013 x86 or x64 redistributable - best is to install both.
