### ISSUE TITLE
Error when running the latest version.

### ISSUE THREAD

**Issue by ghost** [x360ce/x360ce#152]
![image](https://cloud.githubusercontent.com/assets/13013017/8302158/0ca91ff6-199d-11e5-83b9-7933d9343ed0.png)

**Comment by 4ndyD** [comment]
I also have [this issue](http://pastebin.com/i5z9LrjB) when running on Win7 64 - error CS0012

**Comment by samgreen** [comment]
http://www.microsoft.com/en-us/download/confirmation.aspx?id=42642
