### ISSUE TITLE
Computer gets in Stand-by playing Dark Souls 2 SOTFS

### ISSUE THREAD

**Issue by Foxdodger** [x360ce/x360ce#155]
I play normally but seems he don't detect joystick like a impulse key, so if i play on joystick , is like i being afk on PC. So after 15 min my pc enter in standby if i forget to use the mouse in this period.
Any fix?

**Comment by araujorm** [comment]
Issue already reported:

https://github.com/x360ce/x360ce/issues/141
(seems to me you should have searched first)

It seems to have been fixed today on the code, let's hope a new release will come soon :)

**Comment by EJocys** [comment]
New version release: v3.0.7.57 (2015-06-25)
- Update: Updated to xinput1_3.dll v3.4.1.1346.
- Update: Updated x360ce_Games.xml.gz

**Comment by Nucleoprotein** [comment]
Closed by PR #156
