### ISSUE TITLE
No license for x360ce Application

### ISSUE THREAD

**Issue by EJocys** [x360ce/x360ce#160]
At the moment application don't have license. I would like to put x360ce Application under same "GNU Lesser General Public License v3.0" as x360ce.dll

http://choosealicense.com/licenses
http://choosealicense.com/licenses/lgpl-3.0

It would be easier for third party developers to spread it.

Any suggestions or objections?

**Comment by Squall-Leonhart** [comment]
personally, i would suggest a custom license 
GPL Allows that the likes of madcatz or someone else could take the code, make some changes and then sell it

**Comment by Nucleoprotein** [comment]
GPL allows that ? I don't think so. GPL mandates that all modified code must be released under it.

**Comment by Squall-Leonhart** [comment]
It does.

Does the GPL allow me to sell copies of the program for money? (#DoesTheGPLAllowMoney)

```
Yes, the GPL allows everyone to do this. The right to sell copies is part of the definition of free software. Except in one special situation, there is no limit on what price you can charge. (The one exception is the required written offer to provide source code that must accompany binary-only release.)
```

**Comment by EJocys** [comment]
I don't mind to have LGPL license, even if it allows third parties to sell x360ce, as long as third parties are forced to provide all changes they made in an open source format. I doubt that third party would try to make money from x360ce when it is available for free.

**Comment by EJocys** [comment]
Another thing, because we are holding the copyright on the software, we can do whatever we want with it. We are free to re-license it with new version.

**Comment by EJocys** [comment]
So, if nobody objects, I will release x360ce Application 3.1.7.x with "GNU Lesser General Public License v3.0" license after ~24-48 hours. It gives enough freedoms and we can change it for new versions if companies starts to abuse it.

**Comment by EJocys** [comment]
Done.
