### ISSUE TITLE
cant hold both triggers down at the same time

### ISSUE THREAD

**Issue by jelloo** [x360ce/x360ce#162]
Hello.

like the title says, im trying to set up my original xbox360 wireless controller for a game, but it doesnt let me aim and shoot at the same time. all i want is to switch some buttons.

ButtonA to left bumper and left stick-klick to right bumper, nothing more. this works fine when i uncheck the box "pass through" in the options but the triggers wont work anymore.

ive tried all the axis variations + everything else i could imagine to to for several hours now but cant get this issue fixed, its really frustrating and annoying. i would be really happy if someone could help me with this.

sorry for bad english.

bye

**Comment by Nucleoprotein** [comment]
Remapping in x360ce only works for emulated devices, but for original x360 controller you will loose ability to use both triggers at the same time if you use DirectInput to Xinput emulation.
If you want to remap Xinput use Durazno: https://github.com/KrossX/Durazno

**Comment by jelloo** [comment]
thanks for the answere. i tried durazno now but it doesnt work ingame. the gui says the buttons are remapped, i copied all 3 files in the game directory where the exe lies and tried to rename the ddl. nothing works. i think i´ll give up on this, thanks anyway.

edit: got it working now, was using the wrong dll. thanks
