### ISSUE TITLE
Risk of Rain, Monaco, Hero Siege don't recognize controller

### ISSUE THREAD

**Issue by Samkiud** [x360ce/x360ce#170]
I don't know what I'm doing wrong.

I unzip the files in the corresponding folder where the .exe of the game is located. I tried from renaming the .dll files to changing from version 2 to version 1 and nothing works.

The software works with Castle Crashers, Square Heroes and Megabyte Punch, however. I use Windows 7, 32 Bits.

**Comment by Squall-Leonhart** [comment]
check forums for prior threads regarding these games.

**Comment by Samkiud** [comment]
I already did, and I haven't see any viable solution, that's why I'm recurring to this forum.

**Comment by Squall-Leonhart** [comment]
This is not a forum, this is an issue tracker for bugs.

It is not a place to found out what games work with the wrapper.
