### ISSUE TITLE
Latest AVG update blocks x360ce from starting

### ISSUE THREAD

**Issue by SirePi** [x360ce/x360ce#172]
Not an issue of x360ce itself, but I noticed that sometime in the last week it stopped showing the config screen, although the emulation in game works properly.

In order to make it work again, I had to add x360ce.exe to the exceptions list in AVG. Probably one of the latest virus definition updates is blocking it.

**Comment by mirh** [comment]
You should [report](http://www.avg.com/submit-sample) to them. It's really none of our business.

**Comment by Squall-Leonhart** [comment]
AVG is malware

**Comment by SirePi** [comment]
@mirhl, I already did. I also declared that it's not an issue of x360ce, but at the same time I though it would be good to inform you guys of the situation. Even if only for adding a line to the FAQs or the wiki about this possibility, in case someone else faces the same problem.
