### ISSUE TITLE
how to play windows 8.1 apps using xbox 360 emulator x360e

### ISSUE THREAD

**Issue by brbrbr5** [x360ce/x360ce#176]
hi, i am using windows 8.1 in my pc and i want to play fifa 15 ultimate team app which need xbox 360 controller but i gave frontech jil 1731 gamepad . but i can't copy the x360ce files to the game directory C:\Program Files\WindowsApps cause it is inaccessible . so please tell me how to play windows 8.1 apps using xbox 360 emulator x360e ? also i am uploading my x360ce.ini , please see that and tell me is there anything wrong? https://drive.google.com/file/d/0B3nPfc6dsxXud19MTl9Oa3hEM2M/view?usp=sharing

**Comment by Squall-Leonhart** [comment]
You must learn how to take ownership of the location and figure it out for yourself.

**Comment by brbrbr5** [comment]
thank you for replying. ya i have already done that. after taking ownership of game folder and putting the x360ce files inside game folder C:\Program Files\WindowsApps\fifa15 , the app does not starts and hangs up in a gray window and after some time the error message shown and asked to automatic repair the app which redownloads and reinstalls the app and deletes previously installed app's files. Please help me to solve this issue. also please tell me is there any way to run the emulator in a way that will convert the dinput to xinput for all the time even when game is not running and for all games and it will not need to put any files inside every game directory.

**Comment by Squall-Leonhart** [comment]
WindowsApps are architecture dependent afaik, so if you have a 64bit os, the app will be too.

**Comment by brbrbr5** [comment]
ya i used 64bit x360ce but same error happening. please help me.
