### ISSUE TITLE
Can't find the libraries to download it here

### ISSUE THREAD

**Issue by moracabanas** [x360ce/x360ce#177]
Hi, i'm trying to play Shadows of Mordor with x360ce but I can't find the libraries all people are talking about. The wiki is empty and only a README file on Github. Inside the README file there are some libraries tutorial. Inside tutorials there are some links to download libraries, all of them linked to the old google code. When I go to this links I go came here again on Github and i can't find any library. I am desperated now. What can i do?

Thanks for all

**Comment by Squall-Leonhart** [comment]
Have answered this multiple times, im not answering it again.
