### ISSUE TITLE
Problem with x360ce_x64 

### ISSUE THREAD

**Issue by Hiennc** [x360ce/x360ce#180]
I have a trouble with my analog stick
In x360ce_x32 , it always like this
![x32](https://cloud.githubusercontent.com/assets/13377236/8742437/8b8b9bf0-2c8f-11e5-919b-0da17252b0de.jpg)
But in x360_x64 , it works perfectly
![x64](https://cloud.githubusercontent.com/assets/13377236/8742444/9ad1c422-2c8f-11e5-9b12-c2d3d932f6a4.jpg)

Calibration is OK
![cali](https://cloud.githubusercontent.com/assets/13377236/8742538/951c02a8-2c90-11e5-9e33-2876c306f966.jpg)

Trouble again when my game Pro Evolution Soccer 2015 ( PES 2015) only load x32 verion. x64 version could not be loaded in that game. 
I tried many ways ( change xinput1_3.dll 32 >< 64 , convert, use other library.....) but still not work.
Anyone help me. Please!!!!

**Comment by Squall-Leonhart** [comment]
Disable the unused port/controller in device manager, this is an issue with the way the device works.

These devices are actually in violation of usb spec.

**Comment by Hiennc** [comment]
Disable all device. Still not work. 
I plugged it in another computers. It works perfectly without configuration. Directly input.

**Comment by Squall-Leonhart** [comment]
try running the wingman reset utility.
