### ISSUE TITLE
Win 8.1 games doesn,t recognize controller

### ISSUE THREAD

**Issue by Fingal** [x360ce/x360ce#181]
I used x360ce with my old pc with windows 7. now I've got win8.1 and games don't recognize gamepads. drivers are working correctly and I set up everything in x360ce, but games don't respond to gamepad. I tried it with games that worked fine on old pc.

**Comment by juhor00** [comment]
I have kinda same problem. Everything works fine in x360ce but in the NFS Rivals when i have to press  A (x) it doesn't work but R1 does (as A) And I cant switch the buttons in the game. So in the x360ce everything works fine but in the game it messed up.

**Comment by Squall-Leonhart** [comment]
configuration issues belong on the forum.
