### ISSUE TITLE
x360ce not functioning

### ISSUE THREAD

**Issue by jafarali** [x360ce/x360ce#182]
when i try to play don bradman cricket 2014 the x 360ce comes like this. this happened when i reinstall the os windows 8.1. but my previous os is also windows 8.1. before that i can able to play. the controller 1 is connected but now it is saying some directx input some thing like that
![untitled](https://cloud.githubusercontent.com/assets/12654196/8761355/31fb3e6a-2d02-11e5-9643-fda97676fc8f.jpg)

**Comment by Squall-Leonhart** [comment]
You are missing the DirectX managed runtime, a listed requirement.

However that version of the setup app is out of date, we don't even use that file anymore since moving to sharpdx.
