### ISSUE TITLE
Playstation

### ISSUE THREAD

**Issue by wojtenfall** [x360ce/x360ce#183]
Is there any way for the games to show playstation buttons instead of xbox? This is sometimes confusing while using a playstation controller.

**Comment by dwillbarron** [comment]
X360CE has no control over the button prompts that a game displays. This is strictly in the hands of the developer or modders. In the future, general questions about x360ce are best suited for the forum at http://ngemu.com/forums/x360ce.140/ as Github's issue tracker is intended for bug reports and suggested changes.
