### ISSUE TITLE
32-Bit version will not work on Windows 8 (failed to load xinput1_3.dll %1 is not a valid win32 application)

### ISSUE THREAD

**Issue by darkdream787** [x360ce/x360ce#185]
Mine says this every time I even open the x360ce program 32-bit version and I have tried several versions.

"failed to load xinput1_3.dll %1 is not a valid win32 application"

The 64-bit version runs fine but it wont work for 32-bit games and that's what I'm wanting to play, yet I cant even get it to work without an error that stops me from being able to set any buttons. It doesn't detect my controller in game with the 64-Bit version and the 32-Bit one is the proper one to use for this game. Problem is, it wont even work and I see that error all the time. If I try to run the game with the xinput1_3.dll the 32-bit one created while it wasn't working because of the mentioned error, the game just crashes upon startup and wont even open.

I even tried running this on another computer and I am getting the same issue with 4 different versions of this software. The newest one, and 3 older ones from a couple months ago.

I made sure to have every single thing that was on the requirements list to be installed properly before attempting to use this software. I used this software just fine about 4 months ago on another game, but now that I try to use it again recently, it will not work at all.

**Comment by Squall-Leonhart** [comment]
Issue is on your end, runtime is missing or corrupted.

**Comment by darkdream787** [comment]
Your help here absolutely sucks. You put the blame on everything but the program it looks like.

I never said it wasn't an issue on my end, I came here for a solution yo my problem, not a short stuck up reply then closing.

**Comment by EJocys** [comment]
Maybe xinput1_3.dll was corrupted by virus or some other issue. One solution would be to check digital signature and see if DLL file was not modified (maybe I will include into application that feature later). In most cases deleting xinput1_3.dll could help, because it would force application to extract correct DLL file (32-bit, 64-bit).

**Comment by Squall-Leonhart** [comment]
Previous instances of this issue have been caused by incorrect VC runtime being installed (ie, app needs update 3 runtime, and update 1 runtime installed)

**Comment by gamer436** [comment]
i have installed all visual c++ versions still i am getting "failed to load xinput1_3.dll %1 is not a valid win32 application" error in 32 bit version 64bit is fine but most games dorsnt work with 64 bit any solutions
