### ISSUE TITLE
xbox360ce launch error - entry point not found...rpcrt4.dll

### ISSUE THREAD

**Issue by darksouls40k** [x360ce/x360ce#188]
I am using windows 7

A few months ago I used the xbox360ce without any problems...

After a 1 or 2 months of not using it I now cant launch either the version that I had working before or the latest version as of this date.

It gives back the same error:

"
x360ce.exe - Entry poin not found

The procedure entry point I_RpcBindingSetPrivateOption could not be located in the dynamic link library RPCRT4.dll
"

The game which i already had configured the gamepad for is still working like b4 too I just cant launch the app and therefore use it for new games...

I have no idea if it was something i uninstalled in those 2 months, but i read about it on the net and i did stuff like scanning for files integrity, reinstalling microsoft.net4.5.2, reactivating microsoft.net3.5 but nothing ...

Anyone has any idea ?

**Comment by Squall-Leonhart** [comment]
please try removing kb3067505

**Comment by darksouls40k** [comment]
Already tried everything u said including what u wrote on the other site about the updates....

Meanwhile i remembered uninstalling something with directx in its name if im not mistaken, in the programs list cause it was an outdated program that didnt make sense to me to keep it since i already had the latest version... no idea though if this might be related or not...

**Comment by Squall-Leonhart** [comment]
Caused by corrupt windows install.
