### ISSUE TITLE
How to configure controllers offline

### ISSUE THREAD

**Issue by findbmx** [x360ce/x360ce#189]
previously there was a preset option which i cant find it any more on the new version. so what is the best way to configure controllers while offline?

**Comment by Squall-Leonhart** [comment]
The web presets feature has not been removed at all.

**Comment by findbmx** [comment]
no I'm talking about the drop down menu where you could choose between different presets like Philips wireless controller or other controllers to see which one fits. it was in the place of where now is the "game controllers" button.

**Comment by Squall-Leonhart** [comment]
the contents of that menu have been moved to the "Default Settings for most popular controllers" subtab that is exposed by clicking on the "Controller Settings" tab.
