### ISSUE TITLE
It just wont launch

### ISSUE THREAD

**Issue by JonnyC02** [x360ce/x360ce#192]
I am trying to launch the program and it wont i have tried everything but it wont work need help

**Comment by Squall-Leonhart** [comment]
That doesn't give us a lot to work from, so start by checking over the system requirements listed in the readme.

**Comment by specterbane** [comment]
I had to run the application in compatibility mode with Windows 7 to get it to work. Must have been something in one of the newer Windows Updates.

**Comment by JonnyC02** [comment]
Whenever i double click nothing happens it just stays on my desktop even if
i run as admin

**Comment by Nucleoprotein** [comment]
Anti-virus software problem ?

**Comment by JonnyC02** [comment]
Im on windows 8
Was just about to update to 10

**Comment by samgreen** [comment]
http://www.microsoft.com/en-us/download/confirmation.aspx?id=42642

**Comment by artista3d** [comment]
Hi,
I have the same problem. It won't start at all and no errors either. I have updated my dot net. I run win7... 64bit.
Your help will be appreciated. Thank you!

**Comment by Squall-Leonhart** [comment]
It is either blocked by antivirus, or dotnet 4.x is not installed.
