### ISSUE TITLE
Program doesn't start with the game

### ISSUE THREAD

**Issue by iCr4cker** [x360ce/x360ce#193]
I'm trying to play Rocket League with a gamepad called "CSL USB Gamepad C180". If I open the x360ce_x64.exe, the program starts, but if I start the game, the program doesn't run in the background. I had some issues when I first tried it out, but then it worked perfectly. Don't know how i fixed that. After I reinstalled Win 8 (for cleaning it up and so), it didn't work for me again. I tried a few things like reinstalling drivers and reinstalling the game itself and also the program, but it didn't work at all.

This is the gamefolder
![unbenannt](https://cloud.githubusercontent.com/assets/13601170/9022133/c5482c2a-3868-11e5-8e63-84102a85393d.PNG)

Hope you can help <3

**Comment by Squall-Leonhart** [comment]
The application is not supposed to run in the background, you run the application, create the settings file, assign your controller's buttons and vibration settings(if any) and then save and exit.
