### ISSUE TITLE
Not working with Batman: AK

### ISSUE THREAD

**Issue by gentlemanboy** [x360ce/x360ce#194]
I searched alot on the web, and find nothing about it, seems AK thinks my controller is a PS4 controller, and I'm using the same control configs I use on my others games.. please, if anyone knows how to fix it , i will be very grateful :D , and, on the game part of the controller works, but its like, inverted sticks, wrong buttons... (I'm using an generic PS2 controller in a Twin USB adapter)

**Comment by Squall-Leonhart** [comment]
This title is 64bit only as far as i know.

**Comment by gentlemanboy** [comment]
Squall, but i'm using x360ce 64 bits... and dont work
