### ISSUE TITLE
Not working with Batman: AK

### ISSUE THREAD

**Issue by gentlemanboy** [x360ce/x360ce#195]
I searched alot on the web, and find nothing about it, seems AK thinks my controller is a PS4 controller, and I'm using the same control configs I use on my others games.. please, if anyone knows how to fix it , i will be very grateful :D , and, on the game part of the controller works, but its like, inverted sticks, wrong buttons... (I'm using an generic PS2 controller in a Twin USB adapter), Squall said the title is 64bits only, but i'm on a 64 bits system, using x360ce 64 bits... and isnt working...

**Comment by Nucleoprotein** [comment]
This is confirmed, ie. x360ce works fine with Batman AK ?

**Comment by gentlemanboy** [comment]
Doesnt work... it just not recognize the controler or the game inverts all buttons

**Comment by Nucleoprotein** [comment]
@Squall-Leonhart 
 This is confirmed, ie. x360ce works fine with Batman AK ?

**Comment by gentlemanboy** [comment]
doesnt work.

**Comment by Nucleoprotein** [comment]
I'm not asking you... 

PS: If Squall-Leonhart closed this I'm almost sure this was checked and it works fine in that game, so I think this is next configuration related problem.
