### ISSUE TITLE
Grand Theft Auto 64bit Vibration Not Working

### ISSUE THREAD

**Issue by xcessed-identity** [x360ce/x360ce#196]
The vibration seems to work on the latest 32bit version of x360ce but when I use the latest 64bit version of x360ce vibration doesnt work.. Kindly fix the issue.. I am unable to get vibration in GTAV or any 64bit game..

**Comment by Squall-Leonhart** [comment]
Nothing for us to fix.
Your controller just doesn't have a 64bit rumble library.

Vibration confirmed working here with 64bit library.
