### ISSUE TITLE
Force Feedback not working in Resident Evil's series

### ISSUE THREAD

**Issue by zeraln** [x360ce/x360ce#198]
Some games like Darksiders and Castlevania Lords of Shadow the FFB works well, but all games from Resident series not. I already tested in RE HD, 5 and Revelations 2 and nothing. (Rumble actived in game options)
Incompatible FFB for these games? (Using a Twin USB Joystick PS2 and x360ce 2.0.2.160)

**Comment by Squall-Leonhart** [comment]
That version of x360ce is out dated, please use a current and supported version.
