### ISSUE TITLE
Crysis 2 not detecting my gamepad. HELP PLSSSS!!

### ISSUE THREAD

**Issue by davy77anto** [x360ce/x360ce#199]
I own an 'Enter E-GPV' gamepad and, of course, I use x360ce program to play all my games. It works perfectly on all my games like, Assassin's creed series, Bioshock series, GTA 4, NFS Shift 2 etc... But I just dunno what's wrong with crysis 2 that it never ever detects my gamepad. I have tried everthing possible, like, updating the crysis 2 patch to version 1.9 and yet, can't make it to detect my gamepad. 

I tried googling and it never help.

PLS SOMEBODY.. HELP ME!!! PUT ME OUTTA MY MISERY!!!
![image](https://cloud.githubusercontent.com/assets/13693550/9134670/139e11ae-3d24-11e5-8253-704fa47bbf3e.png)

**Comment by Squall-Leonhart** [comment]
only the steam version of crysis 2 recieved xinput support.

**Comment by Squall-Leonhart** [comment]
btw, your xinput dll is over a year old.
