### ISSUE TITLE
x360ce won't launch

### ISSUE THREAD

**Issue by Merig** [x360ce/x360ce#201]
Hi, 
I downloaded the program to play Rocket League with my ps2 controller. I unzipped it in the game folder, but when i try to start it i get this error:
![errore](https://cloud.githubusercontent.com/assets/13717027/9154595/276a6dfc-3e98-11e5-8701-54b0bc604685.PNG)

Any idea on how to solve? 
Thanks

**Comment by samgreen** [comment]
Install .NET runtime: http://www.microsoft.com/en-us/download/confirmation.aspx?id=42642
