### ISSUE TITLE
Trine 2 menu screen problem.. (PLS HELP)

### ISSUE THREAD

**Issue by KrazyCat27** [x360ce/x360ce#202]
Trine 2 is like freezing then going back to the game then freezing again and on and on while on menu screen.. I haven't tried playing it cause this glitch thing is not letting me start it... 
I tried deleting the X360ce files then this fixed it.. Im not sure why though...
Also tried changing setting but that didnt work..

**Comment by KrazyCat27** [comment]
Whenever I see the "default" mouse pointer it freezes the game then it disappears then the mouse in game works but after like a second the "default" mouse pointer is there then freezes the game again..
I was trying to PrtSc but failed to get the "default" mouse pointer to be in the PrtSc

**Comment by KrazyCat27** [comment]
If I only delete the "x360ce.config" It fixed it.. I thought it was about the config files but the xbox360cemu.config is still there but there was no problem...

**Comment by Squall-Leonhart** [comment]
What?

This game works perfectly fine. Your description is vague and not very forthcoming.

**Comment by Squall-Leonhart** [comment]
You are using an unsupported version of the application and dll, upgrade to a recent version.
