### ISSUE TITLE
x360ce doesn't work on Windows 10

### ISSUE THREAD

**Issue by dsxack** [x360ce/x360ce#204]
I use x360ce for gaming to Transistor on Windows 8. It's works fine. But i install Windows 10 and now its not working.

**Comment by icaro56** [comment]
It happens with me too. The exe does not recognizes the xinput1_3.dll.

failed to load xinput1_3.dll x360ce

It looks like it's dll needs to be compiled for windows 10

**Comment by dsxack** [comment]
I've tried both versions of the x86 and x64 for both versions of game

**Comment by Nucleoprotein** [comment]
As you instance GUIDs changed you need to recreate setting file (run x360ce.exe).

If DLL fails to load you do not meet the requirements: https://github.com/x360ce/x360ce#system-requirements
After upgrading OS, you need to reinstall all runtime redistributables.

**Comment by dsxack** [comment]
@tapcio, I installed all requirements and install x360ce.exe without old config (i erased my hard drive, before install Windows 10)

**Comment by icaro56** [comment]
So, I solved my problem yesterday. I install the requirements but the directx 9 (june 2010) does not installed because the system blocked its.

To install the directx 9 I had that to install the full SDK (direct x 9 june 2010) and to use the last x360ce

**Comment by dsxack** [comment]
@icaro56, thanks, I will try this solution tonight

**Comment by icaro56** [comment]
I disable the documentation and libs in this SDK installation. The install process frozen on directx 9 runtime install, but it works.

**Comment by Squall-Leonhart** [comment]
Uh... the SDK isn't needed at all, just the full redistributable package (in the worst case).

Webupdater usually works.
