### ISSUE TITLE
xbox 360 ce won't lunch on win 7 64bit

### ISSUE THREAD

**Issue by HamedJr** [x360ce/x360ce#205]
my friend told me to download x360ce becuase my right analog stick wasn't working but the left stick was fine i downloaded x360 ce but when i lunch it this thing pops out 
![capture](https://cloud.githubusercontent.com/assets/13722703/9157484/f6927db2-3f07-11e5-95e9-eeb1e12e20f3.PNG)

please help me if you can

**Comment by Squall-Leonhart** [comment]
You do not have the necessary DotNet assemblies installed.

**Comment by HamedJr** [comment]
okay what should i download ?

**Comment by Squall-Leonhart** [comment]
The requirements listed on the main page.
