### ISSUE TITLE
Rocket League controller not working

### ISSUE THREAD

**Issue by cvrk** [x360ce/x360ce#206]
I can't get it to work in Rocket league. Can you please look at these settings,and tell me what is wrong ? 
![1](https://cloud.githubusercontent.com/assets/13750100/9200209/671cf3e4-404f-11e5-9eda-516219775e1b.jpg)

![2](https://cloud.githubusercontent.com/assets/13750100/9200221/7e11831c-404f-11e5-8b31-dfc6493c91a4.jpg)
![3](https://cloud.githubusercontent.com/assets/13750100/9200237/9577801a-404f-11e5-95fe-2380e60ac90b.jpg)

![4](https://cloud.githubusercontent.com/assets/13750100/9200265/c00c62aa-404f-11e5-9517-44c1cf71bf02.jpg)

**Comment by cvrk** [comment]
The 360ce.exe is 32bit same as game. The program is in game folder (same folder as game exe). 
I made this work for another game about 1 year ago, but no success for Rocket League. 
If you need me to provide more printscreens i will.

**Comment by Squall-Leonhart** [comment]
Inspect the second image you posted carefully.
