### ISSUE TITLE
Problem with Analog Sticks

### ISSUE THREAD

**Issue by Lonewolf22113** [x360ce/x360ce#207]
I am having a problem with x360ce , both sticks seems to be slighty up , but it seems to be fine everytime you launch x360ce it changes everytime you rebind any button or just press any button also it seems that this issue started happening in the latest version (3.1.7.58) in both 32 and 64 bit version of program.

I made sure that my controller is configured correctly

Rebinding one of the stick makes both of them centered again , but unfortunately it doesn't fix the problem.

![x360ce](https://cloud.githubusercontent.com/assets/13752971/9206417/ef8f4b10-4067-11e5-9f45-cd58d66898e4.png)

**Comment by Squall-Leonhart** [comment]
calibrate your controller in joy.cpl.

This is not an issue with the application.
