### ISSUE TITLE
x360ce won't launch at all

### ISSUE THREAD

**Issue by Renektoff** [x360ce/x360ce#208]
I've been trying to setup my controller - Gamepad Tracer Red Arrow to work with SpeedRunners but it just won't open. I tried moving both the 32 and 64 bit versions to the SpeedRunners executable folder in steam, I tried putting them in a completely irrelevant folder, it just won't open. I try opening them and it just starts loading and absolutely nothing opens. I've checked the system requirements and I have everything needed installed, and my controller is plugged in the USB. I've no clue how to proceed and google didn't help much :/

**Comment by Squall-Leonhart** [comment]
Unity 3D games do not use xinput correctly unless using a custom input mapper, which speedrunners does not.

**Comment by Renektoff** [comment]
Just FYI I managed to get the 64 bit version to run when I used compatibility and set it to run as administrator, and the 32 bit version by using compatibility again and setting it to XP. (Also, the program DOES work on SpeedRunners, as I've seen videos of it on youtube AND I managed to get it work now, thanks anyway. =) ) 

```
 On Sunday, August 16, 2015 10:45 AM, Squall Leonhart <notifications@github.com> wrote:
```

 Unity 3D games do not use xinput correctly unless using a custom input mapper, which speedrunners does not.—

**Comment by Squall-Leonhart** [comment]
XP compatibility just enforces the UAC prompt, running the application as admin would have been sufficient enough to create the dll in a access controlled directory, i assume it is installed to the default C:\program files (x86)\steam directory.
