### ISSUE TITLE
Crashes Sonic All-Stars Racing with Logitech dual-action

### ISSUE THREAD

**Issue by jbienz** [x360ce/x360ce#21]
_From [Paul.Ges...@gmail.com](https://code.google.com/u/103828843747057637757/) on May 22, 2010 18:13:16_

What steps will reproduce the problem? 1. Install Sonic All-Star Racing from Steam
2. Plug in Logitech dual-action (wired, non-rumble)
3. Copy then Run x360ce.exe in the game install folder
4. Load Logitech dual-action settings, save file
5. Run the game, and it goes to black screen, then back to desktop and 
crash. The "Problem details" of the crash dialog reveal that the problem is 
with xinput1_3.dll.

-- What is the expected output? What do you see instead? Was hoping the game would work with my pad!
-- What version of the product are you using? On what operating system? x360ce.App-2.0.2.51.zip on Win 7, 64-bit.

--- What gamepad are you using? On what version of drivers? Logitech Dual-Action. 

--- Please set third label to Core if issue affect emulator (dll file) or App if issue affect x360ce.App application (exe file). Also if you want you can provide any additional information below. Sorry, I don't know what "thired label" means.

This bug occurs both with and without Logitech Profiler running. 

I noticed that the "count" field in the status bar keeps going up, such 
that I cannot actually see any other status message that comes up for more 
than a very short period of time. Is this significant?

_Original issue: http://code.google.com/p/x360ce/issues/detail?id=21_

**Comment by jbienz** [comment]
_From [Paul.Ges...@gmail.com](https://code.google.com/u/103828843747057637757/) on May 23, 2010 20:13:09_

The "vibmod" version seems to work OK with the default configuration, by the way. My 
problems were only with the two beta versions available in the downloads section.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 24, 2010 08:27:11_

Config app 2.0.2.51 is working ? with new dll ?

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 24, 2010 08:27:29_

**Labels:** x360ce-Core

**Comment by jbienz** [comment]
_From [Paul.Ges...@gmail.com](https://code.google.com/u/103828843747057637757/) on May 24, 2010 09:59:50_

Neither 2.0.2.51 nor 2.0.2.47 worked for me.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 25, 2010 14:01:35_

Please check r120

**Comment by jbienz** [comment]
_From [gregory....@laposte.net](https://code.google.com/u/114016125790017964709/) on May 26, 2010 06:05:03_

I have exactly the same Problem:

Same Gamepad (Logitech Dual Action)
Same Game (Sonic All-Star Racing NON-STEAM)
Same OS (Win. 7 x64)

And even r120 won't help (black screen).

**Comment by jbienz** [comment]
_From [Paul.Ges...@gmail.com](https://code.google.com/u/103828843747057637757/) on May 28, 2010 13:48:52_

I just tried with r120 , and it still crashes on load. Here are the "problem details" 
in case that helps. This is the Steam version.

Problem signature:
  Problem Event Name:   BEX
  Application Name: Sonic & SEGA All-Stars Racing.exe
  Application Version:  0.0.0.0
  Application Timestamp:    4b700995
  Fault Module Name:    XINPUT1_3.dll
  Fault Module Version: 3.2.0.120
  Fault Module Timestamp:   4bfc37f1
  Exception Offset: 00008c74
  Exception Code:   c0000417
  Exception Data:   00000000
  OS Version:   6.1.7600.2.0.0.256.48
  Locale ID:    1033
  Additional Information 1: 8ea8
  Additional Information 2: 8ea88cf25695f2c70ec66f04a3abc0b2
  Additional Information 3: 751a
  Additional Information 4: 751adf92aea3568b8ba0e8b75e84519e

**Comment by Squall-Leonhart** [comment]
pretty sure this was fixed a long time ago.
