### ISSUE TITLE
Dark Souls II: SotFS unable to hold keymaping in game, but functions in application (XBOX One Controller)

### ISSUE THREAD

**Issue by mooreppj** [x360ce/x360ce#211]
Hello!
I have been unable to get an XBOX One controller to accept new keymappings for Dark Souls II: SotFS.  What I have tried:

Using the 64-bit executable, create an xinput3_1.dll and x360ce.ini.  Map my keys as I would like them to be in game, save and quit.  Then, in the x360ce.ini I change:
under [Options], Version=1.  
[InputHook]
HookLL=0
HookCOM=1
HookSA=0
HookWT=0
HookDI=0
HookPIDVID=0
HookName=0
HookMode=1

I enabled logging and it appeared as follows for starting up the game (note: I could not get a log to appear if I used xinput3_1.dll version 3.4.1.1346, this printout is from a previous version):
![printout](https://cloud.githubusercontent.com/assets/13840460/9316418/ee614924-4502-11e5-9367-995bd912fc93.jpg)

Also note: The HID information called in the log points to my XBOX One controller (no other controllers are plugged in or have drivers installed).

At this point, all of the controls that I have mapped are not functioning and the controls for the game are the default controls for a gamepad for DS2:SotFS.  If I change HookLL=1, the game crashes on start up.  I suspect the issue is the Xinput3_1.dll.  The 64-bit library dinput8.dll spoofer is present in the game directory as well.  Running a 64-bit version 3.4.1.1346 of xinput3_1.dll, I have been unable to get key mappings recognized or get x360ce.exe to display a log or get an initbeep.  Any thoughts?

**Comment by Squall-Leonhart** [comment]
dinput8 is not required for this game

use durazno,  your controller is already xinput compatible and just needs remapping.

**Comment by mooreppj** [comment]
Great, thank you! I was searching for a remapping program but never came across Durazno.  Cheers to you!
