### ISSUE TITLE
Final Fantasy Type-0

### ISSUE THREAD

**Issue by CeruleanSky** [x360ce/x360ce#212]
When launching \FINAL FANTASY TYPE 0 HD\WIN\fftype0hd.exe it looks for the file " xinput9_1_0.dll " none of the other names load.

I hear the beep that says it loads, but unlike the games where it works, in this case it immediately crashes the game after it loads the dll(beeps) while at the checking savefile screen..  There is no crash when the dll does not load.

I have also tried it with HookMode 0,1,2,3 , though I'm not sure if those actually do anything.

I am using DLL 3.4.1.1346  but I also tested 3.4.0.848 

If there is anything additional you think I can provide, please let me know.

Here is my log file for 3.4.0.848, for some reason 3.4.1.1346 would not produce a log(I tried log=1, debug =1, and log=1 & debug=1):

```
TIME         THREAD   TYPE      DATA
00:46:57.567 00011228 [Core   ] Using game database file:
00:46:57.567 00011228 [Core   ] C:\ProgramData\x360ce\x360ce.gdb
00:46:57.580 00011228 [Core   ] x360ce 3.4.0.848 [fftype0hd.exe - 9512]
00:46:57.581 00011228 [Core   ] Microsoft Windows 7 Home Premium Edition Service Pack 1 (build 7601), 64-bit
00:47:04.863 00011228 [Core   ] [PAD1] Starting
00:47:04.863 00011228 [Core   ] [PAD1] Initializing as UserIndex 0
00:47:04.895 00011228 [DInput ] [PAD1] Creating device
00:47:04.898 00011228 [DInput ] [PAD1] Device created
00:47:04.956 00011228 [DInput ] [PAD1] Detected axis count: 4
00:47:04.975 00011228 [Core   ] [PAD1] Done
00:47:04.981 00011228 [Core   ] Loading C:\Windows\system32\XINPUT9_1_0.dll
```

**Comment by Nucleoprotein** [comment]
On this issue tracker we only support issues from current version and current library version is 3.4.1.1346, you used 3.4.0.848. Please re-test with latest version or this issue will be removed.

**Comment by CeruleanSky** [comment]
I tested with both. 

`I am using DLL >>>>>>> 3.4.1.1346 <<<<<< BUT I ALSO tested 3.4.0.848 `

**Comment by CeruleanSky** [comment]
I tested with both, just wanted to make sure it wasn't caused by a change over the last couple years.

I added some emphasis to the line I wrote above to make this clear:

I am using DLL **>>>>>>> 3.4.1.1346 <<<<<<** BUT I ALSO tested 3.4.0.848 

Ahh, I see the confusion, for some reason 3.4.1.1346 would not produce a log file at all, so I mistakely included a 3.4.0.848 log, I corrected that in my post.

**Comment by Squall-Leonhart** [comment]
Crashes because you are trying to run 64bit game with 32bit dll.

**Comment by Ex-SOLDIER** [comment]
Same problem as CeruleanSky. Game crashes and I use 64bit.  Also running on Windows 10.

**Comment by Squall-Leonhart** [comment]
http://steamcommunity.com/app/340170/discussions/0/537405286661712950/#c537405286661730593

Probably a faulty force feedback driver.

**Comment by CeruleanSky** [comment]
```
d3dcompiler_46.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows
msgdlg.dll:         PE32+ executable (DLL) (GUI) x86-64 Mono/.Net assembly, for MS Windows
steam_api64.dll:    PE32+ executable (DLL) (GUI) x86-64, for MS Windows
xinput9_1_0.dll:    PE32+ executable (DLL) (GUI) x86-64, for MS Windows
fftype0hd.exe:  PE32+ executable (GUI) x86-64, for MS Windows
x360ce_x64.exe: PE32+ executable (GUI) x86-64 Mono/.Net assembly, for MS Windows
```

**Comment by Squall-Leonhart** [comment]
show the controllers info in dxdiag x64.

**Comment by CeruleanSky** [comment]
The device works fine in xpadder and witcher 3.

```
-------------------
DirectInput Devices
-------------------

      Device Name: Twin USB Network Gamepad
         Attached: 1
    Controller ID: 0x1
Vendor/Product ID: 0x0810, 0x0001
        FF Driver: C:\Windows\USB Vibration\dr100&110\811EZFRD64.DLL
   FF Driver Date: 12/24/2010 17:12:12
FF Driver Version: 
   FF Driver Size: 118920 bytes

      Device Name: Twin USB Network Gamepad
         Attached: 1
    Controller ID: 0x0
Vendor/Product ID: 0x0810, 0x0001
        FF Driver: C:\Windows\USB Vibration\dr100&110\811EZFRD64.DLL
   FF Driver Date: 12/24/2010 17:12:12
FF Driver Version: 
   FF Driver Size: 118920 bytes
```

**Comment by Squall-Leonhart** [comment]
Thought so.

Faulty vibration library on a twinusb controller.

**Comment by Nucleoprotein** [comment]
I think Xpadder and Witcher 3 does not use FFB so no crash, this drivers is faulty : https://steamcommunity.com/app/271590/discussions/0/615085406665759609/
Solution - delete the file - you will loose FFB in x64 apps but it will not crash.

**Comment by Squall-Leonhart** [comment]
Yeah, the device uses the standard HID driver and the rumble DLL is just not compatible with it on 8 and 10.

**Comment by Ex-SOLDIER** [comment]
I followed tapcio's link, deleted one .dll file causing the crash and it works now. Thanks a lot!!!
