### ISSUE TITLE
x360ce_x64 doesn't work with Lords of the fallen

### ISSUE THREAD

**Issue by senbonsama** [x360ce/x360ce#213]
it just doesn't work
nothing works
controller greyed out
red button
everything fails
played like 10 games before 
I just can't seem to get the x64 bit version to even properly detect the damn controller?!

**Comment by Nucleoprotein** [comment]
Easiest solution, if you already run x86 with success, you can copy x360ce.ini where x64 x360ce.exe is and run it to create x64 xinput*.dll files. Also this is not a bug, this is a configuration problem, you should write on our forums to get help, not here.

**Comment by senbonsama** [comment]
failed to load xinput1_3: %1 is not a valid win32 application

that's what happens when i delete the game's xinput and leave the x360ce to create its own one  but it just keeps sending this message

**Comment by Squall-Leonhart** [comment]
Missing Visual C++ 2013 update 4 x64 runtime.

**Comment by senbonsama** [comment]
Thanks so much Squall !
also I apologize for the first title it was kinda rude of me xD

**Comment by senbonsama** [comment]
Update :9/8/2015
now I really wanted to try out this game , I downloaded 32bit games later and they all worked but I just wanted to see what's really wrong
I extracted the x360_64.exe into the binaries folder _where the .exe is_ and of course never forget dem libraries
I replaced the game's xinput file, I avoided doing that before because it wouldn't be recognized
opened x360ce , says sth about the configuration file being outdated 
I clicked ok , and voila.. the sound 
+all controls in and green button
navigated to the game settings tab , added the exe, started it from x360ce _I do this way for no reason but some games such as rocket league do not even have an xinput file so when I  open from x360ce it fixes it_
and game opens. PERFECTLY
but for the reason as to why is works now.. I don't know maybe windows updates? no idea
Thank you all <#
