### ISSUE TITLE
X360ce_64 Not Working error message "Failed to load 'xinput1_3.dll': 1% is not a valid win32 application"

### ISSUE THREAD

**Issue by FRANKstarT** [x360ce/x360ce#214]
When i downloaded the file and tried running it for the first time this error message came up.
At first i thought i should replace the file with a proper windows 64 bit xinput from dll.com which i did the error is still popping up please help
![image](https://cloud.githubusercontent.com/assets/13891266/9391026/fdfc5ee0-4774-11e5-8cbe-bd34c7d97877.png)

**Comment by Nucleoprotein** [comment]
Install all required [requirements](https://github.com/x360ce/x360ce#system-requirements).

**Comment by FRANKstarT** [comment]
Everything Installed but still the error is consistent with the application

![image](https://cloud.githubusercontent.com/assets/13891266/9420103/5433eee8-4862-11e5-9954-febf4df7ba1e.png)

![image](https://cloud.githubusercontent.com/assets/13891266/9420124/817a6cb0-4862-11e5-9e0f-5e105511c333.png)

![image](https://cloud.githubusercontent.com/assets/13891266/9420172/dfff8126-4862-11e5-9dae-53cd8b580e0b.png)

![image](https://cloud.githubusercontent.com/assets/13891266/9420179/f863a152-4862-11e5-8588-0a82ec298356.png)

**Comment by Nucleoprotein** [comment]
Delete xinput1_3.dll and ru-run the app, i think you have xinput1_3.dll x86 in same directory as x64 app. 64bit apps cannot load 32bit DLLs and vice-versa.

**Comment by Squall-Leonhart** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by FRANKstarT** [comment]
![image](https://cloud.githubusercontent.com/assets/13891266/9590554/ae578774-5035-11e5-9cad-79d3bf568e76.png)
![image](https://cloud.githubusercontent.com/assets/13891266/9590567/c22c9384-5035-11e5-9eff-084fe7b45505.png)

**Comment by Squall-Leonhart** [comment]
Uninstall and Reinstall Visual C++ 2013 redists.

**Comment by FRANKstarT** [comment]
Same error message coming up

**Comment by FRANKstarT** [comment]
Finally working after upgrading to windows 10
