### ISSUE TITLE
大哥，小米蓝牙手柄不能震动啊！

### ISSUE THREAD

**Issue by ruizhistudio** [x360ce/x360ce#215]
xiaomi的手柄能否出个驱动程序，还强烈要求汉化一下。

**Comment by Squall-Leonhart** [comment]
spam?

**Comment by heeroyuyj** [comment]
@Squall-Leonhart the XiaoMi Bluetooth Wireless GameController got 2 Motor

however, accroding to the Xiaomi Inc., those motors will only vibrate on Android device with Android games

so, he's asking about if it is possible the XiaoMi Bluetooth Wireless GameController's motors works with x360ce

btw: i also got a XiaoMi Bluetooth Wireless GameController :P

**Comment by heeroyuyj** [comment]
@ruizhistudio 小米公司没给出 PC 端的驱动, 所以跟电脑连上之后, 只是识别成了个最基本的蓝牙手柄而已的...

**Comment by Squall-Leonhart** [comment]
Our software only supports vibration on controllers that have a provided driver that include a Force Feedback library.

Supporting controllers that don't have this would need reverse engineering different devices and writing custom supporting code for each of them.
