### ISSUE TITLE
Single Controller is mapping to two devices

### ISSUE THREAD

**Issue by steckdev** [x360ce/x360ce#216]
My Controller is mapping to two devi es and so I am limited to only connecting 2 instead of 4 controllers. Is there a way that I can configure which input of more than 4 are used for the x360ce. How do I determine the other ids?

**Comment by steckdev** [comment]
I ended up re-writing the code to remove the supplemental. I'm not sure if this is ok but I put it right where the wheels re-order occurs. Please let me know if you guys want me to check this in or if this is used by other devices.

```
        var supplementals = devices.Where(x => x.Type == SharpDX.DirectInput.DeviceType.Supplemental).ToArray();
        foreach (var supplemental in supplementals)
        {
            devices.Remove(supplemental);
        }
```

**Comment by EJocys** [comment]
@steckdev 
Thanks for suggestion. I've added this feature to the new version (v3.2.8.73). You will be able to disable or enable exclusion of supplemental devices by using [x] Exclude Supplemental Devices CheckBox on [Options] tab page.

**Comment by steckdev** [comment]
Thanks finally got around to looking at this defect. I'm excited to be able to get all the new features too!
