### ISSUE TITLE
Dark Souls Prepare to Die Edition Registering wrong inputs.

### ISSUE THREAD

**Issue by ZeeIsMee** [x360ce/x360ce#217]
In the x360ce application, everything seems to work fine, all the buttons respond to the right inputs, but whenever I try to play Dark Souls, one of the analogue sticks registers sideways (up and down are left and right, left and right are up and down), what should be A is registering as start, etc. Does anyone know what's wrong?

**Comment by Squall-Leonhart** [comment]
GFWL version?

**Comment by Nucleoprotein** [comment]
GFWL does not exist anymore, stable branch was updated to SteamWorks some time ago.

**Comment by Squall-Leonhart** [comment]
Need log file.

**Comment by ZeeIsMee** [comment]
What log file?

**Comment by Squall-Leonhart** [comment]
The one you should have learned about before posting here for help by reading the tutorials.

**Comment by ZeeIsMee** [comment]
Is it on the forum? Because until I was told there was one, there is no indication that one exists on the main site.
