### ISSUE TITLE
System.ArgumentNullException at startup

### ISSUE THREAD

**Issue by Vilkku** [x360ce/x360ce#22]
I get this error when trying to launch x360ce_x64.exe. All dependencies should be downloaded and installed.

System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at x360ce.Engine.BoardInfo.GetDiskDriveIdGuid()
   at x360ce.Engine.Data.Game.FromDisk(String fileName)
   at x360ce.App.SettingsFile.Load()
   at x360ce.App.Controls.GameSettingsUserControl.InitDefaultList()
   at x360ce.App.Controls.GameSettingsUserControl..ctor()
   at x360ce.App.MainForm.InitializeComponent()
   at x360ce.App.MainForm..ctor()
   at x360ce.App.Program.Main(String[] args)

**Comment by Squall-Leonhart** [comment]
compiled yourself, or downloaded from somewhere?

**Comment by Vilkku** [comment]
From the website (http://www.x360ce.com/Files/x360ce_x64.zip)

**Comment by Squall-Leonhart** [comment]
hmm. started just fine here,

give us some info about your os, language, characters, etc

**Comment by Vilkku** [comment]
Windows 7 Professional (6.1.7601 SP1, build 7601), English language, Finnish locale

EDIT: And 64bit obviously

**Comment by Squall-Leonhart** [comment]
haha, obviously.

Does your user name have accented characters?

**Comment by Vilkku** [comment]
My username is Vilkku, so no. My real surname does have an ö, but I'm not even sure if that's stored in Windows anywhere. All user folders use my username (Vilkku).

**Comment by Squall-Leonhart** [comment]
Does your Hard drive have accent characters in its name, or in the path for Programdata or Program Files?

**Comment by Vilkku** [comment]
AppData: C:\Users\Vilkku\AppData\Roaming  
ProgramData: C:\ProgramData  
Program Files: C:\Program Files & C:\Program Files (x86)

**Comment by Squall-Leonhart** [comment]
thanks, rules out any possible character set issues.

Did you install the DirectX june 2009 websetup or the full installer?

**Comment by Vilkku** [comment]
I used the web installer, though it said that a newer or equivalent version of DirectX has been installed already and that no installation is necessary.

**Comment by Squall-Leonhart** [comment]
was .net 3.5 turned on before you did this?

There are some files... which im not even sure we still need....  that are only installed using the websetup if dotnet 2.0 files are present.

**Comment by Vilkku** [comment]
All the required .NET installers said that everything was already installed. Just tested the DirectX installer and got the same message about it not being needed.

**Comment by Bexile** [comment]
I get the same Error [Exception!] on my other Windows 8.1 x64 Notebook.
And on my fresh Installed Surface Pro its open without any Problem.
TocaEdit X360 Controller Emulator Application 3.0.1.8 Beta 1 (x32_x64)
Hope to know how to FiXiT or wehre the Problem could be.
THx for any solutions.

**Comment by Bexile** [comment]
The old version works without problem:
XBOX 360 Controller Emulator 2.1.2.191 (with x360ce Library 32bit 3.3.1.584) 

Only with the new versions, the problem occurs.

**Comment by Vilkku** [comment]
I had a look at the code referenced by the error message and dug around a bit. I assume the problem is that I have some device which does not have a serial number (referenced for example here http://stackoverflow.com/questions/1350911/problem-with-win32-physicalmedia-serialnumber-property). I do have a card reader internally attached to the computer, I wonder if this could be at fault? I am unsure how x360ce functions, if GetDiskDriveIdGuid() checks every disk in the system or just the one I happen to run x360ce from? I imagine it's the former, as I tried to run it from two different drives an neither worked.

https://github.com/x360ce/x360ce/blob/159bfdc51e9f476b1949f38bfb0d7ae10f1c67d0/x360ce.Engine/Common/BoardInfo.cs#L15-L18

Is there some way I could check the serial number values for everything on my system to confirm one of them is indeed empty? But I guess the real problem is that there should be a check in x360ce for empty ones (unless this is already the case and I'm not correctly diagnosing the issue, in which case I apologize).

**Comment by Squall-Leonhart** [comment]
GUID is generated by windows for each device attached, it doesn't have anything to do with the physical device providing a serial id.

**Comment by Vilkku** [comment]
But, unless I am reading the code incorrectly (which is of course pretty likely), this is what happens:

```
var serialBytes = System.Text.Encoding.ASCII.GetBytes(diskId);
```

Looking at the error message, the problem seems to be that GetBytes expects the argument to be a string, which it isn't. That seems to be the only instance of GetBytes in that file.

```
var diskId = GetDiskDriveID();
```

diskId is set by GetDiskDriveID()...

```
static string GetDiskDriveID()
{
    return GetClassValue<string>("Win32_DiskDrive", "SerialNumber");
}
```

Which reads the SerialNumber value from Win32_DiskDrive. [The docs](https://msdn.microsoft.com/en-us/library/aa394132.aspx) describe this as

> Number allocated by the manufacturer to identify the physical media.
> 
> Example: WD-WM3493798728

Again, sorry if I'm mistaken.

**Comment by Squall-Leonhart** [comment]
Well, its the best theory at the moment, so i'll see what ejocy can do.

Ejocy, can you check this out?

**Comment by Vilkku** [comment]
Just a heads up, I disabled all the disk devices related to the card reader in device manager and x360ce now launches as expected :)

**Comment by Squall-Leonhart** [comment]
Alright, cool, thanks for confirming.

will either need to gracefully catch those empty strings, or block checking on removable disks

**Comment by EJocys** [comment]
It looks like Win32_DiskDrive returns null.

|There is a for loop inside GetClassValue<T>|

Probably last item in the list return null:

foreach (ManagementObject mo in moc)
{
    value = (T)mo[paramName];
}

Evaldas. I will look at it:

**Comment by EJocys** [comment]
I think, I fixed it. Now GetDiskDriveID() will take number of first fixed drive or non-empty number as an alternative.

**Comment by Zarettera** [comment]
I had the same problem, and solved it by disabling my internal SD card reader, thanks for the advice.

**Comment by Chase-san** [comment]
I hope you can update the build on the site soon, so I can get back use of my card reader.

**Comment by EJocys** [comment]
Fixed.

**Comment by DeanBDean** [comment]
I am still having this issue. I have done the other suggestions above. Windows Vista, English. I don't have any internal card readers to disable unfortunately. I do have a cloned drive, not sure if that would cause this issue

**Comment by Nucleoprotein** [comment]
Do you use version v3.0.2.25 Beta 2 (2015-04-30) and Libraries 3.4.1.1245 (2015-04-30) ?
