### ISSUE TITLE
It doesn't work with windows 10 Pro Insider Preview

### ISSUE THREAD

**Issue by alpinjongari** [x360ce/x360ce#220]
It says that it doesn't recognize the .ini file anymore 
Is there any fix about this that i don't know yet? I presume it's the same with windows 10 as well.
On windows 7 and 8 it worked fine.
Please make an update soon cause it's unbearable playing with the keyboard instead of a gamepad
Thank you

**Comment by Squall-Leonhart** [comment]
works fine on all operating systems when the prerequisites are met.
