### ISSUE TITLE
fifa 14 doesnt work

### ISSUE THREAD

**Issue by fazeneofreex** [x360ce/x360ce#222]
I have a ps2 controller with a usb adapter and I set up everything in x360ce and when I start fifa 14 the controls are still wrong but when i check x360ce the controls are right.. It is so frustrating. Please help!

**Comment by Squall-Leonhart** [comment]
logs and screenshots required when reporting issues.

**Comment by fazeneofreex** [comment]
![Uploading Izrezak.PNG…]()
![Uploading mm.PNG…]()

**Comment by fazeneofreex** [comment]
sreenshots?

**Comment by fazeneofreex** [comment]
http://i.imgur.com/88TWaG2.png
http://i.imgur.com/QBPaKb7.png

**Comment by Squall-Leonhart** [comment]
use the forum for game configuration issues
