### ISSUE TITLE
Version confusion.

### ISSUE THREAD

**Issue by Rigel88** [x360ce/x360ce#223]
Current version available on the website is supposed to be 3.2.8.74. But the title of the window and the description window under "About" tab display 3.2.7.67. Changes tab however has info about 3.2.8.74.
![Screenshot](http://i.imgur.com/WUsiNfH.png)
Not a big deal in any way, of course. I just was a little confused when I had to specify which version I was using.

**Comment by EJocys** [comment]
@Rigel88 : Thank you for noticing that. Updated with latest version properly.
