### ISSUE TITLE
x360ce_x64 doesn't work on windows 10

### ISSUE THREAD

**Issue by diegosky1405** [x360ce/x360ce#225]
Not working on windows 10, i get a xinput 1_3.dll error while excecuting the program, see image attached.
![xbox360cebug](https://cloud.githubusercontent.com/assets/14043828/9568885/4aa59a2a-4f2e-11e5-9c59-1acd9df74d71.png)

**Comment by Nucleoprotein** [comment]
@EJocys 
You upgraded to VS2013 U5 and releases are using it ? I think the redist on MS site is too old or something because many similar issues was created in few days.

I think we should go back to static runtime, all redistributes (like Physx DLLs) are using static link to runtime to avoid such issues.

**Comment by EJocys** [comment]
I am using Visual Studio 2015 for some time and using Windows 10. I will see if I can find solution.

**Comment by diegosky1405** [comment]
Thanks for looking into it.

**Comment by Squall-Leonhart** [comment]
Using new VS just for the sake of it is upsetting to end users, please use the v120 or v120_xp toolchains unless we need to move to new version for new features.

**Comment by Squall-Leonhart** [comment]
for op
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by EJocys** [comment]
@Squall-Leonhart I haven't changed Platform Toolsets of C++ projects on VS 2015. All C++ projects are using "Visual Studio 2013 (v120)" toolsets (for that, I have VS 2013 installed too).

**Comment by EJocys** [comment]
Will check XInput DLL's with http://www.dependencywalker.com

Edit: Everything looks normal. All points to v120.

**Comment by EJocys** [comment]
@diegosky1405, could you: 
a) download Dependency Walker 2.2.6000 for x64 [468k] from http://www.dependencywalker.com/
b) Launch depends.exe
c) Open xinput1_3.dll (64-bit) with it.
d) Save results to "File -> Save -> xinput1_3.dwi
e) ZIP xinput1_3.dwi -> xinput1_3.zip (or RAR)
f) Send to evaldas@jocys.com

**Comment by Squall-Leonhart** [comment]
I believe this is just another case of people not reading the notes, where it is specified that 64bit versions of windows need both the x86 and x64 VC Redists installed.

**Comment by diegosky1405** [comment]
@Squall-Leonhart I know at least the basics of VC redists stuff so nope, i did installed both x64 and x86 from your link and nothing changed still same error at startup.

@EJocys Already sent you an email with all the data you asked.

Thanks both for your help.

**Comment by diegosky1405** [comment]
Ok, so i uninstalled all the VC redists and installed them all over again in order and now everything is working , dont know what happened there, thanks everyone you can close this i guess.

**Comment by Squall-Leonhart** [comment]
Was this an upgrade from windows 8?

**Comment by diegosky1405** [comment]
@Squall-Leonhart Nope, clean install.

**Comment by diegosky1405** [comment]
@Squall-Leonhart Clean install.

**Comment by BhoneSeven** [comment]
i have same issue on windows 10 pro. i already tried unistalled and reinstalled again.but have the same problem.plz suggest me any solution for this issue.

![screenshot 3 -1](https://cloud.githubusercontent.com/assets/14161627/9721164/00fe3da2-55bc-11e5-892a-e0d40e6347cc.png)

**Comment by Squall-Leonhart** [comment]
@tapcio 

We need some more verbosity on these error messages,  clearly some file is throwing up an access violation (doesn't exist), we jus don't know what it is.

**Comment by Squall-Leonhart** [comment]
Confirming that on a fresh install of windows 10, only the MSVC runtime and DirectX is required.

Those with issues have done something wrong or tried to hodge podge by dropping and registering random dll's.

**Comment by BhoneSeven** [comment]
i already installed MSVC 2005 to 2015 except 2013 and directX 11 😓😓

**Comment by Squall-Leonhart** [comment]
I have confirmed that for the basic features to work, only MSVC 2013 x64 and x86 are required.

For passthrough, the dx setup must be run to install the missing dx files (most games run this preinstall anyway)

I'm closing this as working for me, i suggest anyone having issues with the missing file error take it to a MSVS specified forum as it is not our applications fault.

**Comment by kaiyes** [comment]
had the exact same error message on windows 10. Solved by installing both  MSVC 2013 x64 and x86. I think @Squall-Leonhart  is right. Both the x64 and x86 are needed.
