### ISSUE TITLE
error when trying to open x360ce_64.exe

### ISSUE THREAD

**Issue by Vergolob** [x360ce/x360ce#227]
![image](https://cloud.githubusercontent.com/assets/14076982/9609075/edb622bc-50d1-11e5-94af-8861859b8549.png)

I am using win 10. No idea how to solve it it seemed to resemble issue #127 but I think it's different.

**Comment by Vergolob** [comment]
nevermind im stuped, it opens now but in the game it still doesn't work after configuring. It doesn't even work after checking the 3 first hookmasks. Game: One Piece: Pirate Warriors 3

**Comment by Squall-Leonhart** [comment]
You don't run it from or overwrite files in the system32 folder, you execute it from the game installation folder.

Follow the outdated tutorials to identify if the game actually uses Xinput.

**Comment by Vergolob** [comment]
I'm just way too bad at using this app. I'm pretty sure it uses Xinput because my friends are using an xbox controller.

**Comment by Squall-Leonhart** [comment]
Xinput is not the only way to use Xbox controllers.

Otherwise Unity engine would be SOL.
