### ISSUE TITLE
 360ce exe not responding

### ISSUE THREAD

**Issue by Suikon** [x360ce/x360ce#229]
O.k.here is my problem.After last installation of windows 7 i tried to play pc game with controller using x360ce emulator software.i have playing games for years with this program..My problem is.he wont open 360ce exe no matter what.i can click 100 time.nothing happen.and game dont recognize file..its just like he is there but cant open it and can recognize him when in game folder..i tried to download file from several websites and outcome is the same..What im missing..Thank all of you in advance

**Comment by Squall-Leonhart** [comment]
```
Windows Vista or newer.
.NET 3.5 (also installs 2.0 and 3.0) (included in Windows 7)
*.NET 4.0 (link to 4.5, also installs 4.0) (included in Windows 8 and 10)*
DirectX End-User Runtime (June 2010) (Required regardless of OS)
Visual C++ Redistributable for Visual Studio 2013 (For x64 systems install both x86 and x64 redistributable)
If you upgraded to Windows 10, you must Uninstall and Reinstall the Visual C++ Redistributable
```
