### ISSUE TITLE
"Blur" crashes at startup

### ISSUE THREAD

**Issue by jbienz** [x360ce/x360ce#23]
_From [fsmcas@gmail.com](https://code.google.com/u/fsmcas@gmail.com/) on May 28, 2010 12:42:17_

What steps will reproduce the problem? 1. Using the version provided on the homepage 
2. setting a gamepad up with x360ce.exe
3. Starting the game "Blur" What is the expected output? What do you see instead? It works perfectly on XInputTest.exe, but the game crashes immediately What version of the product are you using? On what operating system? Win7 x64, newsest version of your program [downloaded today from your
homepage, 05/28/2010] What gamepad are you using? On what version of drivers? A cheap PS3-like gamepad, bigben Please set third label to Core if issue affect emulator (dll file) or App if issue affect x360ce.App application (exe file). Also if you want you can provide any additional information below.

_Original issue: http://code.google.com/p/x360ce/issues/detail?id=23_

**Comment by jbienz** [comment]
_From [k...@argumenta.com](https://code.google.com/u/102453556482632540801/) on May 28, 2010 22:37:04_

I'm getting the same error with logitech rumblepad 2 on win 7 x32 and x360ce.App-
2.0.2.62.zip.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 29, 2010 00:27:54_

Please send crash report.

**Comment by jbienz** [comment]
_From [fsmcas@gmail.com](https://code.google.com/u/fsmcas@gmail.com/) on May 29, 2010 02:51:51_

It's a "has stopped working"-crash.

I hope you can work with the German protocoll:

Name der fehlerhaften Anwendung: Blur.exe, Version: 0.0.0.0, Zeitstempel: 0x562b029a
Name des fehlerhaften Moduls: XINPUT1_3.dll, Version: 3.2.0.120, Zeitstempel: 0x4bfc37f1
Ausnahmecode: 0xc0000417
Fehleroffset: 0x00008c74
ID des fehlerhaften Prozesses: 0xf14
Startzeit der fehlerhaften Anwendung: 0x01cafe8c05984b41
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Blur\Blur.exe
Pfad des fehlerhaften Moduls: C:\Program Files (x86)\Blur\XINPUT1_3.dll
Berichtskennung: 43e5d8f8-6a7f-11df-ae1d-da9d8ae27879

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 29, 2010 02:56:44_

Hym, next STATUS_INVALID_CRUNTIME_PARAMETER error, seems to be some C runtime 
problem, maybe because I use now Visual Studio 2010.

Please install this: http://www.microsoft.com/downloads/details.aspx?FamilyID=a7b7a05e-6de6-4d3a-a423- 37bf0912db84&displaylang=en

and check if error exist after installing.

**Status:** Accepted  
  **Labels:** x360ce-Core

**Comment by jbienz** [comment]
_From [fsmcas@gmail.com](https://code.google.com/u/fsmcas@gmail.com/) on May 29, 2010 03:00:54_

I should install a x86 runtime on my x64-OS?

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 29, 2010 03:05:50_

Yes, you must have both x86 and x64 runtime on x64 system (Windows is multilib system, 
in System32 are x64 binaries, and in SysWoW64 (WoW64 states for Windows over Windows64) 
are x86 binaries, also in WinSxS (Windows Side-by-Side, it allows to have multiple 
version of same library) are both types of libraries.

**Comment by jbienz** [comment]
_From [fsmcas@gmail.com](https://code.google.com/u/fsmcas@gmail.com/) on May 29, 2010 03:12:10_

Thank you, now I can finally play with my brother! =D  Thank you very much.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 29, 2010 03:19:54_

It's working ?

**Comment by jbienz** [comment]
_From [fsmcas@gmail.com](https://code.google.com/u/fsmcas@gmail.com/) on May 29, 2010 03:21:54_

It is working wonderful. Thank you again!

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 29, 2010 03:25:23_

So closing this now, strange because dll is static linked (/MT switch). So better will 
be link this to dynamic runtime, if even if static runtime is needed ...

**Status:** Done

**Comment by jbienz** [comment]
_From [dnl.shar...@gmail.com](https://code.google.com/u/104545392440686114386/) on May 29, 2010 09:53:13_

I have the same problem, i installed both x64 and x86 but game still crash at startup !

Crash Report:

stops working.

Description
Faulting Application Path:  C:\Program Files (x86)\Activision\Blur(TM)\Blur.exe

Problem signature
Problem Event Name: BEX
Application Name:   Blur.exe
Application Version:    0.0.0.0
Application Timestamp:  562b029a
Fault Module Name:  XINPUT1_3.dll
Fault Module Version:   3.2.0.120
Fault Module Timestamp: 4bfc37f1
Exception Offset:   00008c74
Exception Code: c0000417
Exception Data: 00000000
OS Version: 6.1.7600.2.0.0.256.1
Locale ID:  1037
Additional Information 1:   e121
Additional Information 2:   e121b7dd44573d9a088de265fb2d281d
Additional Information 3:   9965
Additional Information 4:   9965c558c3fd090db7feb14763aad3d8

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 29, 2010 12:04:54_

Do you installed this: http://www.microsoft.com/downloads/details.aspx? FamilyID=a7b7a05e-6de6-4d3a-a423-37bf0912db84&displaylang=en ?

**Status:** Started

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 29, 2010 12:15:56_

Please install above file and check if dll in attachment works.

**Attachment:** [xinput1_3.dll](http://code.google.com/p/x360ce/issues/detail?id=23#hc14)

**Comment by jbienz** [comment]
_From [dnl.shar...@gmail.com](https://code.google.com/u/104545392440686114386/) on May 29, 2010 13:00:12_

^^ yes i did and i try downloading your xinput, still the same crash repot !

**Comment by jbienz** [comment]
_From [chef.veg...@googlemail.com](https://code.google.com/u/116379807499464860397/) on May 29, 2010 13:49:58_

Installing the C++ runtime did not fix the problem. Using the dll you supplied here
brings a new report (unfortunately in germany here):

Problemsignatur:
  Problemereignisname:  BEX
  Anwendungsname:   Blur.exe
  Anwendungsversion:    0.0.0.0
  Anwendungszeitstempel:    4bfc8ea9
  Fehlermodulname:  MSVCR100.dll
  Fehlermodulversion:   10.0.30319.1
  Fehlermodulzeitstempel:   4ba1dbbe
  Ausnahmeoffset:   0008ae6e
  Ausnahmecode: c0000417
  Ausnahmedaten:    00000000
  Betriebsystemversion: 6.1.7600.2.0.0.768.3
  Gebietsschema-ID: 1031
  Zusatzinformation 1:  32ef
  Zusatzinformation 2:  32eff7a5044be32137f78441cbe5e0ac
  Zusatzinformation 3:  9451
  Zusatzinformation 4:  94510a17344877c751ea9365a701b549

Do you have any ideas?

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 29, 2010 13:53:05_

Please disable ForceFeedback and retest.

**Comment by jbienz** [comment]
_From [dnl.shar...@gmail.com](https://code.google.com/u/104545392440686114386/) on May 29, 2010 14:03:39_

thats what i get after adding your file and installing c++ runtime both x86 and x64

Source
Blur.exe

Summary
Stopped working

Date
‎30/‎05/‎2010 00:01

Status
Not reported

Description
Faulting Application Path:  C:\Program Files (x86)\Activision\Blur(TM)\Blur.exe

Problem signature
Problem Event Name: BEX
Application Name:   Blur.exe
Application Version:    0.0.0.0
Application Timestamp:  562b029a
Fault Module Name:  MSVCR100.dll
Fault Module Version:   10.0.30319.1
Fault Module Timestamp: 4ba1dbbe
Exception Offset:   0008ae6e
Exception Code: c0000417
Exception Data: 00000000
OS Version: 6.1.7600.2.0.0.256.1
Locale ID:  1037
Additional Information 1:   7295
Additional Information 2:   72957eb930e17910487a655d2d5b4c55
Additional Information 3:   4918
Additional Information 4:   4918ae61b295c8595bc9ab59948e2412

**Comment by jbienz** [comment]
_From [chef.veg...@googlemail.com](https://code.google.com/u/116379807499464860397/) on May 29, 2010 16:10:34_

there are no drivers for my Trust Predator-Gamepad and Win7 doesn't seem to offer
disabling force feedback - or I am just to dumb to find it :-(

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 29, 2010 16:13:35_

Disable in x360ce ini file, or config app.

**Comment by jbienz** [comment]
_From [chef.veg...@googlemail.com](https://code.google.com/u/116379807499464860397/) on May 29, 2010 16:38:32_

That did the trick. Awesome. Thanks a lot.

**Comment by jbienz** [comment]
_From [serban.a...@gmail.com](https://code.google.com/u/109902393778134095833/) on May 29, 2010 17:25:28_

to make vibration work try to set advanced:invers direction to motors and see if it 
stars with vibration:),cause it happened to me in some games and after that it didnt 
crash anymore

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 30, 2010 00:15:19_

I reproduced this on my gamepad, when using windows driver, ie. without FFB driver.
Do you use any FFB drivers ?

**Comment by jbienz** [comment]
_From [serban.a...@gmail.com](https://code.google.com/u/109902393778134095833/) on May 30, 2010 05:08:29_

also using the option swap motors may get you in a game which previously crashed 
with x360ce:)

**Comment by jbienz** [comment]
_From [serban.a...@gmail.com](https://code.google.com/u/109902393778134095833/) on May 30, 2010 05:09:16_

if you are talking to me...i got a rumblepad 2 and i have its driver which includes 
a 
game profiler

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on June 02, 2010 02:41:36_

Issue 26 has been merged into this issue.

**Comment by jbienz** [comment]
_From [Liquid...@gmail.com](https://code.google.com/u/104148055831227371289/) on July 12, 2010 06:33:40_

Thanks a lot tapcio, suggesting to disable Force Feedback worked for me! I alreaddy did all the rest that was suggested in this topic, but setting forcefeedback to 0 in the ini file did the trick.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on July 18, 2010 00:47:44_

Issue 42 has been merged into this issue.

**Comment by jbienz** [comment]
_From [vk3...@gmail.com](https://code.google.com/u/112984427808790774593/) on July 22, 2010 13:23:55_

"blur" crashes at start up. plzz help..
Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: Blur.exe
  Application Version:  0.0.0.0
  Application Timestamp:    562b029a
  Fault Module Name:    Blur.exe
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   562b029a
  Exception Code:   c0000005
  Exception Offset: 0032ce66
  OS Version:   6.1.7600.2.0.0.256.1
  Locale ID:    16393
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on July 23, 2010 01:48:29_

Do you read all issue comments ? Most problem is caused by ForceFeedback=1, so disable it.

**Status:** Accepted

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on August 11, 2010 15:57:47_

**Status:** Fixed

**Comment by jbienz** [comment]
_From [saurabhu...@yahoo.co.in](https://code.google.com/u/111741346608138168122/) on November 14, 2010 07:50:40_

Problem Event Name: APPCRASH
  Application Name: Blur.exe
  Application Version:  0.0.0.0
  Application Timestamp:    562b029a
  Fault Module Name:    Blur.exe
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   562b029a
  Exception Code:   c0000005
  Exception Offset: 0032ce66
  OS Version:   6.1.7600.2.0.0.256.48
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789
pls help..(pc version)

**Comment by jbienz** [comment]
_From [saurabhu...@yahoo.co.in](https://code.google.com/u/111741346608138168122/) on November 14, 2010 08:11:55_

i have no idea about x360ce watsoeva...pardon the ignorance...this ws just a plain install that fails on my pc......Blur(TM)....runs into a black screen...then crashes...n the report is above..(FYI :i have an intel chipset series 965 loaded)...

**Comment by jbienz** [comment]
_From [rocky.ar...@gmail.com](https://code.google.com/u/117704126359533319103/) on March 06, 2011 03:38:00_

Problem Event Name: APPCRASH
  Application Name: Blur.exe
  Application Version:  0.0.0.0
  Application Timestamp:    562b029a
  Fault Module Name:    Blur.exe
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   562b029a
  Exception Code:   c0000005
  Exception Offset: 0032e676
  OS Version:   6.1.7600.2.0.0.256.1
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

same

**Comment by jbienz** [comment]
_From [dark.guy...@gmail.com](https://code.google.com/u/100984604756578406880/) on March 06, 2011 17:09:30_

Those dumps are helpless, imho.

**Comment by jbienz** [comment]
_From [das.in...@gmail.com](https://code.google.com/u/113028346918643608848/) on March 16, 2011 08:34:17_

i face problem when i start my game.... its crash on start up ...it shows this...

 Problem Event Name:    APPCRASH
  Application Name: Blur.exe
  Application Version:  0.0.0.0
  Application Timestamp:    562b029a
  Fault Module Name:    Blur.exe
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   562b029a
  Exception Code:   c0000005
  Exception Offset: 0032ce66
  OS Version:   6.1.7600.2.0.0.256.1
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online: http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409 If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by jbienz** [comment]
_From [danialho...@gmail.com](https://code.google.com/u/116142181712224615034/) on February 16, 2013 11:12:21_

**Status:** Verified

**Comment by voidmaster000** [comment]
Is there anyone to help me?

**Comment by voidmaster000** [comment]
I am having issues launching blur
i cant get to the game
it crashes
pls help
