### ISSUE TITLE
x360ce work correctly in the emulator but not working inside the game

### ISSUE THREAD

**Issue by besoxz** [x360ce/x360ce#230]
so i got a controller and i want to use it in dark souls 2 , but sadly the buttons are very fucked up (i can't look around or look in target) so i tried x360ce it seem to be working very well when i setup the buttons but inside the game it makes no effect i need help plz. 
![capture](https://cloud.githubusercontent.com/assets/14189883/9750647/71243558-564f-11e5-8e01-8b93a47b3e0a.PNG)

**Comment by besoxz** [comment]
i also tried it with other games (skyrim , naruto shippuden ultimate ninja storm 3 ) they don't work too.

**Comment by Squall-Leonhart** [comment]
do people cut out the status bar of the app to troll us?

read compatibility list and tutorials.
