### ISSUE TITLE
NFS Carbon Issue

### ISSUE THREAD

**Issue by Denco96** [x360ce/x360ce#231]
So I followed the installation guide and installed the program. I configured it so that I have slight deadzones on my analog stick otherwise my car is drifting left or right. Anyway when I start the game my change to deadzone is not working. I'm on win 7 64b and I'm using the 32b version of the program.

**Comment by Squall-Leonhart** [comment]
I'm afraid Need for speed Carbon does not utilise Xinput.

The following NFS games use Xinput

Need for Speed: ProStreet
Need for Speed: Undercover
Need for Speed: Shift
Need for Speed: Hot Pursuit (2010)
Need for Speed: Shift 2
Need for Speed: The Run
Need for Speed: Most Wanted (2012)
Need for Speed Rivals
