### ISSUE TITLE
x360c doesn't detect left 4 dead windows 10

### ISSUE THREAD

**Issue by jonaand** [x360ce/x360ce#232]
Hello i have windows 10 64bit rtm
i've installed all Library

and x360ce dont detect left 4 dead 1 and 2 when launch game

i've tried replace xinput1_3.dll to left4dead/bin folder  but dont work

any suggestion? thanks

**Comment by jonaand** [comment]
the solution for me was use x360ce
rename or delete xinput1_3.dll in left4dead/bin folder
and after put x360ce.exe in root folder of game and after configurate x360ce and all done :)

**Comment by Squall-Leonhart** [comment]
Yes, config file must be in same directory as dll or in c:\programdata\x360ce\

**Comment by jonaand** [comment]
because in a lot of pages say
move xniputest1_3.dll to left4dead/bin
and it wrong
the correct is delete xinputest1_3.dll from left4dead/bin
and let x360ce.exe with all in root game folder
