### ISSUE TITLE
Logitech PS3 Controller Not Being Seen

### ISSUE THREAD

**Issue by AMrRain** [x360ce/x360ce#236]
Hello,

I've been having a ton of issues trying to use my Logitech PS3 controller and it's not being seen at all by any of my games or tools such as the x360ce program.

I want to know what I can do to make x360ce see my controller and what I'm doing wrong. 

What I've Done So Far:
Microsoft auto-downloaded a driver for the controller, and the PC does see the controller.

I downloaded a Logitech gamepad driver as well which that program does not see the controller either.

I downloaded motioninjoy which does see the controller in the Driver Manager, but will not download a driver for the controller, I keep getting an error.

I downloaded the Better DS3 tool and that does not see my controller.

Downloaded x360ce that does not see my controller.

**Comment by Squall-Leonhart** [comment]
Take it up with logitech, the controller is clearly not being recognised by windows properly.
