### ISSUE TITLE
Doesn't build in VS 2015

### ISSUE THREAD

**Issue by AqlaSolutions** [x360ce/x360ce#238]
Please make it so I can just download and build it without any code editing!

```
invalid literal suffix '__FUNCTION__'

 PrintLog("Call to unimplemented function "__FUNCTION__);

 Cannot open include file: 'vld.h': No such file or directory   x360ce\dllmain.cpp  12
 cannot open input file 'dxguid.lib'    ditool  x360ce\ditool\LINK  1
```

**Comment by Nucleoprotein** [comment]
VS2015 added C++ string literals so you need to add space between `"` and `__FUNCTION__` to use old behavior..

vld.h is from visual leek detector, used ONLY in debug build.
dxguid.lib is part of DirectX SDK which is required to build.

**Comment by Squall-Leonhart** [comment]
Sounds like a regression in the toolkit to me, report it on microsoft connect.

**Comment by Nucleoprotein** [comment]
No, this is not regression, this is new feature called string literal - http://en.cppreference.com/w/cpp/language/string_literal 
`PrintLog("Call to unimplemented function "__FUNCTION__);` will expand `__FUNCTION__` macro to function name string so now it will require to have space between end of string and start of new string to concentrate strings. I think GCC and Clang will also have syntax error here when compiling in C++11 mode.

**Comment by AqlaSolutions** [comment]
Personally I am not a C++ programmer yet (C# only) so it's hard for me to get into all this stuff like which dependencies with which version I should download and how they should be "connected" to the project. Why aren't they resolved automatically through nuget? I just want to make some corrections for "linear" option (Witcher 3 doesn't allow me to adjust left stick sensitivity). It would be very helpful if you had a step by step guide how to build the solution.

**Comment by Nucleoprotein** [comment]
I think nuget is for C# only. For building library you require DirectX SDK (http://www.microsoft.com/en-us/download/details.aspx?id=6812) and `DXSDK_DIR` environment variable (http://www.computerhope.com/issues/ch000549.htm) pointing to root dir of it. Visual Leek Detector is not required, you can comment out this line: https://github.com/x360ce/x360ce/blob/master/x360ce/x360ce/dllmain.cpp#L12

**Comment by AqlaSolutions** [comment]
Thanks for reply. Looks like my Witcher-related problem can't be fixed as easy as I thought so I can't do it myself. I've just created another issue #240.

**Comment by EJocys** [comment]
@AqlaSolutions: There are some instructions on How to Build Solution here:

https://github.com/x360ce/x360ce/blob/master/Wiki/HowTo.md

**Comment by AqlaSolutions** [comment]
@EJocys  I built the 64-bit version but it seems to be broken. When I launch witcher3 it hangs. It worked with your binaries.

**Comment by EJocys** [comment]
A lot of things changed in version 4.x
