### ISSUE TITLE
 failed to load 'xinput1_3.dll'   

### ISSUE THREAD

**Issue by willypeter** [x360ce/x360ce#245]
hi when i load up my x360ce i get this          failed to load 'xinput1_3.dll'                  System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found ive been trying to get this to work for hours looking everywhere for help

**Comment by Squall-Leonhart** [comment]
Install the System Requirements.

**Comment by willypeter** [comment]
Care to elaborate on what you mean?

**Comment by Nucleoprotein** [comment]
https://github.com/x360ce/x360ce#system-requirements

**Comment by javadave42o** [comment]
I've verified all system requirements, getting the same error message.
Nothing I do prevents this error.

**Comment by javadave42o** [comment]
WIndows 10 - ALL requirements have been met.
Requirements:
Windows Vista or newer.
1. .NET 3.5 (also installs 2.0 and 3.0) (included in Windows 7) - DONE
2. .NET 4.0 (link to 4.6, also installs 4.0) (included in Windows 8 and 10) - DONE (Part of OS)
3. DirectX End-User Runtime (June 2010) (Required regardless of OS) - DONE
4. Visual C++ Redistributable for Visual Studio 2013 (For x64 systems install both x86 and x64 - DONE redistributables)
5. If you upgraded to Windows 10, you must Uninstall and Reinstall the Visual C++ Redistributable - DONE just in case, even though fresh Windows 10
ALL requirements installed and rebooted.
Running x360ce.exe as Administrator
NO EFFECT.. SAME ERROR every time

![x360cefail](https://cloud.githubusercontent.com/assets/18428407/16710160/8161f9f2-45f3-11e6-810a-ab09aa4772a7.jpg)

**Comment by Nucleoprotein** [comment]
Move x360ce.exe to path where you have write access ie. out of "Program Files" and x360ce should create xinput wrapper files on first run.

**Comment by javadave42o** [comment]
I tried that.. moved it to C:\, C:\Games, C:\Games\x360ce, Downloads, Documents, The game's EXE location, My user's home, made sure full access permissions were set for all files and folders where I drop it, even tried adding it to PATH environment variable but still no change. It creates the file every time, but can't read it.

**Comment by MichaelToborg** [comment]
You should not obtain the [xinput1_3.dll](http://www.xinput13dll.org/) file individually from the "DLL download web page." Many reasons exist why should you steer clear of getting dll computer files from suspicious web sites.

**Comment by sophana** [comment]
I have the same problem
x360ce 3.2.9.81 64 bit, windows 10
xinput1_dll is created but can't be read.
same popup displayed

Any solution

**Comment by chaparro152** [comment]
Lo solucione descargandolo desde este sitio https://www.dropbox.com/s/obnds307t4kah5t/x360ce.rar

**Comment by tsanio** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=40784
Visual C++ Redistributable for Visual Studio 2013
Just download the x86 and x64 one by one and not the arm file at all. Then install those.

**Comment by pololita** [comment]
Downloads at https://www.microsoft.com/en-us/download/details.aspx?id=40784 are no longer available :( 
I downloaded x86 file from http://filehippo.com/es/download_visual_c_redistributable_packages_for_visual_studio/
and it seems to work :)

**Comment by mkalkbrenner** [comment]
both, the x64 and the x86 files are here:
https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package

**Comment by Nick63x** [comment]
Hey, Tsanio! works to me! Thanks!

**Comment by Grabdone** [comment]
![screenshot 2](https://user-images.githubusercontent.com/36327928/36061191-b99283f0-0e0b-11e8-8472-ec1447b7e857.png)

**Comment by Grabdone** [comment]
I have tried everything too solve this problem.

**Comment by raja-sekhar-k** [comment]
@tsanio Thanks man.. It worked.. :👍

**Comment by marindha** [comment]
> ![copy1](https://user-images.githubusercontent.com/43509265/45924056-2a0aa700-bf20-11e8-942c-61fe93dbca9d.png)

> ![copy2](https://user-images.githubusercontent.com/43509265/45924057-2b3bd400-bf20-11e8-9c0f-dd30657aca3a.png)


> hi , i met this problem today , 23/9/18 , and download visual cc 2013 both version and now its work, no more error message and u can see its green. thanks 
> i follow this by @javadave42o 

> WIndows 10 - ALL requirements have been met.
> Requirements:
> Windows Vista or newer.
> 
> .NET 3.5 (also installs 2.0 and 3.0) (included in Windows 7) - DONE
> .NET 4.0 (link to 4.6, also installs 4.0) (included in Windows 8 and 10) - DONE (Part of OS)
> DirectX End-User Runtime (June 2010) (Required regardless of OS) - DONE
> **
> 
> > Visual C++ Redistributable for Visual Studio 2013 (For x64 systems install both x86 and x64 - DONE redistributables)
> 
> **

**Comment by inexplicabro** [comment]
> https://www.microsoft.com/en-us/download/details.aspx?id=40784
> Visual C++ Redistributable for Visual Studio 2013
> Just download the x86 and x64 one by one and not the arm file at all. Then install those.

thanks

**Comment by v0x968** [comment]
> both, the x64 and the x86 files are here:
> https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package

That's solution for this issue.
Many thanks.

**Comment by Flainar** [comment]
Salut ! ma poate si pe mine ajuta cineva cu eroarea astea ca nu stiu ce sa ii mai fac sa mearga inainte imi mergea cu un gamepad acum am mai conectat unul la pc si nu mai merge imi apare eroarea asta 
![20190131_113226](https://user-images.githubusercontent.com/47191412/52045348-0221f480-254d-11e9-92eb-742c03e5f0fd.jpg)

**Comment by agentorange89** [comment]
Please help. I have installed all the system requirements for the emulator, and it still fails to load 'xinput1_3.dll'. What should I do?
![Untitled](https://user-images.githubusercontent.com/44745823/56462954-45fdfa80-63d4-11e9-8d7e-143fc8d2ab67.png)

**Comment by sujabino** [comment]
thanks it worked

**Comment by bluecracy** [comment]
Not workin to me. Installed both libraries and tried everything else u said. Damn

**Comment by bluecracy** [comment]
Just noticed that opening the one chaparro152 posted, it appears an error because of net frameworking missing. Maybe is that?

**Comment by bluecracy** [comment]
tried this thing, nothing changed. Wtf is wrong??

**Comment by BertBR** [comment]
> https://www.microsoft.com/en-us/download/details.aspx?id=40784
> Visual C++ Redistributable for Visual Studio 2013
> Just download the x86 and x64 one by one and not the arm file at all. Then install those

It works for me too. Thanks!

**Comment by juanillograph** [comment]
> hi when i load up my x360ce i get this failed to load 'xinput1_3.dll' System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found ive been trying to get this to work for hourslooking everywhere for help


greeting brother this is very easy to solve this problem I have made a video how to solve this, I hope it helps you  https://www.youtube.com/watch?v=PMS_RjQiQlg

**Comment by juanillograph** [comment]
> I have tried everything too solve this problem.

greeting brother this is very easy to solve this problem I have made a video how to solve this, I hope it helps you  https://www.youtube.com/watch?v=PMS_RjQiQlg

**Comment by juanillograph** [comment]
> Not workin to me. Installed both libraries and tried everything else u said. Damn

greeting brother this is very easy to solve this problem I have made a video how to solve this, I hope it helps you  https://www.youtube.com/watch?v=PMS_RjQiQlg

**Comment by Nucleoprotein** [comment]
I not recommend using these files, just install Visual Studio 2013 Runtime which will install that files.

**Comment by Capyv** [comment]
![image](https://user-images.githubusercontent.com/62158034/76658025-7530d380-6573-11ea-84b2-db4fdde79a4e.png)

**Comment by Capyv** [comment]
I tried to delete everything and do it from 0, but when I try to do it I don't get the step of creating the xinput1_3.dll file that appears at the beginning, help please

**Comment by 4tKnight** [comment]
> https://www.microsoft.com/en-us/download/details.aspx?id=40784
> Visual C++ Redistributable for Visual Studio 2013
> Just download the x86 and x64 one by one and not the arm file at all. Then install those.

Thanks man... Works

**Comment by DTA666-sys** [comment]
Anyone still having problems, install the Direct X runtime.

**Comment by ghost** [comment]
h

**Comment by ghost** [comment]
failed to load 'xinput1_3.dll issue

**Comment by AbteuU** [comment]
> https://www.microsoft.com/en-us/download/details.aspx?id=40784 Visual C++ Redistributable for Visual Studio 2013 Just download the x86 and x64 one by one and not the arm file at all. Then install those.

Thank you, that fixed it for me, the dll file was there created and the controller light was red, after installing both (which are still available) the red light turned green and i was also finally able to download pre-configured settings from the WEB. Thanks!

Also i have to say it was a fresh Win10 build, nothing previously installed due to it being a new PC.
