### ISSUE TITLE
x360ce borderlands 2, USB game pad is found but doesn't work in game 

### ISSUE THREAD

**Issue by robowsian** [x360ce/x360ce#247]
I've been reading forums for about 3 hours now trying to troubleshoot this.

I have a generic USB game pad, in advanced settings I can see x360ce recognizing the controller with the axis numbers moving about, same with button presses.

 but in the emulator screen AFTER the buttons have been mapped It does not register my key presses. (No green square) 

I've selected and deselected the pass through etc, changed the dll to 1_2 1_3.dll and I still cannot get that green square.

About to give up on this.

Everything Is up to date x86 & x64 per help section in the program

**Comment by Squall-Leonhart** [comment]
Install the system requirements.
