### ISSUE TITLE
No spring force when using x360ce with Microsoft Sidewinder Force Feedback 2

### ISSUE THREAD

**Issue by jbienz** [x360ce/x360ce#25]
_From [dieteric...@gmail.com](https://code.google.com/u/116969950644694492948/) on May 30, 2010 06:39:28_

What steps will reproduce the problem? 1. Start x360ce.App or any game using the x360ce library What is the expected output? What do you see instead? As a default, my joystick uses its FF motors to simulate the mechanical
spring used in most non-FF joysticks. However, after using x360ce this
effect is disabled, so there is no spring force. Even after closing x360ce. What version of the product are you using? On what operating system? x360ce.App-2.0.2.62
xinput_r120
on Windows 7 64bit What gamepad are you using? On what version of drivers? Microsoft Sidewinder Force Feedback 2 - native drivers Please set third label to Core if issue affect emulator (dll file) or App if issue affect x360ce.App application (exe file). Also if you want you can provide any additional information below. affects both

_Original issue: http://code.google.com/p/x360ce/issues/detail?id=25_

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on June 02, 2010 02:33:53_

native drivers ? ie. you do not have any ForceFeedback driver installed ... ?
You must have proper directinput force feedback driver installed to make this work.

**Status:** Accepted

**Comment by jbienz** [comment]
_From [dieteric...@gmail.com](https://code.google.com/u/116969950644694492948/) on June 02, 2010 10:10:53_

I was unable to find any drivers for my device (it's pretty ancient). Correct me if
I'm wrong but shouldn't it natively support directinput, since it's hardware from
Microsoft? Force Feedback works in other games and in the DirectX SDK samples.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on August 10, 2010 04:21:33_

Please test r171 dll from downloads. Issue should be resolved in r145 .

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on December 19, 2010 17:41:59_

Please re-test with latest version.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on January 30, 2013 09:15:12_

**Status:** WontFix

**Comment by johan84** [comment]
You will fix this problem some day :D ?
