### ISSUE TITLE
x360ce does not work with xbox app on windows 10

### ISSUE THREAD

**Issue by maximumgame** [x360ce/x360ce#259]
Placing the x360ce files inside the xbox app's directory does not have the desired effect. When attempting to stream from xbox one, the app reports there is no controller attached.

**Comment by Squall-Leonhart** [comment]
and probably never will

closed.

**Comment by pepsiisnice** [comment]
X360ce can't handle it that I know of, but check out my video below for another way using input mapper 2
http://youtu.be/gNqW1xA_4nI

**Comment by hiagocmendes** [comment]
Yes, it works! Simply unplug and plug in the controller while playing and the X360CE will show a [ ! ] in issues. You will install the "Device Emulator", something like that name. After that it will work normally. I just tested.
