### ISSUE TITLE
Genuine Xiaomi Mi joystick: left trigger doesn't work properly

### ISSUE THREAD

**Issue by sigod** [x360ce/x360ce#260]
By default triggers configured as buttons.

If I configure them as sliders left one becomes stuck in this position:
![screenshot 2015-10-18 20 34 07](https://github-cloud.s3.amazonaws.com/assets/1175750/10565442/efca4836-75d8-11e5-8712-2cb1e3784b66.png)

Right trigger works fine.

**Comment by Squall-Leonhart** [comment]
this tracker is not for configuration of controllers or games.

**Comment by sigod** [comment]
@Squall-Leonhart Which one then for it?

**Comment by sigod** [comment]
Actually, this issue is about x360ce not working properly with left trigger... Or should I blame some other software?
