### ISSUE TITLE
One controller cobtrolls the other controller 

### ISSUE THREAD

**Issue by MaSven** [x360ce/x360ce#262]
We tried to play some games with 4 controllers. 2 controllers where from CSL Nr. 25622 and Nr. 24130. And 2 xbox360 controller. The problem is one of the xbox360 controllers does also the input for the other xbox360 controller. So the game recognizes 4 players but only 3 controllers. The other two are working like a dream.

**Comment by Squall-Leonhart** [comment]
regression since the virtual passthrough was implemented.

**Comment by KiNGKiMO** [comment]
Same issue as:-
https://github.com/x360ce/x360ce/issues/178

**Comment by frijfrancis1** [comment]
Same issue here
anybody help
