### ISSUE TITLE
Divinity Original Sin uknown dll

### ISSUE THREAD

**Issue by ghost** [x360ce/x360ce#265]
Hello,

My controller isn't  being picked up by Divinity Original Sin : Enhanced Edition.
How do I find out what kind of DLL it needs? I already tried the basic ones.
Also how do I find out if it's accesible by xinput?

Thanks.

**Comment by Squall-Leonhart** [comment]
this title does not have native controller support of any kind.

**Comment by ghost** [comment]
Enhanced Edition does.
The trick was to disable driver signature enforcement. And now it works :)

**Comment by Squall-Leonhart** [comment]
not sure where driver signatures would apply to this, we don't load anything at driver level.

**Comment by ghost** [comment]
Yes, well I assumed at the beginning that it might be something x360ce related because the app saw it but not the game.
I just wanted to leave another comment so if people will have the same issue they'll be to find an answer that might help them.

**Comment by Squall-Leonhart** [comment]
and im saying that it is entirely impossible that your changing the KERNEL LEVEL driver signature check has anything to do with fixing this.

**Comment by tapcio** [comment]
EE is x64 only, use 64bit DLL.

**Comment by Nucleoprotein** [comment]
EE is x64 only, use 64bit DLL.
