### ISSUE TITLE
Street Fighter V controller

### ISSUE THREAD

**Issue by bbtdd8** [x360ce/x360ce#269]
please help make the emulator of controller Xbox 360 work in this game is very importante you will be a hero
the game in the
https://thepiratebay.la/torrent/12636100/Street_fighter_5_beta_cracked_with_karin_rashid_unlocked.
no have a vs mode yet but you can play wit a friend in training mode if controller Works
thx everywone

**Comment by Squall-Leonhart** [comment]
No, i have referred your post in a report to github administration.
