### ISSUE TITLE
Can not use both triggers together.

### ISSUE THREAD

**Issue by dstr0yr** [x360ce/x360ce#273]
Im using a MS wheel/wireless xbox 360 controller/Logitech Extreme 3D PRO and I would like to know how to get my triggers/pedals to work at the same time. For instance I can not ADS and shoot at the same time, dont see any options or fixes for this anywhere.

**Comment by whereisthefuckinfile** [comment]
this seriously needs to be fixed, they cancel each other out as if they are one axis, I know this is not a x360ce issue, but you really need to help us guys

**Comment by Nucleoprotein** [comment]
This is unfixable because DirectInput on such gamepad do not use two axes only one, so this is device/driver depended and user level software like x360ce cannot do anything about it. Also XBOX 360 devices in DirectInput mode behave in this way, so use passtrough for them.
