### ISSUE TITLE
dont work in fallout4 , please help me , thanks

### ISSUE THREAD

**Issue by lovefallout** [x360ce/x360ce#276]
Hello!

I use USB Network Joystick (i gota gamepad) 

to play fallout4 (W7-64 nvidia-358.91)

http://i.imgur.com/1U7Dqoh.jpg (it looks)

sometimes it works perfect 

but many times

when strat fallout4

fallout4.exe is crash (apphangb1)

please help me 

Thanks very much

(I think xinput1_3.dll have some wrong ?@@...)

(xinput1_2.dll xinput1_1.dll xinput9_1_0.dll not work)

**Comment by Squall-Leonhart** [comment]
issue tracker is not for game compatibility / support
