### ISSUE TITLE
Official Gamecube controller no longer works using x360ce for Rocket League.

### ISSUE THREAD

**Issue by TheSponginator** [x360ce/x360ce#278]
Hi, I've been using x360ce to play Rocket League with my Official Nintendo Gamecube controller for a bit under a month now, and have never had any issues until now. Recently, on the 10th of November, a patch was released for the game, and now suddenly, despite the fact that I didn't move any of the x360ce files from Rocket League, my controller no longer works. To resolve this, I have tried restarting my PC, restarting the drivers, validating the steam files and moving the x360ce files to various locations within the Rocket League folder but with no success. I have the files placed in rocketleague>binaries>win32 (as shown in the screenshot attached). 
![screenshot for rocket league support ticket](https://cloud.githubusercontent.com/assets/15813165/11114510/5d7dcfca-8979-11e5-8807-913eb0d699e8.PNG)
I contacted Rocket League support, and they told me  - "Our recent update streamlined the way we support xinput controllers (ie: Xbox 360), but it does not play nicely with your stated emulator (x360ce)". 
(Also, my current version of the software is 3.2.8.76 32-bit.)
So has anyone else had similar issues? And does anyone know any ways of fixing this? Any help is greatly appreciated!

**Comment by Joooop** [comment]
Try ticking "COM" in the game settings tab. Then save the game settings. This worked for me.

**Comment by TheSponginator** [comment]
(Sorry for my slow reply). But your solution has worked perfectly! Thanks so much for the help, much appreciated :)

**Comment by taboo8614** [comment]
This worked for me, Thanks!
