### ISSUE TITLE
Rocket League not working with controllers but other games do

### ISSUE THREAD

**Issue by Phantomised** [x360ce/x360ce#279]
I bought rocket league very recently hoping to play it with my controller. I am fairly familiar with this program as I use it for all my other games including GTA 5 and haven't had a problem with it because the games worked and still worked but it has never worked for rocket league. I have put the files in the binary/win32 for rocket league where all the dll folder are. I don't see where I am going wrong here, help?
![capture1](https://cloud.githubusercontent.com/assets/15815782/11117467/ef3758fc-8931-11e5-8474-5d5762f597e8.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15815782/11117469/ef3b7a36-8931-11e5-8b08-5be345282668.PNG)
![capture](https://cloud.githubusercontent.com/assets/15815782/11117468/ef39e338-8931-11e5-951a-4ee0c1be8986.PNG)

**Comment by Joooop** [comment]
Try ticking "COM" in the game settings tab then save. This worked for me.

**Comment by Squall-Leonhart** [comment]
Ticking com should do nothing, as it is enabled by default since many versions ago.

Use the forum for games though, this is for actual bug reports regarding the code and fully triaged developer reports.
