### ISSUE TITLE
32-bit version problem on Win 10 

### ISSUE THREAD

**Issue by Daveed93** [x360ce/x360ce#280]
Today (November 13th 2015) I got a big update (http://arstechnica.com/information-technology/2015/11/windows-10-november-update-features-fixes-and-enterprise-readiness/) for Win 10 (64-bit) and I think it somehow broke the 32-bit version of x360ce. Every game using 32-bit version runs very sluggish, there's a lot of shuttering etc. When I remove x360ce from the game folder, the game runs fine. There's no problem with 64-bit version. I use the newest version of x360ce (2015-10-04).

**Comment by Daveed93** [comment]
Okay, so reinstalling the gamepad drivers and testing the force feedback in the configuration tab seem to fix the problem.

**Comment by Squall-Leonhart** [comment]
as far as i know, this upgrade again removes the dx redist files.
