### ISSUE TITLE
Central management

### ISSUE THREAD

**Issue by redlath** [x360ce/x360ce#282]
Hi

What's the purpose of having a scan tool with .xml record and "Game settings", if when Applying / sync settings doesn't do it right and no matter what copying the main x360ce.exe to each game folder is required???

CJust saying

I hope it gets addressed soon

Cheers n keep it up

**Comment by EJocys** [comment]
Hi,

> I hope it gets addressed soon

I am in the process of rewriting configuration part of the x360ce Application. New version will be just one step away from dropping INI file, because all required configuration, for all games, will be store inside c:\ProgramData\X360CE folder.
