### ISSUE TITLE
Games Freeze when using x360ce

### ISSUE THREAD

**Issue by ghost** [x360ce/x360ce#287]
I have played Rivals of the Aether and Rocket League using the the x360ce adapter and a Gamecube controller with the 3-in-1 magic joy box adapter. Both games freeze when I play with the Gamecube controller. My question is what the fuck-ity fuck is going on? How do I fix this shit?

**Comment by Squall-Leonhart** [comment]
you can start by writing a 6000 word essay on how to ask for help properly.

**Comment by monosoul** [comment]
Same problem here.
Gamepad is: Logitech dual action
OS: Windows 10 (10.0.10586) x64
x360ce version: 3.2.8.77
Is there anything I can do to help you troubleshoot this issue?
