### ISSUE TITLE
AC: Syndicate

### ISSUE THREAD

**Issue by matjaz94** [x360ce/x360ce#289]
Hi i have a problem with AC: Syndicate. The game accepts the emulator but the buttons 5 and 6 are swapped with 7 and 8 also buttons 1-4 are a mess. I tried remapping them in the emulator but that doesnt help with the issue. If anyone has any ideas it would be greatly appreciated

**Comment by Squall-Leonhart** [comment]
probably same issue as FC4, protection related.

**Comment by Nucleoprotein** [comment]
Most Ubisoft games are not only protected but Ubisoft uses some freaking terrible compiler that produces sh*\* not code... It's hard to debug and I also it one of reasons that their games are so terrible optimized on PC. It may also be related to code quality of Ubisoft games, I think it really poor, and compiler my do its best ...

You've tried HookMask (0x0000000e) ?

**Comment by lawrencedesign** [comment]
Even it's installed in the Program files(x86)  folder it works fine with the x306ce_64 (64bit) version.

**Comment by matjaz94** [comment]
What's hookmask??

**Comment by ARS04** [comment]
My AC creed syndicate no accepts de emulator 

Solution?!

**Comment by Stolen-X** [comment]
@matjaz94 I have the same issue.+ right stick wont work properly.Hate Ubisheet ports.I am still waiting for solution (I mean FC4 not played yet at all...lol x3)

**Comment by lawrencedesign** [comment]
As I said 64bit version works properly. I play the game for days with controller and x360ce_x64

**Comment by Stolen-X** [comment]
@lawrencedesign U are right.Its working.Just need to change xinput1_3.dll to xinput9_1_0.dll

P.S>But with Far Cry 4 x360ce still wont work. FUCK!!!! :)

**Comment by Stolen-X** [comment]
@matjaz94 Use these Hooks:

[InputHook]
HookLL=0
HookCOM=1
HookSA=0
HookWT=0
HOOKDI=1
HOOKPIDVID=1
HookName=0

P.S> Strange, the log file appears when you launch the game on both xinput.dll (i mean 1_3 & 9_1_0)

**Comment by matjaz94** [comment]
Thanks you guys, i changed the hooks like stolen said and also swapped xinput. Now i'm off to stabbing templars. :+1:

**Comment by ARS04** [comment]
Hooks ?
How use those hooks?
where?
Please explain to me

**Comment by Stolen-X** [comment]
@ARS04 Open x360ce.ini and u will see.

**Comment by ARS04** [comment]
I delete hook mode = 1 in the notepad and paste

[InputHook]
HookLL=0
HookCOM=1
HookSA=0
HookWT=0
HOOKDI=1
HOOKPIDVID=1
HookName=0

**Comment by kamalelhaddad** [comment]
any one please give me the full guide 
- did I need to use x360ce_x64 or what ? 
  also I can't find where to change xinput1_3.dll to xinput9_1_0.dll
- did I need to edit the [InputHook] if I use 64

**Comment by ARS04** [comment]
solved problem AC sindycate 100% woks thanks!

**Comment by kamalelhaddad** [comment]
@ARS04 please tell me how with x360ce_x64 or the 32x ?

**Comment by Nucleoprotein** [comment]
Questions about configuration go here: http://ngemu.com/forums/x360ce.140/

**Comment by ARS04** [comment]
@kamalelhaddad 100% in x360ce_x64, in options, in the program go to game settings and activate all 64-bit  xinput files

**Comment by kamalelhaddad** [comment]
@ARS04 Thank you very much I did this and added the hook thing as will & finally it worked 100%
