### ISSUE TITLE
x360ce xinput.dll problem

### ISSUE THREAD

**Issue by Djepaz** [x360ce/x360ce#297]
Hello, 

I have problem as written above with xinput.dll. 
Step by step:
1. I have downloaded x360ce newest version from site: x360ce 3.2.9.81 (2015-10-04) • for 32-bit games
2. I have installed it
3. I got error when creating new xinput1_3.dll which says:  Failed to load 'xinput1_3.dll'
System.ComponentModel.Win32Exception (0x80004005): A dynamic link library (DLL) initialization routine failed.

When I let x360ce to create new xinput file I got that error, but when I use my old xinput1_3.dll from 1-2 years ago I dont have that error. My x360ce was working before I deleted my 1st xinput file by accident and when I have replaced it, I cant get my controller to work.
I have done every installation for compatibility that is listed on site.
I am using Windows 8.
When I place my old xinput files as I sad, I dont have error, but only red light that wont turn green.
I had this same error with old versions and fix was to use old xinput files.
I am trying to run this on game RocketLeague and I have been playing it on x360ce before I deleted that famous xinput file.

I have put xinput1_1 to xinput9_1_0 files and still not working.

**Comment by Djepaz** [comment]
I have tried running x360ce on various games and program still doesnt allow me to use my controller.
Games I have used it: Naruto Shippuden, Assassin creed, Rocket League

**Comment by Squall-Leonhart** [comment]
windows 8 is no longer a supported platform, you must be 7 sp1, 8.1 or 10.
