### ISSUE TITLE
I can't use my gamepad on RWBY: Grimm Eclipse

### ISSUE THREAD

**Issue by JackSpartan276** [x360ce/x360ce#299]
I have a THRUSTMASTER Dual Analog 4 and I'm trying to play RWBY: Grimm Ecplise but it doesn't detects the controller.

**Comment by Wilsu** [comment]
Mine is a ps2 generic gamepad and only works the left analog in the game

**Comment by Squall-Leonhart** [comment]
unity engine, can't fix.
