### ISSUE TITLE
Build error: POINT class not found, JocysCom\Win32 files missing from repo

### ISSUE THREAD

**Issue by SinusPi** [x360ce/x360ce#311]
The solution requires some JocysCom\ files to build, but they're not present in the repo. TOKEN_INFORMATION_CLASS.cs, ABS.cs, TOKEN_ELEVATION_TYPE.cs to name a few.

Trying to build in VS Express 2010, using x360ce.Engine.csproj (because VS Express 2010 wouldn't load projects listed in x360ce_vs2010.sln).

**Comment by Nucleoprotein** [comment]
x360ce_vs2010.sln ? That was only for building dll file for compatibility, I think is only used now for Windows XP support, application requires VS2015 (Community Edition or better recommended).

PS: I think we should upgrade dll to VS2015 U1 and use static runtime.

**Comment by SinusPi** [comment]
OK, moved to VS 2015 U1 CE.

Now I'm missing a POINT class (there isn't one defined in the zip).

Also, JocysCom.ClassLibrary.Win32.NativeMethods.WindowFromPoint is referenced by JocysCom\Controls\ControlsHelper.cs, but the only similar file is x360ce.Engine.Win32.NativeMethods and there's no WindowFromPoint method in there.

**Comment by EJocys** [comment]
Checked-in missing files.

**Comment by SinusPi** [comment]
Confirmed, projects now all build nicely. Thanks!
