### ISSUE TITLE
Got "system invalid operation" exception when running the x360ce_64

### ISSUE THREAD

**Issue by nizar1919** [x360ce/x360ce#313]
Hello,

I tried the x360ce_64 apps and I got the exception you can see in the attached pic. Is there any dll file that I have to download ? 

Thanks,
Nizar
![excep](https://cloud.githubusercontent.com/assets/6376660/11997529/6c8cc16c-aa7e-11e5-904f-b274a93ef928.PNG)

**Comment by Squall-Leonhart** [comment]
dotnet 4.5.2 not installed.
