### ISSUE TITLE
Left and right stick is getting stuck in app when moving them on gamepad.

### ISSUE THREAD

**Issue by Soya420** [x360ce/x360ce#314]
So i have succesfully installed x360ce to rocket league with my Gioteck VX-2 gamepad, the x360ce app has found the game pad and it seems to work. But when i use the analog sticks they seem to get stuck in one point in the app, and if i move them around nothing happens in the app they keep stuck. This happens to both analog sticks, but none of the other buttons: they work fine. Is there any way i can fix this?

https://cloud.githubusercontent.com/assets/16436535/12002914/888b5b3c-ab0d-11e5-86e9-daece0e616c3.jpg

This is a picture of how it looks when the left analog stick is getting stuck, it just stays a one point. it does the same with the right stick.

**Comment by Squall-Leonhart** [comment]
You are using an ancient version.

I don't even......

-facepalm-
