### ISSUE TITLE
PS3 controlers under windows 10 64bit not working, or maybe I´m a total noob.

### ISSUE THREAD

**Issue by r2rangel** [x360ce/x360ce#315]
Windows recognizes the controller as PLAYSTATION(R) 3 Controller, boot up x360ce it recognizes it but no movement from analogs or buttons, controller works fine using six axes app for android (Bluetooth), and also using the spctoolkit under windows 10, and also after installing the toolkit x360ce see it as a 360 controller (duh). did a bit of research and found out that windows driver signature is blocking the use of the PS3 controller, so i´m using spctoolkit for now, pretty sure the ps4 controller has the same issue. By the way, using it with a mini USB cable, no Bluetooth test done on the pc yet, 

spctoolkit source:
https://github.com/nefarius/ScpServer

**Comment by Squall-Leonhart** [comment]
Closed

The PS3 controller uses a non-standard command to bring it out of sleep, as such it is only able to be used when third party drivers are installed.
