### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by twinbllo** [x360ce/x360ce#316]
![untitled](https://cloud.githubusercontent.com/assets/16448531/12008547/3e398a4a-ac75-11e5-9045-2e858055944d.png)

I am new to PC gaming and just realized that it is more complicated. I have been messing around with my computer all day and just too tired to solve this problem. Can anyone help me here?

**Comment by jgibson2** [comment]
I am having this error as well. Win7 32bit.

**Comment by dbvolk** [comment]
Same problem, the versions 2.X are working but when i try the 3.X i get almost the same error message, i guess it is because i'm still using Windows XP and also cause i don't have the .net framework 4.6 installed because it requires vista or superior.

**Comment by Squall-Leonhart** [comment]
Windows XP is no longer supported.

For everyone else, there is Dotnet 4.5.2.  Its not listed in the requirements for nothing.
