### ISSUE TITLE
AC: Syndicate won't work with x360ce

### ISSUE THREAD

**Issue by MentegaManis** [x360ce/x360ce#319]
So, usually i use ps2 controller, plugged in with x360ce on any games and it works just fine. But, not on this game. i used x360ce but all of my buttons are messed up, and the analog sticks won't work correctly. I've tried these suggestions from 2 issues  : 
https://github.com/x360ce/x360ce/issues/289
and
https://github.com/x360ce/x360ce/issues/295
Still not working... Any more suggestion please ?

**Comment by Squall-Leonhart** [comment]
closed duplicate of issue 289

**Comment by Squall-Leonhart** [comment]
don't open new bugs if one exists in the tracker
