### ISSUE TITLE
Force Feedback [FFB] problem 

### ISSUE THREAD

**Issue by Mehrshadhp** [x360ce/x360ce#321]
HI,I have problem with FFB in some games like:Witcher3,NBA 2k16,Mortal Kombat X,GTA V ,and other,the problem is when I run some games and when the game is loading and when I heard the beep sound game crash and in some games like GTA V game stop working ,and when I uncheck the FFB game run normally but without  vibration,I have Windows 10 ,can anyone help me?

**Comment by Squall-Leonhart** [comment]
is problem in your controllers driver, not our code.
