### ISSUE TITLE
DS4 Windows + x360ce will only read inputs if connected via usb

### ISSUE THREAD

**Issue by bloodstormxx** [x360ce/x360ce#322]
I just bought a DualShock 4 controller and tried to use DS4Windows to play dark souls with it, but it didn't work because of an update. I found that x360ce works with DS4Windows and tried again to see if it would work. It works until you try to set up a dll while using the controller over Bluetooth. If anyone can link me the dll and x360ce file of a working DS4Windows+Wireless controller or just tell me how I can create one myself (preferably the latter) that would be greatly appreciated.

**Comment by Squall-Leonhart** [comment]
Bluetooth doesn't map the device to windows in a direct enough manner to permit full hooking.
