### ISSUE TITLE
The Witcher 3 x360 x64 grey square

### ISSUE THREAD

**Issue by Goodgame1805** [x360ce/x360ce#324]
I've been looking for solution for a longer while now and it seems no one has had the same problem as me.
I used the x360ce x64 in my Witcher 3 for a longer while and there were no problems, but i've had a little pause. Today i decided to play a little and it seems that my gamepad is NO LONGER suitable. i changed nothing, in the meanwhile the only game that i installed was Heroes V (could that be the problem?) it USED TO WORK and now, without changing any of the files in the witcher 3 nor the x360ce it doesnt work, in-game no pad input keys work, i have to use the keyboard. I tried to use older and newer versions of x360ce and updated all the components needed for x360ce to work (c++ .net and directx) it's worth to mention that the x360ce x32 WORKS, and the x64 works everywhere but the witcher.
When i run x360ce x64 it shows a grey square and nothing else, there is no pad image or key bindings.

**Comment by Squall-Leonhart** [comment]
Read the troubleshooting section.
