### ISSUE TITLE
x360c messed with all of my games

### ISSUE THREAD

**Issue by Stelio-Kantos** [x360ce/x360ce#327]
i installed it so i could play final fantasy 13 only the right analog stick woudnt work it was turning the screen left and i cant turn right when i looked at the x360 app the right stick xy axis values were going crazy i thought it was only on that game i switched to fallout 4 and it did the same and my fallout worked fine before i uninstalled the way it specified but the changes it made are still present and has made my games unplayable....

**Comment by Stelio-Kantos** [comment]
im using an afterglow 360 controller on windows and the x axis is stuck between 0 and mid 20 when i try to calibrate it. it wont turn right at all. ive tried reinstalling my device as well and that didnt work.

**Comment by Stelio-Kantos** [comment]
I reinstalled x360 to try on my tmini thrustmaster and it works fine for FF13. I tried installing the 64bit but it saying im missing files and cannot install and the 32 bit doesnt work with fallout apparently

**Comment by Nucleoprotein** [comment]
x360ce does NOT install. You run program in game directory to create xinput*.dll files. For FFXIII you need to run it in white_data\prog\win\bin sub-directory.

**Comment by Stelio-Kantos** [comment]
yes what i was trying to do is reverse everything it changed my xbox 360 controller worked perfectly for fallout 4 till i downloaded this....

**Comment by Nucleoprotein** [comment]
So delete xinput*.dll files from game directories.

**Comment by Stelio-Kantos** [comment]
there is none the only game i assigned xinput to x360 was ff13 witch i did delete all of them and the problem kept going i even deleted the zip file. i read the 64 bit version would work with fallout but it wont let me open it after i download it says im missing alot of things

**Comment by Stelio-Kantos** [comment]
and i got my tmini thrustmaster to work fine in ff13 using x360. it just messed up my afterglow 360 controller

**Comment by Stelio-Kantos** [comment]
is there no way to fix the problem with the x axis of the right stick....

**Comment by Squall-Leonhart** [comment]
closed because reporter has no idea what hes talking about.
