### ISSUE TITLE
Trigger pression

### ISSUE THREAD

**Issue by gitti88** [x360ce/x360ce#328]
Hello to everybody, 

First thank you for this great tool! 

I'm wondering if i can set the pressure sensitivity for the left and right triggers (which in my controller is similar to xbox one, they can be pressed gradually). 

When I press one trigger  i can se that the system recognize the pression, and assign a value of 255 , it coul be be great if it assign other numbers due to the quality of the pression.

For example in gta v you will be able to do a gradual accelleration relative to the pression of L2.

If there is a method to do this (admitting that the hardware has the structure to do this as this: http://ecx.images-amazon.com/images/I/71CxzhuVmvL._SL1500_.jpg )

thank you!

**Comment by Squall-Leonhart** [comment]
your controllers triggers are clearly digital only.

**Comment by GuilhermeGS2** [comment]
I have the same issue with iPega 9076, the sensibility works fine when I use the controller on my PS3.

**Comment by Squall-Leonhart** [comment]
ok, and on windows those triggers are on or off.
