### ISSUE TITLE
[Enhancement] DS4 Controller Functionality Settings Tab

### ISSUE THREAD

**Issue by shinra358** [x360ce/x360ce#329]
I would like to request a functionality tab for DS4 controllers which would hold specific features for that controller. Said features include:

-Touchpad > Mouse controls
-Idle Disconnect (time user configurable)
-Gyro Controls
-Rainbow coloring while charging
-Dimming of lightbar based on battery level
-Slow pulse effect with the lightbar when battery is low (same speed as pulse when charging)
-Configure lightbar color per controller
-Turn off controller when game is turned off
-Auto switches to wired controller if plugged in from bluetooth mode and vice versa.

**Comment by Nucleoprotein** [comment]
This is not DS4 driver/utility, we will not bloat emulator with such features which clearly belong to DS4 driver/util.
