### ISSUE TITLE
System Component Model. Win32 Exception (0x80004005) < not found

### ISSUE THREAD

**Issue by wadepoh** [x360ce/x360ce#330]
please help me this.

when i set up xbox controller emulator for 64bit games pop up a window > "System Component Model. Win32 Exception (0x80004005): The specified module could not be found. "  

How do I fix it ??

**Comment by Squall-Leonhart** [comment]
you install the system requirements listed.

**Comment by alexbreezy2** [comment]
pls how do I fix dis problem

**Comment by alexbreezy2** [comment]
please help me this.

when i set up xbox controller emulator for 64bit games pop up a window > "System Component Model. Win32 Exception (0x80004005): The specified module could not be found. " 

How do I fix it ??

**Comment by Git-Aleksandar** [comment]
I fixed it by installing vcredist 2013

**Comment by markitoxD** [comment]
Very thanks GitALeksandar you helped me xD i didnt find any video or explication for this error.

**Comment by a-lint** [comment]
This isn't working for me. It won't fix the issue and I'm running the 64bit version. It will fix the 32bit version, but the controller is still not recognized by the game.
