### ISSUE TITLE
my GAMEPAD issue

### ISSUE THREAD

**Issue by Pakikos** [x360ce/x360ce#337]
Hey!
So ive been trying to play Brawlhalla with my controller , i followed everything  on this post : 
https://steamcommunity.com/app/291550/discussions/0/619574421632224271/

And it hasnt work, i think the reason why is 
http://imgur.com/a/1c34H

I have opened with administrator and i have given the folders aswell. nothin seems to work :( 
I have this controller working for witcher 3 and for one piece pirate warriors, but doesnt get recognized on this game :(

**Comment by Pakikos** [comment]
Please someone help me, it must be an easy fix, it just seems that the program even with administrator rights and the folder that contains the .exe aswell still the access to the path is denied, therefore cant put brawlhalla on game settings at 32bit v9.1
:(

**Comment by Squall-Leonhart** [comment]
closed because duplicate
