### ISSUE TITLE
The Crew is not supported

### ISSUE THREAD

**Issue by AbdulazizBawazir** [x360ce/x360ce#344]
Hello everyone,

I have been trying the emulator with The Crew but, it is not working.
can you please help.

Regards,

**Comment by Squall-Leonhart** [comment]
Reported to work with xinput9_1_0.dll

Also, the issue tracker is not for end users to get help with games.

**Comment by AbdulazizBawazir** [comment]
thanks Squall, I will try... and where can I get the support?
