### ISSUE TITLE
Divinity Original Sin EE

### ISSUE THREAD

**Issue by ewoutbos** [x360ce/x360ce#350]
I can get my my PS3 controller to work. But my Cyborg Rumble pad will crash the game when I press A/X in the title screen. Then if i start the game it works fine untill I press down on the D-Pad which crashes the game aswell. If I only use my PS3 controller it is fine. Both controllers work fine in rocket league (32-bit).
Any Suggestions?

I'm ussing all the xinput dll files in 64Bit mode

**Comment by Squall-Leonhart** [comment]
all available pads must be configured to operate through x360ce with or without native as necessary.

**Comment by ewoutbos** [comment]
They are both correctly configured according to xbox360ce interface, And all the other buttons work just fine. It Just crashes at random times. I'm a game developer myself so i have Microsoft visual studio installed which will try to debug it on crash. 
This is the Crash Dump it makes:
 https://dl.dropboxusercontent.com/u/49489118/CrashDump%20-%2002-02-2016%2015h%2012m%2047s.dmp
I hope someone knows whats going wrong

**Comment by ewoutbos** [comment]
Apparently my cyborg controller is the problem the drivers for it won't run on Windows 10 in 64 bit mode. The problem is not related to xbox360ce
