### ISSUE TITLE
Final Fantasy Type-0, gamepad issue (x360ce_x64)

### ISSUE THREAD

**Issue by Xervils** [x360ce/x360ce#358]
Hello, 
I am new and I decided to write here to ask some help, after two days of trying using x360ce_x64.exe in order to make work Final Fantasy Type-0 with my Trust Predator gamepad. I am trying to make it work on a Lenovo Y50-70 laptop; weeks ago I used an Acer Aspire 5742g and I managed to make everything work with the following setup:
- I had to use x360ce_x64 to make my Trust Predator gamepad work;
- enable the Force Feedback Pass Through in the advanced settings;
- in game settings I selected the file fftype0hd.exe and enable COM, DI, PIDVID (Hook Mask), 64-bit v9.1 (XInput Files) and I made sure that Fake VID was 1118 and Fake PID was 654;
- renaming xinput1_3.dll into xinput9_1_0.dll.
  I tried to do the same thing with the Lenovo laptop, but when game starts I hear the Init Beep (so everything should be okay) but the game still doesn't take the inputs from the gamepad. 
  I have downloaded the latest version of DirectX (12), I have installed .NET 4.0 and I am pretty sure that I installed correctly Visual C++ Redistributable for Visual Studio 2013 (both versions) too.

What am I missing? Thank you for your help!

Ps. I want to make clear that x360ce does work perfectly for me with all other games like Dark Souls (which had the right analog messed up), Guacamelee! and Metal Gear Rising Revengeance. Only this one is the problematic one...

**Comment by Nucleoprotein** [comment]
This is not issue (yet) so you should write this here: http://ngemu.com/forums/x360ce.140/ instead.

**Comment by Xervils** [comment]
I am sorry! Can I copy the same text there?

**Comment by Nucleoprotein** [comment]
Yes...

**Comment by Xervils** [comment]
Thank you, sorry for mistaking '^^
