### ISSUE TITLE
x360ce 64bits issue with Windows10: Failed to load xinput

### ISSUE THREAD

**Issue by ib90** [x360ce/x360ce#359]
I've been using x360ce for a while now, and it worked just fine. 
Since I updated to windows 10, it's 64 bits version it sends this message and it doesn't work:
![x360ce](https://cloud.githubusercontent.com/assets/17229483/13032084/6698ceae-d2c4-11e5-93bb-9fe7807756e2.png)

I'm trying to use it with Fifa 15. 

What should I do?
Thank you!

**Comment by mcc001** [comment]
Hi,
I have the same problem with my W10, never had this error message before, with W7.
I'm using a Thrustmaster Red Legend Edition Steering wheel with the game Split Second.

**Comment by Squall-Leonhart** [comment]
DirectX must be reinstalled after updating the operating system.
