### ISSUE TITLE
XBOX One Controller not connecting

### ISSUE THREAD

**Issue by berry0** [x360ce/x360ce#361]
I have Lego Marvel Superheroes game through Steam. The game works with a single Xbox One controller but not two. I installed x360ce because I believe the game is designed to work with the Xbox 360 controller, not the One controller. I'm running windows 10 64bit. I have 2 XBOX One controllers plugged in and they are registered on ports 1 and 2 in my devices. x360ce loads fine and I have all the files in the same folder as the Lego game EXE. I have all the possible versions of xinput dll's in the file. I have played with numerous settings within x360ce including turning on/off 'pass through', changing the 'pass through ID' and combining the controllers but nothing seems to make much difference. If anyone has any ideas to help it would be appreciated.

**Comment by Squall-Leonhart** [comment]
So long as the xbox one driver is installed, the controller should appear as an xbox 360 controller to games.
