### ISSUE TITLE
Exception! error when launching x360ce_x64.exe

### ISSUE THREAD

**Issue by Djoleriss** [x360ce/x360ce#363]
![227ce7b60ef506b7cf8aa2ccc4bb03af](https://cloud.githubusercontent.com/assets/17320801/13152962/f6d20408-d671-11e5-8f0f-533aa622fa4c.png)

tried even previous versions but always get similar respond, hope it fixable.
thank you in advance.

**Comment by ProBanana123** [comment]
i have the same problem with the 32 bit version when i reinstalled my windows D:

**Comment by Squall-Leonhart** [comment]
install dotnet 4.6.2
