### ISSUE TITLE
"System.InvalidOperation" (Street Fighter V)

### ISSUE THREAD

**Issue by Innexus** [x360ce/x360ce#367]
My friend is having this issue when trying to launch x360ce.

![12789814_771349062995573_1024979335_o](https://cloud.githubusercontent.com/assets/17600527/13471984/bb38004e-e091-11e5-91fa-b63547144ac3.jpg)

Anyone knows what we are missing?

**Comment by Squall-Leonhart** [comment]
Dotnet is not installed
