### ISSUE TITLE
SFV Hangs on launch when using x360ce

### ISSUE THREAD

**Issue by griff-o** [x360ce/x360ce#368]
When I place the x360ce exe in the launch directory for SFV, when I try launching SFV the game opens to a black screen and hangs until I force stop the application. I am wondering if this has been heard of before and if there is a fix. Thanks in advance if anyone can point me in the right direction.

I am using x360ce 3.2.8.77
HORI RAP V4 Hyabusa
xinput 1.3

**Comment by Squall-Leonhart** [comment]
turn off vibration.

**Comment by griff-o** [comment]
Hey sorry for taking so long to get back to you, turning off vibration fixed the issue. Thanks a ton, this program rocks.
