### ISSUE TITLE
360ce Stops work 

### ISSUE THREAD

**Issue by mpperez3** [x360ce/x360ce#371]
Hi Evaldas
I had xpad360ce to play some games. It works fine with two gamepads at two days ago. But today it stops work, seems that there is a problem with one windows 10 update. It stops work when I connect two pads at same time, and it use 20% of CPU. Seem there is in a infinite loop.  
I had tried:
- Restart windows [Obviously]
- Delete all files and download again. 
- Execute in exclusive(empty) folder
  And I have same result.  

Thanks for your job.

**Comment by Squall-Leonhart** [comment]
uninstall the broken update.
