### ISSUE TITLE
Assigning multiple buttons to one key

### ISSUE THREAD

**Issue by ghost** [x360ce/x360ce#384]
So I want to play guitar hero with this program, but pressing the dpad every time I want to strike a note is way too uncomfortable, so I wanted to make that every relevant button on my gamepad (LB,RB,LT,RT,A) emules the Dpad at the same time. I already tried it with LB and it works, but I don't know how to map all 5 buttons to the dpad.

Any ideas?

**Comment by Venryx** [comment]
Would be useful for me as well.
