### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by Federico-Caraffi** [x360ce/x360ce#389]
s

**Comment by Squall-Leonhart** [comment]
turn off passthrough on that controller.

**Comment by Federico-Caraffi** [comment]
@Squall-Leonhart 
Problem solved, Thanks man!

**Comment by Federico-Caraffi** [comment]
The controller works on the emulator but not in games (it wasnt detect like a 360 controller).
I tried the controller in a lot of games: One piece pirate warriors 3, naruto ultimate ninja storm 4, rocket league, nuclear throne, broforce, hotline miami; even goat simulator. So i don't think that the problem are the games...
I tried to  do what the help windows say (copy the xinpunt1_3.dll  file with another name), but it continue to not work.
Please help.

**Comment by Federico-Caraffi** [comment]
please help
