### ISSUE TITLE
Game doesn't seem to be noticing the emulator.

### ISSUE THREAD

**Issue by Halfire08** [x360ce/x360ce#394]
I have a PS4 DualShock 4 Controller and a PS3 USB controller. I've been trying to play Dark Souls and Devil May Cry 4, but there are mapping problems for both games. Like when I hit X(A) the game thinks I'm pressing O(B). When I test the controllers in the emulator it appears to work fine but the games still don't work. I tried running the games without the emulator on and it has the same problem.

**Comment by Squall-Leonhart** [comment]
use the forum
