### ISSUE TITLE
Dualshock 4 Force Feedback

### ISSUE THREAD

**Issue by ghost** [x360ce/x360ce#399]
Hi, when i try to use the Dualshock everythings works just fine but the vibration. The controller es detected and the buttons are correctly mapped. The only thing missing is vibration.

When you use game with native support for the dualshock the controller indeed vibrates.

**Comment by Squall-Leonhart** [comment]
basic windows drivers do not support vibration, ie, no FFB library is present.

games which support the pad natively are talking to it via Raw / HID.
