### ISSUE TITLE
Detection issues

### ISSUE THREAD

**Issue by GeneStarwind09** [x360ce/x360ce#404]
So when I load this it tries to find controller profiles twice. The downloaded profile appears incomplete. Now when I try to record manually nothing happens for controller 1, but it works for controller 2 which is not what I want. I tried closing the second dialog upon loading but I always get errors,etc. There seems to be no way of limiting it to one controller and is really confusing. Please help, thanks.

Edit: I see no replies to the majority of threads here. (Having issue 404 probably doesn't help my case.) I get we're not exactly entitled to support for freeware but a response would be appreciated. This is the controller in question: http://www.amazon.co.uk/Wireless-Bluetooth-Controller-Telescopic-Joystick-EK-054-Black-Red/dp/B016W3SEVA
I got it to play my Steam games on a Windows tablet running Windows 10. I'm not sure of the device ID at this time but I can try and find that if needed. Also the controller detects perfectly in joy.cpl.

**Comment by Squall-Leonhart** [comment]
we do not support bluetooth pads, there are issues involved that prevent hooking working.
