### ISSUE TITLE
GTA V - Vibration

### ISSUE THREAD

**Issue by MagicHarri** [x360ce/x360ce#408]
Hello to you , I've got my TWIN USB GAMEPAD to work with GTA V, but I don't get any vibration inside a game. It worked in games like Wolfenstein Old Blood, New Order, Mad Max, etc. Force feedback is turned on in x360ce. What should I do ? Thanks in advance !

P.S. I can feel it little if I change FFBType to 1 !

**Comment by Squall-Leonhart** [comment]
your gamepad doesn't have a compatible 64bit FFB library
