### ISSUE TITLE
Blank screen - Witcher 3

### ISSUE THREAD

**Issue by Vardion17** [x360ce/x360ce#424]
I wanted to configurate X360CE for The Witcher 3 for the first time on newly installed system. I put the file to right directory (SS 1), but when I open x360ce_x64.exe I get blank, gray screen (SS 2). If I click anything on the keyboard, I get that message box (SS 3). It worked perfectly with The Witcher 3 before. What should I do to make it work again?

http://i.imgur.com/qJ5QJIN.jpg

**Comment by Squall-Leonhart** [comment]
this is caused by a recent windows update.

**Comment by Vardion17** [comment]
Will uninstalling that update work?

**Comment by Nucleoprotein** [comment]
> this is caused by a recent windows update.

Any details ?

**Comment by adiachenko** [comment]
For anyone wondering on how to circumvent this problem, you can simply copy-paste already generated xbox360ce files from other game.
