### ISSUE TITLE
HELP - Quantum Break doesn´t detect my remote PC

### ISSUE THREAD

**Issue by AlJourgensen** [x360ce/x360ce#430]
Hello community

i´m using motionjoy, i already tried x360ce, but with any of this tools i can´t get my ps3 remote to be recognized, he is recognized in all my other games except this one

can somebody please help me

Thank you
![sem titulo](https://cloud.githubusercontent.com/assets/4504771/15100176/b15d8980-1562-11e6-948a-bd186ce87516.png)

**Comment by AlJourgensen** [comment]
I´m using motionjoy, and Better DS3, i alreday tried also ​Xbox360_64Eng tool, nothing works, and i try all configurations possible

**Comment by Squall-Leonhart** [comment]
motionjoy already implies Xinput support.

use Durazno
