### ISSUE TITLE
Webpage down

### ISSUE THREAD

**Issue by RodBelaFarin** [x360ce/x360ce#438]
Hi,

I think your webpage including download is down.

**Comment by AltarBeastiful** [comment]
You could host some files on github in case that happen. It's quite hard to find a trustful mirror if the main site is down.

**Comment by disastranagant** [comment]
Not to mention you need the website for gamedbs and inis.

**Comment by EJocys** [comment]
Restarted web and database server.
@disastranagant Next release of the app will download majority of settings for for hundreds of most popular controllers and games for offline use, so it will be able to operate without online database better. No release date, yet.
