### ISSUE TITLE
Dualshock emulator

### ISSUE THREAD

**Issue by Marspeedsman** [x360ce/x360ce#439]
I really like the x360ce, but I prefer the dualshock system better, and whenever I use the app, games show me Xbox button labels, which can be really confusing (the X button for instance) so can't there be an option to emulate the joystick into a dualshock instead of an Xbox controller? Thanks

**Comment by Squall-Leonhart** [comment]
This is fucking stupid.

closed.

**Comment by Marspeedsman** [comment]
And would you like to enlighten me as to why this question is stupid?

**Comment by Nucleoprotein** [comment]
Because DualShock uses old, DirectInput API and x360ce is in reality a Xinput2DirectInput emulator, ie. nothing to emulate. Also games shows buttons as they like, this is not defined in any API.

**Comment by Marspeedsman** [comment]
That makes sense. If dualshocks are directinput controllers and games only read xinput, they'd never have dualshocks labels.
Sorry for bothering you guys
