### ISSUE TITLE
Problem with Bluetooth gamepad 

### ISSUE THREAD

**Issue by Shmayro** [x360ce/x360ce#453]
The Program show to me 2 Detected controlers , the first is not working but the second is working , the first have the priority so it's make the second not working .
Please how to switch priority or how todisable the first Controler .
Thx a lot :) Team <3
![capture d ecran 66](https://cloud.githubusercontent.com/assets/6267648/16267361/a90bd03a-3889-11e6-8323-ff2b7f6d4d22.png)

**Comment by Squall-Leonhart** [comment]
bluetooth controllers are not supported.

**Comment by Shmayro** [comment]
But it's working i wana just to delete or set as disable the first Controler , there is an option or config for that ?
