### ISSUE TITLE
Add compat with The Legend of Korra

### ISSUE THREAD

**Issue by jprzimba** [x360ce/x360ce#454]
Please Add compat with The Legend of Korra
This is good game but your emulator not working with :(

**Comment by Squall-Leonhart** [comment]
does it evne use xinput?

**Comment by jprzimba** [comment]
Now it's working for me.
I'm using xinput1_1 xinput1_3 and xinput9_1_0 because i don't know what is working... i've put all in game folder and now my generic control is working.
