### ISSUE TITLE
Controller being duplicated

### ISSUE THREAD

**Issue by bbviking** [x360ce/x360ce#455]
The issue I am having is that every time I try to setup the software in a game directory it detects my ONE controller twice, and as two separate controllers despite having the same ID. And for some reason the "Controller 2" is the only one that seems to respond to button inputs, whilst "Controller 1" despite having exactly the same config doesn't respond at all to button inputs. Of course very frustrating for game profiles which are configured for the controller 1 input. This happens EVERY TIME on my computer, even if I delete the config. It doesn't happen though on my other computer. I should also note that there was a point that that the software did in fact work as intended, and then seemingly randomly it decided to change.

Below is screenshots of x360ce open

http://imgur.com/a/5GHVO

**Comment by Squall-Leonhart** [comment]
bluetooth controllers are not supported.
