### ISSUE TITLE
x360ce current advertised version (3.2.9.81) and actual version (3.2.8.77) do not match

### ISSUE THREAD

**Issue by RytoEX** [x360ce/x360ce#458]
On the [x360ce website](http://www.x360ce.com/), it advertises the latest version as "3.2.9.81 (2015-10-04)".  However, the executable files (both 32-bit and 64-bit) acquired from the download links display version "3.2.8.77 (2015-10-04)".  The dates match, but the version numbers do not.  I have provided screenshots below.  This is a minor/trivial issue, but it had caught my eye, and I had not seen it reported yet.

![2016-06-26 18_51_38-xbox 360 controller emulator](https://cloud.githubusercontent.com/assets/624931/16365470/0ecba89e-3bcf-11e6-99d2-906ce0135a91.png)
![2016-06-26 18_44_06-tocaedit x360 controller emulator 3 2 8 77 2015-10-04 64-bit](https://cloud.githubusercontent.com/assets/624931/16365472/18ed7d34-3bcf-11e6-8ab9-34abfc443d41.png)
![2016-06-26 18_43_13-x360ce_x64 exe properties](https://cloud.githubusercontent.com/assets/624931/16365473/1cc8b98c-3bcf-11e6-9414-ea90f3af5b28.png)

**Comment by EJocys** [comment]
@RytoEX 
Thank you for reporting this. v3.2.8.77 is actually v3.2.8.81 (2015-10-04) with these changes
- Fix: Crash when linking settings to controls.
- Fix: 64-bit crash.
- Fix: Offer fix when used tries to start application from Windows folder.
- New: Links to game help.
- Update: Issue solvers updated. Fixed broken links.

I forgot to update version number in assembly file before doing release build. Version number will be corrected in next release.

**Comment by alperen19071** [comment]
heyyyyyyyyyyy

**Comment by melsayed151289-png** [comment]
محتاج تحميل البرنامج

**Comment by melsayed151289-png** [comment]
رائع
