### ISSUE TITLE
Failed to load xinput1_3.dll

### ISSUE THREAD

**Issue by djabr3** [x360ce/x360ce#459]
I'm trying to set x360ce for The Witcher 3 game and this error appears:

"Failed to load 'xinput1_3.dll'
System.Component.Model.Win32Exception (0x80004005): %1 (then in my language:)not Win32 application"

Why is this happening? I've used x360ce earlier on other games but never met such problem. I did all windows updates, checked PC for viruses, reinstalled game - nothing changes.

Can you please suggest what should I do please? I want to play it so bad. Thanks

**Comment by Nucleoprotein** [comment]
You try to use 64bit DLL file with 32bit application or vice versa.

**Comment by djabr3** [comment]
No, I use 64-bit app and dll file is the one that was already installed in game.

**Comment by Pacheco95** [comment]
Same problem here
![capturar](https://cloud.githubusercontent.com/assets/12385467/16570293/f83df29e-4218-11e6-9c45-691ba7752580.PNG)

**Comment by MilanKerslager** [comment]
Same problem here. I have 32bit game (Rocket League) and the same error is reported.
I tryed 64bit version of x360ce, but it told me that I have 32bit game, so no luck.
My system is up-to-date Windows 10 (10.0.14393).

**Comment by drf0rk** [comment]
Same issue here done everything to try resolve

**Comment by eduPHP** [comment]
Same problem here, using windows 10, solved installing vcredist from https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by djabr3** [comment]
Hey stop texting ) I don't remember how do I resolved this

четверг, 17 августа 2017 г. пользователь Eduardo написал:

**Comment by Nucleoprotein** [comment]
1. You need to use correct architecture of x360ce to you game **NOT** system, ie 32bit (x86) x360ce for 32bit games, 64bit (x64) x360ce for 64bit games ! 32bit x360ce run just fine on 64bit system and is **REQUIRED** to support 32bit games.
2. "Not Win32 application" - you system does not have correct Visual Studio run-time libraries - install requirements - https://github.com/x360ce/x360ce#system-requirements 
as stated on page - for x64 systems install both x86 and x64 redistributables !

**Comment by djabr3** [comment]
stop spaming, delete me from dispatch plz!

2017-08-18 19:27 GMT+03:00 Robert Krawczyk <notifications@github.com>:

**Comment by Nucleoprotein** [comment]
You need to unsubscribe yourself, we can't do anything on your github account.
I can close and lock this issue for you if you want.
