### ISSUE TITLE
DS x360ce

### ISSUE THREAD

**Issue by eksuri** [x360ce/x360ce#460]
Dark Souls binds to the first controller present on a host machine, and will bind to my controller directly rather than the emulated device through x360ce.

**Comment by Nucleoprotein** [comment]
@EJocys 
DirectInput wrapper is not included now in executable ? I cant find option to enable it, even changing DIputFile does not create it and it's required for that option to work ...

**Comment by EJocys** [comment]
Looks like a bug to fix. You can download dinput.dll from here as a temporrary workaround:
https://github.com/x360ce/x360ce/raw/master/x360ce.App/Resources/dinput_x86.dll
https://github.com/x360ce/x360ce/raw/master/x360ce.App/Resources/dinput_x64.dll

**Comment by ErikUri** [comment]
I think the issue is actually with Dark Souls grabbing onto some device other than my controller; the game will not connect to a Xbox One controller even. I'll close this for now.
