### ISSUE TITLE
Up/down on both axis are stuck

### ISSUE THREAD

**Issue by MohabMohie** [x360ce/x360ce#462]
OS: Windows 10 clean installation
Gamepad type: Generic

Issue description: the gamepad is working fine on windows 7 machine, but both axis are stuck in an upwards movement and they don't respond to user input on windows 10 machine. This happens on both the x360ce.exe and the calibration tool, so it's probably a windows issue. Is it possible for you to bundle a driver update with the tool or create a workaround to override this issue in your dll files?

Notes: all other buttons are fine, and both axis work fine for left/right movement. The problem is with uo/down movement only, and on the windows 10 OS only.

**Comment by Squall-Leonhart** [comment]
no.

**Comment by MohabMohie** [comment]
Thank you for the response and sorry for the disturbance.
