### ISSUE TITLE
Doesn't work with Steam

### ISSUE THREAD

**Issue by coldwater96** [x360ce/x360ce#465]
Hey, guys.
I have a very strange problem with the program: it does work with pirated copy of the game (DS 2: Scholar of the First Sin, for example) but does not with the copy which I bought and downloaded from Steam. I put it in the right folder, because you can hear the beep and the controller is connected (it works, but the buttons are not the one I set in x360ce) 
The settings in .ini file are same for both. 
I find it realy disappointing, would be very thankful for any help

**Comment by Squall-Leonhart** [comment]
that version of DS2 is 64bit, you have the wrong archtype dll

**Comment by coldwater96** [comment]
Thank you for answer!

What can I do about it? Is there any way to run the game with x360ce?

2016-07-14 16:50 GMT+03:00 Squall Leonhart notifications@github.com:
