### ISSUE TITLE
left trigger activates ABXY

### ISSUE THREAD

**Issue by MarkonLehel** [x360ce/x360ce#469]
For no apparent reason the left trigger is button 1, but button 1 is already mapped for A and if i change it to button 6 (the proper button for LT) then it will activate ABXY but not the trigger.No solution to the problem i am the first one to find it, but sure i will not be the last because this software is pretty effortless.

**Comment by Squall-Leonhart** [comment]
dll version?

**Comment by MuhdAmirulAiman** [comment]
I just encounter this..How to fix this..Anyone????
