### ISSUE TITLE
Use x360 globally

### ISSUE THREAD

**Issue by dagadbm** [x360ce/x360ce#473]
I'm not sure this is the right place to ask but are you thinking of making x360ce global on the whole system?

Something like you only needed to have 2 x360ce executables (32b or 64b in separate folders ofc) and inside you would only need to add the game executable you would like.

It gets a bit crazy having to copy all the x360ce executables (32bits or 64bits) to the games you want to use.

Have you ever considered adding this feature?

Somet

**Comment by EJocys** [comment]
Unfinished Beta version stores all settings for all games inside one folder: c:\ProgramData\X360CE
x360ce.xml
x360ce.Games.xml
x360ce.PadSettings.xml
x360ce.Presets.xml
x360ce.Programs.xml
x360ce.Settings.xml
x360ce.Summaries.xml
I was thinking about using virtual XInput controller (similar to vJoy) so there would be no need to have xinput.dll and INI inside game folders and correct configuration could be loaded by simply detecting game executable name in the process list. Unfortunately, I have limited time to implement that, so progress is very slow.
