### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by Leeryl2f2** [x360ce/x360ce#477]
Running the 32 bit version

![capture](https://cloud.githubusercontent.com/assets/20610050/17473611/ee6dae54-5d83-11e6-84f4-85453a71cc2f.PNG)

**Comment by Nucleoprotein** [comment]
Why you copied this to system32 ? You want to break yours system ?

**Comment by Leeryl2f2** [comment]
I didn't 

Did I?

**Comment by EJocys** [comment]
Please check properties of the shortcut of x360ce.exe and make sure that  its working folder (Start In:) is not c:\windows\system32

**Comment by Leeryl2f2** [comment]
Where should it be? :P

**Comment by EJocys** [comment]
That would be the properties of the icon you are double clicking on when launching x360ce.exe.

a) Are you using scripts to launch x360ce.exe?
b) Have you used commands like Start-Process -FilePath x360ce.exe -WorkingDirectory c:\windwos\system32
c) Are you launching x360ce.exe as an Administrator, which can set working directory to c:\windwos\system32 by default?
d) Check if your Windows is not misconfigured and not using c:\windwos\system32 as a temp folder. (you can check it by starting "Command Prompt" and executing command: SET
e) Try to rename c:\ProgramData\X360CE folder to c:\ProgramData\X360CE**.bak** and restart x360ce.exe
