### ISSUE TITLE
Overcooked - how to use x360ce in this game?

### ISSUE THREAD

**Issue by mehigh85** [x360ce/x360ce#481]
Does anyone have any experience with the game Overcooked? I haven't figured out yet how to map my Hama analog gamepad for this game with x360ce. Thanks in advance!

**Comment by Alapaga** [comment]
I used an old controller to play this game with the latest version of x360ce (32 bits) and it worked for me. I just pasted the binary in the folder containing the game executable.

**Comment by mehigh85** [comment]
Thanks, I'll try out again!

**Comment by mehigh85** [comment]
Thanks, it works with the newest version of x360ce! :)
