### ISSUE TITLE
Right-trigger keeps activating Left-trigger while holding Left-trigger and tapping/holding Right-trigger at the same time

### ISSUE THREAD

**Issue by Underx01** [x360ce/x360ce#508]
Hello,

I started using x360ce_x64 for my games (Hitman, GTA 5) with my Wireless Official XBOX360 Controller
and works great with remapping the buttons, but I encountered a problem while using both triggers:

**If I hold Left-trigger and at the same time start using Right-trigger, either tapping it or holding it (basically shooting (rapidly) in-game) the Right-trigger keeps activating Left-trigger which prevents me from using the Right-trigger/shooting.**

This only happen if I uncheck the "Pass Through" option. But I need to uncheck that so that I can remap some of the button the way I want. After hours of searching on the internet, I found a solution for my problem (from [Youtube](https://www.youtube.com/watch?v=JDK5CYcLupE)) but the xinput1_3.dll is old and doesn't work on any of the new games from 2015-2016. 

I attached [xinput1_3.zip](https://github.com/x360ce/x360ce/files/527270/xinput1_3.zip) the fix-file if someone would like to examine it. Also with that xinput1_3.dll I couldn't remap anything ("Pass Through" was unchecked) but I can't use that xinput1_3.dll file anyway cause it doesn't support the new games.

Could someone help me with fix this issue? Here is my [x360ce.zip](https://github.com/x360ce/x360ce/files/527299/x360ce.zip) ini file.
Thank you in advance for taking the time reading this and perhaps coming up with a solution for this issue.

**Comment by Nucleoprotein** [comment]
"This only happen if I uncheck the "Pass Through" option."
In DirectInput both triggers are using single axis so you cant distinguish if both are pressed or both are released so that is your problem - and this is not fixable, this is know limitation of software.

**Comment by Underx01** [comment]
Thank you Nucleoprotein for the fast reply. 
Ah well, that's too bad, I guess the only solution that I can use is to disable both triggers in x360ce and remapping them into keys/buttons (keyboard/mouse) using Antimicro for example, that would do the trick for now :)
Thanks again for the information.
