### ISSUE TITLE
Pro Evolution Soccer 2017 SL-6555-SBK xbox 360 clone not working

### ISSUE THREAD

**Issue by bobalazs** [x360ce/x360ce#520]
Pro Evolution Soccer 2017 SL-6555-SBK xbox 360 clone not working
In the settings app of PES 2017 there is controller option, if i set it to directinput i can find my controller and set its settings properly. But then ingame doesnt recognize gamepad.
If i start x360ce 32bit (32bit game) the color stays red on controller, no ding sound, not working.
What needs to be done?

**Comment by Nucleoprotein** [comment]
Denuvo protected games are not supported.
