### ISSUE TITLE
[FIFA 16] Buttons are mixed,regardless of setup from x360ce

### ISSUE THREAD

**Issue by Jdefon** [x360ce/x360ce#521]
The controls on fifa are mixed regardless of what I do.
RB is RT and RT is RB,
LT is LB and LB is LT,
When you flick the RS up it goes right,if you flip RS down it goes left.
Does anyone know a fix,please? :(

**Comment by Nucleoprotein** [comment]
Denuvo protected games are not supported.

**Comment by Jdefon** [comment]
Oh,thanks for the heads up.
