### ISSUE TITLE
Controller not working with batman:AA

### ISSUE THREAD

**Issue by jbienz** [x360ce/x360ce#53]
_From [ya1the...@googlemail.com](https://code.google.com/u/107952156054638670530/) on August 05, 2010 07:11:59_

What steps will reproduce the problem? 1.Using speedlink xeox gamepad, and x360ce.App-2.0.2.66.
2.Without FakeAPI enabled
3.With FakeAPI enabled (fakeWMI =1 FakeDI=1) What is the expected output? What do you see instead? Expected output is to get beep and button work when game is loaded. I get the beep and gamepad buttons/vibration works fine with x360ce.exe, but no buttons work in game. Gamepad works with version 3.1.4.1, with fakeAPI=1, but no vibration. What version of the product are you using? On what operating system? x360ce.App-2.0.2.66, windows 7 x64. What gamepad are you using? On what version of drivers? XEOX USB Gamepad, black, driver SL-6555-SBK-A-Win7.rar ( http://www.speed-link.com/?p=2&cat=3132&pid=22714&paus=2 Please set third label to Core if issue affect emulator (dll file) or App if issue affect x360ce.App application (exe file). Also if you want you can provide any additional information below.

_Original issue: http://code.google.com/p/x360ce/issues/detail?id=53_

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on August 05, 2010 06:23:56_

Please set Log=1 and post a log file.

**Status:** Accepted

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on August 05, 2010 07:20:30_

Found critical regression in newest revision, please use xinput lib rev 120 for now.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on August 05, 2010 10:44:21_

r138 should resolve this issue. Please download new version.

**Comment by Squall-Leonhart** [comment]
Was fixed.
