### ISSUE TITLE
x360ce doesn't work on Windows 10

### ISSUE THREAD

**Issue by Osyotr** [x360ce/x360ce#54]
Hi all, I have a problem with x360ce, the library starts with "Failed to load "xinput1_3.dll": the specified module could not be found".
I tried new and old versions, but both are not working. Also, I checked old librares - they are not working, too.
Can't see any logs...

**Comment by Osyotr** [comment]
Took my old config from Dark Souls 2. Now it is working.
New version is still unusable.

**Comment by Squall-Leonhart** [comment]
we'll worry about windows 10 when it is final.

**Comment by dmcfc** [comment]
Well...now it's final and I still get the same error as he did. Has anyone found any solutions or any work around?

**Comment by Squall-Leonhart** [comment]
would help to know exactly what module could not be found.

**Comment by dmcfc** [comment]
Failed to load "xinput1_3.dll": the specified module could not be found

that's what is shown. 

Although the file xinput1_3.dll is in the same folder.

I tried to just copy the app with the other files from win 7 to the same game on win 10 and now it shows this message.

**Comment by Squall-Leonhart** [comment]
did you run the d3d9 june 2010 update?

**Comment by dmcfc** [comment]
If by that you mean DirectX End-User Runtimes, than yes, I did run the update, this two following versions.

https://www.microsoft.com/en-US/download/details.aspx?id=35

http://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by Squall-Leonhart** [comment]
and the visual studio 2013  runtime?

https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by EJocys** [comment]
I will be upgrading to Windows 10 this weekend and will be able to check this issue.

**Comment by Squall-Leonhart** [comment]
Can you check if Passthrough is enabled in the app?

**Comment by ad-ab** [comment]
Can confirm. Had problems on win 10. 
Upgraded to latest x360ce
downloaded https://www.microsoft.com/en-US/download/details.aspx?id=35 
and https://www.microsoft.com/en-us/download/details.aspx?id=40784
and everything started working. 

Thanks a lot guys.

**Comment by Nucleoprotein** [comment]
Confirmed. After installing DX Redist on Windows 10 I have all xinput dlls from 1.0 to 1.4 in system directories, and x360ce works fine.

**Comment by EJocys** [comment]
Can confirm too. After installing requirements, mentioned on x360ce Home Page, x360ce started to work on clean Windows 10 Pro.

**Comment by samthurston** [comment]
Just to chime in, I had trouble after installing all the dx/runtime stuff
on Windows 8.1 until I ran the troubleshooter and created a compatibility
profile. This might be worth mentioning on the documentation.

Frankly I feel the inclusion of the outdated tutorials in the readme does
more harm than good.

**Comment by Squall-Leonhart** [comment]
from what has been said so far, no compatibility profile was required.

**Comment by ad-ab** [comment]
i will just add. on windows 8 i didnt have to install anything. My comment was only for win10
