### ISSUE TITLE
Help, i can't install vibration driver. Apollo GP-3100 gamepad.

### ISSUE THREAD

**Issue by Karaulov** [x360ce/x360ce#540]
How to download Apollo GP-3100 force feedback drivers? 
Or why x360 can't emulate this drivers ?

**Comment by Karaulov** [comment]
( Force Feedback not working )

**Comment by Karaulov** [comment]
Win7 x64

**Comment by Nucleoprotein** [comment]
I can even find drivers to this, I think drivers are terrible broken so no FFB for this device.

**Comment by Karaulov** [comment]
possible to emulate driver ? please create driver emulator for unsupported devices

**Comment by Squall-Leonhart** [comment]
no it isn't and no we won't.

**Comment by Karaulov** [comment]
It is not possible or you not want to do it?

**Comment by Nucleoprotein** [comment]
> please create driver emulator for unsupported devices
Really ?

**Comment by Karaulov** [comment]
Really ?
