### ISSUE TITLE
AC Brotherhood - button names

### ISSUE THREAD

**Issue by herezjarcha** [x360ce/x360ce#547]
Hello,

I'm having a hard time setting up x360ce for Assassin's Creed Brotherhood. I use an official xbox360 controller with chatpad (for other games). The chatpad requires driver different than default for xbox360 controller and uses vJoy for configuration - therefore my device name is "vJoy Device".

The controller works perfectly fine, but the game shows it's prompts as "button 3" or "button 12" instead of simple xbox360 icons. I believe that the game will show buttons as icons when it recognises controller as a standard microsoft device. I tried changing InputHook via both GUI and ini file but no luck. GUI changes seem impossible to save, ini changes simply doesn't work - the game still sees "vjoy device".

Could someone help me with this? I'm pretty much stuck.

**Comment by Squall-Leonhart** [comment]
AC requires com hooking, and vjoy devices are not compatible with that.,

**Comment by herezjarcha** [comment]
So, there's nothing I can do about it? AC2 and AC4 show button icons correctly. Maybe there's an option to customize button names through vjoy? But this doesn't belong to this thread...
