### ISSUE TITLE
dark souls II scholar of the first sin

### ISSUE THREAD

**Issue by frigobbar** [x360ce/x360ce#55]
i just installed the 64 bit release and everything works fine, except for 1 thing. If you chose "Quit" from menu in game , you will move into main menu, but, if you do it, the control resets to default (in specific, your input acts like if you don't have x360ce installed/setted) and you have to restart the .exe to fix it. I tried to do the same in Dark Souls Prepare to Die Edition (obv with x86 version of x360ce) and this defect doesn't happen. I've changed nothing in particular in the options, apart button mappings of my ps2 controller to match the xbox delay, in both games. Another question, is normal that both games takes like a 5-10 secs more to shut down from taskbar when you run this dll's? thanks for all answers

**Comment by Squall-Leonhart** [comment]
your gdb doesn't include the dark souls 2 profile.

**Comment by frigobbar** [comment]
ehm, what do you mean? i think this is a place where you can signal bug to authors of program :\

**Comment by frigobbar** [comment]
update : i found why the games takes like 5-10 secs to close. when i terminate the application (in specific both dark souls ptde or dark souls II sotfs), windows opens werfault.exe but i can't find any log errors about it

**Comment by Squall-Leonhart** [comment]
gamepad not working is not a bug, its a lack of the correct profile being used.

Crash on exit is caused by 'faulty' FFB library

**Comment by frigobbar** [comment]
Your answer are kinda short for a person who need help (obv i don't know what you said in your first post cause i can't see/find any database file and i don't even know what FFB library is), if I am annoying you I will stop it, I'm just here to help myself and your project... or maybe it's just my english that sucks, in anycase i try to explain again.

Dark Souls Prepare to Die Edition :
- Pad WORKS FINE.
- Crash on exiting the game (aka close the exe)

Dark Souls II Scholar of the First Sin : 
- Pad WORKS FINE.
- Pad settings RESETS if you go into menu and chose "EXIT" option (aka go to main menu of game) (you need to restart the game to reload [i assume that dll reloads] and then your configuration work again)
- Crash on exiting the game (aka close the exe)

If they are not bug, or if I am not in the right place to discuss or have some help about that, can you adress me?

Thanks in advance.

**Comment by Squall-Leonhart** [comment]
Force Feedback is the library that provides rumble effects to a controller, many of them have issues when unloading the library and can crash.

A quick read of the tutorial and manual links provided from the Readme would help you, but the file you want to update can be grabbed from https://raw.githubusercontent.com/x360ce/x360ce/master/x360ce/Support/x360ce.gdb

**Comment by frigobbar** [comment]
I updated that file but controller bindings keep resetting when i go into main menu. And i tried almost everything for crashes but i can't do nothing about that, well, thanks anyway.

**Comment by Squall-Leonhart** [comment]
what did you change in the ini that fixed it?

**Comment by frigobbar** [comment]
I enabled hookmask as guide says, but it didn't fix nothing. If you instaquit from in-game menu to  main menu the bindings doesnt reset, but if you wait a bit before quit the bindings reset to default, and you need to restart game, so your configuration will be reloaded. And on the front of crashes when you close app i've no news

**Comment by Nucleoprotein** [comment]
Set 'Timeout=0' (under [InputHook]) and recheck, maybe game reinitializes device and filter it out...

**Comment by Squall-Leonhart** [comment]
This may or may not be related, but GTA5's vibration stops working if you alt+tab

**Comment by EJocys** [comment]
I think I saw this happening in people tutorials about x360ce on YouTube with older version too. Something like: GTA 5 must run in full screen mode for FF to work. I am getting closer to proper force feedback effects on G27 wheel for GTA5, but not close enough. I think I will separate force feedback effect types for left and right motors (combined simulation if possible). Constant type (simulating big left motor) would be for crash/collision and Sine Wave (simulating small right motor) would be perfect to simulate car engine.

**Comment by Squall-Leonhart** [comment]
It works fine in all screen modes that i've tested, it is only if you alt+tab that the FFB stops.

Maybe window binding is being lost due to the launcher opening the device as well?

Maybe we need a gdb entry to disable hooking on certain processes? or does hookmask=0 work?

**Comment by Araeos** [comment]
I experienced the exact same issues as described by the OP and adding `Timeout=0` under `[InputHook]` fixes the controller reset.
Additional info: Every time I open the _Key Bindings_ menu during gameplay the controller seems to hang for a second and then continues to work normally only if the `Timeout=0` line is in the ini. Otherwise the key mapping of x360ce stops working.

**Comment by Nucleoprotein** [comment]
Add `Timeout=0` (infinite timeout) to GDB entry and it will be used now properly, fixed in PR #85
