### ISSUE TITLE
Force feedback stopped working

### ISSUE THREAD

**Issue by HanzoSW** [x360ce/x360ce#555]
It worked perfectly before and i used x360ce mostly for DS3, but after some patch x360ce stopped working at all. So i used motioninjoy for some time, but now motioninjoy is not working so i go back to x360ce an it actualy working, but vibration is not woking. When i test vibration from control panel it wocking fine, but in x360ce test its not working (somethimes only the let motor wocking in test, in the game is not working at all) if i open control panel tes while x360ce is open its not working too.

P.S. Sorry for my english

**Comment by AmrKhedr** [comment]
I have a similar issue with DS2, the Left and Right motors rotate with each other when I test the **Left** motor, while nothing happens when I test the **Right** motor.
And in control panel they work separately without any problem.
