### ISSUE TITLE
Website's down?

### ISSUE THREAD

**Issue by refi64** [x360ce/x360ce#557]
![x360ce](https://cloud.githubusercontent.com/assets/1690697/22187667/2992b40a-e0d0-11e6-83e1-3ffc3e5a9bc7.png)

**Comment by chukyx007** [comment]
Yup. its down. at least to my knowledge. I need it to I just installed a game, and Xbox360ce doesn't load right cuz their website is down. shucks..

**Comment by EJocys** [comment]
Thank you for reporting. Fixed.
