### ISSUE TITLE
x360ce & Denuvo Games

### ISSUE THREAD

**Issue by D-Prince** [x360ce/x360ce#560]
**x360ce!** you guys are awesome, really appreciate your work. :) Because of you guys ,, i can play every single game with my gamepad, Even it works perfectly with Batman: Arkham Knight, donno know how though you have said  **!!! Denuvo protected games are not supported !!!** 
 cant you guys do something about it?! :(

**Comment by Nucleoprotein** [comment]
They my work, but we not support it. Denuvo copy protection can mess-up API hooking we use to make you generic DirectInput gamepad Xinput capable.
