### ISSUE TITLE
32 bit don't work 64 bit work

### ISSUE THREAD

**Issue by ghostofspartas** [x360ce/x360ce#576]
when I try to install 32 bit app it says svcmp120 dll is not found.I checked and it's there.and when I install 64 bit it works just fine please help.

**Comment by Nucleoprotein** [comment]
https://github.com/x360ce/x360ce#system-requirements

"Visual C++ Redistributable for Visual Studio 2013 (For x64 systems install both x86 and x64 redistributables)"
