### ISSUE TITLE
32 bit don't work 64 bit work

### ISSUE THREAD

**Issue by ghostofspartas** [x360ce/x360ce#577]
32 bit programme don't work and say Msvcp120.dll isn't installed (I checked and it's there).while the 64 bit programe work just fine .
Windows 8 64 bit.
I installed c++visual studio 2010 +2015 just to make sure it still doesn't work.

**Comment by Nucleoprotein** [comment]
https://github.com/x360ce/x360ce#system-requirements

"Visual C++ Redistributable for Visual Studio 2013 (For x64 systems install both x86 and x64 redistributables)"

Reinstall if already installed (uninstall first).
