### ISSUE TITLE
NARUTO ULTIMATE NINJA STORM 4 CRASH WHEN FORCE FEEDBACK IS ENABLE X360CE

### ISSUE THREAD

**Issue by divier03** [x360ce/x360ce#579]
I NEED HELP WITH THIS, THE GAME CASH WHEN THE FORCE FEEDBACK IS ENABLED, CAN YOU HELP ME WITH THIS PROBLEM PLEASE? WHEN I UNCHECK THE FORCE FEEDBACK THE GAME RUN WITH NOT PROBLEMS BUT I WANT PLAY WITH FORCE FEEDBACK

**Comment by Squall-Leonhart** [comment]
blame your gamepad.
