### ISSUE TITLE
How To Play As 1 Keyboard And 1 Xinput

### ISSUE THREAD

**Issue by IceBow46** [x360ce/x360ce#583]
Hi, I want to Play Human Fall Flat With My Friend, But Sadly 1 Of My Ps2 Controller Broke, And I want To Play As 1 Keyboard And 1 PS2 Controller, But I Have The Twin Usb GamePad Converter, Is There Any Way To Play With 1 Keyboard and 1 Ps2 Controller With Twin USB GamePad, Sorry If My English Pretty Bad

**Comment by Squall-Leonhart** [comment]
not a valid bug report
