### ISSUE TITLE
Controller Combine Not Working

### ISSUE THREAD

**Issue by RarePika** [x360ce/x360ce#586]
If you've heard of the Nintendo Switch, you probably know about its two "Joy-Con" controllers. With further research, I found out how to connect them to a PC as a controller. I started x360ce to find out that both the Joy-Cons registered as two separate controllers. I tried using the controller combining feature to combine the second controller with the first. One I checked the option, the second controller turns red and doesn't work. Can someone please help me? Thanks!

This other user had this problem: #575

-RarePika

**Comment by Squall-Leonhart** [comment]
nope, not touching this.

bluetooth controllers do not work correctly.

**Comment by RarePika** [comment]
#NotHelpful

**Comment by RarePika** [comment]
The controllers work great individually. It's not the bluetooth, its 360ce being unable to combine the two controllers.

**Comment by RarePika** [comment]
Honestly, your "solution" seems like an excuse so you don't have to deal with the problem

**Comment by Squall-Leonhart** [comment]
no, it is the bluetooth. and we're not touching it because it doesn't work with hook com correctly, which given you're likely trying to use this with GTA5, is why its not working.

**Comment by RarePika** [comment]
Im trying to use it with Portal 2
