### ISSUE TITLE
DEAD OR ALIVE 5 Last Round

### ISSUE THREAD

**Issue by Bexile** [x360ce/x360ce#59]
The game forcing my Controller as DiNPUT, whatever i do, i try diffrent Hook Mask options like COM & DI butt not work. Still the Game push the Controller as DiNPUT.

My Controller have just 13 Buttons [STEELSERIES Free Mobile Wireless Controller] When i play the Game the X button doesn't exist and of course the button mapping is totally different than the Xbox Controller.

Issue 1142:
https://code.google.com/p/x360ce/issues/detail?id=1142&q=dead%20or%20alive

**Comment by Squall-Leonhart** [comment]
Not a bug, this game does not support xinput.
