### ISSUE TITLE
Unbox compatibility issues

### ISSUE THREAD

**Issue by nkeller74** [x360ce/x360ce#599]
I just wanted to make it known that I haven't been able to get the Xbox game Unbox by Prospect to work with x360ce.  This game is supposed to support local multiplayer but the PC version(available on Steam) won't work with standard USB/bluetooth controllers.  I'm hoping someone can test x360ce with this game and report there findings.  Maybe I did something wrong.  Cheers.
-Nate

**Comment by Squall-Leonhart** [comment]
duplicate
