### ISSUE TITLE
Feature to manually set analog stick center/offset

### ISSUE THREAD

**Issue by stevenanthonyr** [x360ce/x360ce#606]
Dead zone support currently lacks the capability to set the center position of the analog stick. This could be done by allowing the user to supply an offset for y or x axis per each stick.

For example, my Switch Pro Controller's left analog stick is flawed; at rest, it is positioned at (-600, -3700). This makes my `Y_max = 20000` and my `Y_min = -25000`, which is very off and affects gameplay significantly. A solution would be to allow for users to supply an offset for each direction, so that I could offset my x and y readings such that the resting position of my analog stick is read in as close to (0, 0) as possible.

Please add this functionality if possible, I imagine it wouldn't be much harder than adding an offset to each axis XInput output right before it's returned and capping the output at the ranges of XInput, though I admit that I have no idea how the internals of this project look, just that the dead zone concept is somewhat similar to (and more complex than) this one. 

It seems to me that implementation would need to be done around [Line 528 of Controller.cpp](https://github.com/x360ce/x360ce/blob/a9a50373814b83a38b7f23e58e9f085d6e78236b/x360ce/x360ce/Controller.cpp#L528), where we could add/subtract offsets based on the axis type right before we convert the value to negative if it's supposed to be. View is located at [x360ce.App/Controls/ThumbUserControl.cs](https://github.com/x360ce/x360ce/blob/master/x360ce.App/Controls/ThumbUserControl.cs)

I don't mind attempting to implement this if someone can point me to resources on how to build this application from source (I'm a scrub and don't know how; is it just running msbuild with the .sln file in the root of this repo?)

**Comment by Nucleoprotein** [comment]
Because is not required, calibrate your gamepad in joy.cpl - calibration will be used by x360ce.

**Comment by stevenanthonyr** [comment]
You're right, Robert. Thanks! I stumbled upon joy.cpl in my tinkering but didn't think it'd work since it's instructions seemed quite deprecated.
