### ISSUE TITLE
Saitex X52Pro does not work Twist on Bumper

### ISSUE THREAD

**Issue by Kykarjamba** [x360ce/x360ce#61]
"Left Shoulder=x-6             (does not work)"
"Right Shoulder=x6            (does not work)"

I appoint any axis on Bumper no one does not work
appoint any button on Bumper all works

I need to assign an axis z (twist) on Bumper

**Comment by Nucleoprotein** [comment]
Your sure you use correct axis index ?

**Comment by Squall-Leonhart** [comment]
Ah, now i understand your problem.

Tapcio, we don't allow Axis to work on digital buttons for some reason?

I can reproduce this when trying to map my analog triggers to the bumpers or buttons.

**Comment by Kykarjamba** [comment]
Please to make a Twist on the Bumper really need to fly in the GTA V.

Thank you so much.

P.S. Sorry for my english.

**Comment by jbienz** [comment]
I fixed this issue tonight with checkin number deaccd2. I added the ability to map analog axis to buttons. The GUI already supports this but the dll did not handle it properly at runtime.

NOTE: Two new config options have been added that weren't there before:

Left Shoulder DeadZone
Right Shoulder DeadZone

There is currently no UI to handle the setting of these deadzones but I have tested them and can verify that they do work.

Kykarjamba you will either need to build the project from source code or just wait few days for Tapico to build an updated release. 

Tapico or Squall, are either of you up for adding a slider somewhere in the GUI to allow for adjusting the new deadzones? I'm really swamped this weekend with other commitments.

**Comment by jbienz** [comment]
Wait, I take that back. I forgot that I added support for dead zones on all buttons. So the following config options were added:

```
 "A DeadZone",
 "B DeadZone",
 "X DeadZone",
 "Y DeadZone",
 "Left Shoulder DeadZone",
 "Right Shoulder DeadZone",
 "Back DeadZone",
 "Start DeadZone",
 "Left Thumb DeadZone",
 "Right Thumb DeadZone",
```

There is no GUI facility for setting any of them. I don't know how we want to handle that.

**Comment by EJocys** [comment]
I can handle that, because I also have to update database and web services.

**Comment by jbienz** [comment]
Awesome EJocys. Thanks. Maybe we add a new tab for "Button Deadzones" or something. That's just a lot of sliders to add. Ping me on e-mail if you'd like me to help test. Thanks again for taking care of this.
