### ISSUE TITLE
HUGE problem with triggers!

### ISSUE THREAD

**Issue by Eminan** [x360ce/x360ce#611]
Hi, i have a really HUGE problem. I can´t press both triggers at the same time. (Xbox One Controller) They null each other. It can be seen in the configuration tab, they work individually but not at the same time.
I don´t know if this is just me but this problem makes it unusable.
v3.2.9.81.

**Comment by Squall-Leonhart** [comment]
use xinput plus instead.

**Comment by iam-jim** [comment]
So there is no way to fix this on 360ce? That's a shame.

**Comment by Nucleoprotein** [comment]
x360ce was designed to be a DirectInput to Xinput 'Emulator' not keys remapping app. In DirectInput triggers are positive/negative half of axis so it is programmatically impossible to fix this.

**Comment by iam-jim** [comment]
But both trigger actually works if I select "Pass Through" then deadzone stops working. If only deadzone worked with "Pass Through" enable. I am sure there are some technical difficulties, to make "Pass Through" and "Dead Zone" work together?

**Comment by Nucleoprotein** [comment]
Because "Pass Through" disables emulation and the remaping/deadzone stuff is done at DirectInput emulation level. It's possible to make thing works in "Pass Through" but not without some bigger rewrite.

**Comment by iam-jim** [comment]
Yah, that makes sense. But can I use the setup of XInputPlus and feed that to x360ce (dead zone, button remapping)?

**Comment by Nucleoprotein** [comment]
I think XInputPlus have all remapping stuff you need.

**Comment by iam-jim** [comment]
Alright, thanks.
