### ISSUE TITLE
D-pad only works in one direction with Monect virtual controller

### ISSUE THREAD

**Issue by D-side** [x360ce/x360ce#63]
This is not a complete description of the problem, since I failed to build this project and couldn't actually find the cause or check if the problem persists with the most recent version.

So, the first issue is **please, provide build instructions for this project**. I would rather track down the issue and submit a pull request than bug you with the issue I can't accurately describe =)

Now for the issue that led me here.

There is an Android application called [Monect PC Remote](http://www.monect.com/) that emulates a game controller with its own DirectInput virtual device on a PC, controlled via UDP from the application.

The issue concerns gamepad mode. I've seen multiple complaints that the `POV`:arrow_right:`D-pad` mapping doesn't work properly with recent versions of `x360ce` library, yet some ancient version of the emulation library seems to work just fine. The exact issue is: D-pad only works upwards, not in any other direction.

I've looked at the code that corresponds to that and found that it was checking the range of 10 degrees in each direction, but now it's been improved and each direction covers an entire semicircle, 90 degrees to both sides. So I failed to see any regression there, but it seems to exist and be related specifically to Monect, since even a cheap hardware gamepad works properly with the latest libraries too.

I've yet to reproduce it. I'm being cautious right now, the controlling application is requesting way too much permissions (calendar access, media files, call status, geolocation), so I'm preparing an empty device to test it safely and find out why is all that needed and what is happening.

I would appreciate any directions/tools for debugging this. I know my way around C++ and I could probably fix this myself once I find the cause.

The only clue I currently have is that POV is a bit off the intended values, except for up:

```
D-Pad Up    0
D-Pad Right 9024
D-Pad Down  18048
D-Pad Left  27072
```

But looking through the code I haven't found any direct comparisons.

**Comment by Squall-Leonhart** [comment]
the project is entirely self contained apart from the DirectX 2006 SDK, im not sure what you would have had troubles with unless you were using an express version of vs....(hint: install the community version)

**Comment by Squall-Leonhart** [comment]
That said...  operation with virtual controllers is not something we will focus on expressly, so no guarantee that it will ever be fixed.

**Comment by D-side** [comment]
I actually have VS2010 Professional. So I doubt it's the issue. It did ask me for SQL Server Data Tools for one of the projects and the downloadable installer for these seems to have been taken down by Microsoft. It's not too important since I only have to build a library. I suppose it doesn't rely on SQL server? :)

Okay, I'll try installing DX SDK 2006 and let you know how it goes.

**UPD:** wow, download speed is ridiculously low :(

**Comment by Squall-Leonhart** [comment]
ah, the current code cannot be built with vs2010 afaik,  some C++11 is being used.

**Comment by D-side** [comment]
All right, that's good news, I have 2013 as well. Will try it out.

**Comment by Nucleoprotein** [comment]
Values of D-PAD are in degrees \* 100, ie. UP is 0 or 36000, Right is 9000, down is 18000 and left is 27000 - https://github.com/x360ce/x360ce/blob/master/x360ce/x360ce/Config.h#L84

As D-PAD is digital, pressing each button should get EXACTLY that values, if not, there something wrong with you device. Code for detecting which POV button is pressed and translating this to XInput buttons is here: https://github.com/x360ce/x360ce/blob/master/x360ce/x360ce/Controller.cpp#L107

**Comment by D-side** [comment]
@tapcio yeah, I've read both of these files through like 4 days ago. Only that the measure is deg/100 and the value "right" is 9000. Nothing new.

Yes, that D-pad behaves as digital, the values are **always** the same every time: `0`, `9024`, `18048` and `27072`. Just noticed a pattern there, they're all multiples of `9024`, offsets are not random! I'll report that to Monect, since they might be able to fix it easily in their driver. Meanwhile, I'd figure out what's wrong here. It's odd that such little offsets drive the emulator nuts when the code is quite specific that they shouldn't. This might cause problems with other devices we may not know.

The weirdest thing about this is, that it works fine with an older version of the library (with games using older Xinput), when the mapping code (currently in `Controller.cpp`) was in a file `x360ce.cpp` or something like that. That was quite some time ago. At that time, the mapper consisted of 2 functions, one of which returned one of 8 integers (`0` to `7` IIRC) depending on the POV, and another one actually mapped that integer to Xinput D-pad. The code was obviously improved since then.

Since the mapping uses not `==` for directions, but [`IN_RANGE`[`2`] macro](https://github.com/x360ce/x360ce/blob/9094f4d314b8058decc23c368abd084af36df230/x360ce/Common/Utils.h) with ranges that seem correct to me &mdash; I just fail to see why the emulator only detects precise equality.

**Comment by D-side** [comment]
Okay, installing DirectX SDK and using VS2013 seemed to have got the build working. DLL at least. I don't need anything else, but I'm getting curious.

Debug mode also appears to need VLD. At least it's easy to identify.

`ditool` build fails to find `dxguid.lib`. Is that supposed to come from DX SDK 2006?

**Comment by Nucleoprotein** [comment]
2006 ????? I use June 2010 ie. latest.
https://www.microsoft.com/en-us/download/details.aspx?id=6812

**Comment by Squall-Leonhart** [comment]
ah, 2010, 2006.. not much of a difference except 2010's has some headers missing for dx8

**Comment by Nucleoprotein** [comment]
Hym, dxguid.lib is even in 2004 (last one with ddraw.lib).

**Comment by Squall-Leonhart** [comment]
lol yeah.

its probably trying to use the Dx included with VS2013,  its missing dxguid iirc.

**Comment by Nucleoprotein** [comment]
@D-side 
You need to set a env value DXSDK_DIR with path to DXSDK directory. Project are already configured to favor DXSDK header/lib.

@Squall-Leonhart 
Why closed ?

**Comment by Squall-Leonhart** [comment]
wrong button....

the close and comment button should really be in Red...

**Comment by Nucleoprotein** [comment]
LOL :P

**Comment by D-side** [comment]
All right, I still can't get `ditool` to build (and I don't really care :P), but I've hit the bottom of the issue. I believe there is an issue [with this code](https://github.com/x360ce/x360ce/blob/master/x360ce/x360ce/Controller.cpp#L106). Not just related to Monect, a general one.

See, the DirectInput POV is supposed to map to 8-positional Xinput D-pad. But the mapping is done in a way that the base Xinput directions (up, right, down, left) map to **exact points** on DirectInput, i. e. only map to **single integer POV value each**; but the rest, diagonal (up-left, down-right and so on) map to **entire ranges between these values**. So should there be a **slightest offset** (even by 1) from the canonical values, the emulator will show them as diagonal.

I personally think that the POV circle should be split into 8 equal ranges that each map to single D-pad direction. If you agree, I can work on and submit (via PR) a patch to fix this.

I only have one question. Why have you factored out these POV values (9000, 18000, 27000...) into a separate file? Just to keep code clean, or is there any feature that required that?

**Comment by D-side** [comment]
@tapcio, @Squall-Leonhart? Is the issue clear? If not, I can draw a pic of the mappings to explain.

I'm not certain this issue only affects Monect, there may be other gamepad drivers that work like that.

**Comment by tapcio** [comment]
It's clear. I almost done fix for this but EJocys merged "Support for Direct Input D-Pad buttons map to XInput buttons, axis and triggers added." and broke my code :p

**Comment by Nucleoprotein** [comment]
I reviewed code and problem is not in that code, previously you can map any value to POV button but that code was disabled in some commit (I dont know why): https://github.com/x360ce/x360ce/blob/master/x360ce/x360ce/Config.cpp#L413
x360ce.App should detect you device values and set correct ones to ini file so ranges can be correctly set, but  above code need to be uncommented first.

Please check PR #82

**Comment by EJocys** [comment]
That part became obsolete, because new method to map D-Pad buttons and axis was implemented.

D-Pad buttons now have 'd' prefix:
D-Pad 1 Buttons:
 d1 (Up), d2 (Right) d3 (Down), d4 (Left)
D-Pad 2 Buttons:
 d5 (Up), d6 (Right) d7 (Down), d8 (Left)
...

Now you can map Axis Trigger and Slider directions (±) to D-Pad Buttons, Normal buttons and other way around.

// This maps D-Pad 1 to Stick (X/Y):
Right Analog Y- Button=d3
Right Analog X- Button=d4
Right Analog X+ Button=d2
Right Analog Y+ Button=d1

// This maps Stick (Axis 1/2) to D-Pad 1:
D-pad Down=x2
D-pad Left=x-1
D-pad Right=x1
D-pad Up=x-2

// Map D-Pad 2 to ABXY keys:
A=d7
B=d6
X=d8
Y=d5

**Comment by jbienz** [comment]
With this change, what do we want to do about the pull request? Just politely decline? I'm trying to clean house a little bit on the open issues and pull requests. I noticed we had a lot of issues left open in the old system that look like they were either addressed or the conversation on them just died out.

**Comment by Nucleoprotein** [comment]
@EJocys 
But D-side need to remap POV Switch values, not button/axis...
D-side gamepad problem is that is not ideally calibrated, so it will return always diagonal with current code. We can do two things to fix this: manually set degrees for its device directions in ini file or map 8 directions ranges (ie. with diagonals). First option is easier and was working before config code was commented out.

**Comment by D-side** [comment]
Actually, the second option is not difficult when you're armed with integer division (since all 8 ranges are equal, we can use it) and it gives additional benefit of no extra configuration requirement.

[Clickable
![](http://i.imgur.com/PYL0daq.png)](http://www.wolframalpha.com/input/?i=plot+y%3Dfloor%5B%282250+%2B+x%29%2F4500%5D+with+x+from+0+to+36000)

The left half-range lies right on the X-axis itself so it's barely visible. I had to use `floor` for the plot, but it's not necessary with integers. On top of it, by taking `n%8` we get `0` across all _up_-range.

**Comment by Nucleoprotein** [comment]
Hym, if you can, make PR.

**Comment by EJocys** [comment]
@D-side 
I assume UP, RIGHT, DOWN, LEFT button value code (Controller.cpp, Line 136) must be replaced with this:
            s8 y = ((2250 + povdeg) / 4500); // y = [0-7] with povdeg from 0 to 36000
            // XINPUT_GAMEPAD_DPAD_UP
            dPadButtons[d \* 4 + 0] = (y >= 0 && y <= 1) || y == 7;
            // XINPUT_GAMEPAD_DPAD_RIGHT
            dPadButtons[d \* 4 + 1] = (y >= 1 && y <= 3);
            // XINPUT_GAMEPAD_DPAD_DOWN
            dPadButtons[d \* 4 + 2] = (y >= 3 && y <= 5);
            // XINPUT_GAMEPAD_DPAD_LEFT
            dPadButtons[d \* 4 + 3] = (y >= 5 && y <= 7);

**Comment by Nucleoprotein** [comment]
SGTM

**Comment by D-side** [comment]
It could be `((2250 + povdeg) / 4500) % 8` (to bring `8`, the rightmost half-range, back to `0`), but it's not necessary. It just gets a clean 8-way mapping (otherwise 0 and 8 both mean _up_).

Then `UP` condition should be like `y <= 1 || y >= 7`, that should will work either way, since the `y` range is math-wired to be in range [0; 8] or [0; 8).

Yep, that's pretty much it.

**Comment by EJocys** [comment]
@D-side New version of application (3.0.3.36 Beta 3, 2015-05-12) and libraries (3.4.1.1299, 2015-05-12) ready for tests. Download files on project home page updated.

**Comment by EJocys** [comment]
Re-uploaded download files. Previous files were *.RAR files with *.ZIP extension, because I've tried to use RAR command line tool which doesn't support ZIP compression.

**Comment by D-side** [comment]
Yep, works now! Thanks!
Build instructions would still come in handy though.

**Comment by EJocys** [comment]
@D-side 
I've added some build instructions here:
https://github.com/x360ce/x360ce/blob/master/Wiki/HowTo.md

If project won't build after all steps are complete then open new issue please.
