### ISSUE TITLE
Need UI option to adjust deadzones for axis to button mappings

### ISSUE THREAD

**Issue by jbienz** [x360ce/x360ce#64]
We recently added the ability to map an axis to a button. This feature also requires configurable deadzones for the buttons, which were also added. The GUI needs to be updated to allow users to configure the following settings:

 "A DeadZone",
 "B DeadZone",
 "X DeadZone",
 "Y DeadZone",
 "Left Shoulder DeadZone",
 "Right Shoulder DeadZone",
 "Back DeadZone",
 "Start DeadZone",
 "Left Thumb DeadZone",
 "Right Thumb DeadZone",

Thanks for offering to own this one EJocys

**Comment by EJocys** [comment]
Done
