### ISSUE TITLE
x360ce.exe doesn't recognize my controller (Controller 1 always red)

### ISSUE THREAD

**Issue by Chrodierent** [x360ce/x360ce#642]
Hello, It's the first time for me to use x360ce v3.2.8.77 because I want to use my cheap controller on PC to play The Witcher 3, but whenever i connect the controller, the red square always turns red and I cant use it inside the game even when I already configure the key to suit my controller. Can anyone pls help me ?

![controller x360ce](https://user-images.githubusercontent.com/30309117/28402124-5dd027a2-6d48-11e7-9cc9-c25435448b28.jpg)

**Comment by wac1996** [comment]
Have you tried going to advanced and clicking off pass through?

**Comment by Chrodierent** [comment]
It's ok, I already figure out the solution, thanks btw

**Comment by anurupr** [comment]
it would be great if you could tell what solution you found
