### ISSUE TITLE
Closes!!

### ISSUE THREAD

**Issue by elvisqc** [x360ce/x360ce#650]
When I copy it to "Sonic and all stars racing transformed" ... I try to open it and it closes and it opens every time ..

**Comment by JuU2** [comment]
I do have the same problem!
After installation I copy&paste the .exe into the gamefolder of "The witcher 3", where the game.exe is located. Then I start X360ce.exe - and it opens and closes it again and again and again.... How can this problem be solved?

**Comment by Squall-Leonhart** [comment]
This is due to running the application in a protected location without elevation.
