### ISSUE TITLE
Wheelman, Saints Row

### ISSUE THREAD

**Issue by Karaulov** [x360ce/x360ce#653]
Sticks are inverted by Y! How to fix it ?

In x360ce settings no inverting. Only in games. Possible to fix it ?

Gamepad : esperanza eg102 (USB NETWORK JOYSTICK)
Windows 7 x64

And i got error x360ce.xml sometime. #

**Comment by Squall-Leonhart** [comment]
you see that submenu with the i(nverted) or h(half axes)
