### ISSUE TITLE
Doesn't work at all with Resident Evil 0

### ISSUE THREAD

**Issue by anjari** [x360ce/x360ce#654]
I'm using xbox360 wired controller on Windows 10.

I want to swap X and B key for RE0. I googled and I found people suggesting x360ce, so I give it a try. I followed the instruction, downloaded the 32 bit version, put the 360ce.exe and INI file in game exe directory, then remapped the keys. When I run the game, the key remapping has no effect at all, the game runs with normal key mapping.

I have tried copying the xinput1_3.dll as xinput1_2.dll, xinput1_1.dll, xinput9_1_0.dll, etc. Still doesn't work.

I'm not sure what's wrong. Could be the latest version of RE0 somehow doesn't work anymore with x360ce?

I enabled the initial beep sound setting, but I don't hear any beep sound at all when the game started, I guess the dll is not loaded at all by the game.

----

I also tried x360ce on another game like Alien Isolation, it doesn't work too.

**Comment by Squall-Leonhart** [comment]
if you have an xinput gamepad, you should use xinputplus or durazno rather then a full emulator.
