### ISSUE TITLE
fixes one controller and breaks the other

### ISSUE THREAD

**Issue by AnessZurba** [x360ce/x360ce#656]
Hi
sorry for not giving description the last time (by mistake)
I have strike FX gamepad from speedlink and dualshock 4 v2
I already have a dedicated emulator for the dualshock that works perfectly
I want to use x360ce with my speedlink gamepad
but as soon as I copy the files to game directory the dualshock stops working on the game
tried to change key bindings for it but it seems that the program doesn't like it
So my suggestion is that the program emulate the strike FX but to leave the dualshock alone

**Comment by AnessZurba** [comment]
I seem to have fixed it by using 360 controller profile but I think it would be better if the program just leaves this controller alone
Anyway, thanks for this awesome tool

**Comment by Squall-Leonhart** [comment]
User error

you are required to set any device that is already an xinput device to pass through in the x360ce application.
