### ISSUE TITLE
1 controller being recognized into two

### ISSUE THREAD

**Issue by tayyabjawad** [x360ce/x360ce#657]
I only connect 1 bluetooth controller with pc while x360 recognizes it as two controllers.Where controller1 cant be configured and controller 2 can?

**Comment by Brocky45** [comment]
You just have to check  " Exclude supplemental devices " in the option tab

**Comment by tayyabjawad** [comment]
i want to play call of duty ghosts but i simply cant get this emulator to work.What should I do?

**Comment by Squall-Leonhart** [comment]
use a mouse and keyboard as the game intended
