### ISSUE TITLE
error 0x80004005

### ISSUE THREAD

**Issue by vusaliko** [x360ce/x360ce#663]
after reinstalation windows 10  this programm dont see my gamepad. It also show me that message:  System.ComponentModel.win32 exception (0x80004005) not found specified modul. It also show this message when i try 32-bit version

**Comment by vusaliko** [comment]
i instaled drivers for gamepad

**Comment by vusaliko** [comment]
smb can help?

**Comment by Squall-Leonhart** [comment]
dot net is missing.
