### ISSUE TITLE
Using XInput 1.4 crashes Rocket League

### ISSUE THREAD

**Issue by Octillerysnacker** [x360ce/x360ce#668]
So I've been trying to get Rocket League working with x360ce for a couple days now, and x360ce only works with Rocket League when using 32 bit Xinput 1.4. The problem is that whenever the xinput dll exists, Rocket League crashes about 10-30 seconds after startup. Debugging the crash gives this:

Unhandled exception at 0x0BF50FE0 in RocketLeague.exe: 0xC0000005: Access violation executing location 0x0BF50FE0.

**Comment by Squall-Leonhart** [comment]
remove your gamepads FFB driver.

**Comment by NothingNinja** [comment]
I'm having this exact same issue, but my FFB driver is disabled and rocket league is still crashing for me. I'm using a third party PS3 wired controller. I know it's been a long time since this response but if you could help me out that would be great.

**Comment by Squall-Leonhart** [comment]
Try the beta at
https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md

**Comment by NothingNinja** [comment]
Thank you so much! everything works perfectly except one issue- the y axis on both sticks is inverted even if i try to change the axis and even if i record it. I also tried checking the invert axis box on the left stick and right stick tabs and that didn't work.
