### ISSUE TITLE
Exception!

### ISSUE THREAD

**Issue by zqmbies** [x360ce/x360ce#669]
System.io.filenotfoundexception c\windows\system32\etc.
at system diagnostics
at x360ce.engine data/appsettings / app controls/appmain/app program
![gitgit](https://user-images.githubusercontent.com/31602267/30012365-3465474c-910d-11e7-8caa-c24d40e7a987.png)

**Comment by zqmbies** [comment]
I'm sorry I am a total noob at all things technology I just want to play Resident Evil 5 with a ps2 controller & was told x360ce was the best way to do that but I cant even open x360ce after dwnloding...

**Comment by thenewadeel** [comment]
maybe you need xinput  dll files

**Comment by Squall-Leonhart** [comment]
a supported dotnet or its directx dependencies are not present
