### ISSUE TITLE
Frame dropping and lag in Rise Of The Tomb Raider.

### ISSUE THREAD

**Issue by SecretButton** [x360ce/x360ce#674]
So I had terrible frame dropping and lag in the game and what fixed it was checking the "Force Feedback Pass Through" option in the advanced tab, hope this helps someone, cheers.

"...Same was happening to me with raise of the romb raider, I got a 40 frame dropping from 60 to 20, so I started messing up with the settings in the interface and I solved at least for me it worked, So in your controller go to the Advanced tab next to the Axis to button and check the option: "Force Feedback Pass Through"(One - Gamepad), that should work, good luck. Xbox360ce V 3.2.8.77"

**Comment by Squall-Leonhart** [comment]
not a bug report

**Comment by CaCTuCaTu4ECKuu** [comment]
You should really mention this somewhere in "Help"
