### ISSUE TITLE
Saitek X-56 Joystick axis mapping to tiny guy nothing on main stick

### ISSUE THREAD

**Issue by Volkion** [x360ce/x360ce#677]
Saitek x-56 has two small digital controllers one on stick one on throttle, Would be cool to try if my initial plan falls through. That is using my Saitek x-56 (right hand) and logitech extreme 3d pro (left hand) and play skyrim. I play Elite dangerous dual stick and it is quite tactile. so I want to see how skyrim plays. How do I get it to detect those Axis though? The Tab that shows the inputs doesnt seem to notice primary stick movement at all.

**Comment by Squall-Leonhart** [comment]
not a valid bug report.
