### ISSUE TITLE
NBA 2K18 Twin USB Joystick help!!!

### ISSUE THREAD

**Issue by pera405** [x360ce/x360ce#678]
So I have a weird problem... X360ce works normal in first couple minutes of gameplay, and then suddenly one controler works as two (player one is controlling p1 and p2 at same time) that is happening a couple a minutes, and then switches back and then again. So I used this with many games, never encounted problem since now.. So i am so pissed i need help.. Please someone HEEEEEEEEELP!

**Comment by madking21** [comment]
facing the same problem here. have u fixed it yet?

**Comment by ltotsas** [comment]
It seems that everybody that use x360ce has issues with nba2k18!

**Comment by pera405** [comment]
So I searched internet for a bit.. Found 100+ threats on multiple forums regarding this issue with Twin usb and 2k18. Issue is not happening when one player is playing with keyboard and other one on twin usb, other from that u can play two player game with one gamepad... Waiting for some help still....

**Comment by ghost** [comment]
I am also facing the same problem. Tried all the hook modes but still no luck :(

**Comment by pera405** [comment]
Nothing works so far... tried it all! Still waiting for some help from dev team.. HELP

**Comment by ghost** [comment]
I found a fix but it is without the use of x360ce. Here is what solved the problem :
http://steamcommunity.com/app/577800/discussions/0/3223871682624711323/

**Comment by ltotsas** [comment]
I confirm. But if one of the controllers disconnect then when you are gonna reconnect it only one controller works.

**Comment by madking21** [comment]
hahaha i am actually the madking21 haaha 

    On Sunday, October 8, 2017 4:48 PM, sinxvii <notifications@github.com> wrote:
 

 I found a fix but it is without the use of x360ce. Here is what solved the problem :
http://steamcommunity.com/app/577800/discussions/0/3223871682624711323/—

**Comment by Squall-Leonhart** [comment]
duplicate of old issue with known workarounds.

**Comment by reiinakano** [comment]
@Squall-Leonhart could you link to the issue with the workarounds? Sorry, I've been searching and couldn't find it.
