### ISSUE TITLE
GTA

### ISSUE THREAD

**Issue by sebbiedoo** [x360ce/x360ce#679]
I have a steering wheel and pedals. I've connected them to the xbox 360 buttons and everything on the app and it all matches up. When I launch GTA with steam I get into a car and it doesnt work. I downloaded the 64 bit and 34 bit and they both dont work...

**Comment by Squall-Leonhart** [comment]
game specific configuration support is on the ngemu forums, closing.

**Comment by Okom1** [comment]
http://nodo.freeforums.net/thread/12065/steering-wheel-working-online-fivem
