### ISSUE TITLE
Double input in Cuphead

### ISSUE THREAD

**Issue by Petar89** [x360ce/x360ce#680]
I have one generic usb controller that i emulate with x360ce in all of my games,but i keep getting double input in Cuphead no matter what i do,it reads my gamepad as two controllers. I would really appreciate the help,it's an awesome game,it needs xbox360 gamepad control scheme to work properly. Hookmask doesn't seem to work...

**Comment by aqumus** [comment]
Even I am getting similar issue where if I press any key from gamepad controller , second player spawns in :(

**Comment by dahrojasca** [comment]
I have the same problem

**Comment by Petar89** [comment]
It's been solved,and trust me,I tried everything,but this actually worked,i'll post a youtube link of the solution

**Comment by Petar89** [comment]
Basically u open cuphead(windowed),then open x360ce,go to options,remove controller,then when u select asign controller,u switch to x360ce and press a buton on gamepad there.It will switch to the control scheme in game that u want.Important thing is that the game remains as a background window,and x360ce as main. It's much clearer in the video this guy made :D

**Comment by Petar89** [comment]
https://www.youtube.com/watch?v=I5OIAo3DjHY

Finally,we can enjoy this wonderfull game,but i would like for admins or programmers to check this out and tell us what is causing this. That video shows the solution,but there has to be another way around it as well.

**Comment by scorninpc** [comment]
Just clear second controller config, dont map any button. Its worked with my Red Dragon

**Comment by arijan108** [comment]
You can try this: https://www.youtube.com/watch?v=CL25dCp_Lh8
It worked for me. Probably someone already posted the fix, but I found this to work for me without going into the mapping settings.

**Comment by YuGiOhJCJ** [comment]
When Cuphead is in windowed mode in background, it is automatically paused, it is stuck on the same frame, so I can't reproduce this temporary fix. And it is just a workaround as you have to do these steps each time you launch the game. Please re-open.
