### ISSUE TITLE
x360ce.exe opens and closes again and again... (infinite loop)

### ISSUE THREAD

**Issue by JuU2** [x360ce/x360ce#681]
After installation of X360ce (for 64-bit-games) I copy&paste the .exe into the gamefolder of "The witcher 3", where the game.exe is located ( C > programs (x86) > The Witcher 3 > bin > 64).  Then I start X360ce.exe - and it opens and closes it again and again and again.... (until I end the process manually via task-manager). 

Does anyone have a solution for this?

**Comment by Squall-Leonhart** [comment]
This happens when the application is run from a protected location without elevation.
