### ISSUE TITLE
Wine issue

### ISSUE THREAD

**Issue by Rosalie241** [x360ce/x360ce#682]
Hello, so I have a steam controller and I'm using the ![sc-controller](https://github.com/kozec/sc-controller) driver, it emulates a xbox360 controller and wine detects this, x360ce too: ![alt tag](https://i.imgur.com/xrDoGX7.png)
![alt tag](https://i.imgur.com/JdJsEF3.png)
However, when I configure my controller, save the config, close x360ce and open it again it gives me an error:
![alt tag](https://i.imgur.com/ZPDhEt7.png)
and ![Cuphead](http://www.cupheadgame.com/) doesn't see the controller:
![alt tag](https://i.imgur.com/U4Z0kry.jpg)
I have no idea what's causing that .ini issue, I don't even touch the file before/after restart, I tried ```chmod 777 *.ini``` in the game directory where the ini file is located, but the error is the same.
This is the log when I configure and save the config: ![wine_x360ce.log](https://gist.github.com/anonymous/72516885ae2dd86966f50a6ca9212239)
and here's the log when it tries to load the config but fails: ![wine_x360ce2.log](https://gist.github.com/anonymous/871cc275c72884988269f308f14d155a)
I'm using a 64-bit wineprefix with dotnet45(```winetricks dotnet45```)
I'm running a custom version of wine with this patch: ![cuphead.patch](https://github.com/tim241/cuphead_wine_instructions/blob/master/cuphead.patch) to make Cuphead work.
I'm using the 32-bit version of x360ce.

**Comment by Squall-Leonhart** [comment]
steam controller emulates xinput by itself, do not use x360ce.
