### ISSUE TITLE
x360ce not applying any changes i make

### ISSUE THREAD

**Issue by haho7o** [x360ce/x360ce#685]
Hello i am using logitech racing wheel and im trying to play need for speed rivals. i downloaded the x360 and placed it in the installation folder of nfs and started it but all controlls were messed up(most were unbound and all were working not properly for examle steerinthe wheel was just moving the camera). i went back and adjusted the controls as they are in the game. clocked save and started the game again. nothing changed. opened x360 again and i saw that all my setting were saved but none applied. can you help me set it up?

**Comment by Squall-Leonhart** [comment]
the issues list is for bugs in the application, not game support.
