### ISSUE TITLE
x360ce detects Mayflash Gamecube adapter, but doesn't respond to input

### ISSUE THREAD

**Issue by JohnRillos** [x360ce/x360ce#686]
I have a Mayflash Gamecube to Wii U controller adapter.  I'm currently trying to use it for Rocket League (although the problem seems to be with x360ce rather than the game).  When I open x360ce, it correctly identifies that I'm using the Mayflash adapter, and detects 4 controllers (despite the fact that only 1 is plugged in, but that may be inevitable).  

Anyway, there are default items assigned to the controls, but I can't reassign them by hitting "record" and have no evidence that the program is detecting any of my button presses for any controller slot.  There is also no response in-game when I load up Rocket League.

How is the program detecting that I have this controller, but not responding to button inputs?

**Comment by Squall-Leonhart** [comment]
adapters such as these simulate the devices connectivity for hot plugging of controllers connected to them.

the issue is likely because of this fact, so disable the connected hid devices relevant to the unplugged ports.

**Comment by ALEEF02** [comment]
Can you better explain how to fix this? @Squall-Leonhart I'm having the _exact_ same problem as @JohnRillos
