### ISSUE TITLE
middle earth shodow of war

### ISSUE THREAD

**Issue by ehsan14756** [x360ce/x360ce#691]
not working on midlle earth shodow of war

**Comment by LodanZark** [comment]
Seems you haven't read the repository description: https://github.com/x360ce/x360ce#reporting-issues

**Comment by ehsan14756** [comment]
is that mean im not able playing with x360ce?

2017-11-02 1:52 GMT+03:30 LodanZark <notifications@github.com>:

**Comment by LodanZark** [comment]
Shadow of War has Denuvo DRM, and that means it is incompatible with x360ce, maybe someday the game will remove the DRM which I hightly doubt, you can check the games list that has denuvo right here: https://en.wikipedia.org/wiki/Denuvo#List_of_Denuvo_games
