### ISSUE TITLE
Nioh complete edition

### ISSUE THREAD

**Issue by JustaP69** [x360ce/x360ce#695]
I downloaded the game and tried to use xbox360ce. the game recognized it, but It also ran in slow motion. When I remove xbox360ce files, everything works perfectly.

**Comment by herasimenia** [comment]
Me too...

**Comment by nosmokingbandit** [comment]
I can't get it to run at all. The game crashes before the title screen.

**Comment by Squall-Leonhart** [comment]
not compatible currently.
