### ISSUE TITLE
Left thumb stick movement is really slow

### ISSUE THREAD

**Issue by ericthings** [x360ce/x360ce#705]
Trying to use with Doom and Just Cause 3. I noticed that the walking movement is really slow using the default left thumb stick. What setting do I need to change to fix this? I'm using with a nintendo switch pro controller also.

**Comment by Squall-Leonhart** [comment]
the issue tracker is not to game related issues.

x360ce is undergoing a rewrite into a virtual driver, so issues with the current wrapper/emulator will be mass closed.
