### ISSUE TITLE
Gamepad problems with Hitman Season 1

### ISSUE THREAD

**Issue by Victor-82** [x360ce/x360ce#707]
I have a problem with my gamepad in the game Hitman season 1. In the game you can't change the buttons. My gamepad has the same buttons than a xbox controller, so I download the x360ce. The program detects my gamepad, and it seems to detect the game without a problem. The buttons are correct in there, but when I start the game, i have the same problems, the buttons are changed. I try to modify this on the x360ce, but when I start the game the buttons remains the same as when I don't have the x360ce.

Is there any chance to modify the buttons on this game? I think I did everything correctly. It's hard to play having the point and shoot buttons on the sticks...

**Comment by Squall-Leonhart** [comment]
uses directinput, not xinput.

**Comment by Victor-82** [comment]
I've just disable the option "enable xinput" but still don't work. What I have to do?

**Comment by Victor-82** [comment]
I have the solution if you have the same problem. You have to put the x360ce in the Retail folder and launch the game from this folder (hitman.exe). The problem was that I put the x360ce in the main folder of the game and start de Launcher.exe and it doesn't work.
