### ISSUE TITLE
Controller detects wrong Buttons. Please Help!

### ISSUE THREAD

**Issue by RindiRasso** [x360ce/x360ce#713]
Hello,

I use a PS2 Controller with a Mayflash  MF001 Universal Adapter combined with the x360ce. Almost every Game works fine, but in some Games the Buttons are switched or wrong detected. Example (XBOX360 Controller Buttons) A is B, B is Y, RT is RB and so on. This happens most in Games were you cant do any Button Configuration. I tried to switch between 32bit and 64bit, reinstalled the Game, Updated 360ce and all does not work.

360ce detects the Button all in the right places and works fine, but when it come to the Game it switches the Buttons.

I would like to Fix this Issue but I don´t know were to start or to do.

Please can u help me???

**Comment by Squall-Leonhart** [comment]
your game is not even usin the xinput library.

closed.

**Comment by RindiRasso** [comment]
What does that mean? Please explain

**Comment by RindiRasso** [comment]
Can u at least explain or give me Tips to fix the Buttons? Great Closed right away with no help at all. Not able to Help. What a Joke
