### ISSUE TITLE
Steam + x360ce + uplay game

### ISSUE THREAD

**Issue by Buranich** [x360ce/x360ce#718]
Hello!

Some days ago i downloaded, installed and configured x360ce, all working fine except one thing.

This thing mean the next situation:
1) I'm launch steam
2) Turn off steam controller support (because this is totally trash)
3) The next step is launching the game called For Honor (has own uplay platform)
4) When all is launched and loaded, the hooking game process from x360ce can't help the game to recognize controller because steam by some "magic" hold his support effect on game process.
5) If I run the game directly by forhonor.exe, game start uplay launcher without steam supporting and all works fine.
---
The question:
How i must run game from steam to do so that x360ce was able to intercept game directly with bypassing steam controller support?

**Comment by Squall-Leonhart** [comment]
none of ubisofts titles that utilise vmprotect are compatible with hook/injection.
