### ISSUE TITLE
 Win32_DiskDrive SerialNumber read failed

### ISSUE THREAD

**Issue by gitti88** [x360ce/x360ce#73]
Hi, i've a big problem:

System.Exception: BoardInfo Win32_DiskDrive SerialNumber read failed: Classe non valida 
   in x360ce.Engine.BoardInfo.GetDiskDriveID()
   in x360ce.Engine.BoardInfo.GetDiskDriveIdGuid()
   in x360ce.Engine.Data.Game.FromDisk(String fileName)
   in x360ce.App.SettingsFile.Load()
   in x360ce.App.Controls.GameSettingsUserControl.InitDefaultList()
   in x360ce.App.Controls.GameSettingsUserControl..ctor()
   in x360ce.App.MainForm.InitializeComponent()
   in x360ce.App.MainForm..ctor()
   in x360ce.App.Program.Main(String[] args)

The program worked since i've try to make my pc faster disistalling stuff and using game boster with advance setting. i tried to restore everything but nothing.

i've win7 sp1 64 bit. IThe strange thing is that the last downloadeble version of x360ce doesn't work, the other (x360ce.App-2.1.2.191) starts but not work with gta v.

**Comment by Squall-Leonhart** [comment]
what version did you download that experienced this error,  I don't care what version is the last to work, it doesn't tell us anything.

**Comment by gitti88** [comment]
all the .exe in your main page. 3.0.2.19 show that error and not start. But it worked for days withou problems. 
x360ce.App-2.1.2.191 starts show me the controller working (botton pushing is sincronized) but in the game joypad not work.

**Comment by Nucleoprotein** [comment]
Current version is 3.0.2.25. Try it.

**Comment by gitti88** [comment]
System.Exception: BoardInfo Win32_DiskDrive SerialNumber read failed: Classe non valida 
   in x360ce.Engine.BoardInfo.GetDiskDriveID()
   in x360ce.Engine.BoardInfo.GetDiskDriveIdGuid()
   in x360ce.Engine.Data.Game.FromDisk(String fileName)
   in x360ce.App.SettingsFile.Load()
   in x360ce.App.Controls.GameSettingsUserControl.InitDefaultList()
   in x360ce.App.Controls.GameSettingsUserControl..ctor()
   in x360ce.App.MainForm.InitializeComponent()
   in x360ce.App.MainForm..ctor()
   in x360ce.App.Program.Main(String[] args)

it give me this

**Comment by Squall-Leonhart** [comment]
The WMI Host service of your OS is either disabled or Corrupt.

**Comment by gitti88** [comment]
ok that could be the issue. then, how can i fix it?

**Comment by Squall-Leonhart** [comment]
enable Windows Management Instrumentation: should be an Automatic Start service type.

If it cannot be started, run the WMI Diagnostic tool.

**Comment by gitti88** [comment]
it seems to not work :(

**Comment by Squall-Leonhart** [comment]
Did you restart after re-enabling it?

**Comment by EJocys** [comment]
I will try to workaround this by adding alternative way to generate number which links games to the user (so configuration can be backed on-line) if first method fails.

**Comment by Nucleoprotein** [comment]
Maybe use LAN Adapter MAC or user SID?

**Comment by gitti88** [comment]
not work also after rebooting. wait for ejocys 's fix

**Comment by gitti88** [comment]
nothing yet? sorry for double post :P

**Comment by EJocys** [comment]
Please download and try new version: 3.0.3.31 (2015-05-10)

**Comment by gitti88** [comment]
ok, it works! now i've to try if joypad will work in the game. You are my hero, the best, thank you for the fix!

**Comment by EJocys** [comment]
Fixed
