### ISSUE TITLE
Stick Fight: The Game, pad detected 2 times

### ISSUE THREAD

**Issue by Aethyrion** [x360ce/x360ce#731]
The game detects both my original DirectInput USB controller and the x360 emulated one at the same time. I'd like to block the original inputs.

I have already tried all of the Hook Masks and renaming xinput1_3.dll into xinput9_1_0.dll with no success.

Any idea ?

**Comment by Squall-Leonhart** [comment]
http://www.unity3dgames.eu/stick-fight.html

Read the faqs.
Can't do anything on this engine presently.

**Comment by LuixAS** [comment]
This is for any future brave adventurer. The solution is to hide the original controllers using hidhide. Good luck out here.
