### ISSUE TITLE
Force feedback not works with "Esperanza EG102" gamepad.

### ISSUE THREAD

**Issue by Karaulov** [x360ce/x360ce#732]
Force feedback not works with "Esperanza EG102" gamepad.

Vid 0079
Pid 0006

How to edit x360ce.ini for support force feedback(vibration)?

**Comment by seuvah** [comment]
bad driver. uninstall driver and install this http://razier.com/wp-content/uploads/2013/07/Win7x64GamepadDriverAVF.zip. And it should work  i have same gamepad. =)

**Comment by Karaulov** [comment]
Driver works but vibration not works :(

**Comment by Karaulov** [comment]
![hmwsjvy 1](https://user-images.githubusercontent.com/6445336/36409523-0a78ef0c-161d-11e8-9eae-6bd37a05baa7.png)

**Comment by seuvah** [comment]
Have You Enabled ff . Post force feedback tab. Also if you have steam client running , there is issue with vibration.

**Comment by seuvah** [comment]
Try this config =)

[x360ce Esperanza 32bit.zip](https://github.com/x360ce/x360ce/files/1739219/x360ce.Esperanza.32bit.zip)

**Comment by Karaulov** [comment]
Not works in x360ce, and in gamepad settings not works.

**Comment by seuvah** [comment]
Drivers are correct.  I have same gamepad. Im out of ideas sorry =(

**Comment by Karaulov** [comment]
Windows 10 x64 russian

**Comment by seuvah** [comment]
(Параметры-Устройства-Принтеры и Сканеры-Устройства и принтеры(внизу или справа нажать) там вибери джойстик Настройка контролера) - там есть графа вибрации ?

**Comment by seuvah** [comment]
Понятно попробуй фикс вибрации для виндовс 10 вот он зскачай и запусти от имени администратора и проверь вибрацию опять 

[win-8-10-usb-gamepad-vibration-fix.zip](https://github.com/x360ce/x360ce/files/1739993/win-8-10-usb-gamepad-vibration-fix.zip)

**Comment by Karaulov** [comment]
спасибо за помощь, но никакого эффекта, я попробую потом что-нибудь еще сам посмотрю

**x360ce can't bypass bad driver and directly use vibration ?**

**Comment by Karaulov** [comment]
Драйвер был плохой, нужно качать с офф сайта ))))

http://esperanza.pl/szczegolyTresci.php?kid=19&id=70&kat=0&lan=4&cur=2

http://esperanza.pl/upload/EG102.zip

Теперь вибрация работает!

**Comment by seuvah** [comment]
У меня виндовс 7 64бит, толькочто проверил на вин10 дествительно драйвер непашет. Поставил на вин10 этот  все работает .
[SPEEDLINK STRIKE SL-6535-SBK-01.zip](https://github.com/x360ce/x360ce/files/1740147/SPEEDLINK.STRIKE.SL-6535-SBK-01.zip)
