### ISSUE TITLE
x360ce in Windows 10 games like Minecraft: Windows 10 Edition?

### ISSUE THREAD

**Issue by s5bug** [x360ce/x360ce#745]
It's (nearly) impossible to edit the permissions for Windows game folders correctly, is there some way to get controllers working there without being able to write the DLLs necessary for xinput "hacking"?

**Comment by Squall-Leonhart** [comment]
we do not support anything you are trying to do.

we will have a VMProtect / UWP compatible version of x360ce available in short time.

**Comment by s5bug** [comment]
What does WMProtect / UWP mean? 🤔

**Comment by Nucleoprotein** [comment]
VMProtect is code protector used also in Denuvo protected games as first layer of protection.
UWP is Universal Windows Platform - ie. anything "modern" from Windows Store like "Minecraft: Windows 10 Edition"

**Comment by Logerfo** [comment]
just to be sure, vmprotect support is not out yet, right? i'm currently unable to make x360ce work with the crew 2 closed beta
