### ISSUE TITLE
no ini file

### ISSUE THREAD

**Issue by Gauthamraju31** [x360ce/x360ce#747]
even after running the x360ce.exe file there is no ini file created. please help

**Comment by Trollgaard-Sr** [comment]
Version 4.7.0.29 Build 2018-06-16
Win10 x64
Controller: Microsoft Sidewinder FFB 2
Game: Arma 3
Mission: Trying to use x360ce to give better Force Feedback as Arma 3 has weak support.

Force feedback works when testing, but stops working when closing x360ce.
First FFB test after deleting settings in %programdata% and setting up controller again works, but then it stops working again.

No ini-file gets created in game folder. No dll files gets created

**Comment by EJocys** [comment]
Important: x360ce.exe version 4 works differently from old version 3. Version 4 creates "Virtual Xbox 360 Controller" inside your Windows operating system when running. Version 4 is no longer use INI or DLL files inside the game folder. This allows for x360ce.exe to support more modern games. You must minimise (not close) x360ce.exe version 4 during the game to make sure that it can constantly update "Virtual Xbox 360 Controller".

@Trollgaard-Sr there is a bug in version 4.7 with Force Feedback. FF needs to be re-enabled to work. I will try to fix it in 4.8.x.x.
