### ISSUE TITLE
Problem build x360ce 

### ISSUE THREAD

**Issue by Karaulov** [x360ce/x360ce#755]
I got many errors while x360ce build. 

Exit command "copy #######" with error, etc. Some files missing, etc....

How to build x360ce in release mode with 2017 visual studio?

**Comment by Karaulov** [comment]
Result: x360ce crashes. (I was manual copy files to resource dir, since they appeared in the wrong folders!)

[x360ce.zip](https://github.com/x360ce/x360ce/files/1821942/x360ce.zip)

**Comment by Karaulov** [comment]
Build log (RU) : https://pastebin.com/M26TXHtg

**Comment by Karaulov** [comment]
In debug mode, can be compiled, but Release not works.

And i got error if run in Debugger : 

**---------------------------

---------------------------
'PadSetting' class property names must match 'SettingName' class property names. Please make sure that these properties exists in 'SettingName' class:



AxisToDPadDeadZone, AxisToDPadEnabled, AxisToDPadOffset, ButtonA, ButtonB, ButtonBack, ButtonGuide, ButtonStart, ButtonX, ButtonY, DPad, DPadDown, DPadLeft, DPadRight, DPadUp, ForceEnable, ForceOverall, ForceSwapMotor, ForceType, GamePadType, LeftMotorPeriod, LeftShoulder, LeftThumbAntiDeadZoneX, LeftThumbAntiDeadZoneY, LeftThumbAxisX, LeftThumbAxisY, LeftThumbButton, LeftThumbDeadZoneX, LeftThumbDeadZoneY, LeftThumbDown, LeftThumbLeft, LeftThumbRight, LeftThumbUp, LeftTrigger, LeftTriggerDeadZone, PassThrough, RightMotorPeriod, RightShoulder, RightThumbAntiDeadZoneX, RightThumbAntiDeadZoneY, RightThumbAxisX, RightThumbAxisY, RightThumbButton, RightThumbDeadZoneX, RightThumbDeadZoneY, RightThumbDown, RightThumbLeft, RightThumbRight, RightThumbUp, RightTrigger, RightTriggerDeadZone, LeftThumbLinearX, LeftThumbLinearY, RightThumbLinearX, RightThumbLinearY, LeftMotorStrength, RightMotorStrength, LeftMotorDirection, RightMotorDirection, ButtonADeadZone, ButtonBDeadZone, ButtonBackDeadZone, ButtonStartDeadZone, ButtonXDeadZone, ButtonYDeadZone, LeftThumbButtonDeadZone, RightThumbButtonDeadZone, LeftShoulderDeadZone, RightShoulderDeadZone, DPadDownDeadZone, DPadLeftDeadZone, DPadRightDeadZone, DPadUpDeadZone, LeftTriggerAntiDeadZone, LeftTriggerLinear, RightTriggerAntiDeadZone, RightTriggerLinear
---------------------------
ОК   
---------------------------**

**Comment by blabbouze** [comment]
I didn't manage to compile with Visual Studio 2013 and 2017, but I had no issues with 2015 (both in Debug/Release mode).

You need to compile the targets in that order : 

- MinHook library
- x360ce
- x360ce.Engine
- x360.App (stable) or x360.App.Beta (last version)

**Comment by EJocys** [comment]
Updated instructions for Visual Studio 2017 https://github.com/x360ce/x360ce/blob/master/Wiki/HowTo.md

    C++ projects are using "Visual C++ Build Tools v14.0".
    This means that you have to include this feature on "Visual Studio 2017 Installer":
    
        Desktop development with C++
            [x] VC++ 2015.3 v140 toolset for desktop (x86,x64)
