### ISSUE TITLE
( 4.2.0.2 Alpha) Axis Y (Left and Right sticks) always inverted.

### ISSUE THREAD

**Issue by KiNGKiMO** [x360ce/x360ce#762]
Hello,

I tried X360CE 4.2.0.2 Alpha today, Left and Right sticks have Y axis inverted all the time, No matter which axis I select, even the record button gives the same result.

Thanks for the great effort.

**Comment by NothingNinja** [comment]
I'm having the same issue, and I noticed something; when i use the record function it detects Haxis6 for the right stick y axis, which isn't an option to select.

**Comment by TrainedNoob** [comment]
Exactly even I cant access Inverted Axis6 any fix will be helpful

**Comment by EJocys** [comment]
Thanks for reporting. Going to fix it in next release.

**Comment by KiNGKiMO** [comment]
Thanks EJocys, 
It's fixed by https://github.com/x360ce/x360ce/commit/dd74e7e79469d1747803d1caf1576936613f9c38 I suppose?

We hope for a new alpha soon.

**Comment by EJocys** [comment]
@KiNGKiMO: Yes, I am planning to release new alpha this week.

**Comment by EJocys** [comment]
Fixed in  v4.3.0.0 Alpha. Download is available here:
https://github.com/x360ce/x360ce/releases
