### ISSUE TITLE
Double Input in Assault Android Cactus.  HookCOM had no effect

### ISSUE THREAD

**Issue by fragmental** [x360ce/x360ce#767]
I have a Logitech RumblePad 2.  My controller is detected by Assault Android Cactus, but the rumble/vibration doesn't work.  In an attempt to get rumble vibration to work, I tried x360ce.  While, rumble/vibration did work with x360ce, it resulted in double input(or ghosted input).  One controller acting as two. 

I tried using 
`[InputHook]
HookMode=1
HookCOM=1`
to my x360ce.ini

and adding:
```
[cactus.exe]
Name=cactus.exe
HookMask=0x00000002
```
to my 360ce.gdb file in
c:\users\All Users\x360ce

but it didn't seem to make any difference.

**Comment by Squall-Leonhart** [comment]
https://unity3d.com/showcase/case-stories/assault-android-cactus

**Comment by fragmental** [comment]
@Squall-Leonhart What does that article have to do with this issue?  And why did you close the issue?

**Comment by Squall-Leonhart** [comment]
https://github.com/x360ce/x360ce/blame/master/Wiki/CompatibilityList.md#L282
