### ISSUE TITLE
Can't get it to work on GTA V

### ISSUE THREAD

**Issue by mohahm1978** [x360ce/x360ce#77]
I have 3 controllers
1- G-27 Racing wheel
2- Metal strike 3D 
3- Dual vibration usb joystick

All three are detected in the program and setup is OK!
When in-game nothing works
tried disconnecting them one-by-one.repeat the steps,put in-game directory,same result.
please help

**Comment by Ayoub13Berrahel** [comment]
I play GTA V and it worked for me you just have to keep the software open when you play

**Comment by Squall-Leonhart** [comment]
" just have to keep the software open when you play"

no you don't, the software is only a configurator for the ini, once configured everything is handled internally by the DLL generated.

mohahm, 
you need the 64bit xinput1_3,  you can add gta5 to the games list and synchronise the 64bit dll from this tab.

**Comment by mohahm1978** [comment]
Squall-Leonhart 
could you explain what to do step-by-step please

**Comment by Squall-Leonhart** [comment]
Switch to 'Game Settings'
On the 'My Game Settings' sub tab, Add the GTA5.exe
Select this newly added game
Look for Xinput Files on the right side ofthe screen.
Unselect 32bit v1.3 and select 64bit v1.3
Press Synchronise

**Comment by mohahm1978** [comment]
Squall-Leonhart
Can't find the Synchronise button :)

**Comment by EJocys** [comment]
If you don't see it then configuration is is synchronized already.

**Comment by mohahm1978** [comment]
![1](https://cloud.githubusercontent.com/assets/12304146/7556038/8e1a770c-f769-11e4-803f-28f08b5e665a.jpg)

any missing files?

Also,here's my x360ce.ini
[Options]
UseInitBeep=1
Log=0
Console=0
DebugMode=0
InternetDatabaseUrl=http://www.x360ce.com/webservices/x360ce.asmx
InternetFeatures=1
InternetAutoload=1
AllowOnlyOneCopy=1
ProgramScanLocations=C:\Program Files,C:\Program Files (x86)
Version=1
CombineEnabled=0

[InputHook]
HookMode=1

[Mappings]
PAD1=IG_900a9bc0973611e48001444553540000
PAD2=IG_dab76d10967d11e48001444553540000
PAD3=IG_b5d9f8f0968711e48002444553540000
PAD4=IG_b63ba0f0968711e48003444553540000

[PAD1]
[PAD2]
[PAD3]
[PAD4]

[IG_900a9bc0973611e48001444553540000]
ProductName=Logitech G27 Racing Wheel USB
ProductGuid=c29b046d-0000-0000-0000-504944564944
InstanceGuid=900a9bc0-9736-11e4-8001-444553540000
AxisToDPadDeadZone=256
AxisToDPad=0
AxisToDPadOffset=0
A=1
B=3
GuideButton=
Back=9
Start=10
X=2
Y=4
D-pad POV=1
D-pad Down=DOWN
D-pad Left=LEFT
D-pad Right=RIGHT
D-pad Up=UP
UseForceFeedback=0
ForcePercent=100
SwapMotor=0
FFBType=0
ControllerType=1
LeftMotorPeriod=60
LeftMotorStrength=100
LeftMotorDirection=0
Left Shoulder=6
Left Analog X AntiDeadZone=0
Left Analog Y AntiDeadZone=0
Left Analog X Linear=0
Left Analog Y Linear=0
Left Analog X=1
Left Analog Y=
Left Thumb=20
Left Analog X DeadZone=0
Left Analog Y DeadZone=0
Left Analog Y- Button=0
Left Analog X- Button=0
Left Analog X+ Button=0
Left Analog Y+ Button=0
Left Trigger=a-6
Left Trigger DeadZone=0
PassThrough=0
RightMotorPeriod=120
RightMotorStrength=100
RightMotorDirection=0
Right Shoulder=5
Right Analog X AntiDeadZone=0
Right Analog Y AntiDeadZone=0
Right Analog X Linear=0
Right Analog Y Linear=0
Right Analog X=
Right Analog Y=
Right Thumb=15
Right Analog X DeadZone=0
Right Analog Y DeadZone=0
Right Analog Y- Button=16
Right Analog X- Button=17
Right Analog X+ Button=18
Right Analog Y+ Button=19
Right Trigger=a-2
Right Trigger DeadZone=0
ForcesPassThrough=0
PassThroughIndex=0
Combined=0
CombinedIndex=0
[IG_dab76d10967d11e48001444553540000]
ProductName=MetalStrik 3D
ProductGuid=b0110583-0000-0000-0000-504944564944
InstanceGuid=dab76d10-967d-11e4-8001-444553540000
AxisToDPadDeadZone=256
AxisToDPad=0
AxisToDPadOffset=0
A=1
B=
GuideButton=
Back=
Start=
X=2
Y=3
D-pad POV=
D-pad Down=x2
D-pad Left=x-1
D-pad Right=x1
D-pad Up=x-2
UseForceFeedback=0
ForcePercent=0
SwapMotor=0
FFBType=0
ControllerType=0
LeftMotorPeriod=0
LeftMotorStrength=100
LeftMotorDirection=0
Left Shoulder=x-6
Left Analog X AntiDeadZone=0
Left Analog Y AntiDeadZone=0
Left Analog X Linear=0
Left Analog Y Linear=0
Left Analog X=
Left Analog Y=
Left Thumb=0
Left Analog X DeadZone=0
Left Analog Y DeadZone=0
Left Analog Y- Button=0
Left Analog X- Button=0
Left Analog X+ Button=0
Left Analog Y+ Button=0
Left Trigger=
Left Trigger DeadZone=0
PassThrough=0
RightMotorPeriod=0
RightMotorStrength=100
RightMotorDirection=0
Right Shoulder=x6
Right Analog X AntiDeadZone=0
Right Analog Y AntiDeadZone=0
Right Analog X Linear=0
Right Analog Y Linear=0
Right Analog X=
Right Analog Y=
Right Thumb=0
Right Analog X DeadZone=0
Right Analog Y DeadZone=0
Right Analog Y- Button=0
Right Analog X- Button=0
Right Analog X+ Button=0
Right Analog Y+ Button=0
Right Trigger=
Right Trigger DeadZone=0
ForcesPassThrough=0
PassThroughIndex=0
Combined=0
CombinedIndex=0
[IG_b5d9f8f0968711e48002444553540000]
ProductName=Dual USB Vibration Joystick
ProductGuid=e00212bd-0000-0000-0000-504944564944
InstanceGuid=b5d9f8f0-9687-11e4-8002-444553540000
AxisToDPadDeadZone=256
AxisToDPad=0
AxisToDPadOffset=0
A=3
B=2
GuideButton=
Back=9
Start=12
X=4
Y=1
D-pad POV=1
D-pad Down=DOWN
D-pad Left=LEFT
D-pad Right=RIGHT
D-pad Up=UP
UseForceFeedback=0
ForcePercent=0
SwapMotor=0
FFBType=0
ControllerType=0
LeftMotorPeriod=0
LeftMotorStrength=100
LeftMotorDirection=0
Left Shoulder=7
Left Analog X AntiDeadZone=0
Left Analog Y AntiDeadZone=0
Left Analog X Linear=0
Left Analog Y Linear=0
Left Analog X=1
Left Analog Y=-2
Left Thumb=10
Left Analog X DeadZone=0
Left Analog Y DeadZone=0
Left Analog Y- Button=0
Left Analog X- Button=0
Left Analog X+ Button=0
Left Analog Y+ Button=0
Left Trigger=5
Left Trigger DeadZone=0
PassThrough=0
RightMotorPeriod=0
RightMotorStrength=100
RightMotorDirection=0
Right Shoulder=8
Right Analog X AntiDeadZone=0
Right Analog Y AntiDeadZone=0
Right Analog X Linear=0
Right Analog Y Linear=0
Right Analog X=6
Right Analog Y=-3
Right Thumb=11
Right Analog X DeadZone=0
Right Analog Y DeadZone=0
Right Analog Y- Button=0
Right Analog X- Button=0
Right Analog X+ Button=0
Right Analog Y+ Button=0
Right Trigger=6
Right Trigger DeadZone=0
ForcesPassThrough=0
PassThroughIndex=0
Combined=0
CombinedIndex=0
[IG_b63ba0f0968711e48003444553540000]
ProductName=Dual USB Vibration Joystick
ProductGuid=e00212bd-0000-0000-0000-504944564944
InstanceGuid=b63ba0f0-9687-11e4-8003-444553540000
AxisToDPadDeadZone=256
AxisToDPad=0
AxisToDPadOffset=0
A=3
B=2
GuideButton=
Back=9
Start=12
X=4
Y=1
D-pad POV=1
D-pad Down=DOWN
D-pad Left=LEFT
D-pad Right=RIGHT
D-pad Up=UP
UseForceFeedback=0
ForcePercent=0
SwapMotor=0
FFBType=0
ControllerType=0
LeftMotorPeriod=0
LeftMotorStrength=100
LeftMotorDirection=0
Left Shoulder=7
Left Analog X AntiDeadZone=0
Left Analog Y AntiDeadZone=0
Left Analog X Linear=0
Left Analog Y Linear=0
Left Analog X=1
Left Analog Y=-2
Left Thumb=10
Left Analog X DeadZone=0
Left Analog Y DeadZone=0
Left Analog Y- Button=0
Left Analog X- Button=0
Left Analog X+ Button=0
Left Analog Y+ Button=0
Left Trigger=5
Left Trigger DeadZone=0
PassThrough=0
RightMotorPeriod=0
RightMotorStrength=100
RightMotorDirection=0
Right Shoulder=8
Right Analog X AntiDeadZone=0
Right Analog Y AntiDeadZone=0
Right Analog X Linear=0
Right Analog Y Linear=0
Right Analog X=6
Right Analog Y=-3
Right Thumb=11
Right Analog X DeadZone=0
Right Analog Y DeadZone=0
Right Analog Y- Button=0
Right Analog X- Button=0
Right Analog X+ Button=0
Right Analog Y+ Button=0
Right Trigger=6
Right Trigger DeadZone=0
ForcesPassThrough=0
PassThroughIndex=0
Combined=0
CombinedIndex=0

![2](https://cloud.githubusercontent.com/assets/12304146/7556074/f66df26a-f76a-11e4-8964-faf9f1323c76.JPG)
![3](https://cloud.githubusercontent.com/assets/12304146/7556076/0b856ca0-f76b-11e4-84e0-4ad45def4e0f.JPG)

**Comment by Squall-Leonhart** [comment]
press winkey+r
enter 'joy.cpl'
on the Advanced screen, make sure that the wheel is set as the preferred device.

**Comment by jbienz** [comment]
I notice in the config file above that CombineEnabled is set to 0 and all controllers have Combined set to 0. This means controller combining is disabled and controllers 2 - x will not work in GTA V. Having said that, this doesn't explain why controller 1 isn't working. It should work just fine.

**Comment by mohahm1978** [comment]
Solved !!!!
I was the dump here !!!!
I tried re-bind the keys with the wheel,the point is it's actually working with no key remapping.
still working on the steering deadzone
Sorry guys for confusing you :)
