### ISSUE TITLE
System.Runtime.InteropServices.SEHException (0x80004005)

### ISSUE THREAD

**Issue by HeyItsIlic** [x360ce/x360ce#771]
I installed FIFA 18 and wanted to enable right analog stick. I downloaded x360ce for 64-bit games and then this appeared:
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
at SharpDX.DirectInput.DirectInput..ctor()
at x360ce.App.MainForm..ctor()
at x360ce.App.Program.Main(String[] args)

Help please!

**Comment by Squall-Leonhart** [comment]
access violation, you're missing required dependencies.

**Comment by kishorekumar2110** [comment]
Please can u tell me how you signed this problem?.I have this problem too.

**Comment by kishorekumar2110** [comment]
Just remove the bcrypt.dll file from the folder and try. It worked for me.

**Comment by DedSecMF** [comment]
It worked Thankss
