### ISSUE TITLE
Impossible to map buttons in the new alpha 4.2.0 

### ISSUE THREAD

**Issue by KikkeRivera** [x360ce/x360ce#772]
I try to map the buttons of an xbox control (S Controller) in alpha 4.2.0 on Windows 10, but it is impossible even though the drivers are correctly installed.

The version 3.2.8.77 (2015-10-04) and the 2.0.2.160 Beta 2 perfectly recognize each button and allow me to perform the mapping.

**Comment by Squall-Leonhart** [comment]
You have to click add to add mappings.

**Comment by EJocys** [comment]
"[x] Auto Map" feature, which is not implemented yet, will be default option in the future, to make sure that configuration is easier and less confusing.
