### ISSUE TITLE
Beta Testing: X360CE 4.3.0.0 Alpha

### ISSUE THREAD

**Issue by EJocys** [x360ce/x360ce#775]
This issue is for reporting bugs found in Beta Testing: X360CE 4.3.0.0 Alpha
4.3.0.0 Alpha is intended to test Virtual Emulation. Download links and instructions can be found here:
https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md

**Comment by danduuuin** [comment]
I found an bug, the Y-Axis and the buttons are still inverted (like in the previous Alpha version). But still, everything works fine.

**Comment by EJocys** [comment]
@danduuuin I've updated link on BetaTesting.md, which was pointing to 4.2.0.2. Please check your version of Application (redownload if necessary) and make sure that Y-Axis "Axis 2" have inverted setting mapped: "IAxis 2"

**Comment by danduuuin** [comment]
I redownloaded the Application and I changed the Y-Axis from "Axis 2" to "IAxis 2", but then the Y-Axis didn't work, I had to change it back to "Axis 2".

**Comment by EJocys** [comment]
@danduuuin Strange. I've retested 4.3.0.0 Alpha on 3 different controllers, "XBox One", "SpeedLink XEOX Pro", "Logitech F710" and axis map works as intended (normal and inverted mode). Make sure that application title contains "... 4.3.0 Alpha (Build: 218-04-07) 32-bit".

**Comment by danduuuin** [comment]
![image](https://user-images.githubusercontent.com/38164248/38458761-2686ece0-3aa2-11e8-8931-920bc549ea6b.png)

I'm sure, that I've downloaded the right version.

**Comment by danduuuin** [comment]
I've tested this version on the "Gioteck VX-2 Wired" controller.

**Comment by EJocys** [comment]
Interesting that "IAxis 2" mapping do not work. Do you have same issue with right stick (usually "IAxis 5" or "IAxis 6" is mapped to thumb-Y).

Can you open [Left Stick] tab and check "Y - Vertical Axis" group box. Above the image you will see "DI" and "XI" values. If everyhing is all right (IAxis 2 mapped), then DI value will go from 0 (left thumb is up) to 65535 (left thumb is down), and XI value will go from 32767 (left thumb is up) to -32768 (left thumb is down). Try to move left thumb and see if both values are changing and if values are correct when left thumb is all way up or all way down.

**Comment by EJocys** [comment]
I see that image displays correct DInput to XInput conversion (red line), but blue dot (which displays active status of converted value, moves in wrong direction). I will check later if it is related with the issue you are having.

**Comment by danduuuin** [comment]
The DI values go from 0 (left thumb up) to 65535 (left thumb down). But when I set the Y-Axis to "IAxis 2", the XI values stay at -1. When I set the Y-Axis to "Axis 2", the XI values are inverted.

**Comment by EJocys** [comment]
@danduuuin Thanks. Probably value coversion fails somwhere, but at the moment I have no idea where. Could you:
a) open c:\ProgramData\X360CE\Errors folder
b) wipe all error files (*.htm) from it
c) map "IAxis 2" to Left Stick Axis Y
d) refresh that folder and see if there are new error files *.htm
e) if new files are generated (probably not with "SharpDXException" or "ViGEmException" in the name) then maybe it will tell us where program fails. Could you open one with te browser and paste lines which starts with " at" from it.

If application will not generate error file then I am out of ideas at the moment. Maybe I will find it in the process of developing or somebody else reports some extra details. Ok, enough deveoping for today. Time to kill some monsters :).

P.S.: That thing with the image is not related to your issue. I just fixed it (will be included in next release).

**Comment by danduuuin** [comment]
I deleted all the error files, I mapped "IAxis 2" to the Left Stick Y-Axis and the only files, that were generated, are "SharpDXException" and "ViGEmException".

**Comment by EJocys** [comment]
@danduuuin Thank you. Could you check if deadzone on axis is not set to 100% by the chance (which interestingly produces "bug" with similar symptom).

If not then, it means that I have to find the issue later. I have to update conversion so that inverted axis will produce 0 as centered XInput value instead of -1.

**Comment by danduuuin** [comment]
The deadzone is set to 0%.

![image](https://user-images.githubusercontent.com/38164248/38459591-d1a0abd0-3aab-11e8-88a3-5e7d65db0393.png)

**Comment by EJocys** [comment]
@danduuuin Thank you again for your help. I will post new ideas or solution if it comes to my mind later.

**Comment by danduuuin** [comment]
No problem. Also, thanks for trying to help me :)

**Comment by danduuuin** [comment]
I've found one more bug with the buttons. I know it sounds a little bit complicated. The buttons are inverted. For example the Y button is the X button and vice versa. That same happens for the A & B button. When I map the Y button to my Y button (it's the "Button 1" for me), then it works as the Y & X button. I have the same problem with the other buttons (A, B, X, Y).

**Comment by Squall-Leonhart** [comment]
Something is iffy with the vibration test sliders, move it to 1% and you get full vibration which gets slower as you approach 50%, then you can barely hear the motors at 51%, and then it ramps back up approaching 100%

**Comment by EJocys** [comment]
@Squall-Leonhart: Some motors have weird effects untill you set direction right. In current implementation  both FF axis directions must be set to "Positive" in order for motors to work properly/separate. I think, I will split Force feedback into different implementations (you will be able to choose with drowpdown like before), because some controllers support some specific, but weird settings only.

**Comment by EJocys** [comment]
@danduuuin: does your controller have [Mode] button? Some controllers swap PoV with Axis, Axis with Buttons, or remap other layout. You can open [Direct Input], and see which controller [Mode] does what.

Also, You can close app, and reset all settings by deleting all *.XML files from "c:\ProgramData\X360CE" folder. This will ensure that there no Virtual devices or some other configuration issues messing up mappings.

**Comment by KiNGKiMO** [comment]
@EJocys Thank you for the update, IAXIS works just fine now.

Here are my test results so far:

1-
HID Guardian Install button does nothing (x360ce executed as admin though), is this normal?
Shall I install HID Guardian myself to test or it's not supported yet?

2-
After uninstalling ViGEM Bus, Issues tab circle is still gray, If you click the issues tab you see the install solution still... I remeber the issues tab circle used to be indicating, right?

**Comment by blabdouze** [comment]
It seems that sometimes when you close x360ce (after it runs for a few hours), it will not remove the virtual device from the Game controller list, registering him again when you reopen it : 

![sans titre](https://user-images.githubusercontent.com/15141805/38469190-f0915120-3b50-11e8-9b9f-ccf5cf5d3aa8.png) 

This prevent your controller from being used in game (but it all works fine in x360ce). You need to restart your computer to make it work again. 

I've added a screen when the virtual device works perfectly (only one _Controller (XBOX 360 for Windows)_) : 
![image](https://user-images.githubusercontent.com/15141805/38469207-37c60284-3b51-11e8-9236-730f5e97fa02.png)

**Comment by danduuuin** [comment]
@EJocys I deleted all of the .xml files, now the buttons and the Y-Axis work without any problems. Thank you! 👍 😄

**Comment by mickael28** [comment]
@EJocys , the Force Feedback in my Fanatec CSR keeps on just pushing the wheel to the left, I've not feel it pushing to the right. Is that normal? or do I need to configure anything?

And, is there any option in the software to configure a spring to the center in the wheel? It feels really soft and without any kind of resistance without it...

**Comment by KiNGKiMO** [comment]
@EJocys 
Any new alphas in the way?

Thanks.

**Comment by EJocys** [comment]
@KiNGKiMO: Yes, probably this weekend.

**Comment by KiNGKiMO** [comment]
@EJocys 
Well, was just about to report 4.4.0.0 ALPHA Issues, but you already fixed them 😄 
Looks like we'll be needing a new alpha if you please 😁

**Comment by EJocys** [comment]
@KiNGKiMO Re-released 4.4.0.2 alpha today (2018-04-24). It can be downloaded from:
https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md

**Comment by EJocys** [comment]
Re-released 4.4.0.3 alpha. Fixed bug where it would not update HidGuardian registry in some cases. It can be downloaded from:
https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md

**Comment by KiNGKiMO** [comment]
(4.4.0.3 alpha, and probably older releases)

If you leave x360ce running long enough (1 Hour or so), the interface hangs (Cannot select tabs, cannot click anything, cannot even move x360ce window. Also if you right click the taskbar icon you cannot select from Open/Exit).

The virtual gamepads are working in games/joy.cpl while x360ce interface is frozen.

**Comment by EJocys** [comment]
@KiNGKiMO: Thanks for reporting. I will try to run in debug mode for more than 1 hour 
 tomorrow.

**Comment by KiNGKiMO** [comment]
I Uninstalled HIDGuardian (looks like it doesn't work correctly with my Logitech dual action controllers). So, even though HIDGuardian is not installed, ViGEm.HidGuardianHelper still trying to access registry. I deleted HidGuardian key from regedit and now x360ce isnt working, creating "FCE_NullReferenceException.htm" files at Errors folder.


![untitled](https://user-images.githubusercontent.com/11393200/39244623-7ace5958-4891-11e8-85b0-5bb757b1ca3c.jpg)

**Comment by KiNGKiMO** [comment]
Update:
I played for over two hours with no interface freeze, and that's after I uninstalled HID Guardian.

**Comment by EJocys** [comment]
@KiNGKiMO Thank you for reporting. Fixed crash when x360ce to access non existing HidGuardian registry and crash when device information was refreshed during DInput device list update. I will re-relase new x360ce App later today.

**Comment by EJocys** [comment]
Re-released 4.4.0.5 alpha.
Fixed crash when x360ce to access non existing HidGuardian registry and crash when device information was refreshed during DInput device list update. Updated some other things.
It can be downloaded from:
https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md

**Comment by KiNGKiMO** [comment]
@EJocys Thank you so much for fixes and release.

My 1st run notice, at devices tab/map device to controller window you still have "Hide" checkbox enabled, also "HID Guardian" drop menu.. I think they should be enabled only if/when HID Guardian is installed.

**Comment by Squall-Leonhart** [comment]
virtual control still non functional on windows 7.

its funny coz VGX does work lol

**Comment by Nucleoprotein** [comment]
@Squall-Leonhart 
We can wait 2 years in alpha and then un-support Windows 7 like MS 😉 

PS: MS basic support for Windows 7 ended January 13, 2015 ...

**Comment by Squall-Leonhart** [comment]
Can't select POV under the D-PAD drop down

and the d-pad <direction> menu's just try to set POV-1

also for some reason Library can't work unless Virtual has first.

**Comment by EJocys** [comment]
@Squall-Leonhart Yeah, sorry for that. Took old laptop from the storage, blew away the dust and started to install Windows 7 32-bit. Win7 32-bit and 64-bit test environment probably will be ready in 2 hours.

@Nucleoprotein I like your idea. :)

**Comment by KiNGKiMO** [comment]
@EJocys 
After some HID Guardian beta tests with Nefarius, here's what's needed to be done:

1- HID Guardian doesn't and can't hide devices by instance path, so only device HWID should be added to AffectedDevices reg value.

2- As of HID Guardian V3, only HidCerberus can whitlelist processes (I haven't checked the source code yet), so x360ce needs to add itself to whitelisted processes the same way HidCerberus does.

**Comment by EJocys** [comment]
@KiNGKiMO:

1. x360ce application use HID DeviceID to hidde device. HidGuardian enumerates devices and writes IDs into registry. I double checked and HID DeviceIDs used by x360ce are the same as "Hardware ID"s enumerated by HidGuardian. IDs differ in capital and lower cases, which are automatically fixed by x360ce app.

2. x360ce application adds its own Process ID to white list into registry when starts.
https://github.com/x360ce/x360ce/blob/master/x360ce.App.Beta/ViGEm/HidGuardianHelper.cs
AddCurrentProcessToWhiteList() 

I had to look at source code of HidGuardian myself, because documentation is unclear at the moment. Terminology is very mixed. There is a DevicePath, HID DeviceID, HardwareID and HardwareIDs and it is very unclear which one is actually used. So, I've used value which mached one enumerated by HidGuardian itself.

I could not make HidGuardian to work reliably. Probably, for HidGuardian "hide/show" list to take effect,  x360ce application must remove and re-add hardware device programtically.

P.S. At the moment, I am trying to resolve the issue where virtual emulation hangs Windows 7 when new device is connected :).

**Comment by Squall-Leonhart** [comment]
> P.S. At the moment, I am trying to resolve the issue where virtual emulation hangs Windows 7 when new device is connected :).

You can't fix this in x360ce, it occurs because VIGEM expects presence of a function only available when xusb21 is on the system, which requires the Xbox360 software for windows | https://www.microsoft.com/accessories/en-au/d/xbox-360-controller-for-windows

SCP driver had the same requirement.

**Comment by EJocys** [comment]
@Squall-Leonhart Thanks for pointing this out. I probably forgot it if you mentioned that before. Proper fix would be for ViGEm to check its own requirements. I will add fix/workaround on x360ce app, which will be to check if "Xbox 360 Controller for Windows" software is installed. Initialization of ViGEm will be prevented until user follows advice and resolves the issue.

**Comment by Squall-Leonhart** [comment]
I probably didn't mention it at all, but the VIGEM framework did mention it back before they shuffled around the git pages.

**Comment by KiNGKiMO** [comment]
@EJocys 
1-
Here's an example:
![logitech01](https://user-images.githubusercontent.com/11393200/39483020-56bd8f18-4d71-11e8-9468-b3cec78dc62e.png)
x360ce will add these values to AffectedDevices:
`HID\VID_046D&PID_C216\6&33a2c19e&0&0000
HID\VID_046D&PID_C216\6&6d32fa8&0&0000
`
These wont make my controllers hidden, HID Guardian doesn't hide devices by instances.

`HID\VID_046D&PID_C216`
Adding this will make the two contollers hidden... and That's what x360ce should add to AffectedDevices.

2- x360ce adds its own Process ID to white list into registry ONLY if the Whitelist key is created, so you've to create a key named Whitelist under Parameters first for it to work.... The thing is, starting from V3 Hid Guardian doesn't even care about the  Whitelist key or what's in it.... So x360ce doesnt support HID Guardian V3 and needs to add itself to V3 whiletlist in a very different way, it's not in the registry anymore.

I Hope I got myself clear this time.

**Comment by Nucleoprotein** [comment]
If HID Guardian not use device instances then is veeery broken...

**Comment by EJocys** [comment]
@KiNGKiMO thanks for info. I wrote email to HidGuardian dev for more clarification and asked for HID Device ID support so that devices could be hidden individually.

**Comment by EJocys** [comment]
@Squall-Leonhart Finished testing on Windows 7 32-bit and 64-bit OS. Virtual Emulation works as expected now. I will try to adjust x360ce to work with HidCerberus and HidGuardian v3. Developer responded and said that new design allows to use Device ID, so all looking good. I will release new x360ce application after fixing issues with HidGuardian/HidCerberus.

**Comment by EJocys** [comment]
I've started new "Beta Testing: X360CE 4.5.0.0 Alpha" issue:
[#783 Beta Testing: X360CE 4.5.0.0 Alpha](https://github.com/x360ce/x360ce/issues/783)

Extra checks and bug fixes must bring more stability, especially for Windows 7 users.

I reverted HidGuardian to old version. New HidGuardian version looks over-complicated and have too many third party libraries, like use of 3 different configuration formats XML, JSON and YAML in projects, when native XML is superior and covers everything possible. I need to wait for HidGuardian 3.x documentation to make sure that I can create small and clean C# API client without any third party libraries.

@KiNGKiMO I am using short "HID\VID_046D&PID_C216" format for AffectedDevices now, but it fails to work in my tests. I think, that rational thing to do would be to wait for stable release and API document. I can focus on bringing back old INI (DLL library) emulation support to X360CE 4.x.

I will close this issue now. If I forgot something on this issue then please copy/paste it on the new issue page.
