### ISSUE TITLE
FIFA 18 Windows 10 error

### ISSUE THREAD

**Issue by KrKoNi** [x360ce/x360ce#778]
![1](https://user-images.githubusercontent.com/38403018/38780205-ab625e24-40db-11e8-9cd6-765f862dfcb6.png)
When I start x360ce in FIFA folder, appears this error (WIN 10).
In other games x360ce works good.

If I start x360ce with compatibility mode Win 8/7? x360ce works good, but there are no changes in FIFA. If I create xinput1_4.dll, FIFA see 2 gamepads in one (one button press on the gamepad = two button press in FIFA). How to solve this problem?

**Comment by Nucleoprotein** [comment]
1. We don't support piracy - I see that game is cracked.
2. We don't support Denuvo protected games.
