### ISSUE TITLE
Beta Testing: X360CE 4.5.0.0 Alpha

### ISSUE THREAD

**Issue by EJocys** [x360ce/x360ce#783]
This issue is for reporting bugs found in Beta Testing: X360CE 4.5.0.0 Alpha. Release contains stability fixes and better support for Windows 7.

Alpha is intended to test Virtual Emulation. Download links and instructions can be found here:
https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md

**Comment by Squall-Leonhart** [comment]
I'm getting a blank area where the controller mapping screen should be, that disapears if i click to ignore an incorrectly occuring message asking for the xbox 360 accessory package to be installed.

**Comment by Squall-Leonhart** [comment]
![image](https://user-images.githubusercontent.com/1098176/39551285-c27f4732-4ea7-11e8-8f80-551cea755d91.png)

**Comment by Squall-Leonhart** [comment]
lol, still not getting movement on the emulated xbox controller.

**Comment by Squall-Leonhart** [comment]
Ok, the issue with x360ce not getting input on the emulated controller seems to be some sort of compatibility issue with XBCD driver,  which doesn't occur with VDX.

**Comment by Squall-Leonhart** [comment]
My controller is the VID_1BAD&PID_F023
![image](https://user-images.githubusercontent.com/1098176/39551829-fb237a48-4ea9-11e8-8e27-9bdfb9bc582b.png)

**Comment by EJocys** [comment]
@Squall-Leonhart So, X360CE says that you don't have XBOX Drivers & Software installed?
I think we must try to resolve the issue with installer. Could you try to uninstall "Microsoft Xbox 360 Accessories" and install again. I would like for X360CE issue go "OK" on its own and without ignoring issue. Maybe installer "repair" option will be enough. Also, close X360CE, backup content of "c:\ProgramData\X360CE" for later review if needed, and wipe this folder (in case something wrong with the mapping). Make sure there are no XInput*.dll files inside same folder as X360ce.exe. X360CE must say "Microsoft" in the corner:
![image](https://user-images.githubusercontent.com/11958537/39552587-c2640aa8-4e61-11e8-8237-4ffdad5cbc80.png)

**Comment by Squall-Leonhart** [comment]
clean reinstall has done nothing for the accessories for windows thing.

swapping back to the microsoft driver makes the emulated device work when created, but it won't with the XBCD driver.

**Comment by EJocys** [comment]
I assume that controls move when button "[ ] Get XInput State" is unchecked?
![image](https://user-images.githubusercontent.com/11958537/39552769-914247f4-4e62-11e8-86a5-b56341e0a8de.png)
It must show mapping results without asking results from XInput*.DLL

I need to figure out where communication breaks i.e. when settings are sent to virtual device or when settings are retrieved via xinput3_1.dll.

**Comment by EJocys** [comment]
Also, can you see any error files inside c:\ProgramData\X360CE\Errors, where file date is after launch of x360ce.exe

**Comment by EJocys** [comment]
Ok. Enough work for today. See you tomorrow :).

**Comment by Squall-Leonhart** [comment]
It's also asking for the 360 controller software on windows 8.1, which no such software exists.

**Comment by Squall-Leonhart** [comment]
Product
--
Name: | Jocys.com X360 Controller Emulator 4.5.0.0 (TEST)
Machine: | 
Username: | 
Executable: | D:\Projects\XBCD\XBCD Installer\x360ce\x360ce.exe
Build Date: | 2018-05-03 07:40:25
 
Exception
--
Exception Date: | 2018-05-03 09:07:19
Target.Type: | SharpDX.Result
Target.Name: | CheckError

-----------------------
SharpDXException: HRESULT: [0x80004001], Module: [General], ApiCode: [E_NOTIMPL/Not implemented], Message: Not implemented
-----------------------

SharpDX.SharpDXException: HRESULT: [0x80004001], Module: [General], ApiCode: [E_NOTIMPL/Not implemented], Message: Not implemented

   at SharpDX.Result.CheckError()

**Comment by EJocys** [comment]
@Squall-Leonhart Thanks. I will try to add more information into exception so we will know which part is failing (device acquiring, getting info about device, getting status info or setting force feedback). I will re-upload new x360ce.exe when ready.

Could you check if there is a larger error file with similar time, but with the code line of exception?

**Comment by EJocys** [comment]
@Squall-Leonhart About Windows 8.x.
https://support.xbox.com/en-GB/xbox-on-windows/accessories/xbox-controller-for-windows-setup

Microsoft claims that "_Drivers for Windows 8.1 and Windows 8 are installed by default. Simply plug your controller into a USB port and the driver will self-install._"

Most people don't have X360 controler to trigger drivers install. So, question is are drivers actually installed? 

Also, Microsoft says: "If you’re having trouble with the drivers, you can install the controller software on a Windows 8.1 or Windows 8 PC by using Windows 7 compatibility mode."

I can disable check for X360 controller drivers or add this instruction to Windows 8 users.

If you’re having trouble with the X360 controller drivers, you can install the controller software on a Windows 8.x PC by using Windows 7 compatibility mode. Download Windows 7 program that matches the processor on your computer (32-bit or 64-bit). In the downloads location on your PC, right-click the downloaded program and select Properties. On the Compatibility tab, select the Run this program in compatibility mode for checkbox, and then select Windows 7 from the dropdown list. Select Apply, and then select OK. Double-click the program to run it. The Xbox 360 Accessories Setup program installs the necessary files on the computer. You might be prompted to restart when finished.

**Comment by EJocys** [comment]
@Squall-Leonhart I've uploaded new version (4.5.0.4) with extra logging for you to try. There will be more info in one of the exception files, about where it failed:
https://www.x360ce.com/Files/Beta/x360ce.zip

**Comment by Squall-Leonhart** [comment]
my MLG pad installs the xusb21 driver that is included in 8 just fine, then i overrode it wit hthe xbcd driver.

VDX works, but X360CE doesn't.

that file is failing to start downloading, i just see a 0b file

**Comment by EJocys** [comment]
@Squall-Leonhart Could you wipe c:\ProgramData\X360CE\Errors and run https://www.x360ce.com/Files/Beta/x360ce.zip, so that new error file (one of the larger *.htm), generated inside c:\ProgramData\X360CE\Errors, gives us exact line where x360ce application fails.

**Comment by Squall-Leonhart** [comment]
It didn't create a different error.

**Comment by Squall-Leonhart** [comment]
Product
--
Name: | Jocys.com X360 Controller Emulator 4.5.0.4 (TEST)
Machine: | 
Username: | 
Executable: | D:\Projects\XBCD\XBCD Installer\x360ce\x360ce.exe
Build Date: | 2018-05-04 03:48:43


Exception
--
Exception Date: | 2018-05-04 20:47:20
Target.Type: | SharpDX.Result
Target.Name: | CheckError

----------------------------
SharpDXException: HRESULT: [0x80004001], Module: [General], ApiCode: [E_NOTIMPL/Not implemented], Message: Not implemented
----------------------------

SharpDX.SharpDXException: HRESULT: [0x80004001], Module: [General], ApiCode: [E_NOTIMPL/Not implemented], Message: Not implemented

   at SharpDX.Result.CheckError()

**Comment by EJocys** [comment]
@Squall-Leonhart Thanks. I will try to figure out the issue with logging the error and reupload the app.

**Comment by EJocys** [comment]
@Squall-Leonhart
Switched debug information setting from "Embedded" to "Full". Please:
a) Download https://www.x360ce.com/Files/Beta/x360ce_debug.zip file (version 4.6.0.0). 
b) Extract all files (x360ce.exe, x360ce.pdb, x360ce.Engine.dll, x360ce.Engine.pdb)
c) Delete all  files inside c:\ProgramData\X360CE\Errors
d) Run extracted x360ce.exe, and look for new error file (*.htm), generated inside c:\ProgramData\X360CE\Errors
e) Post error file content here.
We should see exact line number of the exception.

**Comment by Squall-Leonhart** [comment]
Nada, same error.

nothing new,   could this be linked to why i could never get the Record function to work?

![image](https://user-images.githubusercontent.com/1098176/40005619-bf4e901c-57db-11e8-9252-4960951b1920.png)

**Comment by EJocys** [comment]
@Squall-Leonhart Yes, because it looks like it fails to acquire state of Direct Input device. And you are sure that x360ce.pdb file is in the same folder as x360ce.exe? I try to figure out other way to get error code line and reupload updated exe.

**Comment by Squall-Leonhart** [comment]
Yes it is, there might be something missing in the apps dinput that is present in the dll

i wonder why that would be when the device is picked up everywhere else, including the library method.

**Comment by EJocys** [comment]
@Squall-Leonhart 
Another re-upload, with custom exception writing.
a) Download https://www.x360ce.com/Files/Beta/x360ce_debug.zip file (version 4.6.0.1).
b) Extract all files (x360ce.exe, x360ce.pdb, x360ce.Engine.dll, x360ce.Engine.pdb)
c) Delete all files inside c:\ProgramData\X360CE\Errors
d) Run extracted x360ce.exe, and look for * *DInputException* *.htm error file, generated inside c:\ProgramData\X360CE\Errors
e) Post error file content here.
If same happens when maybe I am looking at wrong place :).

**Comment by Squall-Leonhart** [comment]
ok, without the library, got a new file

[FCE_DInputException_20180516_043937.569084.zip](https://github.com/x360ce/x360ce/files/2006267/FCE_DInputException_20180516_043937.569084.zip)

**Comment by EJocys** [comment]
@Squall-Leonhart Excellent. Now we know that application is failing when trying to set force feedback effect on left motor. I guess that removing check from "[ ] Enable Force Feedback" checkbox on [Force Feedback] tab will allow Virtual Device to run OK. I will update code so it will be possible to retrieve more information about FF capabilities available on your device.

**Comment by Squall-Leonhart** [comment]
The errors stopped being logged, but the device isn't picking up any movement still, nor is recording working.

**Comment by Squall-Leonhart** [comment]
didn't we have a tool that prints device capabilities to a txt file at one point?

**Comment by Squall-Leonhart** [comment]
// Offset  Type           Aspect       Flags                                   Instance  Name                   
// ------  -------------  -----------  --------------------------------------  --------  -----------------------
//     20  ZAxis          33024        AbsoluteAxis                                   2  Z Axis                 
//     16  RxAxis         33024        AbsoluteAxis                                   3  X Rotation             
//     12  RyAxis         33024        AbsoluteAxis                                   4  Y Rotation             
//      8  RzAxis         33024        AbsoluteAxis                                   5  Z Rotation             
//     32  PovController  33024        PointOfViewController                          0  Hat Switch             
//      0  Unknown                     Collection, NoData                             0  Collection 0 - Game Pad
//      0  Unknown                     Collection, NoData                             1  Collection 1           
//      0  Unknown                     Collection, NoData                             2  Collection 2           
//      0  Unknown                     Collection, NoData                             3  Collection 3           
//      0  Unknown                     Collection, NoData                             4  Collection 4           
//     28  XAxis          33025        AbsoluteAxis, ForceFeedbackActuator            0  X                      
//     24  YAxis          33025        AbsoluteAxis, ForceFeedbackActuator            1  Y                      
//     52  Button         32770        PushButton, ForceFeedbackEffectTrigger         0  1                      
//     53  Button         32770        PushButton, ForceFeedbackEffectTrigger         1  2                      
//     54  Button         32770        PushButton, ForceFeedbackEffectTrigger         2  3                      
//     55  Button         32770        PushButton, ForceFeedbackEffectTrigger         3  4                      
//     56  Button         32770        PushButton, ForceFeedbackEffectTrigger         4  5                      
//     57  Button         32770        PushButton, ForceFeedbackEffectTrigger         5  6                      
//     58  Button         32770        PushButton, ForceFeedbackEffectTrigger         6  7                      
//     59  Button         32770        PushButton, ForceFeedbackEffectTrigger         7  8                      
//     60  Button         32770        PushButton, ForceFeedbackEffectTrigger         8  9                      
//     61  Button         32770        PushButton, ForceFeedbackEffectTrigger         9  10                     
//     48  Unknown        -2147450880  NoData, Output                                22  Unknown 22             


Constant | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters, StartDelay | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters

Ramp | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters, StartDelay | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters

Square Wave | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters, StartDelay | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters

Sine Wave | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters, StartDelay | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters

Triangle Wave | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters, StartDelay | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters

Saw Tooth Up Wave | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters, StartDelay | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters

Saw Tooth Down Wave | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters, StartDelay | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters

Spring | Duration, Gain, Axes, Direction, TypeSpecificParameters, StartDelay | Duration, Gain, Axes, Direction, TypeSpecificParameters

Damper | Duration, Gain, Axes, Direction, TypeSpecificParameters, StartDelay | Duration, Gain, Axes, Direction, TypeSpecificParameters

Inertia | Duration, Gain, Axes, Direction, TypeSpecificParameters, StartDelay | Duration, Gain, Axes, Direction, TypeSpecificParameters

Friction | Duration, Gain, Axes, Direction, TypeSpecificParameters, StartDelay | Duration, Gain, Axes, Direction, TypeSpecificParameters

Custom | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters, StartDelay | Duration, Gain, TriggerButton, Axes, Direction, Envelope, TypeSpecificParameters

**Comment by EJocys** [comment]
@Squall-Leonhart Could you press [Test...] button (Top Right)

![image](https://user-images.githubusercontent.com/11958537/40080640-80444d6e-5883-11e8-99ba-29430575c4c4.png)

 and make sure that all check boxes are unchecked (maybe test is enabled and query of state or processing is disabled)

![image](https://user-images.githubusercontent.com/11958537/40080493-01e15106-5883-11e8-8605-eb86709e446f.png)

**Comment by EJocys** [comment]
@Squall-Leonhart Is it correct that there are no new errors (*htm files) created even if you restart the x360ce.exe application?

**Comment by Squall-Leonhart** [comment]
those aren't set, i did play with the ui a  bunch trying to get it to see input.

at this point im thinking sharpdx is missing some fringe device type that my driver sets.

no new errors occur with Vibration off, but still doesn't see any input.

**Comment by KiNGKiMO** [comment]
Hello @EJocys 
How does x360ce detect HID Guardian version, it says (HidGuardian Virtual Device 1.14.0.0), but this is not correct... the installed version is 1.5.2.0... Same goes for ViGEm Bus.

We're waiting a new alpha as well ;)

Thanks.

Edit:
1- HID Guardian 1.5.2.0 is not working, please use the latest V1 (1.14.0.0)
2- Whitelist key should be created by x360ce if it's not already created.

**Comment by EJocys** [comment]
Created new issue https://github.com/x360ce/x360ce/issues/795

@KiNGKiMO 
Updated HID Guardian to 1.14. Tested hiding/un-hiding devices and it worked.
