### ISSUE TITLE
Inputs issues for Sidewinder Force Feedback 2 with x360ce_x64.exe

### ISSUE THREAD

**Issue by bobi32** [x360ce/x360ce#79]
Hello,

I’m trying to make my good old flight joystick (a Microsoft Sidewinder Force Feedback 2) work for aerial controls in GTAV (therefore I use the last — well the one downloadable from the README.MD file, ie 3.0.2.25 — 64 bits version of x360ce app).

I can configure and use almost all of the controls except for two of them, with two similar issues BUT slightly different behavior for each issue:
1. on one hand, I’m trying to set the twist rudder control of the flight joystick to left and right bumpers (which correspond to ingame rudder control): the rudder itself is recognized at a Z-axis with R value variating from 0 to 65535 with a rest value of 32767; by recording inputs it sets inverted half axis 6 for left bumper and half axis for right bumper, but then neither the green led-like indicator doesn’t lights when I use the twist in x360ce, nore the input is recognized ingame;
2. on the other hand, I want to use the POV hat of the flight jeystick as the right stick of the emulated X360 controller (as it is used ingame to control point of view, it seems both logical and convenient to me); as the POV hat is recognized as the DirectInput DPad, when recording inputs it sets Stick Up to DPad Up, and so on; despite I’ve set other buttons of the stick to XInput DPad (6 for up, 7 for left, 5 for right and 8 for down), and these are recognized, once configured the right stick doesn’t react in x360ce when using the POV hat, and the POV hat is also unusable ingame.
The main difference with rudder control is that, when I quit and relaunch x360ce_x64.exe, configuration for bumpers remains whereas right stick directions configuration empties itself…

FYI, I setted right axes configuration to empty, and they remain empty, as I’m trying to use DPad directions to configure it, not axes. I have however set right stick button to button 3, and this configuration remains on relaunch of the App.

I’ll make myselft clear by stating that all of the configuration I setted, except for the aforementionned ones, work flawlessly in both x360ce_x64 and GTAV (only this inputs won’t work).

Another thing I noticed (I don’t know if it’s a problem) is x360ce_x64 remains in active processes even after I closed the app. However, whether I kill it (to _really_ close the app) or not doesn’t impact at all the behavior I described here.

One last thing: I’ve configured the app to be launched as administrator so that it has write access in GTAV folder to manage the lib and conf file. The app therefore shows itself as elevated.

**Comment by Squall-Leonhart** [comment]
Rudder's and pedal's require special case support, its already been mentioned we need to look into implementing this, preferably per device and not as a global toggle.

**Comment by bobi32** [comment]
I’m a bit confused by your answer: shouldn’t you focus on fine mappings between DirectInput and XInput, based on a few concepts (buttons, axes, dpad, etc) as they are shown in windows gamepad manager? Thus through direct editing of the config file you could propose fine configuration regardless of the physical device itself, in default of a graphical tool which could hardly cover all possibilities.

Considering you’re already able, in x360ce interface, to bring a tab which lists all metrics bound to the device inputs (as I said, I saw the twist left & right of my stick has a direct and coherent effect on Z-axis R field) and your record function can detect this inputs, I definitely think this kind of fine in-notepad configuration is not so hard to provide, regardless of the device concerned.

To synthetize: if not the case, I strongly suggest you should focus on the raw data, not the devices.

As a second point, you didn’t answer for the POV hat that I can’t use for the right stick, I can’t think I’m the only one wanting this kind of usage, and maybe I’m just misusing the app for this one.

PS: as I realize I’m not necessarily clear myself, I’ll just add that my stick doesn’t have a specific rudder or pedal device, just an additional axis-type input as I can make the stick slightly turn over its own axis, to a few degrees to the left or the right; the original goal was to give a rudder control without a specific device, with what I consider even a more natural use (as with this stick you can yaw on your aircraft just as you roll and pitch: with similar movements on the stick).

**Comment by Squall-Leonhart** [comment]
You misunderstand.
https://msdn.microsoft.com/en-us/library/windows/hardware/ff543445%28v=vs.85%29.aspx

Rudders and Pedals are literally, 'special case support'.

Making them work, will make other things not work.

DIGITAL buttons cannot currently be used for either of the sticks (directly), its not something i think anyone ever really considered as being necessary, but we do have an axis to dpad setting  that we needs to be fixed, which we could expand to  cover either stick.

**Comment by EJocys** [comment]
New release (x360ce 3.0.3.32, 2015-05-11) have full support of Axis to D-Pad Button and Normal Button mapping. Please try it and see which problems remains. I will try to look into controller combining issues next, because I would like to use Wheel for cars and Joystick for plains in GTA V.

**Comment by bobi32** [comment]
Hi EJocys,
Yesterday I already tested the previous version (3.0.3.30, 2015-05-10 if I remember correctly), given that your commit comment indicated that it might answer my needs, and in fact it did for both issues I previously encountered. I can’t see how this last version could break that, but I’ll give it a try later and let you know.

Edit: it works flawlessly too, many thanks! :D

**Comment by EJocys** [comment]
@bobi32: Thank you for letting us know. I will close this issue now.
