### ISSUE TITLE
Mark of Ninja support

### ISSUE THREAD

**Issue by elkanbrand** [x360ce/x360ce#791]
I have used x320ce (with PS2 controller & USB adapter, 32-bit system, Win 7) in the past with a few games with no issue. Installing this in Mark of the Ninja and adjusting settings results in the same problem. When the game is started and the controller is active, the menu quickly cycles down as if the L-stick is stuck. I can select menu options but the problem persists in every menu or during mission play, making the controller unusable. Disabling all directional input, adjusting dead zone, etc, does nothing. Anyone had this issue and been able to resolve it in Mark of the Ninja, Shank, or other game?

I have no desire to play an arcade game like this with a keyboard. I looked at the publisher forums but it seemed pointless to post there. I would like to play this but will not purchase another game from them as this one has been a waste of $$.

**Comment by Squall-Leonhart** [comment]
mark of the ninja has had support for a long time.
