### ISSUE TITLE
Doesn't Work With Dark Souls REMASTERED

### ISSUE THREAD

**Issue by Dan1997123** [x360ce/x360ce#794]
Please fix it

**Comment by Squall-Leonhart** [comment]
there will be no fixes for 3.x,  please give the 4.7 alpha a try.

**Comment by ramesh45345** [comment]
@Squall-Leonhart I have tested Dark Souls Remastered using 4.8.0.14 Alpha, it seems to be working fine. I believe this issue can be closed.

**Comment by panda-byte** [comment]
@ramesh45345 I'd be very happy if you could share the settings you used. I used the 4.8.0.14 alpha, started it (from some directory, as the new version doesn't have to be in the game directory, right?), added the game's .exe, set up the mappings (which all worked perfectly), checked 'Enable 1 Mapped Device' and 'Get XInput State'. The game is a 64bit version (on Win 10), I tried different settings for 'XInput Files' and 'DInput File', none seem to work. Someone wrote about this issue on [reddit](https://www.reddit.com/r/darksouls/comments/8mg11h/x360ce_fix/), but his solution didn't work for me either.

**Comment by panda-byte** [comment]
I should mention, Steam itself and all other Steam games recognize the controller input without problems. Dark Souls even recognizes a button press from the controller on the main screen to continue, but after that, none. The option to use a gamepad won't even show up.

**Comment by Squall-Leonhart** [comment]
we don't use libraries in 4.8.

**Comment by panda-byte** [comment]
Oh, so the input files don't matter? I somehow got it to work, though, I don't know what is was exactly, maybe some combination of Steam and x360ce settings. Thank you for your answer, though!
