### ISSUE TITLE
Beta Testing: X360CE 4.6.x.x Alpha

### ISSUE THREAD

**Issue by EJocys** [x360ce/x360ce#795]
This issue is for reporting bugs found in Beta Testing: X360CE 4.6.x.x Alpha. This release contains performance, HID Guardian, permission and many other fixes and updates.

Alpha is intended to test Virtual Emulation. Download links and instructions can be found here:
https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md

**Comment by KiNGKiMO** [comment]
@EJocys Thanks for the update.

1- Whitelist key still not created if it's not there...
2- At x360ce exit, it creates PID key at Whitelist too, it should create the key only at run and delete it at exit.

**Comment by Squall-Leonhart** [comment]
still no response on my pad,  ejocys, do you have a Xbox 360 or original controller handy?

**Comment by EJocys** [comment]
@KiNGKiMO will fix in next update
@Squall-Leonhart  Yes, I have original X360 controller.
Note: During testing of HID Guardian, X360CE threw some exceptions in SharpDX code with Access Denied error. All mappings were frozen. Could not solve the issue by disconnecting device or application restarting, but Windows restart helped. What about old X360CE 3.x. Does it work?
Use this download (with debugging information) so we can see lines where code is crashing:
https://github.com/x360ce/x360ce/releases/download/4.6.0.5/x360ce_debug.zip
Paste c:\ProgramData\X360CE\Errors\*.htm crash content here.

**Comment by Squall-Leonhart** [comment]
The DLL does work fine,
the old applications cannot record input though, which might be why the emulation isn't working.

I have a feeling SharpDX has an issue with XBCD, so if you install that on the windows 7 machine with the x360 controller it might give you a means to debug the issue.

**Comment by EJocys** [comment]
@Squall-Leonhart Correction: I have new Xbox One controller. Tested on Windows 7 32-bit with virtual emulation just now. Works fine. I broke my Xbox 360 controller long time ago. I will get my hands on official Xbox 360 Controller Tomorrow. Then I will be able to test it on Windows 7 and see if I can replicate the issue. Are you sure that some other application (like Steam in gaming mode) or service is not using that controller in an exclusive mode?

**Comment by Squall-Leonhart** [comment]
Definitely,  other games can pick it up,  it works in the X360CE app when using the library, just not when using record feature or virtual.

if i return to the xusb driver it works, but I want to use XBCD because it has superior dinput capability.

i reproduced the same issue on my win8 vm with usb passthrough, the xusb driver can work, but xbcd is just ignored by record and virtual.

**Comment by EJocys** [comment]
@Squall-Leonhart 
I've just realised something. Are we talking about...
Original Original Original Xbox "The Duke" Controller (2001):
![image](https://user-images.githubusercontent.com/11958537/40580145-d76d47b6-6130-11e8-92ed-f3a75c874733.png)
or Original Original Xbox Controller S (2003)
![image](https://user-images.githubusercontent.com/11958537/40580147-e8638008-6130-11e8-866a-056e8f0e9d45.png)
I will get access to Original Xbox 360 Controller (2005)
and currently have access to Xbox One Controller (2012)

**Comment by Squall-Leonhart** [comment]
Actually, I have  both the  Xbox S and a 360 type

my xbox 360 pad is a MLG Pro circuit  360, https://www.youtube.com/watch?v=Xi9wrqGz7aY

which is use with XBCD.
http://www.mediafire.com/file/32e4566jjj5nzja/XBCD_Installer_0.2.7.exe
this version is signed to atleast install on windows 7 without test mode.

**Comment by EJocys** [comment]
@Squall-Leonhart Picture is getting clearer :). Ok, I will get one of these and Xbox to USB converter cable. It will be an interesting experiment. One day, maybe, I will get even a console too :).

**Comment by Squall-Leonhart** [comment]
![image](https://user-images.githubusercontent.com/1098176/40580397-9fb6b6e0-6180-11e8-9ce3-fd5c45b668c5.png)

**Comment by Squall-Leonhart** [comment]
![image](https://user-images.githubusercontent.com/1098176/40580399-b02ebacc-6180-11e8-92d6-4611cb568611.png)

**Comment by EJocys** [comment]
Every time I work on code to support old INI/DLL emulation, I have doubts. I could spend that time on fixing Virtual emulation bugs, adding new features like simple DInput mapping to keyboard/mouse or fixing mouse/keyboard mapping to XInput. Do we really need old Library support or Virtual emulation is the future?

**Comment by Squall-Leonhart** [comment]
The library still has some functionality that  virtualization can't have right?

**Comment by EJocys** [comment]
@Squall-Leonhart I can't remember any important functionality which can't be implemented on Virtual emulation. Version 3.x will be always available for people who need old emulation.

**Comment by KiNGKiMO** [comment]
Virtual emulation is the future indeed... I also think it's much better if you drop ini/dll support from new versions.

**Comment by WindowStations** [comment]
Sorry if this is the wrong place to ask, but does anyone know how to detect if a Window (Windows.UI.Core.CoreWindow or ApplicationFrameWindow by class name) is actively processing XINPUT?  I have Windows 10 installed on different machines.  Some machines accept and support XINPUT automatically, while other machines do not.  By accept, I mean they respond to input and change keyboard focus/selection.  The problem is how to seamlessly yield input to these windows by their class names, only when input is being processed internally.  I am trying to avoid double input/output.  Input/output from the OS and also input/output from my desktop application.  By default my application yields to the OS when these windows get foreground focus, but it would be nice if my software could detect that no such processing is being done.  Thus my application can be the primary device processing input/output to that window.
Thanks

**Comment by EJocys** [comment]
OK then. Today, I've started to focus on things which will help to release stable app with Virtual Emulation faster. I will remove support for old INI/DLL emulation from version 4.x slowly, because I wan't each release to be more stable and more complete. 3 unnecessary buttons on front interface are gone, so it looks less confusing and a little bit more user friendly already. And my Original Xbox Controller S is on the way :).

**Comment by KiNGKiMO** [comment]
Great news, good luck @EJocys 
Is it possible for x360ce to accept parameters? -nogui is really needed for me to start testing in live environment, also profiles would be great feature.

**Comment by EJocys** [comment]
@KiNGKiMO 
About "-nogui". I am slowly trying to separate main code from GUI. At the moment, closest thing is to minimise app, which will stop nearly all GUI updates. After public release, I will try to split main main code into a separate DLL for use with X360CE Server (windows service) application.

About profiles. Do you mean something like [Export...] and [Import] buttons for Game or Controller, which will export/import all relevant settings into/from separate file? or different mappings for the same Game?

**Comment by KiNGKiMO** [comment]
@EJocys 
That's good, windows service is even better...

About profiles, yes that's what I mean, plus a command to start with a specific profile, like x360ce.exe -profile=abcd

**Comment by EJocys** [comment]
@KiNGKiMO I can easily make "-profile" parameter to set default settings folder.

-profile=<folder_path>|<profile_name>

:: Simple name (or relative path) can point to Profiles folder.
-profile=Profile1 -> %ALLUSERSPROFILE%\X360CE\Profiles\\<profile_name>
        c:\ProgramData\X360CE\Profiles\Profile1

:: Full rooted path can point to specified folder:
-profile=c:\MyX360CeProfiles\MyProfile1

**Comment by KiNGKiMO** [comment]
@EJocys  Yeah, that will be great then.

**Comment by EJocys** [comment]
@Squall-Leonhart Tested original "Microsoft Xbox Controller S". Had same issue with DInput states not updating when using old unsigned XBCD drivers and "Mayflash" digitally signed drivers (https://www.s-config.com/xbcd-mayflash-xbox-joystick-driver). Figured out that I need to call device.Poll() method for some controllers before requesting DInput state. Updated x360ce.exe. Your device should work now.
Please download and test latest version from: http://www.x360ce.com/files/beta/x360ce.zip

P.S.: Tested force feedback. Big motor works as intended, but needs fix, because big motor starts to spin when force is sent to the small motor.

**Comment by EJocys** [comment]
@Squall-Leonhart Fixed CooperativeLevel settings bug, left after my experiments.
Please re-download and test latest version from: http://www.x360ce.com/files/beta/x360ce.zip

**Comment by Squall-Leonhart** [comment]
You are brilliant!

**Comment by Squall-Leonhart** [comment]
Just gotta work out the issue with the xbox 360 software not being detected properly.

**Comment by Squall-Leonhart** [comment]
I think you need to put vibration behind the device poll as well.

hmm yah, it kind of feels like FFB is set up before cooperative level is ready, so it just doesn't work if x360ce is started with it enabled.

if you turn FFB on after starting it works.

**Comment by Squall-Leonhart** [comment]
ah,  device goes yellow when hidden.

**Comment by Squall-Leonhart** [comment]
We need HID Cerberus and interaction with it to autowhite list the x360ce process

**Comment by EJocys** [comment]
@KiNGKiMO 

Added support for -Profile=<name|path> parameter where "name" and "path" will point to folder with settings (app will create one if not exists). Supports environment variables. Examples:

:: Example with name (name contains valid file name chars only)
:: Profile path will be set to: %ALLUSERSPROFILE%\X360CE\Profiles\\\<name>
x360ce.exe -Profile=MyProfile

:: Example with path (name contains valid path name chars i.e. contains "\" char for example)
x360ce.exe -Profile=.\x360ce
x360ce.exe -Profile=d:\MyProfiles\Demo
x360ce.exe -Profile="%LOCALAPPDATA%\x360ce"

Note: If application finds ".\x360ce\x360ce.Options.xml" file then it will use settings from ".\x360ce" folder as current Profile automatically. This allows to keep x360ce.exe and all its settings inside same folder without using -Profile argument.

App is missing another feature - monitoring of started/closed processes so that it could switch to correct game settings automatically.

@Squall-Leonhart 

Fixed. Application will not check for installed Microsoft Xbox Controller drivers on Windows 8+ or later, because OS will be installing drivers and software automatically.

---------------------------------

Download (4.7.0.14) is here:
http://www.x360ce.com/files/beta/x360ce.zip

Next, I will focus more on getting mapping configuration right when new controller is detected. Have to export proper (most popular and complete) configurations from the database. After that is done, app can go from "Alpha" to "Beta".

**Comment by Squall-Leonhart** [comment]
need 4.7.0.15 built when you have a moment Ejocys,  I fixed the drivers Issue on 7.

**Comment by EJocys** [comment]
@Squall-Leonhart Thank you. Done. Download (4.7.0.15) is here:
http://www.x360ce.com/files/beta/x360ce.zip

**Comment by Squall-Leonhart** [comment]
hmm, ok, that didn't fix it after all.

the check for the Visual C redists is working, 

could it be the SetSeverity line?

for the redists you have
>			SetSeverity(IssueSeverity.None);

for the Xbox accessories you have
>            SetSeverity(IssueSeverity.None, 0, program1);

**Comment by EJocys** [comment]
@Squall-Leonhart Last two parameters will be ignored. 
So problem is that application still says that you don't have drivers and application installed?

Which version of Windows are you testing on? Windows 7 64-bit or 32-bit? I will retest on my machine.

**Comment by Squall-Leonhart** [comment]
Win 7 64

just tried another clean install of the accessories to no change.

**Comment by EJocys** [comment]
@Squall-Leonhart I can replicate the issue.

**Comment by EJocys** [comment]
@Squall-Leonhart Found the issue.
Application is checking these sub keys for installed programs:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
HKEY_CURRENT_USER\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall

I must add this key to the list:
HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Products

**Comment by EJocys** [comment]
@Squall-Leonhart Fixed. Download (4.7.0.19) is here:
http://www.x360ce.com/files/beta/x360ce.zip

**Comment by KiNGKiMO** [comment]
@EJocys incredible.
Just had to reinstall windows, started x360ce and the issues detector needs "VC ++ 2015 Redist." I've 2017 installed already, 2017 should be sufficient because it has 2015 included, is this correct?

![image](https://user-images.githubusercontent.com/11393200/40877599-fc782c80-6683-11e8-9f42-bf5a9738e4d4.png)

**Comment by Squall-Leonhart** [comment]
you must only have the x64 version installed.

**Comment by EJocys** [comment]
@KiNGKiMO 
Yes. Installing "Visual C++ 2017 Redistributable (x86)" and "Visual C++ 2017 Redistributable (x64)", will remove warning about "Visual C++ 2015...".

I recommend "Visual C++ 2015..." by default, because ViGEm is using it. I think that, you are safe to use "Visual C++ 2017..." version unless developer used some specific function and restricted to specific redistributable version.

**Comment by Squall-Leonhart** [comment]
Hmm, so my issue now is that if i start x360ce with rumble enabled, it won't work.
i have to replug the controller, and start x360ce with it disabled.

Then when i first enable vibration it will be stuck vibrating, so i unselect it and it stops, the second time selecting it will work correctly.

I believe its set cooperative related.

**Comment by EJocys** [comment]
@Squall-Leonhart OK, will look into this issue next.

**Comment by Squall-Leonhart** [comment]
it might be a XBCD specific glitch, the FFB library needs an overhaul and im not the right person for that job, the last thing i did with it add a patch to implement directional constant vibration for x360ce compatibility and cleaned some warnings.

**Comment by KiNGKiMO** [comment]
@Squall-Leonhart Nope, I have both installed.

@EJocys this is not the case, x360ce didnt work correctly (RED led Icon) at controller 1 and 2..

I installed VC++ 2015 Redist. and it worked (Green icon)... Strange though.

**Comment by Squall-Leonhart** [comment]
what version of 2017 did you have?
14.13.26020 works for me.

**Comment by KiNGKiMO** [comment]
14.14.26429

**Comment by EJocys** [comment]
@KiNGKiMO Maybe, for compatibility reasons, I need to remove "Visual C++ 2017" as an alternative, because "Visual C++ 2015" must work 100%.

**Comment by KiNGKiMO** [comment]
@EJocys Yes, consider it then please.

**Comment by Squall-Leonhart** [comment]
14.14.26429 also working for me.

**Comment by KiNGKiMO** [comment]
@Squall-Leonhart download link please?

**Comment by KiNGKiMO** [comment]
@EJocys Me and my friends played some games today, I used x360ce, each time we changed a game, I found x360ce GUI hangs, the pads were still working though... Do you remember the GUI hang I told you about before?

**Comment by EJocys** [comment]
@KiNGKiMO I will try to replicate the issue again.

**Comment by EJocys** [comment]
@KiNGKiMO Updated code lines which where causing GUI hanging due to refreshing information from detected Direct Input devices.

You can try fixed version (4.7.0.24):
http://www.x360ce.com/files/beta/x360ce.zip

**Comment by KiNGKiMO** [comment]
@EJocys Thanks, I'll try and report tomorrow.

**Comment by KiNGKiMO** [comment]
@EJocys morning man,
The new fix didn't work, but I finally got the issue narrowed  down to windows scaling...
So all you have to do to replicate the issue, is just execute x360ce and change display scaling.

![image](https://user-images.githubusercontent.com/11393200/40964613-dc17a09a-68ab-11e8-8878-4328aae1706b.png)

**Comment by EJocys** [comment]
@KiNGKiMO Thanks. I was able to replicate the issue. Disabling all interface and Direct Input updates during screen changes fixed issue on my PC. Please try new fixed version (4.7.0.26):

http://www.x360ce.com/files/beta/x360ce.zip

**Comment by KiNGKiMO** [comment]
@EJocys Fix confirmed, Thank you so much...

**Comment by KiNGKiMO** [comment]
![image](https://user-images.githubusercontent.com/11393200/41070855-4b5e2ba0-69f5-11e8-9274-9d824285a6ab.png)

I had an issue trying to hide this device with HIDGuardian.
x360ce adds "HID\VID_0810&PID_0001" to AffectedDevices, but the device is still not hidden.

I tried "HID\VID_0810" but no effect. as well.
Finally tried these, and they worked:
HID\VID_0810&PID_0001&Col01
HID\VID_0810&UP:0001_U:0004

So, shall x360ce adds the 2nd value shown at Hardware Ids Property?

**Comment by Squall-Leonhart** [comment]
the current hidguardian implementation will glitch and the controller will appear within seconds again,  unless you replug then it doesn't work at all.

**Comment by KiNGKiMO** [comment]
@Squall-Leonhart Well, it works just fine with me with no glitches at all, I tried with two different devices (Logitech Dual Action & Twin USB PSX Adapter).

What I meant above is the value that should be added to AffectedDevices... x360ce should detect the correct value... that's it.

**Comment by EJocys** [comment]
@KiNGKiMO I will see what I can do with it. Without proper HID Guardian documentation implementing it looks more like poking around in the dark :).

**Comment by EJocys** [comment]
Created new issue #808 

Last week, developing slowed down a bit, because primary job is wearing me down more, so that I have just enough brain power left for Battlefield 4, Diablo III, YouTube and 9GAG :). Next, I will focus more on getting mapping configurations right when new controller is detected. Have to export proper (most popular and complete) configurations from the database.

@KiNGKiMO 
Updated HID Guardian support. Now it will add all hardware ids to filter list which starts with "HID\\VID_HHHH&PID_HHHH. I would not call it a "high quality work" :), but I will make it better in the future.

**Comment by KiNGKiMO** [comment]
@EJocys brilliant as usual, thank you so much for your effort and time continuing such a great project.
