### ISSUE TITLE
Windows April 2018 Update and x360ce

### ISSUE THREAD

**Issue by tmarquesbr** [x360ce/x360ce#799]
I'm using the program after my controller seems unfit for games (and steam overlay) by its button mapping (button 1 is Triangle/Y, button 2 is Circle/B, Rs and Ls are inverted and so on...), and I'm using the program for most of the games, but since Windows April 2018 Update I was struck by the gaming fps bug situation involving a few games. I tried most of the things (graphic driver, game bar...) but an accident put my mind in doubt. I opened one of the games without the controller and suddenly it was working as it nothing happened. I plugged it again, to make sure I did something amazing, and it was completely slow again. I noticed the game was using x360ce and I decided to test something akward. I took x360ce.ini from the game folder (forcing the program to deactivate) and turned the game on again. Surprise! The game was working normally, making the x360ce a possible culprit. I don't know if there's a coincidence or a REAL connection between them, but...

So far, the games I tested positively was:
- Star Ocean - The Last Hope Remaster
- Arslan The Warriors of Legend
- Warriors All Stars
- Final Fantasy XV

There was also something I noticed. Since the controller only works when the game is running, the FPS goes up when it's playing "background". This was noted when I saw FFXV jumping from 9 FPS to nearly 60 FPS since I'm using Windowed Mode and with x360ce working.

**Comment by Squall-Leonhart** [comment]
issue is your controllers vibration library.
