### ISSUE TITLE
Force feedback on DirectInput devices doesn't work

### ISSUE THREAD

**Issue by jbienz** [x360ce/x360ce#8]
_From [ejocys](https://code.google.com/u/ejocys/) on April 24, 2010 05:02:06_

What steps will reproduce the problem? 1. Run x360ce.exe
2. Open [Controller X][Advanced] tab
3. Check [x] Enable Force Feedback
4. Move "Test Left Motor" slider.

What is the expected output?

   Left motor must start to rumble.

What do you see instead?

App will crash and this error will be recorded if logging is enabled:

[DINPUT] [PAD1] CreateEffect (1) failed with code HR = DIERR_INVALIDPARAM 
[DINPUT] [PAD1] CreateEffect (1) failed with code HR = DIERR_INVALIDPARAM

_Original issue: http://code.google.com/p/x360ce/issues/detail?id=8_

**Comment by jbienz** [comment]
_From [ejocys](https://code.google.com/u/ejocys/) on April 24, 2010 03:04:12_

I've added DirectInput force feedback C++ source code example from Microsoft:
x360ce\x360ce\Support\FFConst.zip
Force feedback works on my device when using this example. Maybe it will help since
example code is very similar to x360ce\x360ce\x360ce\directinput.cpp.

**Comment by jbienz** [comment]
_From [serban.a...@gmail.com](https://code.google.com/u/109902393778134095833/) on April 24, 2010 05:46:32_

i respect you for this application!keep up the good love im in love"" with my 
rumblepad2 for quite some years now and wanted to be able to play games that require 
xbox 360 controller .i used until now the toca edit xbox emulator but your version 
is much more awesome!

**Comment by jbienz** [comment]
_From [serban.a...@gmail.com](https://code.google.com/u/109902393778134095833/) on April 24, 2010 05:57:14_

ok with the 2.0.2.47 i dont have vibration in assassijns creed 2 anymore in 2.0.2.46 
it worked

**Comment by jbienz** [comment]
_From [serban.a...@gmail.com](https://code.google.com/u/109902393778134095833/) on April 24, 2010 05:57:17_

ok with the 2.0.2.47 i dont have vibration in assassijns creed 2 anymore in 2.0.2.46 
it worked

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 24, 2010 06:09:49_

Please test r106

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 24, 2010 06:12:12_

Seems setting direction to 0,0 not works on every gamepad (works on my Trustmaster)

**Comment by jbienz** [comment]
_From [serban.a...@gmail.com](https://code.google.com/u/109902393778134095833/) on April 24, 2010 06:14:00_

i cant test it since i dont compile versions,i only download them from download 
section:(

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 24, 2010 06:27:35_

Here

**Comment by jbienz** [comment]
_From [serban.a...@gmail.com](https://code.google.com/u/109902393778134095833/) on April 24, 2010 06:33:07_

10x.testing...btw i tested soome more and it seems that vibration does not work 
everytime you enter the game is it a game problem or x360ce bug?

**Comment by jbienz** [comment]
_From [serban.a...@gmail.com](https://code.google.com/u/109902393778134095833/) on April 24, 2010 06:48:14_

i tested xinput1_3.7 and its the same thing

**Comment by jbienz** [comment]
_From [serban.a...@gmail.com](https://code.google.com/u/109902393778134095833/) on April 24, 2010 07:32:31_

ok i found the problem.you have to enable all fake ids to get vibration to work 
everytime you enter the game,now the problem is after you do that you cant enter 
x360ce again because it starts and exits instantly

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 24, 2010 07:33:56_

Strange because for me it work in any configuration.

**Comment by jbienz** [comment]
_From [danialho...@gmail.com](https://code.google.com/u/116142181712224615034/) on April 24, 2010 07:39:11_

Vibration is not working i nthe latest setup app.

it worked fine in the previous version i used which was .35

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 24, 2010 08:22:55_

Bleh, ejocys break force with it changes, reverted this changes and build. Please test.

**Attachment:** [xinput1_3.dll](http://code.google.com/p/x360ce/issues/detail?id=8#hc14)

**Comment by jbienz** [comment]
_From [ejocys](https://code.google.com/u/ejocys/) on April 24, 2010 13:23:13_

FF doesn't work for me. Tried different versions with different options. Maybe its
windows (I am using Windows 7 64-bit OS + DirectX February 2010).

**Comment by jbienz** [comment]
_From [ejocys](https://code.google.com/u/ejocys/) on April 24, 2010 13:32:15_

... or Logitech wheel or gremlins. Do we have anyone here with 64-bit OS and working
Force Feedback?

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 24, 2010 13:58:35_

I have Win 7 x64, Thrustmaster Dual Trigger 3-in-1 and working ...
I cannot debug this issue because works for me ...

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 24, 2010 16:34:09_

**Labels:** -Priority-Medium Priority-High x360ce-Core

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 24, 2010 16:34:20_

**Owner:** tapcio

**Comment by jbienz** [comment]
_From [ejocys](https://code.google.com/u/ejocys/) on April 25, 2010 02:21:36_

As I've mentioned before, force feedback works only with "TocaEdit XInput 3.0 Vista"
version: http://www.tocaedit.com/IB/index.php?automodule=downloads&req=download&id=30 included XInput DLL supports extra FF options:

UseForceFeedback=1
ForceLargeGain=8500
ForceLargePeriod=120000
ForceLargeFadeTime=10
ForceLargeFadeIn=0
ForceLargeFadeOut=0
ForceLargeStartMag=3750
ForceSmallGain=8500
ForceSmallPeriod=30000
ForceSmallFadeTime=10
ForceSmallFadeIn=0
ForceSmallFadeOut=0
ForceSmallStartMag=3750
WheelInertiaGain=2500
WheelSpringGain=5000

Source code is unavailable and I can't find decompiler which could disassemble it in
readable format.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 25, 2010 02:42:35_

TocaEdit XInput 3.0 Vista by Kalessian ?
Kalessian only fix NULL pointer in original 3.0 (possible by commenting out some 
code).
Original  3.0 code is one big mess.
My DLL is far better. I tested it on my Thrustmaster and Logitech Rumblepad 2 (wired) 
on different computer in AC2, works fine with FF.
I really don't know why is not working for you... 
Even in app help, is about not working FF in GTA IV on newer dll. Thats not true, on 
my system all works fine.
All these old setting modify fade thats are NOT needed because games in xinput modify 
motor speed self. Wheel option add spring inertia to effect. Seems 3.0 uses periodic 
force, not constant force.

You gamepad has support for constant force effect ?

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 25, 2010 02:45:56_

Sorry for double comment. In DirectInput is not possible to doing LeftMotor = only left 
motor in gamepad or RightMotor = only right motor ! This is DirectInput limitation and 
cannot be done. Maybe some FF Driver allows set effect to work in similar way, but 
Logitech & Thrustmaster not.

**Comment by jbienz** [comment]
_From [ejocys](https://code.google.com/u/ejocys/) on April 25, 2010 03:33:14_

> Even in app help, is about not working FF in GTA IV on newer dll

I've updated App help, now it relates to FF and Logitech Wheel

> You gamepad has support for constant force effect ?

Yes it supports "Constant" force. Microsoft 'FFConst' VC++ example use constant force
and it works on my wheel. PrepareForce(...) inside DirectInput.cpp is nearly
identical to code inside Microsoft's FFConst.cpp which means that code fails not
because effect parameters are missing. Maybe wheel device is not ready or something.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 25, 2010 03:35:54_

PrepareForce(...) should be called twice. Both calls fails ? Log or something ?

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 25, 2010 03:49:18_

//fix Summary

**Summary:** Force feedback on DirectInput devices doesn't work  
  **Status:** Started

**Comment by jbienz** [comment]
_From [ejocys](https://code.google.com/u/ejocys/) on April 25, 2010 04:02:03_

Yes, PrepareForce(...) is called twice and both fails.

11:57:16.967065:: [DINPUT] [PAD1] CreateEffect (0) failed with code HR =
DIERR_INVALIDPARAM 
11:57:16.967065:: [DINPUT] [PAD1] CreateEffect (1) failed with code HR =
DIERR_INVALIDPARAM 

I will try to get Logitech Rumble Pad II and see if this is Logitech Wheel specific
issue or something else.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 25, 2010 04:16:08_

Maybe it have only one FF axis ?

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 25, 2010 04:35:55_

Please try r115 .

**Comment by jbienz** [comment]
_From [ejocys](https://code.google.com/u/ejocys/) on April 25, 2010 04:51:53_

> Maybe it have only one FF axis ?

Yes, FFConst reports one axis (g_dwNumForceFeedbackAxis = 1).

 // Enumerate and count the axes of the joystick 
    if( FAILED( hr = g_pDevice->EnumObjects( EnumAxesCallback,
        ( VOID\* )&g_dwNumForceFeedbackAxis, DIDFT_AXIS ) ) ){
   ...  
   }

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 25, 2010 04:53:26_

If it's a single FF axis r115 should work. Please test.

**Comment by jbienz** [comment]
_From [ejocys](https://code.google.com/u/ejocys/) on April 25, 2010 05:34:13_

Nope, doesn't work. Same:
[DINPUT] [PAD1] CreateEffect (0) failed with code HR = DIERR_INVALIDPARAM 
[DINPUT] [PAD1] CreateEffect (1) failed with code HR = DIERR_INVALIDPARAM 

AS, I've said, maybe its not the parameters (since FFConst have same "prepare effect"
code and works) maybe device or something is locked, not ready (some line which runs
before preparing FF effect function), maybe parameter type is wrong. I will try to
investigate differences between FFConst and c360ce since I am only one who can
replicate it, maybe I will come up with something one day :).

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on April 30, 2010 09:32:55_

Please test Force Editor, it can create, and test any DirectInput effect. It's from 
very old SDK (summer 2004).

**Attachment:** [fedit.zip](http://code.google.com/p/x360ce/issues/detail?id=8#hc32)

**Comment by jbienz** [comment]
_From [Pasha.St...@gmail.com](https://code.google.com/u/117076518774592796386/) on May 25, 2010 05:07:51_

Greetings. At me too problems with FF, sometimes it very weak, but in most cases is 
absent completely. Has tested fedit, I do not have effects SPRING, FRICTION, DAMPER, 
INERTIA

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 25, 2010 05:29:17_

x360ce at the moment use only Constant Force effects.

**Comment by jbienz** [comment]
_From [Pasha.St...@gmail.com](https://code.google.com/u/117076518774592796386/) on May 25, 2010 05:37:43_

what to do with the r115 ?

**Comment by jbienz** [comment]
_From [tegstew...@gmail.com](https://code.google.com/u/116189399172650361156/) on May 27, 2010 17:42:29_

Verified with version 3.2.0.120 of the dll and 2.0.2.62 of the exe.  Running Vista
using a wired Logitech RumblePad 2.

The error is caused when using either left or right motor.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on May 28, 2010 03:30:36_

Dunno, I tested rev 91 on my pal wired Logitech RumblePad 2 on Windows 7 with newest 
drivers and FF works.

**Comment by jbienz** [comment]
_From [Bleach.s...@gmail.com](https://code.google.com/u/107383026477779544830/) on May 31, 2010 01:22:14_

Windows 7 x64, Saitek p580

FF working in Control Panel, but in games and such tools as XInputTest.exe and 
x360ce.exe - isnt, and the last one crashes when I trying to move "Test Left Motor" 
slider or "Test Right Motor"

I was trying: x360ce vibmod 3.1.4.1 and XBOX 360 Controller Emulator 2.0.2.62 Beta 2 
(XInput 3.2.0.120) with x360ce Core (xinput1_3.dll) 3.2.0.120.

Anyway the gamepad works great in Blur, but no FF ((

**Comment by jbienz** [comment]
_From [thiagopo...@gmail.com](https://code.google.com/u/105528905149306317312/) on June 23, 2010 06:43:29_

I got one of those PS2 usb generic gamepads, and FF works great!
Tested on Batman:AA.

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on August 05, 2010 17:03:25_

@ejocys

Please test attached debug build.

**Labels:** -x360ce-Core x360ce-Lib  

**Attachment:** [xinput1_3.dll](http://code.google.com/p/x360ce/issues/detail?id=8#hc41)

**Comment by jbienz** [comment]
_From [ejocys](https://code.google.com/u/ejocys/) on August 06, 2010 00:36:38_

I've got latest version. Force feedback works on Logitech RumblePad 2. It works on Xbox 360 Controller when in Native mode too.

I think I need to update App because sometimes DirectInput and xinput1_3 device order doesn't match until I re-load preset. I will check it more thoroughly this weekend.

@tapcio

**Comment by jbienz** [comment]
_From [tapcio](https://code.google.com/u/tapcio/) on August 10, 2010 04:20:32_

This issue was resoled in r145

**Status:** Fixed

**Comment by jbienz** [comment]
_From [danialho...@gmail.com](https://code.google.com/u/116142181712224615034/) on February 16, 2013 11:12:21_

**Status:** Verified

**Comment by nyakze** [comment]
Using Rumblepad 2 on 4.10.0.0 Alpha, vibration works when i click test in Force Feedback section of x360ce, but not in games.
