### ISSUE TITLE
Logitech G920 SW+P - Constant Red Light X360ce

### ISSUE THREAD

**Issue by RazzleDazzleYT** [x360ce/x360ce#801]
I have set up my Logitech G920 Steering Wheel and Pedals.

I've extracted the x360ce files to my GTA V Directory.

I have selected all 46 Popular Controller Settings.
I have mapped all of the buttons.
Pass-Through is unchecked.

It recognises the Steering Wheel but is still Red.

HELP!!
Thanks In Advance

**Comment by Okom1** [comment]
Try this http://nodo.freeforums.net/thread/12065/steering-wheel-working-online-fivem
