### ISSUE TITLE
Beta Testing: X360CE 4.7.x.x

### ISSUE THREAD

**Issue by EJocys** [x360ce/x360ce#808]
This issue is for reporting bugs found in Beta Testing: X360CE 4.7.x.x Alpha. This release contains HID Guardian, permission and stability fixes and updates. I've stared removing old DLL/INI emulation support.

Alpha is intended to test Virtual Emulation. Download links and instructions can be found here:
https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md

More details about last release here:
https://github.com/x360ce/x360ce/releases

**Comment by KiNGKiMO** [comment]
@EJocys Thanks so much...

BTW, are there any differences between x86 and x64 builds?

**Comment by EJocys** [comment]
@KiNGKiMO Some time ago some features would not work if you ran x360ce.exe with different architecture from OS. For example 32-bit x360ce.exe was unable to remove and re-detect device if it was running on 64-bit OS. These issues were resolved by calling devcon.exe with correct architecture when needed and by using C# conditions like
```
#if WIN64
	[StructLayout(LayoutKind.Sequential, Pack = 8, CharSet = CharSet.Unicode)]
#else
	[StructLayout(LayoutKind.Sequential, Pack = 1, CharSet = CharSet.Unicode)]
#endif 
```
There should be no differences between 32-bit and 64-bit builds now. All features must work the same. If something doesn't work then it is a bug which needs to be fixed. Probably it makes the sense to switch  x360ce.exe 4.x project to "Any CPU" type and have only one build.

**Comment by Squall-Leonhart** [comment]
i recommend using the 32bit version, the 64bit  version will often have no vibration capability on cheap controllers.

**Comment by EJocys** [comment]
Created new Beta Testing: X360CE 4.8.x.x #818 

@Squall-Leonhart:  Fixed issue with non-working force feedback when controller is re-connected.
