### ISSUE TITLE
Build with Windows SDK for Windows 8.1

### ISSUE THREAD

**Issue by EJocys** [x360ce/x360ce#81]
@tapcio 

I've tried to build project with Windows SDK for Windows 8.1 installed.
And there is an issue with
C:\Program Files (x86)\Windows Kits\8.1\Include\um\Xinput.h

This file have conditions:
# if(_WIN32_WINNT >= _WIN32_WINNT_WIN8)

  // All stuff related to XINPUT_BATTERY_INFORMATION and XINPUT_KEYSTROKE
# endif //(_WIN32_WINNT >= _WIN32_WINNT_WIN8)

It makes sense because we are targeting Vista in our project:
C:\Projects\TocaEdit\x360ce\x360ce\targetver.h
# define _WIN32_WINNT _WIN32_WINNT_VISTA

If I wrap Battery Information and Keystroke code inside our project then it all builds fine with Windows 8.1 SDK except this file:

C:\Projects\TocaEdit\x360ce\x360ce\x360ce.def
if won't accept conditions and complains about: error LNK1120: 2 unresolved externals    related to Battery Information and Keystroke methods.

Do you know what would be the best way to resolve this?

Can we set _WIN32_WINNT to target Win 8, so we could unlock properties and methods defined in  Xinput.h from Windows SDK 8?

C:\Projects\TocaEdit\x360ce\x360ce\targetver.h
# define _WIN32_WINNT _WIN32_WINNT_WIN8

**Comment by Squall-Leonhart** [comment]
problem with win8 sdk, is dll's and apps built with it look for xinput1_4 and  xaudio 2_9, which anything below windows 8 doesn't have.

**Comment by EJocys** [comment]
I am not C++ developer, but I assume that _WIN32_WINNT flag just allows to control which features we are allowed to use in our code. With _WIN32_WINNT = _WIN32_WINNT_WIN8 we are still going to build xinptut1_3.dll which runs on Windows XP but with 2 extra functions supported by xinput1_4.dll.

**Comment by Nucleoprotein** [comment]
Use xinput.h from DXSDK, it will compile with all exports ie. your include dir order is incorrect.
_XINPUT_BATTERY_INFORMATION and _XINPUT_KEYSTROKE are in all Xinputs from 1.1 to 1.3.
1.4 changes: 

```
// XInput 1.4 functions
DWORD(WINAPI* XInputGetAudioDeviceIds)(DWORD dwUserIndex, LPWSTR pRenderDeviceId, UINT* pRenderCount, LPWSTR pCaptureDeviceId, UINT* pCaptureCount);

// XInput 1.4 undocumented functionss
DWORD(WINAPI* XInputGetBaseBusInformation)(DWORD dwUserIndex, struct XINPUT_BUSINFO* pBusinfo); // 104
DWORD(WINAPI* XInputGetCapabilitiesEx)(DWORD unk1, DWORD dwUserIndex, DWORD dwFlags, struct XINPUT_CAPABILITIESEX* pCapabilitiesEx); // 108
```

As you can see, i'v added struct  keyword to compile 1.4 function without know type to new types: XINPUT_BUSINFO and XINPUT_CAPABILITIESEX

My xinput.h from DXSDK: http://vpaste.net/6GkIJ

**Comment by EJocys** [comment]
Microsoft recommends to use Windows SDK for Windows 8.1 which supports older Windows versions.

x360ce project builds successfully if I set #define _WIN32_WINNT _WIN32_WINNT_WIN8. And, I think, this is what we want: One Xinput library which covers all versions and features of XInputs (from Windows XP to Windows 8.1, Windows 10, and beyond). _WIN32_WINNT is just a project wide parameter and it should not affect other projects.

If xinput1_3.dll built with #define _WIN32_WINNT _WIN32_WINNT_WIN8 runs fine on Windows XP then, I think, we could drop outdated SDK and move to one which suits Visual Studio 2013 features better.

I would always set this parameter to latest version (windows 8.1 for today) if it produces backwards compatible xinput dll: #define _WIN32_WINNT  _WIN32_WINNT_WINBLUE

**Comment by Squall-Leonhart** [comment]
Microsoft also says that posix names are deprecated, and only allows software developesr to use x64 detours if they are willing to pay ;3

That said, we aren't even building dll's for XP (v120 used instead of v120_xp)

**Comment by Nucleoprotein** [comment]
I do not like to use a Windows 8+ only headers because switching to v120_xp will use Windows 7 SDK and will fail to build because some headers are missing. 
Solution:
1. define structures in some header file
2. force _WIN32_WINNT _WIN32_WINNT_WIN8 only for xinput.h

PS: @Squall-Leonhart dll on v120_xp should build just fine.

**Comment by EJocys** [comment]
> use x64 detours if they are willing to pay ;3

Damn, Microsoft Research Detours v3 Professional just $9,999.95 :) at
http://www.microsoftstore.com/store/msusa/en_US/pdp/Microsoft-Research-Detours-v3-Professional/productID.253663300

**Comment by Nucleoprotein** [comment]
Yeah, MS Detours are really cheap ... and they are not better that minhook.

**Comment by TsudaKageyu** [comment]
Yeah, that's exactly why I created MinHook :P

**Comment by Squall-Leonhart** [comment]
Hahaha!

**Comment by EJocys** [comment]
Agreed then on  @tapcio Solution.
