### ISSUE TITLE
add option start with windows

### ISSUE THREAD

**Issue by mkultimate** [x360ce/x360ce#810]
it would be good to add an option and minimize the tray when you start with windows

**Comment by KiNGKiMO** [comment]
Yep, that would be great... Still hoping for the service version though.

**Comment by EJocys** [comment]
Uploaded new release (4.8.0.11) with "Minimize to Tray" and "Start with Windows" options on [Options] tab page.

![image](https://user-images.githubusercontent.com/11958537/42377212-4e35df4e-811a-11e8-8da2-5da2243338b3.png)

https://github.com/x360ce/x360ce/releases

@KiNGKiMO : It will come one day :). I am slowly separating interface code from main mapping engine.
