### ISSUE TITLE
Can't get Risk of Rain to detect input with x360ce

### ISSUE THREAD

**Issue by IllumiC** [x360ce/x360ce#811]
I got it working with my PS3 controller using scarletcrush (directinput)
but I've been trying to get it to work with my G920 wheel to no avail.

Using dll version 3.4.1.1357

**Comment by IllumiC** [comment]
Thanks

**Comment by Squall-Leonhart** [comment]
github is for  bugs, not for support.

**Comment by IllumiC** [comment]
Yeah it's a bug that it ain't working

**Comment by Squall-Leonhart** [comment]
no it isn't.
