### ISSUE TITLE
эмулятор геймпада Xbox 360

### ISSUE THREAD

**Issue by STRONG-RUSSIA** [x360ce/x360ce#815]
Здравствуйте! Помогите пожалуйста! Но Ваша программа уже не может взломать игру MotoGP18 и я не могу в неё играть. Обновите свою программу если не трудно или усовершенствуйте её. Я буду Вам очень признателен.
С Уважением к Вам STRONG RUSSIA

**Comment by EJocys** [comment]
Попробуйте Бета версию 4, которая работает по другому принципу чем старая версия 3:
https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md
