### ISSUE TITLE
Application doesn't prompt me to create any files but throws exception:

### ISSUE THREAD

**Issue by LuminousCodeGH** [x360ce/x360ce#819]
Could not find a part of the path "C:\ProgramData\X360CE\x360ce.Settings.xml".
I downloaded both version from the git page and extracted the one .exe from both.

**Comment by EJocys** [comment]
Which version of application?

**Comment by EJocys** [comment]
Thank you for reporting. Re-released old version and updated links.

https://github.com/x360ce/x360ce/releases/download/3.2.9.82/x360ce.zip
https://github.com/x360ce/x360ce/releases/download/3.2.9.82/x360ce_x64.zip
