### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by jusrinshow** [x360ce/x360ce#821]
when you click download for 64bit games I then pop up the window 404 this is not the web page you are looking for. what should I do

**Comment by EJocys** [comment]
Thank you for reporting. Re-released old version and updated links.

https://github.com/x360ce/x360ce/releases/download/3.2.9.82/x360ce.zip
https://github.com/x360ce/x360ce/releases/download/3.2.9.82/x360ce_x64.zip
