### ISSUE TITLE
64-bit version continually warns about 32-bit xinput1_3.dll

### ISSUE THREAD

**Issue by jacobq** [x360ce/x360ce#822]
App Version: v3.3.6.0
OS: Windows 10 (.0.17134.112)
Arch: x86_64

When I run the 32-bit version, it seems to run correctly: detects controller, shows "green" status indicator on "Controller 1" tab, etc. However, when I run the 64-bit version (also in its own folder on the Desktop) I get prompted to update `xinput1_3.dll`"

>	Name	Description	Fix
>	DLL File	New version of this file is available:
> xinput1_3.dll
> 
> Old version: 0.0.0.0
> New version: 3.4.1.1357
> 
> Do you want to update this file?

If I do this (click "Create") then I get prompted again saying:
> You are running 64-bit application but xinput1_3.dll on the disk was built for 32-bit architecture.Do you want to replace xinput1_3.dll file with 64-bit version?

Clicking "Create" for that prompt does not dismiss it. It stays there until "Ignore All" or "Cancel" is clicked (in which case it appears again shortly).
So I am stuck. If I ignore the 32-bit DLL and try to use the app I immediately encounter a "Failed to load...not a valid Win32 application." message. If I delete `xinput1_3.dll` from the folder and try again, this time choosing to ignore the first prompt and not install/update the DLL, then app doesn't seem to work (status indicator is red, clicking "Save" appears to have no effect, etc.)

What am I doing wrong? I did (re)install the MS VC++ 2013 redistributables for x86 and x64. I've tried running elevated / as admin (no difference).

![image](https://user-images.githubusercontent.com/1633459/42410891-5333f9de-81b7-11e8-9f97-17e7b6965e00.png)
![image](https://user-images.githubusercontent.com/1633459/42410896-5942956a-81b7-11e8-9bfc-26f0fcbb8eb2.png)
![image](https://user-images.githubusercontent.com/1633459/42410966-cfd122ae-81b8-11e8-9486-9727b976a6c8.png)

**Comment by EJocys** [comment]
Thank you for reporting. Re-released old version and updated links.

https://github.com/x360ce/x360ce/releases/download/3.2.9.82/x360ce.zip
https://github.com/x360ce/x360ce/releases/download/3.2.9.82/x360ce_x64.zip
