### ISSUE TITLE
Gamepad fine, no FF

### ISSUE THREAD

**Issue by ThijsBoehme** [x360ce/x360ce#83]
I use my Gioteck VX-2 with your program, and it works fine in all games as of now, but I can not get Force Feedback working.
Can you help? What files do you need?

**Comment by Nucleoprotein** [comment]
You require a DirectInput compatible force feedback driver (FFD) from controller manufacturer, and I do not see any on Gioteck site. You have such driver ?

**Comment by ThijsBoehme** [comment]
I guess I don't have that, didn't know I needed that!

**Comment by Squall-Leonhart** [comment]
http://www.gioteck.com/setup-guide-vx-1-vx-2-controllers-pc/

They use only windows HID driver,  no vibration library provided by vendor.

**Comment by ThijsBoehme** [comment]
Too bad then, thanks for the info.
