### ISSUE TITLE
Shining Resonance Refrain

### ISSUE THREAD

**Issue by Diablo2000** [x360ce/x360ce#834]
I've been trying for an couple of days now to get this game to recognize the controller on my PC. So far I'm of two minds about the problem, either the game simply won't recognize the xinput1_3.dll file.
I tried making copies of the file changing the names like the help section says, but it was to no avail. I am kinda out of ideas at this point.

**Comment by KiNGKiMO** [comment]
Delete V3 from game directory and please use the latest V4 alpha (it's standalone, don't move to game folder).
https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md

**Comment by Diablo2000** [comment]
It did work. It has been a couple of weeks and I forgot to close the topic. So I will just say, thanks very much. It did help.
