### ISSUE TITLE
Tom Clancy's Rainbow 6 Seige

### ISSUE THREAD

**Issue by ALEEF02** [x360ce/x360ce#835]
Hi,
I'm trying to set this up for Rainbow 6 Seige, but I can't get it to work. Any ideas? The square at the top left is green and the virtual controller is turning green with the buttons I press. It is also in the root folder of the game

**Comment by KiNGKiMO** [comment]
-Don't put x360ce in game folder...

-Make sure that you've  XBOX 360 controller showed at control panel's (joy.cpl) and working.
![image](https://user-images.githubusercontent.com/11393200/43164109-91ab2c64-8f90-11e8-9de8-bfbce797c95a.png)

-Hide your original gamepad.
![image](https://user-images.githubusercontent.com/11393200/43164195-d18d0bb8-8f90-11e8-93d0-5bc90cd5a894.png)
