### ISSUE TITLE
Sleeping Dogs Definitive Edition

### ISSUE THREAD

**Issue by jpvg10** [x360ce/x360ce#838]
Hello! I'm trying to get x360ce to work with this game but no luck so far. I've followed [this ](http://tylau0.blogspot.com/2015/01/sleeping-dogs-definitive-edition.html) popular guide but can't make it work (and maybe it's a little outdated?)

Thanks in advance!

**Comment by KiNGKiMO** [comment]
I advice you to use latest alpha:
https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md

**Comment by jpvg10** [comment]
That's awesome man! I just tried and it worked!

**Comment by jpvg10** [comment]
Also, it solved my problems with Hollow Knight. Superb work, thanks a lot!

**Comment by KiNGKiMO** [comment]
Yep, should work with every game that supports xbox 360 controller.
