### ISSUE TITLE
VALKYRIE DRIVE -BHIKKHUNI- game wont detect x360ce

### ISSUE THREAD

**Issue by gittyno1** [x360ce/x360ce#850]
The game works with controller, its just that controlls are messed up, and game wont detect when i install x360ce into instalation directory and start a game.

I can tell it wont detect because i dont hear bleep and remaped controlls wont work.

**Comment by ghost** [comment]
Try to use latest alpha release:
https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md

It works differently, so read the instructions

**Comment by gittyno1** [comment]
i will try. thank you.
