### ISSUE TITLE
[Feature Request] SWITCH

### ISSUE THREAD

**Issue by i486** [x360ce/x360ce#862]
Please accept my apologies for requesting this here. 

But it seems Xonar community member Virus is no longer there anymore and this github project link is linked to his username. So i am trying my luck to contact him here.

So Hello, Virus. If you're here I would greatly appreciate if you update your Xonar Front Panel Switch application, so it can switch between "2 Speakers & FP Headphone" 

Thank you very much

**Comment by Squall-Leonhart** [comment]
This is not a message board to contact Tapeq

**Comment by i486** [comment]
How to contact Tapeq?
