### ISSUE TITLE
Won't detect controllers outside of x360ce

### ISSUE THREAD

**Issue by Notahrowawayaccount** [x360ce/x360ce#867]
I used this program to play many games with a Gamecube adaptor and recently got a new Xbox one controller, but some games won't recognize my new controller despite deleting the previous files made by x360ce as well as deleting the program itself.

Reinstalling those games didn't fix this.

Examples,, Spelunky did recognize the new controller after deleting x360ce, but Crypt of the Necrodancer didn't.

**Comment by ghost** [comment]
You should try the latest X360CE 4.8.0.14 Alpha release (you can find it [here](https://github.com/x360ce/x360ce/releases)). At this version you don't have to put any files into the games's folder, it just creates a virtual gamepad.
But better read [the instructions](https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md) before using it and don't forget to hide your original gamepad using HiDGuardian which is built into X360CE.

**Comment by Notahrowawayaccount** [comment]
> You should try the latest X360CE 4.8.0.14 Alpha release (you can find it [here](https://github.com/x360ce/x360ce/releases)). At this version you don't have to put any files into the games's folder, it just creates a virtual gamepad.
> But better read [the instructions](https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md) before using it and don't forget to hide your original gamepad using HiDGuardian which is built into X360CE.

No, im trying to restore the games to before X360CE. I no longer have a need to use it, but some games got "stuck" with whatever X360CE does to the input settings.

**Comment by Squall-Leonhart** [comment]
sounds like you wrongly placed the xinput files in the  windows system directory.

also some games that claim xinput support will only work with a microsoft brand xbox 360 controller.

**Comment by tluanga34** [comment]
I too just ruined my MYGT C04 . Right thumb axis become 90deg off calibration. No longer work on Android. All the default mapping inside the controller is gone.

**Comment by Squall-Leonhart** [comment]
closing because not possible without doing dumb shit.
