### ISSUE TITLE
Not working on Assassin's creed Odyssey

### ISSUE THREAD

**Issue by Noxyno** [x360ce/x360ce#869]
Hey ! I'm trying to play to AC Odyssey with x360ce but it doesnt find the game when I try to setup it. It's weird because it worked on AC Origins :/ 
I hope you'll help me thx !

**Comment by ghost** [comment]
You should try the latest X360CE 4.8.0.14 Alpha release (you can find it [here](https://github.com/x360ce/x360ce/releases)). At this version you don't have to put any files into the games's folder, it just creates a virtual gamepad.
But better read [the instructions](https://github.com/x360ce/x360ce/blob/master/Wiki/BetaTesting.md) before using it and don't forget to hide your original gamepad using HiDGuardian which is built into X360CE.

**Comment by Squall-Leonhart** [comment]
vmprotect+denuvo is not and can never be supported by versions older than 4.8

**Comment by palnikola** [comment]
Instruction page is not available can @TheEzio121
