### ISSUE TITLE
NOT WORKING IN DEVIL MAY CRY HD COLLECION

### ISSUE THREAD

**Issue by Belissimoo** [x360ce/x360ce#870]
I have fully set up the controller but it wont work in devil may cry hd collection

**Comment by Squall-Leonhart** [comment]
use vigem based 4.8

**Comment by RyuuzakiL5** [comment]
WHAT THE FUCK is a "vigem based 4.8"??????

**Comment by EJocys** [comment]
https://github.com/x360ce/x360ce/releases
X360CE 4.8.0.14 Alpha
