### ISSUE TITLE
X360ce not working in fifa 18

### ISSUE THREAD

**Issue by kishorekumar2110** [x360ce/x360ce#879]
I installed FIFA 18 and wanted to enable right analog stick. I downloaded x360ce for 64-bit games and then this appeared:
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
at SharpDX.DirectInput.DirectInput..ctor()
at x360ce.App.MainForm..ctor()
at x360ce.App.Program.Main(String[] args)

Help please!

**Comment by Squall-Leonhart** [comment]
RTM
