### ISSUE TITLE
x360ce - IndexOutOfRangeException

### ISSUE THREAD

**Issue by xwing007** [x360ce/x360ce#90]
Hello,
I have downloaded latest version of x360ce v3.0.3.36 Beta 3 (2015-05-12)
This version does not work for me.
My english is very poor, so please check short video (20 secs) There you will see what is my problem
http://youtu.be/n17v9B7HlGY
First .exe file is x360ce_v3.0.2.25 Beta 2 (2015-04-30) and works very well for me.
Second .exe file is x360ce_v3.0.3.36 Beta 3 (2015-05-12) and still get error message.
I have installed Windows 8.1 x64, .NET 3.5 and 4.5, MS Visual C++ 2010 (x86 and x64),  MS Visual C++ 2012 (x86 and x64),  MS Visual C++ 2013 (x86 and x64), DirectX_Jun2010_redist.exe.
I'll be grateful for any help and advice.

![exc](https://cloud.githubusercontent.com/assets/12469764/7665511/7026bd28-fbba-11e4-972b-426a3323199c.jpg)

**Comment by Nucleoprotein** [comment]
Partition serial number issue backs again, maybe use LAN Adapter MAC instead or something :P?

**Comment by EJocys** [comment]
@xwing007: Could you download debug version (with *.pdb files) and post crash dialog screenshot. It should give us exact line where crash happens:
www.x360ce.com/files/x360ce_debug.zip
www.x360ce.com/files/x360ce_x64_debug.zip

@tapcio: It is a different error now. I would like to link games to the disk. LAN MAC only as an alternative. Because with Disk Id, games configuration will move with the disk and games on it Probably both must be supported so application can find user's game configuration in case of Disk or PC (NIC) replacement.

**Comment by xwing007** [comment]
Hello,
Here you are screenshots:

1) x64 
![x360ce_x64_error](https://cloud.githubusercontent.com/assets/12469764/7666275/a1a6143c-fbdf-11e4-9b87-deb708efa826.JPG)

2) x86
![x360ce_x86_error](https://cloud.githubusercontent.com/assets/12469764/7666274/a1a29b90-fbdf-11e4-8b51-e52b0423644e.JPG)

**Comment by EJocys** [comment]
@xwing007: Thank you. I've uploaded new debug release and included debug information of "x360ce.Engine" project. Please download updated x86 version file and try again:

www.x360ce.com/files/x360ce_debug.zip

**Comment by xwing007** [comment]
Hi EJocys,
Here is screenshot of x86 version as you wish ;-)

x86 (2)
![x360ce_x86_ 2 error](https://cloud.githubusercontent.com/assets/12469764/7666755/b3637b54-fbf0-11e4-9a62-e8a45b68c35e.JPG)

**Comment by Nucleoprotein** [comment]
Hym, so here: https://github.com/x360ce/x360ce/blob/master/x360ce.Engine/Common/BoardInfo.cs#L206 but I do not see anything that can cause array index to be out of range.

**Comment by EJocys** [comment]
@tapcio: maybe 'index' is negative.

@xwing007: I've updated code with new fix. Please re-download and try new version:

www.x360ce.com/files/x360ce_debug.zip

**Comment by xwing007** [comment]
Ok, We have a progress. ;-)
The x360ce starts without "IndexOutOfRangeException", but there is a new error message.
Check screenshot.
![x360ce_x86_error 3](https://cloud.githubusercontent.com/assets/12469764/7667517/cf20ac94-fc0a-11e4-9e53-2ea9d29dc2b5.JPG)

**Comment by Nucleoprotein** [comment]
You not have a VS2013 debug runtime - which is normal for user system. Release build should work fine now, so wait for update.

**Comment by EJocys** [comment]
@xwing007: Updated non debug downloads. Please re-download and try:

www.x360ce.com/files/x360ce.zip
www.x360ce.com/files/x360ce_x64.zip

P.S.: Don't forget to delete previous xinput1_3.dll and x360ce.exe, to make sure you are not running debug version.

**Comment by xwing007** [comment]
Hellooo,
You got IT ! :+1: :+1: 
It works now perfectly.
It was a quick action. ;-)
THANK YOU!

**Comment by EJocys** [comment]
Good :).
