### ISSUE TITLE
Saints Row IV compatibility.

### ISSUE THREAD

**Issue by franciebrady** [x360ce/x360ce#91]
I have no idea what I'm doing wrong, but I run Win 7 64, have a Logitech Rumble Gamepad F510, and cannot get it to respond in SRIV. I've tried both 32 and 64 bit versions, and I can get the x360ce app to recognize the controller, but not the game. It looks like it requires the COM hook, so I have that checked as well. If anyone had any insight, that would be amazing. Thanks.

**Comment by Squall-Leonhart** [comment]
use the forum for game specific support.
