### ISSUE TITLE
controller working fine UNTIL i get to the menu screen

### ISSUE THREAD

**Issue by desibe** [x360ce/x360ce#92]
ive been using x360ce for years with every game that supports a controller and it worked flawlessly with ps2 controllers and a converter. two of the games im having same problems with are I Am Bread and Toren. controller works when i boot the games up, i can skip the developer/publisher/software splash screens using buttons on the controller, but as soon as i get to the main menu, the title screen, the controller stops responding.

similar issue with another game, so i decided not to open a new thread about it. Risk of rain v1.2.8.
controller works even during the menu, but as soon as the gameplay starts, it stops responding. the only button i can use is the pause(start) button, it takes me to the pause screen, in which the controller works. if i unpause, its unresponsive again. Risk of rain v1.2.4. at the same time, with the same settings has no problems.

**Comment by Squall-Leonhart** [comment]
I am bread is Unity engine (uses Raw Input for buttons) - will not work with x360ce unless a custom xinput manager is used by the developer
Toren, i have no idea about:
Risk of Rain has controller compatibility issues and does not even need x360ce

issue tracker is not for game related support: use the forum for that.
