### ISSUE TITLE
64bit version not loading if folder has *.pdb file?

### ISSUE THREAD

**Issue by frzsombor** [x360ce/x360ce#920]
I had difficulties trying to get the 64bit version load, because I always got a "blank" app screen.
There are a few similar issues without explanation and without solution (ex: 622, 581, 634). (Don't want to reference them, maybe not related).

Finally I found the problem, but it's very strange. There was a random PDB file in the folder, and after trying out everything, when I removed the `somefile.pdb`, x360ce loaded without any problem.
I can also confirm this strange thing to happen in any folder.

If I put `x360ce_x64.exe` to a new, empty folder, and I put an empty file with any name, but with a PDB file extension, x360ce can't load, gives blank gray screen, not showing anything.

Is this just some craziness in my system, or anyone else can confirm this bug?

Version: v3.2.10.82

![image](https://user-images.githubusercontent.com/7306657/53126484-7f46f500-3560-11e9-883b-b1d9ce289d49.png)

![image](https://user-images.githubusercontent.com/7306657/53126457-6fc7ac00-3560-11e9-8a39-1eefa1175027.png)

**Comment by Squall-Leonhart** [comment]
Working as expected
