### ISSUE TITLE
x360ce not working on metro Exodus

### ISSUE THREAD

**Issue by 2pado** [x360ce/x360ce#927]
Ok so my Switch pro controller has been working on all games except metro Exodus, any help would be appreciated

**Comment by callmeEthan** [comment]
Late respond but if anyone have this problem, this solution works for me.
After setting up x360ce, duplicate your xinput1_3.dll to 5 files and rename those file to:
• xinput1_4.dll
• xinput1_3.dll
• xinput1_2.dll
• xinput1_1.dll
• xinput9_1_0.dll  (you actually only need 1 of them, I'm just lazy to figure out which. This is sure fix for me)
Finally launch Metro Exodus.
