### ISSUE TITLE
x360ce not working with rayman origins

### ISSUE THREAD

**Issue by Geistica** [x360ce/x360ce#928]
Hello I'm trying to get my controller work with rayman origins but the game doesn't reconize the controller. I have tried to rename the xinput to Dinput8 since it needs that but it gives me an error "The Procedure entry Point Could not be located in dynamic link library" I'm guessing that you need to do something in the software or ini to change the settings to Dinput. How would I do that? I might have messed up a bit.

**Comment by Squall-Leonhart** [comment]
dinput is not xinput.
