### ISSUE TITLE
Compatibility list link on web side and readme is broken

### ISSUE THREAD

**Issue by HunterZ** [x360ce/x360ce#930]
The website ("Supported Games" link at top of page) and README.md both point to a compatibility list at https://github.com/x360ce/x360ce/blob/master/Wiki/CompatibilityList.md, but that link gives a 404 error.

**Comment by Squall-Leonhart** [comment]
right you are, the wiki's are at https://github.com/x360ce/x360ce/wiki/Compatibility-List now

a change not made by us, but by github.

**Comment by EJocys** [comment]
@HunterZ Thank you for reporting. Fixed.
