### ISSUE TITLE
single keyboard cannot be used for 2 controllers

### ISSUE THREAD

**Issue by eventuallyconsistent** [x360ce/x360ce#933]
I'm using an ultimarc ipac board to generate keyboard signals, which works great for most titles I have configured into my arcade cabinet.

x360ce 4.8 works great for the more modern titles i am trying to add, and I have successfully configured both controller 1 and 2 separately, but it does not seem possible to bind the keyboard as input device to both controllers.

Is this a bug, a feature request, or user error on my part?  Sifting through the repo in the meantime to see if i can guess myself.

**Comment by Squall-Leonhart** [comment]
keyboards are not supported
