### ISSUE TITLE
[GUIDE] x360ce on Linux

### ISSUE THREAD

**Issue by Bumbadawg** [x360ce/x360ce#935]
i wrote a guide to have x360ce.exe work on Linux via wine for Split/Second.
This will be useful to anyone trying to have it work under wine:
https://github.com/ValveSoftware/Proton/issues/2257#issuecomment-484494262

**Comment by Squall-Leonhart** [comment]
Linux is not supported.

**Comment by antony-jr** [comment]
I have not tested this with a game but I got it running with the following steps,

* Install .NET 4.0, DirectX and VC++ via winetricks

Remember to set ``` WINEPREFIX ```. if you don't understand this then you are probably using the default prefix so you do not have to worry about it.

```
 $ winetricks dotnet40 directxfullsetup vcrun2010
```

**That's it, now trying running the application with wine. It should work.**
