### ISSUE TITLE
[X360CE 4.9.0.0]Mirror's Edge

### ISSUE THREAD

**Issue by AkiraJkr** [x360ce/x360ce#938]
Windows 10.
Controller: Twin USB Joystick(PS2 Controller)

EDIT: It's apparently Steam Input that's causing the issue...but not really. Apparently, with Steam Input hidden, I appear to have better control of the camera, but I still have inverted Y Axis on the left stick.

Without Steam Input running, it appears that left stick Y axis is still inverted, and right stick is...a mess, and slow too.

ANOTHER EDIT: If you need me testing live, or anything like that, please, do tell me, I'm more than happy to test issues. My Discord is AkiraJkr#6764

**Comment by Squall-Leonhart** [comment]
Configure your control properly.
