### ISSUE TITLE
[Bug] Newest redist not being recognized

### ISSUE THREAD

**Issue by HKunogi** [x360ce/x360ce#941]
Using the newest beta version it keeps saying that i need the vs redist 2015, even i have those installed
https://aka.ms/vs/16/release/VC_redist.x64.exe
https://aka.ms/vs/16/release/VC_redist.x86.exe
That contains from 2015~2019, it seems to look for the 2015 only, not recognizing those, thus giving me errors on the issue tab, asking to install it, and install the drivers, even i already having it installed, and i cant install the 2015 cause those ones already contains it, so when trying to install the microsoft installer says its already installed.

**Comment by EJocys** [comment]
Thank you for reporting. I will try to fix it in next release.

**Comment by Squall-Leonhart** [comment]
I do not experience this with 4.x, closing as fixed / WFM.
