### ISSUE TITLE
x360ce.Engine.XmlSerializers Project Reference

### ISSUE THREAD

**Issue by HKunogi** [x360ce/x360ce#943]
The file x360ce.Engine.XmlSerializers.dll seems to be referenced on the app and app beta projects, but its not a compiled file from the engine project, so cannot be found on the x360ce.Engine output dir after compilation, leading to error at compiling the app and app beta projects.

**Comment by EJocys** [comment]
Thank you. Removed optional x360ce.Engine.XmlSerializers.dll reference. Should compile now.
