### ISSUE TITLE
Alpha Protocol Problems

### ISSUE THREAD

**Issue by SMR95** [x360ce/x360ce#944]
Hi all!

I want to play Alpha Protocol with gamepad in STEAM, but it has been impossible. I did the configuration of the x360ce and I noticed that the characteristic sound was not reproduced at the start of the game, then in the options menu I chose the gamepad and for a small second the icons of the XBOX buttons were shown, but then disappeared I left the menu, I re-entered and the control option was still disabled.

I have repeated the process several times and I have not been able to find a way for the game to recognize the gamepad. It is the only one in my library that does not recognize it, otherwise, all my games recognize it.

I have Windows 8.1 Pro, the Alpha Protocol is version 1.1 and the X360 Controller Emulator is 3.2.8.77 32-bit. I hope you can help me find the problem to achieve an optimal configuration.

**Comment by Squall-Leonhart** [comment]
use 4.x alpha instead.

**Comment by SMR95** [comment]
Hello, thanks for answering.

I'm sorry, but it could be more specific: with 4.x alpha it refers to a version of the game or a version of x360ce. How could I perform the action?

I hope it is not too much trouble. Thanks for your time

**Comment by SMR95** [comment]
Hello @Squall-Leonhart!
Thank you for answering my request.
I downloaded version 4.9.0.0 and I must say that the game recognizes the control perfectly (although setting the buttons is more difficult). Everything has been excellent, thanks for your recomendation. For users who do not have much computer knowledge has been a great help.
