### ISSUE TITLE
ditool has incorrect configuration; and also, will auto-compile be made available?

### ISSUE THREAD

**Issue by ghost** [x360ce/x360ce#945]
Trying to compile this project has been a nightmare. Would you be willing to set up auto-compiling with AppVeyor so each commit will have a link to download the latest build?

**Comment by ghost** [comment]
I managed to get it to compile after some difficulty. Apparently the Release configuration of ditool is targeting the windows xp version of the v140 toolset, which none of the other library projects do.

**Comment by Squall-Leonhart** [comment]
User has false assumption.
