### ISSUE TITLE
4.9.0.0 Alpha - Guide button mapping not responding

### ISSUE THREAD

**Issue by issues-guy** [x360ce/x360ce#949]
I mapped button 12 on my controller to the Guide button in x360ce successfully using the record feature, but the Guide button press is not being triggered at all when I push button 12. Is there a special procedure to get this feature working? Or has it not yet been fully implemented yet?

Thanks!

**Comment by Tuxie** [comment]
Yes, it seems like x360ce doesn't support the guide button. reWASD supports it perfectly so it's definitely possible to implement. The problem I have with reWASD is that it doesn't support mapping multiple physical controllers to a single virtual one.

**Comment by EJocys** [comment]
Guide button map not implemented yet, I will try to add it in next release.

**Comment by EJocys** [comment]
Thank you for reporting this issue. Added support for Guide button (v4.17.12.0, 2020-11-15). You can download latest version from here:
https://github.com/x360ce/x360ce/releases
