### ISSUE TITLE
can't find x360ce.exe file

### ISSUE THREAD

**Issue by DevLtAus** [x360ce/x360ce#95]
I checked a tutorial on how to use x360ce & it mentioned a .exe file, but I can't find said file anywhere, please help.

**Comment by Nucleoprotein** [comment]
Here https://github.com/x360ce/x360ce or here http://x360ce.github.io/x360ce/

**Comment by DevLtAus** [comment]
thanks

**Comment by DevLtAus** [comment]
um... I still can't find the .exe file, can you just tell me where it is? Note: When telling me about computers, think of me as your type-writer, letter-sending grandfather that just doesn't really get much about computers.

**Comment by Nucleoprotein** [comment]
Under downloads, you need to unpack zip file.
