### ISSUE TITLE
Vibration or force feedback not working with x360ce 4.9 alpha when enabling

### ISSUE THREAD

**Issue by fjamal080** [x360ce/x360ce#951]
Force feed back not working with x360ce alpha 4.9 also when i want to use my generic controller again instead of virtual i don't know how to revert the changes back to the old settings when i disable x360ce settings hid guardian and virtual gamepad the controller still does not show in the game controllers unless i enable the x360ce settings again

**Comment by Squall-Leonhart** [comment]
Known issue, start 4.x with vibration disabled, then enable it.

turn it back off before closing x360ce.
