### ISSUE TITLE
Sonic Generations: Crash on Exit with COM Hook Mask

### ISSUE THREAD

**Issue by r543** [x360ce/x360ce#952]
Sonic Generations crashes on exit as long as the COM Hook is enabled.
(I'm aware that the Compatibility List says it works without a Hook but I think that's a mistake)

Further Info:
Sonic Generations is a game with bad dinput support.
You might have heard of the infamous Quickstep Issue, not sure if that was fixed (as I'm no longer having it) but instead I have some cutscenes that skip themselves (looks like the game checks if the controller is there by pressing start?), those are both of the Eggman Abducted cutscenes (after the Time Eater shows up the game suddenly skips it) as well as the Boss Intro cutscene for Shadow.
Those issues don't happen with xinput.

If the COM Hook Mask is enabled, this all works fine, minus exiting the game as that makes it crash/bring up the error that it's no longer responding.
Without the COM Hook Mask, the game seems to recognize the Direct Input Controller and all the Direct Input issues are there again...

Initially, when I set up x360ce for Sonic Generations(just a few days ago), I didn't have the COM Hook checked and had those crashes.
However, after I enabled it, the crashes were gone and the Game worked fine until yesterday where it crashed on exit.
After removing the COM Hook it worked again, but this caused a cutscene skip when I continued the game.
Due to that I started checking the whole thing again and completely removed x360ce as well as the controller configuration from the game, just to make sure nothing's messed up.

**Comment by Squall-Leonhart** [comment]
it works without a hook, it was tested by me.

users should be moving to 4.x which offers a better compatibility for pure xinput apps.
