### ISSUE TITLE
Failed to load xinput1_3.dll

### ISSUE THREAD

**Issue by Kwerd90121** [x360ce/x360ce#954]
this really annoys me am using windows 7 ultimate 64bit and the 360ce 64bit version doesn't work how do i fix this i have all the requirements to run this
![image](https://user-images.githubusercontent.com/50899785/58151083-2be95d80-7c9b-11e9-884d-02c7bbf6a119.png)

**Comment by wrongtarget** [comment]
do you fix it 
pls tell me bec i have the same problem

**Comment by Kwerd90121** [comment]
Nah man the mods or other people won't help

**Comment by Kwerd90121** [comment]
This error bothers me i can't play my yakuza kiwami

**Comment by FURBY76** [comment]
To fix it Download Visual C++ Redistributable Packages for Visual Studio 2013 from MS
