### ISSUE TITLE
Xbox360 compatibility issue

### ISSUE THREAD

**Issue by Laxaeus** [x360ce/x360ce#956]
Hello,
I always used this program to play various games without problems but lately some games I'm trying to play with don't recognize the controller. I put the xbox360ce.exe file in the main directory of the game (where the game executable is), I configure every single button correctly, I save the configuration, I can see from the xbox controller virtual image that when I push the buttons I get the green light feebacks on screen, I close the app and then I try to run my games but they do not recognize the controller at all.

The games are Dark Souls: Remastered and Subnautica: Below Zero and few others, but I'm mainly concerned with those two. Is there some kind of problem with these games in particular that I'm not aware of? Is there a fix? Thank you.

**Comment by Jedah85** [comment]
Not sure about DS:R since I haven't played it but Subnautica: Below Zero is a Unity game, which means it's not compatible with X360ce.
