### ISSUE TITLE
Not working with installed logitech drivers. Driving Force GT NFS Payback

### ISSUE THREAD

**Issue by G1tterB3nj4m1n** [x360ce/x360ce#958]
My driving Force GT worked nearly perfectly without the logitech drivers. Had problems with the triggers. they only came up to 195/255 what was a huge problem by the acceleration. after Ive installed the logitech drivers the acceleration worked good, 255/255 but the sterring wouldnt work. I think Game is now using the whee with the logitech drivers, and without X360ce. How can i fix this?? So NFS again wants to use  x360ce ? Btw cant delete the logitech drivers, tried around 999999 times.........

**Comment by Squall-Leonhart** [comment]
use the logitech calibration reset application.
