### ISSUE TITLE
Can't run .exe file

### ISSUE THREAD

**Issue by DevLtAus** [x360ce/x360ce#96]
I can't run the .exe file on my computer, I am trying to use it for  Bully scholarship edition, but for some reason, my computer says "This app can't run on your PC" I downloaded the 64 bit version, just so you know.

**Comment by Squall-Leonhart** [comment]
The nyou either do not have Dot Net installed, or your Operating System is not 64bit

**Comment by DevLtAus** [comment]
k

**Comment by Kamil6020** [comment]
I have this problem too

but I will add that a few weeks ago still work

system 64bit

**Comment by silverbacknet** [comment]
Did you use the most recent release from 7/7? What's the exact error? (Screenshot if you can't copy-paste.) What's the exact Windows version?

**Comment by DevLtAus** [comment]
sorry, this is working, I just didn't download certain files. Plus, there was no error, just a lack of file

**Comment by samgreen** [comment]
http://www.microsoft.com/en-us/download/confirmation.aspx?id=42642
