### ISSUE TITLE
the controller is grey so i cant play with the controller in nsuns3

### ISSUE THREAD

**Issue by DioSama2** [x360ce/x360ce#960]
It is shown like this:
![image](https://user-images.githubusercontent.com/51488112/59148103-ed7acf00-8a0c-11e9-9649-e5186c4d4091.png)
It is very weird. when I try to record a button it records. The animation of the controller is not shown. I don't know what to do.

**Comment by Laczi** [comment]
I have the same problem, it does not seem to show the animation, but more importantly the game itself won't detect the controller

**Comment by DioSama2** [comment]
> I have the same problem, it does not seem to show the animation, but more importantly the game itself won't detect the controller

have you solved it?

**Comment by Laczi** [comment]
Yes, I have

**Comment by stefyy98** [comment]
@Laczi how did you solve the problem?

**Comment by Laczi** [comment]
If I remember correctly all I did was check the Pass Through box in the Advanced panel. From there on everything worked correctly

**Comment by Squall-Leonhart** [comment]
passthrough disables x360ce.
