### ISSUE TITLE
Can't fix incorrectly mapped buttons

### ISSUE THREAD

**Issue by JSOakes** [x360ce/x360ce#963]
I was trying to play the PC version of Madden NFL 08 with my new controller, but the buttons were incorrectly mapped.  So I downloaded x360ce and remapped all the buttons to how they should be.

Although all my buttons are shown to be correctly mapped in the x360ce application, whenever I start the game the buttons are still incorrectly mapped.  It's as if x360ce hasn't changed anything.

Please help - Thanks.

**Comment by Squall-Leonhart** [comment]
use Durazno to adjust xinput mappings on xinput controllers.
