### ISSUE TITLE
Old Win Trust 6.1.7601.17932 Windows 7. Installing hotfix KB3033929 does not fix the issue. X360CE 4.10.0.0 Alpha

### ISSUE THREAD

**Issue by Borre1** [x360ce/x360ce#965]
Old Win Trust 6.1.7601.17932 isse on Windows 7. Installing Security Update for Windows 7 for x64-based Systems (KB3033929) does not fix the problem, so there has to be another system update that is requierd for x360ce to work. X360CE 4.10.0.0 Alpha

**Comment by Squall-Leonhart** [comment]
No support for people who choose not to have windows updated to atleast Dec 2016.
