### ISSUE TITLE
Че то не понятное совсем))

### ISSUE THREAD

**Issue by artshini** [x360ce/x360ce#967]
Включен геймпад в пк сразу,открываю прогу она летит сразу же моментально.2)Открыл прогу,нажал добавить,вставил геймпад,прога полетела.Вопрос как это решается?Пробовал на 4.10 и 4.9

**Comment by siNeZix** [comment]
Та же самая проблема(((

**Comment by siNeZix** [comment]
У меня эта проблема появилась после установки драйвера на мой гемпад Ritmix GP-007. До этого всё работало.

**Comment by Squall-Leonhart** [comment]
I don't speak klingon
