### ISSUE TITLE
Controller got duplicated

### ISSUE THREAD

**Issue by HydraCodes** [x360ce/x360ce#968]
Now that Bluetooth Controllers are supported, i tried using x360ce. I used the 64bit version first before using the 32bit version, when i used the 64bit one, it seems to work. But when i used the 32bit one, the controllers got duplicated, resulting in  'Controller 1' and 'Controller 2' with the same id, and only Controller 2 receives input

Is there a way to remove Controller 2 and use Controller 1 again? This is annoying for some games

**Comment by Squall-Leonhart** [comment]
delete the config in programdata and config all over again
