### ISSUE TITLE
need for speed rivals

### ISSUE THREAD

**Issue by almurphy123** [x360ce/x360ce#97]
downloaded x360ce 64 bit.have tried everything,  I get error message any time I try a setting ,would like to know were to begin, windows 8.1

**Comment by Squall-Leonhart** [comment]
Game specific help  and tutorials are available on the forum.

**Comment by almurphy123** [comment]
X360ce shows visual ++ c 2010 need for speed rivals requires version 2012.also MScv100th. Dll missing. It's in the computer .fixer dll. Can you help.
