### ISSUE TITLE
Controllers 1's Right analog is always up 

### ISSUE THREAD

**Issue by mohdyr** [x360ce/x360ce#970]
Hi,

I usually use 3 USB controllers on my laptop to play games. I use x360ce_64 for my controller settings for the game. My issue is, whenever i plug in my 1st controller the right analog of the controller is always pressing up. I thought my first controller is defected, But i interchanged the controllers and put it in my first USB controller slot the problem occurs the same for other controllers too. I have attached a Screenshot for the same. Please help me to rectify this problem
![Controller Problem 3](https://user-images.githubusercontent.com/52462501/60528513-36732a00-9d12-11e9-86fe-eb99ba4e6787.jpg)
![Controller Problem](https://user-images.githubusercontent.com/52462501/60528514-36732a00-9d12-11e9-973c-2c1640eae622.jpg)
![Controller Problem 2](https://user-images.githubusercontent.com/52462501/60528515-36732a00-9d12-11e9-8ccf-f29b024947f0.jpg)

**Comment by Squall-Leonhart** [comment]
calibrate the gamepad from joy.cpl
