### ISSUE TITLE
[New DLL Name]InputRedirection-Qt, a few Steam games

### ISSUE THREAD

**Issue by ParzivalWolfram** [x360ce/x360ce#971]
There seems to be a new XInput DLL name starting to float around, "xinputgamepad.dll" (and a companion DLL, "xinputgamepadd.dll")
Can anyone else confirm?

**Comment by Squall-Leonhart** [comment]
These are not api dlls

**Comment by ParzivalWolfram** [comment]
Replacing these with the generated DLLs from x360ce allows x360ce to work,
as no included name actually works. They are, indeed, API DLLs.

**Comment by Squall-Leonhart** [comment]
They are not API dlls, they are Qt framework proxy dll's to import the  correct system xinput library.

**Comment by ParzivalWolfram** [comment]
They don't behave as such.

**Comment by Squall-Leonhart** [comment]
Yes they do.

**Comment by ParzivalWolfram** [comment]
That isn't my experience, but this is going nowhere and isn't productive.
