### ISSUE TITLE
problem configuring 360ce with a wireless bluetuth controller

### ISSUE THREAD

**Issue by amid19** [x360ce/x360ce#972]
i have a wireless controller which works perfectly with 360ce when its wired ,but when i add it by bluetuth it is detected as connected and the the green light is there but nothing works, in the previous windows it was working but now i cant figure out what i am missing 

https://nsa40.casimages.com/img/2019/07/06/190706094124125716.png
https://nsa40.casimages.com/img/2019/07/06/190706095954236629.png

**Comment by Rogus** [comment]
I also have one wireless controller it works on the wireless part, but when I choose the controller xbox 360 for windows it can't register the inputs even if I choose that hide part for the ps4 controller. What I've found in some of the open issues is that you delete the C:\Program Files\X360CE\ folder and try to manually setup again and see if it works.

**Comment by Squall-Leonhart** [comment]
not a bug report.
bluetooth is not supported.
