### ISSUE TITLE
Fifa 19 Crash

### ISSUE THREAD

**Issue by ItsMeRiO** [x360ce/x360ce#974]
Fifa 19 game crashes when I connected the controller in the middle of the game. I'm trying to play online using parsec and every time another player connects his controller the game closes. Need Help!
PS2 Controller
Twin USB Joystick adapter

**Comment by reiprado** [comment]
Hi team, I have the same issue as ItsMeRiO using PS2 controller with that blue dual adapter. If I let xinput1_3.dll the x360ce doesn't affect the game, when I rename to xinput1_4.dll (used to work in Fifa 18) makes the game crash immediately after the splash screen.
Tried to use an old 360ce version, the newest stable one and even the new alpha without any success. (all of them works flawlessly in Fifa 18).

**Comment by Squall-Leonhart** [comment]
use 4.x alpha

**Comment by reiprado** [comment]
Using 4x alpha as already tried doesn't solve the problem.

**Comment by Squall-Leonhart** [comment]
Disable vibration
WFM.

**Comment by reiprado** [comment]
Already disabled
