### ISSUE TITLE
x360ce not registering my ps2 controller (Game:Rocket league)

### ISSUE THREAD

**Issue by ListlessGeneral** [x360ce/x360ce#979]
Hi I just bought a adapter yesterday and found out that have to download this software. So I did and tried launching it with Rocket league (I placed it where the rocket league.exe is located (yes its the 32 bit one)) but when I connect my ps2 controller and press the analog and move the joy stick the joystick on the screen doesn't move in either of the 2 ports of the adapter. and when I connect my other controller this happens
![x360ce1](https://user-images.githubusercontent.com/45923053/61484416-fc5f8480-a9af-11e9-89ef-782bf571697a.PNG)
 and when I press the analog this happens 
![x360ce2](https://user-images.githubusercontent.com/45923053/61484540-303aaa00-a9b0-11e9-90d9-b1ab8ad66ba9.PNG)
I dont know if its my controller or the software (or user error) but if its my controller you would think that at least one of them would work but instead one doesn't register and the other acts out. So i'm leaning towards software and/or user error.
Please help!
Thanks in advance

**Comment by Squall-Leonhart** [comment]
use the alpha
