### ISSUE TITLE
XInput stick range

### ISSUE THREAD

**Issue by cetygamer** [x360ce/x360ce#985]
Game: Lara Croft and the Guardian of Light
Gamepad: 8BitDo NES30 Pro
x360ce version: 3.2.9.82

Issue:

I configured my controller in x360ce, added xinput1_3.dll, xinput9_1_0.dll files. Game picked up controller and configuration with no problem. But when I push left stick all the way to down-left corner, the game stops reading XInput stick values and thinks that the stick is in neutral position (0, 0), the characted stops running.

Is there a way to lower max range of XInput (-32768)? So the game wouldn't ever get those XInput values?

**Comment by Squall-Leonhart** [comment]
use 4.x

**Comment by cetygamer** [comment]
4.x is highly unstable, doesn't pick up my gamepad and crashes the target game on launch.

**Comment by Squall-Leonhart** [comment]
then you're not using it right.
