### ISSUE TITLE
is there an option in the future to workaround simultaneous keypress issue of LT and RT

### ISSUE THREAD

**Issue by bobalazs** [x360ce/x360ce#986]
i've always had a problem with this 360 clone SPEED-LINK  SL-6555-SBK controller, where when both LT and RT are pressed the axis doesn't work. Many games require both keys to be pressed, like shoot arrow, LS - draw RT - release arrow, and i always had a problem. I had to remap keys because of this.
Triggers look like this:
LS pressed fully https://i.imgur.com/JsJHCSq.jpg
RS pressed fully https://i.imgur.com/9MkEYzp.jpg
both pressed: https://i.imgur.com/3aGXEf5.jpg

**Comment by Squall-Leonhart** [comment]
no
