### ISSUE TITLE
Doesn't work with Ancestors Humankind Odyssey

### ISSUE THREAD

**Issue by NabilOulbaz** [x360ce/x360ce#992]

**Comment by d-ferente** [comment]
![image](https://user-images.githubusercontent.com/15008167/64135140-cc334000-cdbb-11e9-93d5-f8e174947d64.png)

It won't allow us to fix/check the configs and won't work in game either

**Comment by NabilOulbaz** [comment]
That's exactly my issue too. Please look into this .

**Comment by AndriesK** [comment]
That was my issue as well, I fixed it by temporarily moving **Ancestors-Win64-Shipping.pdb** into a different directory and then moving it back once I was finished with x360ce. I have no idea but this might happen because the files have the same name.

**Comment by robgha01** [comment]
This is similar to https://github.com/x360ce/x360ce/issues/920 if its the pdb bugging it out.

**Comment by a-nanasov** [comment]
alpha version 4 works, however I have an issue with buttons mapping

**Comment by Squall-Leonhart** [comment]
the pdb is a debug symbol package.

anyway, 3.x is not our focus now

**Comment by serkanaslan2k** [comment]
> That was my issue as well, I fixed it by temporarily moving **Ancestors-Win64-Shipping.pdb** into a different directory and then moving it back once I was finished with x360ce. I have no idea but this might happen because the files have the same name.

Thanks a lot brother. 
l spent too time for this problem. You are my hero 👍
