### ISSUE TITLE
cannot instal virtual device driver

### ISSUE THREAD

**Issue by thesh4man** [x360ce/x360ce#994]
I'm using x360ce build 4.9.0.0 and have warning on issues tab, it's said "you need to install virtual driver emulation to work". but every time I click install, the driver cannot be installed, even though I run x360ce with administrator privilege. the warning keeps appear and I cannot map my joystick. any idea how to resolve this problem ?.
![image](https://user-images.githubusercontent.com/55033534/64479815-9e4c6200-d1e6-11e9-8eca-1af95f7f42a0.png)
thank you.

**Comment by Squall-Leonhart** [comment]
Use the installer here
https://github.com/ViGEm/ViGEmBus/releases

**Comment by thesh4man** [comment]
@Squall-Leonhart I installed Xbox 360 Accessories Software 1.2 and ViGEmBus_Setup_1.16.115.exe but the issue still happens.

**Comment by Squall-Leonhart** [comment]
the accessory software is not relevant to windows 8 or 10, remove it.

**Comment by thesh4man** [comment]
@Squall-Leonhart it works, thank you very much.

**Comment by mano82** [comment]
I'm still having this issue even after installing vigembus driver

**Comment by Squall-Leonhart** [comment]
clear the log.

**Comment by Pecanek** [comment]
Hello, i installed the vigembus driver and still need to install that Virtual Device Driver. I dont know where are that Accessories software that you were talking about and i dont know how you mean to clear log. Please help.

**Comment by bxnjxmin** [comment]
> Hello, i installed the vigembus driver and still need to install that Virtual Device Driver. I dont know where are that Accessories software that you were talking about and i dont know how you mean to clear log. Please help.

I have the same problem... Please help.

Thanks :)

**Comment by Rexork** [comment]
I have same problem on windows 11. Tried to download latest version of ViGEmBus and didnt work. Tried 1.16.115 as "thesh4man" and it also didn't work

**Comment by theuz521** [comment]
Voces vão resolver o problema novo? Tenho windows 11 e instalei esse novo que iria resolver o problema e ele não resolveu

**Comment by Rexork** [comment]
> Voces vão resolver o problema novo? Tenho windows 11 e instalei esse novo que iria resolver o problema e ele não resolveu

I didn’t quite understand what you wrote when translating through a translator. If you meant did I solve the problem, then no. But I solved the problem in a different way. I knew that on Steam you can add a third-party game downloaded from a torrent and use support for Steam controllers, but for some reason it didn’t work for the version of Elden Ring that I downloaded that time (for all other games it worked) and I tried use x360ce. When I encountered the problem already mentioned, I tried doing something for a while, but nothing helped. In the end, I simply downloaded the game from another torrent and for some unknown reason, support for Steam controllers started working. It’s annoying when there’s no point in a problem's solution (im translating from RU to ENG and so sorry for not clear)

**Comment by imonuppers** [comment]
same thing happend downloaded the drivers and nothing happend please help!

**Comment by SCION016** [comment]
First try to install vgembus... If the problem persists U have to install the drivers manually... Go to control panel device manager and allocate the driver that says others then unknown device (it usually shows that it is not installed properly⚠️)  double click on the unknown device then click on the *driver tab* then click on update driver... On the window shown to update driver click on *browse my computer for drivers*  then click on *browse* now allocate *where you installed ViGEmBus* it is normally installed in 
*C:\program files\nefarius software solutions\ViGEmBus Bus Driver\* 
Then click Next... It will install the drivers successfully ✅ 
Done try to open x360ce again to check if the problem is fixed

**Comment by isaquecosta7262-web** [comment]
#Estou como mesmo problema e não estou conseguindo resolver uso Windows 11 Preciso de uma ajuda por favor

**Comment by sidoshi43266-glitch** [comment]
for installing microsoft c++ 2015-2019 it says product installed already but i cant find it anywhere?

**Comment by natanbuta851-bit** [comment]
@SCION016 I Tried looking for 'unknown device' and i couldnt find anything like this and a updated all the drivers in 'system devices' aswell if you mean that and i still have the problem
